TRUNCATE TABLE TR_CD_DEALS_O_TABLE;
INSERT INTO TR_CD_DEALS_O_TABLE
SELECT '' Response,
       TO_CHAR(TO_DATE (ISSUE_DATE, 'MM/DD/YYYY'), 'DD-Mon-YYYY') DEAL_DATE,
       TO_CHAR(TO_DATE (ISSUE_DATE, 'MM/DD/YYYY'), 'DD-Mon-YYYY') SETTLEMENT_DATE,
       CASE WHEN GET_PARAM('BANK_ID') ='02' THEN 'CBUAE' WHEN GET_PARAM('BANK_ID') ='01' THEN 'CBKWT' END COUNTERPARTY_STRING,
       '/ABK/BANKING/FIS/HTM' TRADING_BOOK,
       'FIS' DEPT_NAME,
       'CDBCBK' SUBTYPE,
       'BUY' BUY_OR_SELL,
       '' MARKET,
       TRIM(IDENTIFIER) SEC_DEFN_NAME,
       '100' PRICE_STRING,
       INTEREST_RATE||'%' YIELD,
       TRIM(AMOUNT) QTY_TRADED,
       '' IS_INVESTMENT,
       '' CONFIRM_METHOD,
       '' SI_FLOW_PAY_SSI_ID,
       '' SI_FLOW_PAY_NOSTRO,
       '' SI_FLOW_PAY_SETT_METHOD,
       '' SI_FLOW_PAY_CPTY_AGENT,
       '' SI_FLOW_REC_SSI_ID,
       '' SI_FLOW_REC_NOSTRO,
       '' SI_FLOW_REC_SETT_METHOD,
       '' SI_FLOW_REC_CPTY_AGENT,
       '' BANK_CUSTODIAN_ACCT,
       'DEF_COC' COST_OF_CARRY_REF_RATE_CODE
  FROM TR_CD_DEALS;
COMMIT;
EXIT; 
