TRUNCATE TABLE COM_LOAN_O_TABLE;
INSERT INTO COM_LOAN_O_TABLE
SELECT DISTINCT
'' Response,
D.DEALNO DEAL_IDENTIFIER,
CASE WHEN trim(D.PORT)='PORT' THEN '/ABK/KUWAIT/BANKING/MM/CORPORATE' ELSE '/ABK/KUWAIT/BANKING/MM/INTERBANK' END TRADING_BOOK,
CASE WHEN TRIM(D.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ENTITY_NAME,
CASE WHEN  TRIM(D.PRODUCT) ='ISLMC' OR TRIM(D.PORT)='ISLM'  THEN 'ISLAMIC'ELSE 'MM' end DEPT_NAME,--*** We had mapped to PRODCODE column
case --when D.BR='01' then CASE WHEN TRIM(D.PORT)='CORP' THEN 'CORP' WHEN  TRIM(D.PRODUCT) ='ISLMC' OR TRIM(D.PORT)='ISLM'  THEN 'ISLAMC' ELSE 'BANK' END 
	 when trim(C.CMNE)='CENTRALKWT' then 'CBKPLA'
     when D.BR='01' AND TRIM(D.PRODTYPE) IN ('LC','BC') THEN 'CORP' 
     when D.BR='01' AND TRIM(D.PRODTYPE) IN ('BB','LB') THEN 'BANK' 
     when D.BR='01' THEN 'ISLAMC'  
     when D.BR='51' then CASE WHEN TRIM(D.PRODTYPE) IN ('LC','BC') THEN 'CORP' ELSE 'BANK' END
END SUBTYPE,
trim(C.CMNE) COUNTERPARTY_STRING,
TO_CHAR(D.DEALDATE,'DD-Mon-YYYY')  DEAL_DATE,--***
TO_CHAR(D.VDATE,'DD-Mon-YYYY') START_DATE,--***
TO_CHAR(D.MDATE,'DD-Mon-YYYY') END_DATE,--***
CASE WHEN D.AL='L' THEN 'SHORT' ELSE 'LONG' END SIDE_SIDE_ONE_LONG_OR_SHORT,
CASE WHEN D.AL='L' AND SUBSTR(D.RATECODE,1,2)='FI' THEN 'FIX/DEPO'
     WHEN D.AL='L' AND SUBSTR(D.RATECODE,1,2)!='FI' THEN 'FLT/DEPO'
     WHEN D.AL='A' AND SUBSTR(D.RATECODE,1,2)='FI' THEN 'FIX/LOAN'
     WHEN D.AL='A' AND SUBSTR(D.RATECODE,1,2)!='FI' THEN 'FLT/LOAN'
END TYPE_STRING,
D.CCY CURRENCY_STRING,
abs(TO_CHAR(D.CCYAMT,'9999999999999999990.99999999')) SIDE_SIDE_1_NOTNAL_AMT_VALUE,
SUBSTR(D.BASIS,1,1)||'/'||SUBSTR(D.BASIS,2,3) SIDE_SIDE_ONE_BASIS_CODE,
CASE WHEN TRIM(D.INTPAYCYCLE)='M' THEN 'MONTHLY'
     WHEN TRIM(D.INTPAYCYCLE)='Q' THEN 'QUARTERLY'
     WHEN TRIM(D.INTPAYCYCLE)='S' THEN 'SEMI'
     WHEN TRIM(D.INTPAYCYCLE)='A' THEN 'ANNUAL'
     ELSE 'BULLET' END SIDE_SIDE_ONE_CREATION_FREQ,--INFY/BANK NEEDS TO GIVE CORRECT VALUE
D.INTRATE SIDE_SIDE_ONE_FIX_RATE,
TO_CHAR(D.SPREAD_8,'9999999999999999990.99999999') SIDE_SIDE_ONE_SPREAD_RATE,
CASE WHEN SUBSTR(D.RATECODE,1,2)='FI' THEN ' ' ELSE 'FLOATING' END "SIDE.$1.CASH_FLOW_SIDE_TYPE",
CASE WHEN D.RATECODE LIKE 'LI%' THEN D.RATECODE ELSE NULL END "SIDE.$1.REFERENCE_RATE",
'Auto' AUTO_OR_PENDING,
CASE WHEN TRIM(C.BIC) IS NOT NULL THEN 'SWIFT' ELSE '' END CONFIRM_METHOD,--***
'' SIDE_CURREC_SI_FLOW_PAY_SSI_ID,--@@@
CASE WHEN TRIM(S.SMEANS)='BRDGE' THEN 'BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TO_CHAR(S.SACCT) END SIDE_CURREC_SI_FLOW_PAY_NOSTRO,
CASE WHEN TRIM(S.SMEANS)='NOS' THEN 'SWIFT' ELSE '' END SIDE_CUR_SI_FLOW_PAY_SETT_MTHD,--***
'  ' SIDE_CUR_SI_FLOW_PAY_CPTY_AGNT,
'' SIDE_CURREC_SI_FLOW_REC_SSI_ID,--@@@
CASE WHEN TRIM(S.SMEANS)='BRDGE' THEN 'BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TO_CHAR(S.SACCT) END SIDE_CURREC_SI_FLOW_REC_NOSTRO,
CASE WHEN TRIM(S.SMEANS)='NOS' THEN 'SWIFT' ELSE '' END SIDE_CUR_SI_FLOW_REC_SETT_MTHD,--***
'  ' SIDE_CUR_SI_FLOW_REC_CPTY_AGNT,
CASE WHEN TRIM(S.SMEANS)='BRDGE' THEN 'BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TO_CHAR(S.INTSACCT) END SIFLOW_INTEREST_PAY_NOSTRO,
CASE WHEN TRIM(S.INTSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SIFLOW_INT_PAY_SETT_METHOD,--***
'  ' SIFLOW_INTEREST_PAY_CPTY_AGENT,
'' SIFLOW_INTEREST_PAY_SSI_ID,--@@@
CASE WHEN TRIM(S.SMEANS)='BRDGE' THEN 'BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TO_CHAR(S.INTSACCT) END SIFLOW_INTEREST_RECIEVE_NOSTRO,
CASE WHEN TRIM(S.INTSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SIFLOW_INT_RECIEVE_SETT_METHOD,--***
'  ' SIFLOW_INT_RECIEVE_CPTY_AGENT,
'' SIFLOW_INTEREST_RECIEVE_SSI_ID,--@@@
'  ' SIDE_SIDE_ONE_COMP_METHOD,
'  ' SIDE_SIDE_ONE_COMP_FREQUENCY,
'S' SIDE_SIDE_ONE_START_DD_CNVNTN,--*** TO_CHAR(D.VDATE,'DD-Mon-YYYY')
'S' SIDE_SIDE_ONE_END_DD_CNVNTN,--*** TO_CHAR(D.MDATE,'DD-Mon-YYYY')
'S' SIDE_SIDE_1_CASH_FLW_D_CNVNTN, ---CASE WHEN TRIM(D.INTDATERULE) IS NULL THEN 'B' ELSE D.INTDATERULE END
'' AMORTISATION_TYPE,
'' AMORTISATION_FREQUENCY,
'' AMORTISATION_START_DATE,
'' AMORTISATION_END_DATE,
'' AMORTISATION_STEP_AMOUNT,
TRIM(D.PRODTYPE)  PRODTYPE
FROM DLDT D
INNER JOIN CUST C ON TRIM(D.CNO)=TRIM(C.CNO)
LEFT JOIN SCHD S ON TRIM(D.DEALNO)=TRIM(S.DEALNO) AND S.SCHDSEQ='001' AND D.BR=S.BR  
WHERE D.MDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(D.REVDATE) IS NULL;
COMMIT;
UPDATE COM_LOAN_O_TABLE SET SUBTYPE='INTGRP' WHERE TRIM(COUNTERPARTY_STRING)=CASE WHEN GET_PARAM('BANK_ID')='51' THEN 'AEAHLK' WHEN GET_PARAM('BANK_ID')='01' THEN 'ABKDXB' END;
COMMIT;
--UPDATE NOSTRO TO SCBDLE FROM SCBLDE
--UPDATE COM_LOAN_O_TABLE SET SIDE_CURREC_SI_FLOW_PAY_NOSTRO='SCBDLE' WHERE TRIM(SIDE_CURREC_SI_FLOW_PAY_NOSTRO)='SCBLDE';
--UPDATE COM_LOAN_O_TABLE SET SIDE_CURREC_SI_FLOW_REC_NOSTRO='SCBDLE' WHERE TRIM(SIDE_CURREC_SI_FLOW_REC_NOSTRO)='SCBLDE';
--UPDATE COM_LOAN_O_TABLE SET SIFLOW_INTEREST_PAY_NOSTRO='SCBDLE' WHERE TRIM(SIFLOW_INTEREST_PAY_NOSTRO)='SCBLDE';
--UPDATE COM_LOAN_O_TABLE SET SIFLOW_INTEREST_RECIEVE_NOSTRO='SCBDLE' WHERE TRIM(SIFLOW_INTEREST_RECIEVE_NOSTRO)='SCBLDE';
--COMMIT;
UPDATE COM_LOAN_O_TABLE A SET SIDE_CURREC_SI_FLOW_PAY_SSI_ID=(SELECT TRIM(SSI_ID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE 
 ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) AND TRIM(A.COUNTERPARTY_STRING)=TRIM(B.CPTY_NAME) AND 
TRIM(B.NOSTRO_ID) = TRIM(A.SIDE_CURREC_SI_FLOW_PAY_NOSTRO) AND TRIM(A.CURRENCY_STRING) = TRIM(B.CURRENCY));
UPDATE COM_LOAN_O_TABLE A SET SIDE_CURREC_SI_FLOW_REC_SSI_ID=(SELECT TRIM(SSI_ID) FROM (SELECT * FROM TREASURY_REC_SSI_O_TABLE WHERE 
ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_REC_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) 
UNION SELECT * FROM TREASURY_PAY_SSI_O_TABLE WHERE ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) 
) B WHERE TRIM(A.COUNTERPARTY_STRING)=TRIM(B.CPTY_NAME) AND 
TRIM(B.NOSTRO_ID) = TRIM(A.SIDE_CURREC_SI_FLOW_REC_NOSTRO) AND TRIM(A.CURRENCY_STRING) = TRIM(B.CURRENCY));
UPDATE COM_LOAN_O_TABLE A SET SIFLOW_INTEREST_PAY_SSI_ID=(SELECT TRIM(SSI_ID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE 
 ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE SSI_TYPE='INT/COUPON' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) AND TRIM(A.COUNTERPARTY_STRING)=TRIM(B.CPTY_NAME) AND 
TRIM(B.NOSTRO_ID) = TRIM(A.SIFLOW_INTEREST_PAY_NOSTRO) AND TRIM(A.CURRENCY_STRING) = TRIM(B.CURRENCY));
UPDATE COM_LOAN_O_TABLE A SET SIFLOW_INTEREST_RECIEVE_SSI_ID=(SELECT TRIM(SSI_ID) FROM (SELECT * FROM TREASURY_REC_SSI_O_TABLE WHERE 
ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_REC_SSI_O_TABLE B WHERE SSI_TYPE='INT/COUPON' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) 
UNION SELECT * FROM TREASURY_PAY_SSI_O_TABLE WHERE ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE SSI_TYPE='INT/COUPON' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) 
) B WHERE TRIM(A.COUNTERPARTY_STRING)=TRIM(B.CPTY_NAME) AND 
TRIM(B.NOSTRO_ID) = TRIM(A.SIFLOW_INTEREST_RECIEVE_NOSTRO) AND TRIM(A.CURRENCY_STRING) = TRIM(B.CURRENCY));
COMMIT;
UPDATE COM_LOAN_O_TABLE A SET (AMORTISATION_TYPE,AMORTISATION_FREQUENCY,AMORTISATION_START_DATE,AMORTISATION_END_DATE,AMORTISATION_STEP_AMOUNT) = ( SELECT AMORTISATION_TYPE,AMORTISATION_FREQUENCY,TO_CHAR(AMORTISATION_START_DATE,'DD-Mon-YYYY') ,TO_CHAR(AMORTISATION_END_DATE,'DD-Mon-YYYY') ,AMORTISATION_STEP_AMOUNT FROM(
select DEALNO,'AMORTISE' AMORTISATION_TYPE,CASE WHEN MONTHS_BETWEEN( MAX(INTSTRTDTE), MIN(INTSTRTDTE))/(COUNT(*)-2) = 6 THEN 'SEMI_ANNUAL' 
                                                WHEN MONTHS_BETWEEN( MAX(INTSTRTDTE), MIN(INTSTRTDTE))/(COUNT(*)-2) = 12 THEN 'ANNUAL'
                                                WHEN MONTHS_BETWEEN( MAX(INTSTRTDTE), MIN(INTSTRTDTE))/(COUNT(*)-2) = 3 THEN 'QUATERLY' END AMORTISATION_FREQUENCY, min(INTSTRTDTE) AMORTISATION_START_DATE, max(INTSTRTDTE) AMORTISATION_END_DATE,ABS(MIN(TOTPAYAMT-INTAMT)) AMORTISATION_STEP_AMOUNT from schd where dealno in(
select DEALNO from schd
inner join COM_LOAN_O_TABLE on trim(DEAL_IDENTIFIER) = trim(dealno)
where abs(PRINAMT) !=SIDE_SIDE_1_NOTNAL_AMT_VALUE
) group by DEALNO 
) B WHERE TRIM(A.DEAL_IDENTIFIER) = TRIM(B.DEALNO)
);
COMMIT;
EXIT; 
