TRUNCATE TABLE EQUITY_MF_O_TABLE;
INSERT INTO EQUITY_MF_O_TABLE
SELECT distinct 
'' RESPONSE,
'' DEAL_IDENTIFIER,
case when TRIM(Z.PORT)='ACIC' then '/ABK/KUWAIT/BANKING/EQUITY/OUTSOURCE/ACIC' 
     WHEN TRIM(Z.PORT)='DTS' then '/ABK/KUWAIT/BANKING/EQUITY/AFS/DTS'   
     WHEN TRIM(Z.PORT)='EQU' then '/ABK/KUWAIT/BANKING/EQUITY/AFS'  
     WHEN TRIM(Z.PORT)='TS' then '/ABK/KUWAIT/BANKING/EQUITY/TREASURY_SHARES'  
     WHEN TRIM(Z.PORT)='FUND' then '/ABK/KUWAIT/BANKING/EQUITY/AFS' ELSE Z.PORT END
     TRADING_BOOK,
TRIM(s.SECID) EQUITY_MF_DEFN_NAME,
CASE WHEN TRIM(z.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ENTITY_NAME,
'EQUITIES' DEPT_NAME,
case when trim(z.PORT)='TS' then 'TRY_SH' else  'AFS'  end SUBTYPE,--case when INVTYPE='A' then 'AFS' when INVTYPE='H' then 'HTM' when INVTYPE='T' then 'HFT'   end
'BUY' BUY_OR_SELL,
'TRADE' IS_INVESTMENT,
ed.ISSUER_STRING COUNTERPARTY_STRING,
get_param('EOD_DATE') DEAL_DATE,
get_param('EOD_DATE') PAYIN_DATE,
get_param('EOD_DATE') PAYOUT_DATE,
z.CCY CURRENCY_STRING,
round(z.AVGCOSTPERUNIT,8) PRICE_STRING,--round(z.CLPRICE_8,8)--round(z.AVGCOSTPERUNIT,8)
CASE WHEN TRIM(S.SECID) NOT LIKE  '%FUND%' AND trim(S.SECID)!='EQ ALAHLI GULF' THEN z.NETQTY end QTY_TRADED,
case when trim(z.COST) in  ('2340','2310','0300') then 'KSE' when trim(z.COST) in  ('2350','2320') then 'UNLISTED' when trim(z.COST) in  ('2360') then 'NSE' END EXCHANGE,
'' CONFIRM_METHOD,
'' EXCUTION_METHOD,
CASE WHEN TRIM(PS)='S' THEN '' ELSE NULL END SI_FLOW_PAY_SSI_ID,
'' SI_FLOW_PAY_NOSTRO,--CASE WHEN TRIM(PS)='S' THEN CCYSACCT ELSE NULL END SI_FLOW_PAY_NOSTRO,
'' SI_FLOW_PAY_SETT_METHOD,
CASE WHEN TRIM(PS)='S' THEN '' ELSE NULL END SI_FLOW_PAY_CPTY_AGENT,
CASE WHEN TRIM(PS)='P' THEN '' ELSE NULL END SI_FLOW_REC_SSI_ID,
'' SI_FLOW_REC_NOSTRO,--CASE WHEN TRIM(PS)='P' THEN CCYSACCT ELSE NULL END SI_FLOW_REC_NOSTRO,
'' SI_FLOW_REC_SETT_METHOD,
CASE WHEN TRIM(PS)='P' THEN '' ELSE NULL END SI_FLOW_REC_CPTY_AGENT,
'DEF_COC' COST_OF_CARRY_REF_RATE_CODE, 
TRIM(CUSTODION) SI_FLOW_REC_CUSTODIAN_ACCT,
'ABKKWT' HOLDING_ENTITY_NAME,
CASE WHEN TRIM(S.SECID)LIKE  '%FUND%' or trim(S.SECID)='EQ ALAHLI GULF' THEN 'MANUAL' end AUTO_OR_MANUAL_RESET,
CASE WHEN TRIM(S.SECID)LIKE  '%FUND%' or trim(S.SECID)='EQ ALAHLI GULF' THEN TOTAL_COST_ON_INVESTMENT end SETTLEMENT
FROM SPSH S 
inner join (SELECT * FROM TR_EQU_AND_SEC_OUTSTANDING WHERE TRIM(TYPE)='Investments' AND TRIM(NETQTY) != 0 AND TRIM(NETQTY) IS
 NOT NULL AND CASE WHEN TRIM(SECID)='ABK TREASURY' AND TRIM(PORT) !='TS' THEN 0 ELSE 1  END = 1) z on trim(s.secid) = trim(z.secid)
inner join EQUITY_DEFN_O_TABLE ed on trim(ed.NAME) = trim(z.secid)  
LEFT JOIN CUST C ON TRIM(C.cmne)=TRIM(ed.ISSUER_STRING)
LEFT JOIN TREASURY_CUSTODION ON TRIM(SECURITY_OR_EQUITIES) = TRIM(s.SECID)
WHERE TRIM(s.SECID) IN (SELECT TRIM(SECID) FROM TR_EQU_AND_SEC_OUTSTANDING WHERE TRIM(TYPE)='Investments' AND TRIM(NETQTY) != 0 AND TRIM(NETQTY) IS NOT NULL AND CASE WHEN TRIM(SECID)='ABK TREASURY' 
AND TRIM(PORT) !='TS' THEN 0 ELSE 1  END = 1)
--DEALDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(S.PRODTYPE) IN ('E1','E2','T1')
;
UPDATE EQUITY_MF_O_TABLE SET DEAL_IDENTIFIER='444'||lpad(rownum,'4','0');
COMMIT;
EXIT;
