TRUNCATE TABLE FX_SWAP_O_TABLE;
INSERT INTO FX_SWAP_O_TABLE
select DISTINCT
'' Response,
CASE WHEN TRIM(A.PORT) ='CORP' THEN 'FX_SWAP_SPOT_FWD_SALES' ELSE 'FX_SWAP_SPOT_FWD_MARKET' END PRODUCT_TYPE,
TO_CHAR(TO_DATE(A.DEALDATE,'YYYY-MM-DD'),'DD-Mon-YYYY')  DEAL_DATE,--***
A.DEALNO DEAL_IDENTIFIER,
CASE WHEN trim(A.PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(A.PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END TRADING_BOOK,
CASE WHEN TRIM(A.BR)='01' AND trim(A.PORT) = 'CORP' THEN 'CORP'
     WHEN TRIM(A.BR)='01' AND trim(A.PORT) != 'CORP' THEN 'BANK'
     WHEN TRIM(A.BR)='51' AND TRIM(C.BIC) IS NULL THEN 'CORP'
     WHEN TRIM(A.BR)='51' AND TRIM(C.BIC) IS NOT NULL THEN 'BANK'
END SUBTYPE,
'FX' DEPT_NAME,--*** We had mapped to PRODCODE column
CASE WHEN A.BR=1 THEN 'ABKKWT' ELSE 'ABKUAE' END ENTITY_NAME,
'' ACCOUNTING_CODE,
CASE WHEN A.CCYTERMS='M' THEN TRIM(A.CCY)||'/'||TRIM(A.CTRCCY) ELSE TRIM(A.CTRCCY)||'/'||TRIM(A.CCY) END  NEAR_LEG_CCY_PAIR,
A.DISAGGCCY DCO_CURRENCY,
TRIM(a.ccy) TRADED_CCY,--CASE WHEN A.CCYTERMS='M' THEN A.CTRCCY ELSE A.CCY
trim(CMNE) NEAR_LEG_CPTY,
CASE WHEN A.PS='P' AND A.CCYTERMS='M' THEN 'BUY'    
     WHEN A.PS='S' AND A.CCYTERMS='M' THEN 'SELL'   
     WHEN A.PS='P' AND A.CCYTERMS='D' THEN 'SELL'
     WHEN A.PS='S' AND A.CCYTERMS='D' THEN 'BUY' 
END NEAR_LEG_FX_BUY_SELL,
TO_CHAR(CASE WHEN A.CCYTERMS='M' THEN ABS(A.CCYAMT) ELSE ABS(A.CTRAMT) END,'9999999999999999990.99999999') NEAR_LEG_CCY_ONE_AMOUNT,
TO_CHAR(A.CCYRATE_8-CASE WHEN TRIM(A.PORT) ='CORP' THEN TO_CHAR(A.CORPSPREAD_8,'99999990.99999999') else '0' END,'9999999999999999999.99999999') NEAR_LEG_MARKET_SPOT_RATE,
TO_CHAR(CASE WHEN A.CCYTERMS='D' THEN ABS(A.CCYAMT) ELSE ABS(A.CTRAMT) END,'9999999999999999990.99999999') NEAR_LEG_CCY_TWO_AMOUNT,
TO_CHAR(TO_DATE(A.VDATE,'YYYY-MM-DD'),'DD-Mon-YYYY') NEAR_LEG_VALUE_DATE_ONE,--***
trim(CMNE) FAR_LEG_CPTY,
abs(TO_CHAR(CASE WHEN B.CCYTERMS='M' THEN B.CCYAMT ELSE B.CTRAMT END,'9999999999999999990.99999999')) FAR_LEG_CCY_ONE_AMOUNT,
TO_CHAR(B.CCYRATE_8-CASE WHEN TRIM(A.PORT) ='CORP' THEN TO_CHAR(B.CORPSPREAD_8,'99999990.99999999') else '0' END,'9999999999999999990.99999999') FAR_LEG_MARKET_FWD_RATE,
abs(TO_CHAR(CASE WHEN B.CCYTERMS='D' THEN B.CCYAMT ELSE B.CTRAMT END,'9999999999999999990.99999999')) FAR_LEG_CCY_TWO_AMOUNT,
TO_CHAR(TO_DATE(B.VDATE,'YYYY-MM-DD'),'DD-Mon-YYYY') FAR_LEG_VALUE_DATE_ONE,--***
CASE WHEN A.BR=1 THEN 'ABKKWT' ELSE 'ABKUAE' END NEAR_LEG_SPOT_RISK_ENTITY,
CASE WHEN trim(A.PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(A.PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END NEAR_LEG_SPOT_TRD_BOOK,
CASE WHEN A.BR=1 THEN 'ABKKWT' ELSE 'ABKUAE' END NEAR_LEG_FWD_RISK_ENTITY,
CASE WHEN trim(A.PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(A.PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END NEAR_LEG_FWD_TRD_BOOK,
CASE WHEN B.BR=1 THEN 'ABKKWT' ELSE 'ABKUAE' END FAR_LEG_SPOT_RISK_ENTITY,
CASE WHEN trim(B.PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(B.PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END FAR_LEG_SPOT_TRD_BOOK,
CASE WHEN B.BR=1 THEN 'ABKKWT' ELSE 'ABKUAE' END FAR_LEG_FWD_RISK_ENTITY,
CASE WHEN trim(B.PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(B.PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END FAR_LEG_FWD_TRD_BOOK,
'' "NEAR_LEG.MARKET_SPOT_RATE",
'' "NEAR_LEG.CUSTOMER_SPOT_RATE",
'' "NEAR_LEG.MARKET_FWD_RATE",
'' "NEAR_LEG.CUSTOMER_FWD_RATE",
'' "FAR_LEG.MARKET_SPOT_RATE",
'' "FAR_LEG.CUSTOMER_SPOT_RATE",
'' "FAR_LEG.CUSTOMER_FWD_RATE",
'' "FAR_LEG.MARKET_FWD_POINTS",
'' "FAR_LEG.CUSTOMER_SWAP_POINTS",
'' "FAR_LEG.MARKET_SWAP_POINTS",
'' "DECOMPOSE_CALENDAR_SET",
'' "DCO_1_N_L.MARKET_SPOT_RATE",
'' "DCO_1_N_L.CUSTOMER_SPOT_RATE",
'' "DCO_1_N_L.SPOT_RISK_ENTITY",
'' "DCO_1_N_L.SPOT_TRD_BOOK",
'' "DCO_1_N_L.MARKET_FWD_RATE",
'' "DCO_1_N_L.CUSTOMER_FWD_RATE",
'' "DCO_1_N_L.FWD_RISK_ENTITY",
'' "DCO_2_N_L.MARKET_SPOT_RATE",
'' "DCO_2_N_L.CUSTOMER_SPOT_RATE",
'' "DCO_2_N_L.SPOT_RISK_ENTITY",
'' "DCO_2_N_L.SPOT_TRD_BOOK",
'' "DCO_2_N_L.MARKET_FWD_RATE",
'' "DCO_2_N_L.CUSTOMER_FWD_RATE",
'' "DCO_2_N_L.FWD_RISK_ENTITY",
'' "DCO_1_F_L.MARKET_SPOT_RATE",
'' "DCO_1_F_L.CUSTOMER_SPOT_RATE",
'' "DCO_1_F_L.SPOT_RISK_ENTITY",
'' "DCO_1_F_L.SPOT_TRD_BOOK",
'' "DCO_1_F_L.CUSTOMER_FWD_RATE",
'' "DCO_1_F_L.MARKET_FWD_POINTS",
'' "DCO_1_F_L.CUSTOMER_FWD_POINTS",
'' "DCO_1_F_L.FWD_RISK_ENTITY",
'' "DCO_1_F_L.CUSTOMER_SWAP_POINTS",
'' "DCO_1_F_L.MARKET_SWAP_POINTS",
'' "DCO_2_F_L.MARKET_SPOT_RATE",
'' "DCO_2_F_L.CUSTOMER_SPOT_RATE",
'' "DCO_2_F_L.SPOT_RISK_ENTITY",
'' "DCO_2_F_L.SPOT_TRD_BOOK",
'' "DCO_2_F_L.CUSTOMER_FWD_RATE",
'' "DCO_2_F_L.MARKET_FWD_POINTS",
'' "DCO_2_F_L.CUSTOMER_FWD_POINTS",
'' "DCO_2_F_L.FWD_RISK_ENTITY",
'' "DCO_2_F_L.CUSTOMER_SWAP_POINTS",
'' "DCO_2_F_L.MARKET_SWAP_POINTS",
CASE WHEN TRIM(C.BIC) IS NOT NULL THEN 'SWIFT' ELSE '' END CONFIRM_METHOD,--***
'' SI_FLOW_PAY_SSI_ID,--@@@
CASE WHEN A.PS='P' AND A.CCYTERMS='M' THEN CASE WHEN TRIM(A.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CTRCCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CTRSACCT END  
     WHEN A.PS='S' AND A.CCYTERMS='M' THEN CASE WHEN TRIM(A.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CCYSACCT  END
     WHEN A.PS='P' AND A.CCYTERMS='D' THEN CASE WHEN TRIM(A.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CTRCCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CTRSACCT END 
     WHEN A.PS='S' AND A.CCYTERMS='D' THEN CASE WHEN TRIM(A.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CCYSACCT  END  
END SI_FLOW_PAY_NOSTRO,--A.CCYSACCT SI_FLOW_PAY_NOSTRO,
CASE WHEN ((A.PS='S' AND A.CCYTERMS='M') OR (A.PS='P' AND A.CCYTERMS='D')) AND TRIM(A.CCYSMEANS)='NOS' THEN 'SWIFT'  WHEN ((A.PS='P' AND A.CCYTERMS='M') OR (A.PS='S' AND A.CCYTERMS='D')) AND TRIM(A.CTRSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SI_FLOW_PAY_SETT_METHOD,--***
'' SI_FLOW_PAY_CPTY_AGENT,
'' SI_FLOW_REC_SSI_ID,--@@@
CASE WHEN A.PS='P' AND A.CCYTERMS='M' THEN CASE WHEN TRIM(A.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CCYSACCT  END  
     WHEN A.PS='S' AND A.CCYTERMS='M' THEN CASE WHEN TRIM(A.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CTRCCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CTRSACCT END
     WHEN A.PS='P' AND A.CCYTERMS='D' THEN CASE WHEN TRIM(A.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CCYSACCT  END 
     WHEN A.PS='S' AND A.CCYTERMS='D' THEN CASE WHEN TRIM(A.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CTRCCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CTRSACCT END  
END SI_FLOW_REC_NOSTRO,--A.CTRSACCT SI_FLOW_REC_NOSTRO,
CASE WHEN ((A.PS='S' AND A.CCYTERMS='M') OR (A.PS='P' AND A.CCYTERMS='D')) AND TRIM(A.CTRSMEANS)='NOS' THEN 'SWIFT'  WHEN((A.PS='P' AND A.CCYTERMS='M') OR (A.PS='S' AND A.CCYTERMS='D')) AND TRIM(A.CCYSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SI_FLOW_REC_SETT_METHOD,--***
'' SI_FLOW_REC_CPTY_AGENT,
'' SI_FLOW_FAR_PAY_SSI_ID,--@@@
CASE WHEN A.PS='P' AND B.CCYTERMS='M' THEN CASE WHEN TRIM(B.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CCYSACCT  END  
     WHEN A.PS='S' AND B.CCYTERMS='M' THEN CASE WHEN TRIM(B.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CTRCCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CTRSACCT END
     WHEN A.PS='P' AND B.CCYTERMS='D' THEN CASE WHEN TRIM(B.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CCYSACCT  END 
     WHEN A.PS='S' AND B.CCYTERMS='D' THEN CASE WHEN TRIM(B.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CTRCCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CTRSACCT END  
END SI_FLOW_FAR_PAY_NOSTRO,--B.CCYSACCT SI_FLOW_FAR_PAY_NOSTRO,
CASE WHEN ((A.PS='S' AND A.CCYTERMS='M') OR (A.PS='P' AND A.CCYTERMS='D')) AND TRIM(A.CTRSMEANS)='NOS' THEN 'SWIFT'  WHEN((A.PS='P' AND A.CCYTERMS='M') OR (A.PS='S' AND A.CCYTERMS='D')) AND TRIM(A.CCYSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SI_FLOW_FAR_PAY_SETT_METHOD,--***
'' SI_FLOW_FAR_PAY_CPTY_AGENT,
'' SI_FLOW_FAR_REC_SSI_ID,--@@@
CASE WHEN A.PS='P' AND B.CCYTERMS='M' THEN CASE WHEN TRIM(B.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CTRCCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CTRSACCT END  
     WHEN A.PS='S' AND B.CCYTERMS='M' THEN CASE WHEN TRIM(B.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CCYSACCT  END
     WHEN A.PS='P' AND B.CCYTERMS='D' THEN CASE WHEN TRIM(B.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CTRCCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CTRSACCT END 
     WHEN A.PS='S' AND B.CCYTERMS='D' THEN CASE WHEN TRIM(B.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CCYSACCT  END  
END SI_FLOW_FAR_REC_NOSTRO,--B.CTRSACCT SI_FLOW_FAR_REC_NOSTRO,
CASE WHEN ((A.PS='S' AND A.CCYTERMS='M') OR (A.PS='P' AND A.CCYTERMS='D')) AND TRIM(A.CCYSMEANS)='NOS' THEN 'SWIFT'  WHEN ((A.PS='P' AND A.CCYTERMS='M') OR (A.PS='S' AND A.CCYTERMS='D')) AND TRIM(A.CTRSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SI_FLOW_FAR_REC_SETT_METHOD,--***
'' SI_FLOW_FAR_REC_CPTY_AGENT,
CASE WHEN TRIM(A.PORT) ='CORP' THEN TO_CHAR(A.CORPSPREAD_8,'99999990.99999999') else '0' END NEAR_LEG_SPOT_MARGIN_POINTS,
CASE WHEN TRIM(A.PORT) ='CORP' THEN TO_CHAR(B.CORPSPREAD_8,'99999990.99999999') else '0' END FAR_LEG_SPOT_MARGIN_POINTS 
FROM  FXDH A
INNER JOIN CUST C ON TRIM(A.CUST)=TRIM(C.CNO)
INNER JOIN FXDH B ON A.SWAPDEAL=B.DEALNO AND B.FARNEARIND='F' AND TO_DATE(B.VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')  AND A.BR=B.BR
LEFT JOIN GFPF GF ON TRIM(GF.GFOCID) = TRIM(C.CMNE)
LEFT JOIN MAP_CIF MC ON TRIM(MC.GFCLC)||TRIM(MC.GFCUS) = TRIM(GF.GFCLC)||TRIM(GF.GFCUS) 
WHERE  A.SWAPDEAL>0 AND TRIM(A.REVDATE) IS NULL and A.PRODCODE!='CCS' AND TRIM(C.CMNE)!='CCIRS' AND TRIM(A.PORT)!='EQFX' AND TRIM(B.PORT)!='EQFX' AND TRIM(B.PORT)!='CORP';
COMMIT;
INSERT INTO FX_SWAP_O_TABLE
select DISTINCT
'' Response,
CASE WHEN TRIM(A.PORT) ='CORP' THEN 'FX_SWAP_SPOT_FWD_SALES' ELSE 'FX_SWAP_SPOT_FWD_MARKET' END PRODUCT_TYPE,
TO_CHAR(TO_DATE(A.DEALDATE,'YYYY-MM-DD'),'DD-Mon-YYYY')  DEAL_DATE,--***
A.DEALNO DEAL_IDENTIFIER,
CASE WHEN trim(A.PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(A.PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END TRADING_BOOK,
CASE WHEN TRIM(A.BR)='01' AND trim(A.PORT) = 'CORP' THEN 'CORP'
     WHEN TRIM(A.BR)='01' AND trim(A.PORT) != 'CORP' THEN 'BANK'
     WHEN TRIM(A.BR)='51' AND TRIM(C.BIC) IS NULL THEN 'CORP'
     WHEN TRIM(A.BR)='51' AND TRIM(C.BIC) IS NOT NULL THEN 'BANK'
END SUBTYPE,
'FX' DEPT_NAME,--*** We had mapped to PRODCODE column
CASE WHEN A.BR=1 THEN 'ABKKWT' ELSE 'ABKUAE' END ENTITY_NAME,
'' ACCOUNTING_CODE,
CASE WHEN A.CCYTERMS='M' THEN TRIM(A.CCY)||'/'||TRIM(A.CTRCCY) ELSE TRIM(A.CTRCCY)||'/'||TRIM(A.CCY) END  NEAR_LEG_CCY_PAIR,
A.DISAGGCCY DCO_CURRENCY,
TRIM(a.ccy)  TRADED_CCY,--CASE WHEN A.CCYTERMS='M' THEN A.CTRCCY ELSE A.CCY
trim(CMNE) NEAR_LEG_CPTY,
CASE WHEN A.PS='P' AND A.CCYTERMS='M' THEN 'BUY'    
     WHEN A.PS='S' AND A.CCYTERMS='M' THEN 'SELL'   
     WHEN A.PS='P' AND A.CCYTERMS='D' THEN 'SELL'
     WHEN A.PS='S' AND A.CCYTERMS='D' THEN 'BUY' 
END NEAR_LEG_FX_BUY_SELL,
TO_CHAR(CASE WHEN A.CCYTERMS='M' THEN ABS(A.CCYAMT) ELSE ABS(A.CTRAMT) END,'9999999999999999990.99999999') NEAR_LEG_CCY_ONE_AMOUNT,
TO_CHAR(A.CCYRATE_8,'9999999999999999999.99999999') NEAR_LEG_CUSTOMER_SPOT_RATE,
TO_CHAR(CASE WHEN A.CCYTERMS='D' THEN ABS(A.CCYAMT) ELSE ABS(A.CTRAMT) END,'9999999999999999990.99999999') NEAR_LEG_CCY_TWO_AMOUNT,
TO_CHAR(TO_DATE(A.VDATE,'YYYY-MM-DD'),'DD-Mon-YYYY') NEAR_LEG_VALUE_DATE_ONE,--***
trim(CMNE) FAR_LEG_CPTY,
abs(TO_CHAR(CASE WHEN B.CCYTERMS='M' THEN B.CCYAMT ELSE B.CTRAMT END,'9999999999999999990.99999999')) FAR_LEG_CCY_ONE_AMOUNT,
TO_CHAR(B.CCYRATE_8,'9999999999999999990.99999999') FAR_LEG_CUSTOMER_FWD_RATE,
abs(TO_CHAR(CASE WHEN B.CCYTERMS='D' THEN B.CCYAMT ELSE B.CTRAMT END,'9999999999999999990.99999999')) FAR_LEG_CCY_TWO_AMOUNT,
TO_CHAR(TO_DATE(B.VDATE,'YYYY-MM-DD'),'DD-Mon-YYYY') FAR_LEG_VALUE_DATE_ONE,--***
CASE WHEN A.BR=1 THEN 'ABKKWT' ELSE 'ABKUAE' END NEAR_LEG_SPOT_RISK_ENTITY,
CASE WHEN trim(A.PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(A.PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END NEAR_LEG_SPOT_TRD_BOOK,
CASE WHEN A.BR=1 THEN 'ABKKWT' ELSE 'ABKUAE' END NEAR_LEG_FWD_RISK_ENTITY,
CASE WHEN trim(A.PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(A.PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(A.PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END NEAR_LEG_FWD_TRD_BOOK,
CASE WHEN B.BR=1 THEN 'ABKKWT' ELSE 'ABKUAE' END FAR_LEG_SPOT_RISK_ENTITY,
CASE WHEN trim(B.PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(B.PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END FAR_LEG_SPOT_TRD_BOOK,
CASE WHEN B.BR=1 THEN 'ABKKWT' ELSE 'ABKUAE' END FAR_LEG_FWD_RISK_ENTITY,
CASE WHEN trim(B.PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(B.PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(B.PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END FAR_LEG_FWD_TRD_BOOK,
TO_CHAR(A.INTERNALRATE_8,'9999999999999999990.99999999') "NEAR_LEG.MARKET_SPOT_RATE",
'' "NEAR_LEG.CUSTOMER_SPOT_RATE",
'' "NEAR_LEG.MARKET_FWD_RATE",
'' "NEAR_LEG.CUSTOMER_FWD_RATE",
TO_CHAR(B.INTERNALRATE_8,'9999999999999999990.99999999') "FAR_LEG.MARKET_SPOT_RATE",
'' "FAR_LEG.CUSTOMER_SPOT_RATE",
'' "FAR_LEG.CUSTOMER_FWD_RATE",
TO_CHAR(B.CCYPD_8,'9999999999999999990.99999999')  "FAR_LEG.MARKET_FWD_POINTS",
'' "FAR_LEG.CUSTOMER_SWAP_POINTS",
'' "FAR_LEG.MARKET_SWAP_POINTS",
'' "DECOMPOSE_CALENDAR_SET",
'' "DCO_1_N_L.MARKET_SPOT_RATE",
'' "DCO_1_N_L.CUSTOMER_SPOT_RATE",
'' "DCO_1_N_L.SPOT_RISK_ENTITY",
'' "DCO_1_N_L.SPOT_TRD_BOOK",
'' "DCO_1_N_L.MARKET_FWD_RATE",
'' "DCO_1_N_L.CUSTOMER_FWD_RATE",
'' "DCO_1_N_L.FWD_RISK_ENTITY",
'' "DCO_2_N_L.MARKET_SPOT_RATE",
'' "DCO_2_N_L.CUSTOMER_SPOT_RATE",
'' "DCO_2_N_L.SPOT_RISK_ENTITY",
'' "DCO_2_N_L.SPOT_TRD_BOOK",
'' "DCO_2_N_L.MARKET_FWD_RATE",
'' "DCO_2_N_L.CUSTOMER_FWD_RATE",
'' "DCO_2_N_L.FWD_RISK_ENTITY",
'' "DCO_1_F_L.MARKET_SPOT_RATE",
'' "DCO_1_F_L.CUSTOMER_SPOT_RATE",
'' "DCO_1_F_L.SPOT_RISK_ENTITY",
'' "DCO_1_F_L.SPOT_TRD_BOOK",
'' "DCO_1_F_L.CUSTOMER_FWD_RATE",
'' "DCO_1_F_L.MARKET_FWD_POINTS",
'' "DCO_1_F_L.CUSTOMER_FWD_POINTS",
'' "DCO_1_F_L.FWD_RISK_ENTITY",
'' "DCO_1_F_L.CUSTOMER_SWAP_POINTS",
'' "DCO_1_F_L.MARKET_SWAP_POINTS",
'' "DCO_2_F_L.MARKET_SPOT_RATE",
'' "DCO_2_F_L.CUSTOMER_SPOT_RATE",
'' "DCO_2_F_L.SPOT_RISK_ENTITY",
'' "DCO_2_F_L.SPOT_TRD_BOOK",
'' "DCO_2_F_L.CUSTOMER_FWD_RATE",
'' "DCO_2_F_L.MARKET_FWD_POINTS",
'' "DCO_2_F_L.CUSTOMER_FWD_POINTS",
'' "DCO_2_F_L.FWD_RISK_ENTITY",
'' "DCO_2_F_L.CUSTOMER_SWAP_POINTS",
'' "DCO_2_F_L.MARKET_SWAP_POINTS",
CASE WHEN TRIM(C.BIC) IS NOT NULL THEN 'SWIFT' ELSE '' END CONFIRM_METHOD,--***
'' SI_FLOW_PAY_SSI_ID,--@@@
CASE WHEN A.PS='P' AND A.CCYTERMS='M' THEN CASE WHEN TRIM(A.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CTRCCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CTRSACCT END  
     WHEN A.PS='S' AND A.CCYTERMS='M' THEN CASE WHEN TRIM(A.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CCYSACCT  END
     WHEN A.PS='P' AND A.CCYTERMS='D' THEN CASE WHEN TRIM(A.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CTRCCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CTRSACCT END 
     WHEN A.PS='S' AND A.CCYTERMS='D' THEN CASE WHEN TRIM(A.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CCYSACCT  END  
END SI_FLOW_PAY_NOSTRO,--A.CCYSACCT SI_FLOW_PAY_NOSTRO,
CASE WHEN ((A.PS='S' AND A.CCYTERMS='M') OR (A.PS='P' AND A.CCYTERMS='D')) AND TRIM(A.CCYSMEANS)='NOS' THEN 'SWIFT'  WHEN ((A.PS='P' AND A.CCYTERMS='M') OR (A.PS='S' AND A.CCYTERMS='D')) AND TRIM(A.CTRSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SI_FLOW_PAY_SETT_METHOD,--***
'' SI_FLOW_PAY_CPTY_AGENT,
'' SI_FLOW_REC_SSI_ID,--@@@
CASE WHEN A.PS='P' AND A.CCYTERMS='M' THEN CASE WHEN TRIM(A.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CCYSACCT  END  
     WHEN A.PS='S' AND A.CCYTERMS='M' THEN CASE WHEN TRIM(A.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CTRCCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CTRSACCT END
     WHEN A.PS='P' AND A.CCYTERMS='D' THEN CASE WHEN TRIM(A.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CCYSACCT  END 
     WHEN A.PS='S' AND A.CCYTERMS='D' THEN CASE WHEN TRIM(A.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(A.CTRCCY)||CASE WHEN TRIM(A.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE A.CTRSACCT END  
END SI_FLOW_REC_NOSTRO,--A.CTRSACCT SI_FLOW_REC_NOSTRO,
CASE WHEN ((A.PS='S' AND A.CCYTERMS='M') OR (A.PS='P' AND A.CCYTERMS='D')) AND TRIM(A.CTRSMEANS)='NOS' THEN 'SWIFT'  WHEN((A.PS='P' AND A.CCYTERMS='M') OR (A.PS='S' AND A.CCYTERMS='D')) AND TRIM(A.CCYSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SI_FLOW_REC_SETT_METHOD,--***
'' SI_FLOW_REC_CPTY_AGENT,
'' SI_FLOW_FAR_PAY_SSI_ID,--@@@
CASE WHEN A.PS='P' AND B.CCYTERMS='M' THEN CASE WHEN TRIM(B.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CCYSACCT  END  
     WHEN A.PS='S' AND B.CCYTERMS='M' THEN CASE WHEN TRIM(B.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CTRCCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CTRSACCT END
     WHEN A.PS='P' AND B.CCYTERMS='D' THEN CASE WHEN TRIM(B.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CCYSACCT  END 
     WHEN A.PS='S' AND B.CCYTERMS='D' THEN CASE WHEN TRIM(B.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CTRCCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CTRSACCT END  
END SI_FLOW_FAR_PAY_NOSTRO,--B.CCYSACCT SI_FLOW_FAR_PAY_NOSTRO,
CASE WHEN ((A.PS='S' AND A.CCYTERMS='M') OR (A.PS='P' AND A.CCYTERMS='D')) AND TRIM(A.CTRSMEANS)='NOS' THEN 'SWIFT'  WHEN((A.PS='P' AND A.CCYTERMS='M') OR (A.PS='S' AND A.CCYTERMS='D')) AND TRIM(A.CCYSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SI_FLOW_FAR_PAY_SETT_METHOD,--***
'' SI_FLOW_FAR_PAY_CPTY_AGENT,
'' SI_FLOW_FAR_REC_SSI_ID,--@@@
CASE WHEN A.PS='P' AND B.CCYTERMS='M' THEN CASE WHEN TRIM(B.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CTRCCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CTRSACCT END  
     WHEN A.PS='S' AND B.CCYTERMS='M' THEN CASE WHEN TRIM(B.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CCYSACCT  END
     WHEN A.PS='P' AND B.CCYTERMS='D' THEN CASE WHEN TRIM(B.CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CTRCCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CTRSACCT END 
     WHEN A.PS='S' AND B.CCYTERMS='D' THEN CASE WHEN TRIM(B.CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(B.CCY)||CASE WHEN TRIM(B.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE B.CCYSACCT  END  
END SI_FLOW_FAR_REC_NOSTRO,--B.CTRSACCT SI_FLOW_FAR_REC_NOSTRO,
CASE WHEN ((A.PS='S' AND A.CCYTERMS='M') OR (A.PS='P' AND A.CCYTERMS='D')) AND TRIM(A.CCYSMEANS)='NOS' THEN 'SWIFT'  WHEN ((A.PS='P' AND A.CCYTERMS='M') OR (A.PS='S' AND A.CCYTERMS='D')) AND TRIM(A.CTRSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SI_FLOW_FAR_REC_SETT_METHOD,--***
'' SI_FLOW_FAR_REC_CPTY_AGENT,
CASE WHEN TRIM(A.PORT) ='CORP' THEN TO_CHAR(A.CORPSPREAD_8,'99999990.99999999') else '0' END NEAR_LEG_SPOT_MARGIN_POINTS,
CASE WHEN TRIM(A.PORT) ='CORP' THEN TO_CHAR(B.CORPSPREAD_8,'99999990.99999999') else '0' END FAR_LEG_SPOT_MARGIN_POINTS 
FROM  FXDH A
INNER JOIN CUST C ON TRIM(A.CUST)=TRIM(C.CNO)
INNER JOIN FXDH B ON A.SWAPDEAL=B.DEALNO AND B.FARNEARIND='F' AND TO_DATE(B.VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')  AND A.BR=B.BR
LEFT JOIN GFPF GF ON TRIM(GF.GFOCID) = TRIM(C.CMNE)
LEFT JOIN MAP_CIF MC ON TRIM(MC.GFCLC)||TRIM(MC.GFCUS) = TRIM(GF.GFCLC)||TRIM(GF.GFCUS) 
WHERE  A.SWAPDEAL>0 AND TRIM(A.REVDATE) IS NULL and A.PRODCODE!='CCS' AND TRIM(C.CMNE)!='CCIRS' AND TRIM(A.PORT)!='EQFX' AND TRIM(B.PORT)!='EQFX' AND TRIM(B.PORT)='CORP';
--UPDATE FX_SWAP_O_TABLE SET SI_FLOW_PAY_NOSTRO='SCBDLE' WHERE TRIM(SI_FLOW_PAY_NOSTRO)='SCBLDE';
--UPDATE FX_SWAP_O_TABLE SET SI_FLOW_REC_NOSTRO='SCBDLE' WHERE TRIM(SI_FLOW_REC_NOSTRO)='SCBLDE';
--UPDATE FX_SWAP_O_TABLE SET SI_FLOW_FAR_REC_NOSTRO='SCBDLE' WHERE TRIM(SI_FLOW_FAR_REC_NOSTRO)='SCBLDE';
--UPDATE FX_SWAP_O_TABLE SET SI_FLOW_FAR_PAY_NOSTRO='SCBDLE' WHERE TRIM(SI_FLOW_FAR_PAY_NOSTRO)='SCBLDE';
--COMMIT;
--UPDATE FX_SWAP_O_TABLE SET SUBTYPE='INTGRP' WHERE TRIM(NEAR_LEG_CPTY)='AEAHLK';
UPDATE FX_SWAP_O_TABLE A SET SI_FLOW_PAY_SSI_ID=(SELECT TRIM(SSI_ID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE 
 ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) AND TRIM(A.NEAR_LEG_CPTY)=TRIM(B.CPTY_NAME) AND 
TRIM(B.NOSTRO_ID) = TRIM(A.SI_FLOW_PAY_NOSTRO) AND SUBSTR(TRIM(A.NEAR_LEG_CCY_PAIR),1,3) = TRIM(B.CURRENCY));
UPDATE FX_SWAP_O_TABLE A SET SI_FLOW_REC_SSI_ID=(SELECT TRIM(SSI_ID) FROM (SELECT * FROM TREASURY_REC_SSI_O_TABLE WHERE 
ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_REC_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) 
UNION SELECT * FROM TREASURY_PAY_SSI_O_TABLE WHERE ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) 
) B WHERE TRIM(A.NEAR_LEG_CPTY)=TRIM(B.CPTY_NAME) AND 
TRIM(B.NOSTRO_ID) = TRIM(A.SI_FLOW_REC_NOSTRO) AND SUBSTR(TRIM(A.NEAR_LEG_CCY_PAIR),5,3) = TRIM(B.CURRENCY));
UPDATE FX_SWAP_O_TABLE A SET SI_FLOW_FAR_PAY_SSI_ID=(SELECT TRIM(SSI_ID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE 
 ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) AND TRIM(A.FAR_LEG_CPTY)=TRIM(B.CPTY_NAME) AND 
TRIM(B.NOSTRO_ID) = TRIM(A.SI_FLOW_FAR_PAY_NOSTRO) AND SUBSTR(TRIM(A.NEAR_LEG_CCY_PAIR),5,3) = TRIM(B.CURRENCY));
UPDATE FX_SWAP_O_TABLE A SET SI_FLOW_FAR_REC_SSI_ID=(SELECT TRIM(SSI_ID) FROM (SELECT * FROM TREASURY_REC_SSI_O_TABLE WHERE 
ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_REC_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) 
UNION SELECT * FROM TREASURY_PAY_SSI_O_TABLE WHERE ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) 
) B WHERE TRIM(A.FAR_LEG_CPTY)=TRIM(B.CPTY_NAME) AND 
TRIM(B.NOSTRO_ID) = TRIM(A.SI_FLOW_FAR_REC_NOSTRO) AND SUBSTR(TRIM(A.NEAR_LEG_CCY_PAIR),1,3) = TRIM(B.CURRENCY));
COMMIT;
EXIT; 
