TRUNCATE TABLE INTERNAL_DEALS_O_TABLE;
INSERT INTO INTERNAL_DEALS_O_TABLE
SELECT TRIM(DEALNO) DEAL_IDENTIFIER,
       to_char(DEALDATE,'dd-Mon-yyyy') DEAL_DATE,
       to_char(VDATE,'dd-Mon-yyyy') START_DATE,
       to_char(MDATE,'dd-Mon-yyyy') END_DATE,
       CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END CURRENCY_PAIR,
       CASE WHEN CTRPRINAMT<0 THEN 'SELL' ELSE 'BUY' END BUY_SELL,
       TO_CHAR(BID,'999990.99999999') SPOTRATE,
       CASE WHEN CTRPRINAMT <0 THEN SUBSTR(CCYBASIS,1,1)||'/'||SUBSTR(CCYBASIS,2,3)  ELSE SUBSTR(CTRBASIS,1,1)||'/'||SUBSTR(CTRBASIS,2,3)  END DEPO_BASIS,
       CASE WHEN CTRPRINAMT <0 THEN SUBSTR(CTRBASIS,1,1)||'/'||SUBSTR(CTRBASIS,2,3) ELSE SUBSTR(CCYBASIS,1,1)||'/'||SUBSTR(CCYBASIS,2,3) END LOAN_BASIS,
       CCYNEARRATE_8 NEAR_RATE,
       ABS(case when  CTRPRINAMT < 0 then CCYPRINAMT  else CTRPRINAMT  end) RIGHT_NEAR_VAL,
       ABS(case when  CTRPRINAMT < 0 then CTRPRINAMT  else  CCYPRINAMT end) LEFT_NEAR_VAL,
       ABS(CTRAMT) LT_F_VAL,
       ABS(CCYAMT) RT_F_VAL,
       CCYFARRATE_8 FWD_CTRCT_RATE,
       CASE WHEN CTRPRINAMT<0 THEN TO_CHAR(CCYINTRATE_8,'999990.99999999') ELSE TO_CHAR(CTRINTRATE_8,'999990.99999999') END  DEPO_RATE,
       CASE WHEN CTRPRINAMT<0 THEN TO_CHAR(CTRINTRATE_8,'999990.99999999')  ELSE TO_CHAR(CCYINTRATE_8,'999990.99999999')END  LOAN_RATE
  FROM FXIH
  LEFT JOIN SPOT_RATES_O_TABLE ON CURRENCY_PAIR = CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END
  WHERE MDATE > to_date(get_param('EOD_DATE'),'dd-mm-yyyy') AND BR = '01' AND REVDATE IS NULL;
  COMMIT;
  EXIT; 
