TRUNCATE TABLE FX_INTERANL_NEAR_DEALS_O_TABLE;
INSERT INTO FX_INTERANL_NEAR_DEALS_O_TABLE
SELECT DISTINCT
'' Response,
CASE WHEN TRIM(F.PORT) ='CORP' THEN 'FX_SPOT_SALES' ELSE 'FX_SPOT_MARKET' END PRODUCT_TYPE,
to_char(DEALDATE,'dd-Mon-yyyy') DEAL_DATE,--***
trim(DEALNO)||'_INTERANL_NEAR_REV' DEAL_IDENTIFIER,
CASE WHEN trim(PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END TRADING_BOOK,
CASE WHEN trim(PORT)='FXBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(PORT)='CORP' THEN '/ABK/KUWAIT/BANKING/FX/TREASURY'
     WHEN trim(PORT)='FXTR' THEN '/ABK/KUWAIT/TRADING/FX/DEALER1'
     WHEN trim(PORT)='PORT' THEN '/ABK/KUWAIT/TRADING/DERIVATIVES/DEALER1'
     END MAIN_LEG_SPOT_TRD_BOOK,
'BANK' SUBTYPE,
'FX' DEPT_NAME,--*** We had mapped to PRODCODE column
'' ACCOUNTING_CODE,
CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ENTITY_NAME,
CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END MAIN_LEG_SPOT_RISK_ENTITY,
'ABKKWT' MAIN_LEG_CPTY,
CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END MAIN_LEG_CCY_PAIR,
case when  TRIM(CCY)||'/'||TRIM(CTRCCY) like '%KWD%' then 'KWD'  when TRIM(CCY)||'/'||TRIM(CTRCCY) like '%USD%' then 'USD'  else TRIM(CTRCCY) end  SPOT_RISK_CCY,
'' DCO_CURRENCY,
CASE WHEN PS='P' AND CCYTERMS='M' THEN 'SELL' 
     WHEN PS='S' AND CCYTERMS='M' THEN 'BUY'
     WHEN PS='P' AND CCYTERMS='D' THEN 'BUY'
     WHEN PS='S' AND CCYTERMS='D' THEN 'SELL' 
     END MAIN_LEG_FX_BUY_SELL,
TO_CHAR(ABS(CCYPRINAMT),'9999999999999999990.99999999') MAIN_LEG_CCY_ONE_AMOUNT,
TO_CHAR(CCYNEARRATE_8,'9999999999999999990.99999999') MAIN_LEG_MARKET_SPOT_RATE, ----NEEDS TO CHECK PROPER LOGIC TO AVAIL CORRECT VALUE
TO_CHAR(ABS(CTRPRINAMT),'9999999999999999990.99999999') MAIN_LEG_CCY_TWO_AMOUNT,
to_char(VDATE,'dd-Mon-yyyy')  MAIN_LEG_VALUE_DATE_ONE,--***
TRIM(DEALTEXT) MEMO_FIELD_1,
'' CONFIRM_METHOD,--***
'' SI_FLOW_PAY_SSI_ID,--@@@
'' SI_FLOW_PAY_NOSTRO,--CASE WHEN TRIM(PS)='S' THEN CCYSACCT ELSE CTRSACCT END SI_FLOW_PAY_NOSTRO,
'' SI_FLOW_PAY_SETT_METHOD,--***CASE WHEN TRIM(PS)='S' AND TRIM(CCYSMEANS)='NOS' THEN 'SWIFT' ELSE '' END
'' SI_FLOW_PAY_CPTY_AGENT,
'' SI_FLOW_REC_SSI_ID,--@@@@
'' SI_FLOW_REC_NOSTRO,--CASE WHEN TRIM(PS)='S' THEN CTRSACCT ELSE CCYSACCT END SI_FLOW_REC_NOSTRO,
'' SI_FLOW_REC_SETT_METHOD,--***CASE WHEN TRIM(PS)='S' AND TRIM(CTRSMEANS)='NOS' THEN 'SWIFT' ELSE '' END
'' SI_FLOW_REC_CPTY_AGENT,
'' SPOT_MARGIN_POINTS
FROM FXIH F
WHERE MDATE > to_date(get_param('EOD_DATE'),'dd-mm-yyyy') AND BR = '01'
        AND REVDATE IS NULL  and VDATE <= to_date(get_param('EOD_DATE'),'dd-mm-yyyy');
COMMIT;
EXIT;
 
