TRUNCATE TABLE INTEREST_RATES_O_TABLE;
INSERT INTO INTEREST_RATES_O_TABLE
SELECT 
'' Response,
SUBSTR(CONTRIBRATE,1,3)||'-LIBOR' Curve_ID,
SUBSTR(CONTRIBRATE,4,4) Type,
Y.MTYEND Nominal,
SUBSTR(R.BASIS,1,1)||'/'||SUBSTR(R.BASIS,2) Basis,
Y.BIDRATE_8 Bid,
Y.OFFERRATE_8 Offer,
TO_CHAR(Y.BPDATA,'DD-Mon-YYYY') Base_Date
FROM YCRH Y
INNER JOIN RATE R ON R.CCY=Y.CCY
where -- y.ccy in ('USD',case when get_param('BANK_ID')='01' then 'KWD' when get_param('BANK_ID')='02' then 'AED' end) and 
y.BIDRATE_8 <> 0
and Y.BPDATA > TO_DATE('01-01-2013','DD-MM-YYYY') 
--AND TRIM(CONTRIBRATE) !='SWAP'
GROUP BY SUBSTR(CONTRIBRATE,1,3)||'-LIBOR',SUBSTR(CONTRIBRATE,4,4),Y.MTYEND,R.BASIS,Y.BIDRATE_8,Y.OFFERRATE_8,Y.BPDATA ;
commit;
INSERT INTO INTEREST_RATES_O_TABLE
SELECT 
'' Response,
SUBSTR(CONTRIBRATE,1,3)||'-LIBOR' Curve_ID,
SUBSTR(CONTRIBRATE,4,4) Type,
Y.MTYEND Nominal,
SUBSTR(R.BASIS,1,1)||'/'||SUBSTR(R.BASIS,2) Basis,
Y.BIDRATE_8 Bid,
Y.OFFERRATE_8 Offer,
TO_CHAR(Y.BPDATA,'DD-Mon-YYYY') Base_Date
FROM YCRH Y
INNER JOIN RATE R ON R.CCY=Y.CCY
where  y.ccy NOT in ('USD',case when get_param('BANK_ID')='01' then 'KWD' when get_param('BANK_ID')='02' then 'AED' end) and y.BIDRATE_8 <> 0 AND Y.BPDATA=to_date(get_param('EOD_DATE'),'dd-mm-yyyy')
--AND TRIM(CONTRIBRATE) !='SWAP'
GROUP BY SUBSTR(CONTRIBRATE,1,3)||'-LIBOR',SUBSTR(CONTRIBRATE,4,4),Y.MTYEND,R.BASIS,Y.BIDRATE_8,Y.OFFERRATE_8,Y.BPDATA ;
commit;
EXIT; 
