
--ACCOUNT WISE TTUM4_TRY
select ACCOUNT_NUMBER,CURRENCY_CODE,CASE WHEN PART_TRAN_TYPE='D' THEN -1  ELSE 1 END *SUM(TRANSACTION_AMOUNT) TRANSACTION_AMOUNT from TTUM4_TRY_O_TABLE 
where NOT regexp_like (ACCOUNT_NUMBER,'[A-Z]') GROUP BY ACCOUNT_NUMBER,PART_TRAN_TYPE,CURRENCY_CODE;

--ACCOUNT WISE FINACLE
SELECT FORACID,ACCT_CRNCY_CODE,SUM(CLR_BAL_AMT) FROM TBAADM.GAM@DM2 WHERE FORACID IN(SELECT TRIM(ACCOUNT_NUMBER) from TTUM4_TRY_O_TABLE 
where NOT regexp_like (ACCOUNT_NUMBER,'[A-Z]'))  AND BANK_ID='01' GROUP BY FORACID,ACCT_CRNCY_CODE;


SELECT ACCOUNT_NUMBER, CURRENCY_CODE, TRANSACTION_AMOUNT, FORACID, ACCT_CRNCY_CODE, CLR_BAL_AMT,TRANSACTION_AMOUNT-CLR_BAL_AMT DIFFERENCE FROM (
select ACCOUNT_NUMBER,CURRENCY_CODE,CASE WHEN PART_TRAN_TYPE='D' THEN -1  ELSE 1 END *SUM(TRANSACTION_AMOUNT) TRANSACTION_AMOUNT from TTUM4_TRY_O_TABLE 
where NOT regexp_like (ACCOUNT_NUMBER,'[A-Z]') GROUP BY ACCOUNT_NUMBER,PART_TRAN_TYPE,CURRENCY_CODE
)A 
LEFT JOIN 
(
SELECT FORACID,ACCT_CRNCY_CODE,SUM(CLR_BAL_AMT) CLR_BAL_AMT FROM TBAADM.GAM@DM2 WHERE FORACID IN(SELECT TRIM(ACCOUNT_NUMBER) from TTUM4_TRY_O_TABLE 
where NOT regexp_like (ACCOUNT_NUMBER,'[A-Z]'))  AND BANK_ID='01' GROUP BY FORACID,ACCT_CRNCY_CODE
) B ON TRIM(A.ACCOUNT_NUMBER) = B.FORACID AND TRIM(CURRENCY_CODE) = TRIM(ACCT_CRNCY_CODE)

SELECT GL_SUB_HEAD_CODE,ACCT_CRNCY_CODE,SUM(CLR_BAL_AMT) FROM TBAADM.GAM@DM2 WHERE FORACID IN(SELECT TRIM(ACCOUNT_NUMBER) from TTUM4_TRY_O_TABLE 
where regexp_like (ACCOUNT_NUMBER,'[A-Z]'))  AND BANK_ID='01' GROUP BY GL_SUB_HEAD_CODE,ACCT_CRNCY_CODE;

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--GLSH WISE TTUM4_TRY
SELECT GLSH,CURRENCY_CODE,SUM(TRANSACTION_AMOUNT) TRANSACTION_AMOUNT FROM(
select SUBSTR(ACCOUNT_NUMBER,6,5) GLSH,CURRENCY_CODE,CASE WHEN PART_TRAN_TYPE='D' THEN -1  ELSE 1 END *SUM(TRANSACTION_AMOUNT) TRANSACTION_AMOUNT from TTUM4_TRY_O_TABLE 
where NOT regexp_like (ACCOUNT_NUMBER,'[A-Z]') GROUP BY SUBSTR(ACCOUNT_NUMBER,6,5),PART_TRAN_TYPE,CURRENCY_CODE
) GROUP BY GLSH,CURRENCY_CODE;


--GLSH WISE FINACLE
SELECT GL_SUB_HEAD_CODE,ACCT_CRNCY_CODE,SUM(CLR_BAL_AMT) FROM TBAADM.GAM@DM2 WHERE FORACID IN(SELECT TRIM(ACCOUNT_NUMBER) from TTUM4_TRY_O_TABLE 
where NOT regexp_like (ACCOUNT_NUMBER,'[A-Z]'))  AND BANK_ID='01' GROUP BY GL_SUB_HEAD_CODE,ACCT_CRNCY_CODE;


SELECT GLSH, CURRENCY_CODE, TRANSACTION_AMOUNT, GL_SUB_HEAD_CODE, ACCT_CRNCY_CODE, CLR_BAL_AMT,TRANSACTION_AMOUNT-CLR_BAL_AMT DIFFERENCE FROM (
SELECT GLSH,CURRENCY_CODE,SUM(TRANSACTION_AMOUNT) TRANSACTION_AMOUNT FROM(
select SUBSTR(ACCOUNT_NUMBER,6,5) GLSH,CURRENCY_CODE,CASE WHEN PART_TRAN_TYPE='D' THEN -1  ELSE 1 END *SUM(TRANSACTION_AMOUNT) TRANSACTION_AMOUNT from TTUM4_TRY_O_TABLE 
where NOT regexp_like (ACCOUNT_NUMBER,'[A-Z]') GROUP BY SUBSTR(ACCOUNT_NUMBER,6,5),PART_TRAN_TYPE,CURRENCY_CODE
) GROUP BY GLSH,CURRENCY_CODE
)A 
LEFT JOIN 
(
SELECT GL_SUB_HEAD_CODE,ACCT_CRNCY_CODE,SUM(CLR_BAL_AMT) CLR_BAL_AMT FROM TBAADM.GAM@DM2 WHERE FORACID IN(SELECT TRIM(ACCOUNT_NUMBER) from TTUM4_TRY_O_TABLE 
where NOT regexp_like (ACCOUNT_NUMBER,'[A-Z]'))  AND BANK_ID='01' GROUP BY GL_SUB_HEAD_CODE,ACCT_CRNCY_CODE
) B ON TRIM(A.GLSH) = B.GL_SUB_HEAD_CODE AND TRIM(CURRENCY_CODE) = TRIM(ACCT_CRNCY_CODE)

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--MIGRA ACCOUNTS
SELECT GL_SUB_HEAD_CODE,ACCT_CRNCY_CODE,SUM(CLR_BAL_AMT) FROM TBAADM.GAM@DM2 WHERE FORACID IN(SELECT TRIM(ACCOUNT_NUMBER) from TTUM4_TRY_O_TABLE 
where regexp_like (ACCOUNT_NUMBER,'[A-Z]'))  AND BANK_ID='01' GROUP BY GL_SUB_HEAD_CODE,ACCT_CRNCY_CODE; 
