update treasury_product_mapping set DEPT_NAME = trim(DEPT_NAME), INDICATOR= trim(INDICATOR), SUBTYPE= trim(SUBTYPE),BORROWING_BACID = trim(BORROWING_BACID),PLACEMENT_BACID=trim(PLACEMENT_BACID), CONTINGENT_LIABILITY_BACID= trim(CONTINGENT_LIABILITY_BACID),
 CONTG_LIABILITY_CONTRA_BACID= trim(CONTG_LIABILITY_CONTRA_BACID), CONTINGENT_ASSET_BACID= trim(CONTINGENT_ASSET_BACID), CONTINGENT_ASSET_CONTRA_BACID= trim(CONTINGENT_ASSET_CONTRA_BACID), CONTIGENT_GLSH= trim(CONTIGENT_GLSH);
 
 
TRUNCATE TABLE TREASURY_OPEN_DEALS;
--FX SPOT AND OUTRIGHT
INSERT INTO TREASURY_OPEN_DEALS
SELECT DEAL_IDENTIFIER,MAIN_LEG_CPTY MNEMONIC,DEPT_NAME||'_SPOT' PRODUCT_TYPE,SUBTYPE,TO_CHAR(MAIN_LEG_FX_BUY_SELL)  INDICATOR,SUBSTR(MAIN_LEG_CCY_PAIR,1,3) CCY,TO_NUMBER(MAIN_LEG_CCY_ONE_AMOUNT) FCY_AMOUNT 
, B.C8RTE RATE,MAIN_LEG_CCY_ONE_AMOUNT*B.C8RTE KWD_AMOUNT,to_char(case when MAIN_LEG_FX_BUY_SELL='BUY' then 'V1' else 'V2' end) EQU_ACCT_TYPE  FROM FX_SPOT_DEALS_O_TABLE A
LEFT JOIN C8PF B ON  SUBSTR(MAIN_LEG_CCY_PAIR,1,3) = B.C8CCY 
UNION ALL
SELECT  DEAL_IDENTIFIER,MAIN_LEG_CPTY MNEMONIC,DEPT_NAME||'_OUTRIGHT' PRODUCT_TYPE,SUBTYPE,TO_CHAR(MAIN_LEG_FX_BUY_SELL) INDICATOR ,SUBSTR(MAIN_LEG_CCY_PAIR,1,3) CCY ,TO_NUMBER(MAIN_LEG_CCY_ONE_AMOUNT),
B.C8RTE,MAIN_LEG_CCY_ONE_AMOUNT*B.C8RTE,to_char(case when MAIN_LEG_FX_BUY_SELL='BUY' then 'V3' else 'V4' end) equ_acct_type FROM FX_OUTRIGHT_DEALS_O_TABLE A
LEFT JOIN C8PF B ON  SUBSTR(MAIN_LEG_CCY_PAIR,1,3) = B.C8CCY
UNION ALL
SELECT DEAL_IDENTIFIER,MAIN_LEG_CPTY MNEMONIC,DEPT_NAME||'_SPOT' PRODUCT_TYPE,SUBTYPE, case when TO_CHAR(MAIN_LEG_FX_BUY_SELL)='BUY' then 'SELL' else 'BUY' end  INDICATOR,SUBSTR(MAIN_LEG_CCY_PAIR,5) CCY,TO_NUMBER(MAIN_LEG_CCY_TWO_AMOUNT) FCY_AMOUNT
,B.C8RTE RATE,MAIN_LEG_CCY_TWO_AMOUNT*B.C8RTE KWD_AMOUNT,to_char(case when MAIN_LEG_FX_BUY_SELL='BUY' then 'V2' else 'V1' end) EQU_ACCT_TYPE FROM FX_SPOT_DEALS_O_TABLE A
LEFT JOIN C8PF B ON  SUBSTR(MAIN_LEG_CCY_PAIR,5) = B.C8CCY
UNION ALL
SELECT DEAL_IDENTIFIER,MAIN_LEG_CPTY MNEMONIC,DEPT_NAME||'_OUTRIGHT' PRODUCT_TYPE,SUBTYPE, case when TO_CHAR(MAIN_LEG_FX_BUY_SELL)='BUY' then 'SELL' else 'BUY' end INDICATOR,SUBSTR(MAIN_LEG_CCY_PAIR,5),TO_NUMBER(MAIN_LEG_CCY_TWO_AMOUNT),B.C8RTE,
MAIN_LEG_CCY_TWO_AMOUNT*B.C8RTE,to_char(case when MAIN_LEG_FX_BUY_SELL='BUY' then 'V4' else 'V3' end) equ_acct_type  FROM FX_OUTRIGHT_DEALS_O_TABLE A
LEFT JOIN C8PF B ON  SUBSTR(MAIN_LEG_CCY_PAIR,5) = B.C8CCY;

--COMLOAN
INSERT INTO TREASURY_OPEN_DEALS
SELECT TO_CHAR(DEAL_IDENTIFIER) DEAL_IDENTIFIER,COUNTERPARTY_STRING MNEMONIC,DEPT_NAME,SUBTYPE,SIDE_SIDE_ONE_LONG_OR_SHORT,CURRENCY_STRING,
TO_NUMBER(SIDE_SIDE_1_NOTNAL_AMT_VALUE) FCY_AMOUNT,B.C8RTE RATE,SIDE_SIDE_1_NOTNAL_AMT_VALUE*B.C8RTE KWD_AMOUNT,case when c.PRODTYPE='BB' then 'F1'
when c.PRODTYPE='BC' then 'D1'
when c.PRODTYPE='LB' then 'M1'
when c.PRODTYPE='LC' then 'L6'
when c.PRODTYPE='WL' then 'M2'
when c.PRODTYPE='MB' then 'F2' end EQU_ACCT_TYPE FROM COM_LOAN_O_TABLE A
LEFT JOIN C8PF B ON  A.CURRENCY_STRING = B.C8CCY
LEFT JOIN DLDT C ON TRIM(A.DEAL_IDENTIFIER) = TRIM(C.DEALNO)
WHERE TO_DATE(START_DATE,'DD-MON-YYYY') <= TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY')
UNION ALL
SELECT TO_CHAR(DEAL_IDENTIFIER) DEAL_IDENTIFIER,COUNTERPARTY_STRING MNEMONIC,DEPT_NAME,SUBTYPE,SIDE_SIDE_ONE_LONG_OR_SHORT,CURRENCY_STRING,
TO_NUMBER(SIDE_SIDE_1_NOTNAL_AMT_VALUE) FCY_AMOUNT,B.C8RTE RATE,SIDE_SIDE_1_NOTNAL_AMT_VALUE*B.C8RTE KWD_AMOUNT,
case when c.PRODTYPE ='BC' then 'R4'
when c.PRODTYPE = 'BB' then 'R3'
when c.PRODTYPE = 'LB' then 'R1'
when c.PRODTYPE='MB' then 'T5' end EQU_ACCT_TYPE FROM COM_LOAN_O_TABLE A
LEFT JOIN C8PF B ON  A.CURRENCY_STRING = B.C8CCY
LEFT JOIN DLDT C ON TRIM(A.DEAL_IDENTIFIER) = TRIM(C.DEALNO)
WHERE TO_DATE(START_DATE,'DD-MON-YYYY') > TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY');

--REPO
INSERT INTO TREASURY_OPEN_DEALS
SELECT DEAL_IDENTIFIER,COUNTERPARTY_STRING MNEMONIC,DEPT_NAME,SUBTYPE,SIDE_SIDE_ONE_LONG_OR_SHORT,CURRENCY_STRING,SIDE_SIDE_1_NOTNAL_AMT_VALUE FCY_AMOUNT,C8RTE RATE,C8RTE*SIDE_SIDE_1_NOTNAL_AMT_VALUE KWD_AMOUNT,'OS' EQU_ACCT_TYPE
 FROM REPO_O_TABLE A
LEFT JOIN C8PF B ON  CURRENCY_STRING = B.C8CCY;



-- FX SWAP
INSERT INTO TREASURY_OPEN_DEALS
SELECT DEAL_IDENTIFIER,MNEMONIC , DEPT_NAME||'_SWAP_NEAR',SUBTYPE, BUY_SELL,  CCY, AMOUNT FCY_AMOUNT,  C8RTE RATE   , C8RTE*AMOUNT KWD_EQU_AMOUNT,EQU_ACCT_TYPE FROM (
select DEAL_IDENTIFIER,NEAR_LEG_CPTY MNEMONIC ,DEPT_NAME,SUBTYPE,TO_CHAR(NEAR_LEG_FX_BUY_SELL) BUY_SELL,FAR_LEG_CPTY,SUBSTR(NEAR_LEG_CCY_PAIR,1,3) CCY ,NEAR_LEG_CCY_ONE_AMOUNT AMOUNT,TO_CHAR(CASE WHEN NEAR_LEG_FX_BUY_SELL='SELL' then 'W2' else 'W1' end) EQU_ACCT_TYPE
  from FX_SWAP_O_TABLE WHERE TO_DATE(NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY') > TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY')
UNION ALL
select DEAL_IDENTIFIER,NEAR_LEG_CPTY MNEMONIC ,DEPT_NAME,SUBTYPE,TO_CHAR(CASE WHEN NEAR_LEG_FX_BUY_SELL='SELL' then 'BUY' else 'SELL' end),FAR_LEG_CPTY,SUBSTR(NEAR_LEG_CCY_PAIR,5,3) CCY1 ,NEAR_LEG_CCY_TWO_AMOUNT AMOUNT1,
TO_CHAR(CASE WHEN NEAR_LEG_FX_BUY_SELL='SELL' then 'W1' else 'W2' end)  from FX_SWAP_O_TABLE  WHERE TO_DATE(NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY') > TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY')
) 
LEFT JOIN C8PF ON C8CCY = CCY
UNION ALL
SELECT DEAL_IDENTIFIER,MNEMONIC ,DEPT_NAME||'_SWAP_FAR',SUBTYPE ,BUY_SELL,  CCY, AMOUNT FCY_AMOUNT,  C8RTE RATE   , C8RTE*AMOUNT KWD_EQU_AMOUNT,EQU_ACCT_TYPE FROM (
select DEAL_IDENTIFIER,FAR_LEG_CPTY MNEMONIC ,DEPT_NAME,SUBTYPE,TO_CHAR(CASE WHEN NEAR_LEG_FX_BUY_SELL='SELL' then 'BUY' else 'SELL' end) BUY_SELL,FAR_LEG_CPTY,SUBSTR(NEAR_LEG_CCY_PAIR,1,3) CCY ,FAR_LEG_CCY_ONE_AMOUNT AMOUNT,TO_CHAR(CASE WHEN NEAR_LEG_FX_BUY_SELL='SELL' then 'W3' else 'W4' end) EQU_ACCT_TYPE
  from FX_SWAP_O_TABLE
UNION ALL
select DEAL_IDENTIFIER,FAR_LEG_CPTY MNEMONIC ,DEPT_NAME,SUBTYPE,TO_CHAR(NEAR_LEG_FX_BUY_SELL),FAR_LEG_CPTY,SUBSTR(NEAR_LEG_CCY_PAIR,5,3) CCY1 ,FAR_LEG_CCY_TWO_AMOUNT AMOUNT1,
TO_CHAR(CASE WHEN NEAR_LEG_FX_BUY_SELL='SELL' then 'W4' else 'W3' end)  from FX_SWAP_O_TABLE
) 
LEFT JOIN C8PF ON C8CCY = CCY;

--SWAP
INSERT INTO TREASURY_OPEN_DEALS
SELECT IDENTIFIER,COUNTERPARTY MNEMONIC,  PAY_REC DEPT_NAME,SUBTYPE, FIXED_FLOAT,  CCY,  FCY_AMOUNT, C8RTE RATE   , C8RTE*FCY_AMOUNT KWD_EQU_AMOUNT ,EQU_ACCT_TYPE FROM(
SELECT IDENTIFIER,COUNTERPARTY,'DERIVATIVES_PAY' PAY_REC, "SIDESIDE.CASH_FLOW_SIDE_TYPE" FIXED_FLOAT,END_DATE,SUBSTR(CCY_CALENDAR_SET,1,3) CCY,SUBTYPE,PAY_SIDE_NOTIONAL_AMT_VALUE FCY_AMOUNT,
CASE WHEN SUBTYPE='IRSH' THEN 'S8' WHEN SUBTYPE='CCIRST'THEN 'W7' END EQU_ACCT_TYPE FROM SWAP_O_TABLE WHERE TO_DATE("SIDE.PAY_SIDE.END_DATE",'DD-MON-YYYY') > TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND TO_DATE("SIDE.PAY_SIDE.START_DATE",'DD-MON-YYYY') <= TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY')
UNION ALL
SELECT IDENTIFIER,COUNTERPARTY,'DERIVATIVES_REC' PAY_REC, "SIDESIDE.CASH_FLOW_SIDE_TYPE",END_DATE,SUBSTR(CCY_CALENDAR_SET,5,3) CCY,SUBTYPE,RECEIV_SIDE_NOTIONAL_AMT_VALUE,
CASE WHEN SUBTYPE='IRSH' THEN 'S7' WHEN SUBTYPE='CCIRST'THEN 'W8' END EQU_ACCT_TYPE  FROM SWAP_O_TABLE WHERE TO_DATE(SIDE_RECEIVE_SIDE_END_DATE,'DD-MON-YYYY') > TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND TO_DATE(SIDE_RECEIVE_SIDE_START_DATE,'DD-MON-YYYY') <= TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY')
)
 LEFT JOIN C8PF B ON  CCY = B.C8CCY;
 
 update TREASURY_OPEN_DEALS set EQU_ACCT_TYPE='YA' where trim(DEAL_IDENTIFIER) in('3019527');
 
--COM LOAN PAID PRINCIPLE AMOUNT
--update TREASURY_OPEN_DEALS set FCY_AMOUNT=FCY_AMOUNT-5750000,KWD_AMOUNT = RATE*(FCY_AMOUNT-5750000)  where trim(DEAL_IDENTIFIER)='3017876';

--update TREASURY_OPEN_DEALS set FCY_AMOUNT=FCY_AMOUNT-1350000,KWD_AMOUNT = RATE*(FCY_AMOUNT-1350000)  where trim(DEAL_IDENTIFIER)='3017877'; 
 
update TREASURY_OPEN_DEALS set FCY_AMOUNT = FCY_AMOUNT*-1,KWD_AMOUNT = KWD_AMOUNT*-1 where trim(INDICATOR)='BUY';

update TREASURY_OPEN_DEALS set FCY_AMOUNT = FCY_AMOUNT*-1,KWD_AMOUNT = KWD_AMOUNT*-1 where trim(INDICATOR)='LONG';

update TREASURY_OPEN_DEALS set FCY_AMOUNT = FCY_AMOUNT*-1,KWD_AMOUNT = KWD_AMOUNT*-1 where trim(PRODUCT_TYPE)='DERIVATIVES_PAY';

DROP TABLE TREASURY_OPEN_INV_DEASL; 


CREATE TABLE TREASURY_OPEN_INV_DEASL AS
SELECT DEAL_IDENTIFIER, NAME SECID, COUNTERPARTY_STRING, INSTRUMENT_CLASS_DATA_NAME, A.SUBTYPE, BUY_OR_SELL, 
CASE WHEN A.SUBTYPE='AFS' THEN '3A+3D+3G+3K+3W+3X+3Y+3Z+4A' 
     WHEN A.SUBTYPE='TRY_SH' THEN 'NL' 
     WHEN substr(NAME,1,3)='CBK' THEN 'OT' 
     WHEN substr(NAME,1,3)='KTB' THEN 'NT'
     WHEN SD ='GOVERNMENT' THEN '4D'
     END EQU_ACCT_TYPE,
ISSUE_CCY CCY, QTY, BID MARKET_PRICE, AMOUNT  FCY_AMOUNT, C8RTE RATE ,  C8RTE*AMOUNT  KWD_AMOUNT,SUBSTR(ON_BOOK_BACID,1,5) GLSH, ON_BOOK_BACID BACID FROM (
select DEAL_IDENTIFIER,NAME,TO_CHAR(COUNTERPARTY_STRING) COUNTERPARTY_STRING,INSTRUMENT_CLASS_DATA_NAME,SUBTYPE,BUY_OR_SELL,ISSUE_CCY,CASE WHEN BUY_OR_SELL='SELL' THEN 1 ELSE -1 END*QTY QTY,CASE WHEN substr(TRIM(NAME),1,3) IN('CBK','KTB') THEN 1 ELSE  BID END BID,CASE WHEN BUY_OR_SELL='SELL' THEN 1 ELSE -1 END*QTY*CASE WHEN substr(TRIM(NAME),1,3) IN('CBK','KTB') THEN 1 ELSE  BID END AMOUNT 
from SEC_BUY_SELL_O_TABLE a
left join SECURITY_DEFN_O_TABLE b on trim(b.NAME) = trim(a.SEC_DEFN_NAME)
left join spsh on trim(dealno) = trim(DEAL_IDENTIFIER)
left join SECURITY_PRICES_O_TABLE c on trim(a.SEC_DEFN_NAME) = trim(c.SECURITY)
UNION
select DEAL_IDENTIFIER,NAME,TO_CHAR(COUNTERPARTY_STRING),INSTRUMENT_CLASS_DATA_NAME,SUBTYPE,BUY_OR_SELL,ISSUE_CCY,CASE WHEN BUY_OR_SELL='SELL' THEN 1 ELSE -1 END*nvl(QTY_TRADED,round(SETTLEMENT/PRICE_STRING,2)) QTY,PRICE,CASE WHEN BUY_OR_SELL='SELL' THEN 1 ELSE -1 END*nvl(QTY_TRADED,round(SETTLEMENT/PRICE_STRING,2))*PRICE AMOUNT from EQUITY_MF_O_TABLE a
left join EQUITY_DEFN_O_TABLE b on trim(b.NAME) = trim(a.EQUITY_MF_DEFN_NAME)
left join EQUITY_PRICES_O_TABLE c on trim(a.EQUITY_MF_DEFN_NAME) = trim(c.SECURITY)
) A
LEFT JOIN TREASURY_INV_PRODUCT_MAPPING B ON TRIM(INSTRUMENT_CLASS_DATA_NAME) = TRIM(INSTRUMENT_CLASS) AND TRIM(A.SUBTYPE) = TRIM(B.SUBTYPE) AND TRIM(BUY_OR_SELL) = TRIM(INDICATOR)
LEFT JOIN C8PF ON TRIM(C8CCY) = TRIM(ISSUE_CCY)
LEFT JOIN (select DISTINCT trim(SECID) SECID,TRIM(SD) SD from TR_EQU_AND_SEC_OUTSTANDING) OI ON OI.SECID = TRIM(NAME)


 
--update TREASURY_OPEN_DEALS set EQU_ACCT_TYPE='V7' where trim(DEAL_IDENTIFIER)='1058374' and EQU_ACCT_TYPE='V2';
 
---------------------------------------
 
 --VALIDATE
SELECT EQU_ACCT_TYPE,CCY,SUM(FCY_AMOUNT) FROM TREASURY_OPEN_DEALS GROUP BY EQU_ACCT_TYPE,CCY;

SELECT SCACT,SCCCY,SUM(SCBAL/C8PWD) FROM SCPF 
LEFT JOIN C8PF ON C8CCY = SCCCY
WHERE SCACT IN('D1','F1','M1','M2','F2','R3','R4','V2','V1','V4','V3','OS','S8','W7','S7','W8','W1','W2','W4','W3','L6')
AND SCBAL <>0 GROUP BY SCACT,SCCCY;

select DEAL_IDENTIFIER, PRODUCT_TYPE, a.SUBTYPE, a.INDICATOR, CCY, FCY_AMOUNT, RATE, KWD_AMOUNT, EQU_ACCT_TYPE,BORROWING_BACID, PLACEMENT_BACID, CONTINGENT_LIABILITY_BACID,
 CONTG_LIABILITY_CONTRA_BACID, CONTINGENT_ASSET_BACID, CONTINGENT_ASSET_CONTRA_BACID, CONTIGENT_GLSH from TREASURY_OPEN_DEALS a
left join treasury_product_mapping b  on trim(a.PRODUCT_TYPE) = trim(b.DEPT_NAME) and trim(a.SUBTYPE) = trim(b.SUBTYPE) and trim(a.INDICATOR) = trim(b.INDICATOR);

--NEED TO CHECK MULTIPLE ACCOUNT
select DEAL_IDENTIFIER, PRODUCT_TYPE, a.SUBTYPE, a.INDICATOR, CCY, FCY_AMOUNT, RATE, KWD_AMOUNT, EQU_ACCT_TYPE,BORROWING_BACID, PLACEMENT_BACID, CONTINGENT_LIABILITY_BACID,
CONTG_LIABILITY_CONTRA_BACID, CONTINGENT_ASSET_BACID, CONTINGENT_ASSET_CONTRA_BACID, CONTIGENT_GLSH,SCAB||SCAN||SCAS LEG_INTERNAL_ACCOUNT_NUM,NEEAN LEG_EXTERNAL_ACCOUNT_NUM from TREASURY_OPEN_DEALS a
left join treasury_product_mapping b  on trim(a.PRODUCT_TYPE) = trim(b.DEPT_NAME) and trim(a.SUBTYPE) = trim(b.SUBTYPE) and trim(a.INDICATOR) = trim(b.INDICATOR)
LEFT JOIN (
select TRIM(GFOCID) GFOCID ,SCAB,SCAN,SCAS,SCACT,SCCCY,SCBAL/C8PWD SCBAL from scpf
LEFT JOIN GFPF ON  TRIM(SCAN) = TRIM(GFCPNC)
LEFT JOIN C8PF ON C8CCY =  SCCCY
where SCBAL <>0
) ON SCCCY = CCY AND SCACT = EQU_ACCT_TYPE AND GFOCID = TRIM(MNEMONIC)
LEFT JOIN NEPF ON NEAB||NEAN||NEAS = SCAB||SCAN||SCAS
order by PRODUCT_TYPE desc,DEAL_IDENTIFIER desc


--SPOT POSITION
select CCY, BUY_SELL,BRANCH, AMOUNT  FCY_AMOUNT,c8rte  RATE,c8rte*amount  KWD_EQU_AMOUNT,'YX+V0' EQU_ACCT_TYPE,'51000000' BACID from TR_SPOT_POSITION_DEALS
left join c8pf on c8ccy = ccy

--EQUITY AND SECURITY
select * from TREASURY_OPEN_INV_DEASL

------------------------------------------


--Equation

--T2 AND R5 FOR COM LOAN CONTIGENT BALANCE

select * from (
SELECT to_char(SCACT) SCACT, SCCCY, SCBAL/C8PWD SCBAL FROM (
select SCACT,SCCCY,sum(scbal) scbal from scpf where SCACT in('V1','V2','V3','V4','V7','F1','F2','D1','M1','L6','M2','OS','W1','W2','W3','W4','W7','W8','S7','S8','NT','OT','NL','R3','R4','T5','4D','R1')  group by SCACT,SCCCY
) 
LEFT JOIN C8PF ON C8CCY= SCCCY
WHERE scbal <> 0
union ALL
SELECT '3A+3D+3G+3K+3W+3X+3Y+3Z+4A',SCCCY,SCBAL/C8PWD
FROM( SELECT SCCCY,SUM(SCBAL) SCBAL FROM SCPF WHERE SCACT IN('3A','3D','3G','3K','3W','3X','3Y','3Z','4A') AND SCBAL <> 0 GROUP BY  SCCCY )
LEFT JOIN C8PF ON C8CCY=SCCCY
UNION ALL
SELECT 'YX+V0',SCCCY,SCBAL/C8PWD
FROM( SELECT SCCCY,SUM(SCBAL) SCBAL FROM SCPF WHERE SCACT IN('YX','V0') AND SCBAL <> 0 GROUP BY  SCCCY  having SUM(SCBAL)<>0 )
LEFT JOIN C8PF ON C8CCY=SCCCY
)
order by SCACT,SCCCY;

--OPICS

select * from (
SELECT EQU_ACCT_TYPE,to_char(CCY) CCY,SUM(FCY_AMOUNT) FROM TREASURY_OPEN_DEALS GROUP BY EQU_ACCT_TYPE,CCY
UNION ALL
select EQU_ACCT_TYPE,to_char(CCY) ccy,sum(FCY_AMOUNT) from TREASURY_OPEN_INV_DEASL GROUP BY EQU_ACCT_TYPE,to_char(CCY)
UNION ALL
SELECT EQU_ACCT_TYPE,CCY,SUM(AMOUNT) FCY_AMOUNT FROM(
SELECT  'YX+V0' EQU_ACCT_TYPE,A.CCY, case when BUY_SELL='SELL' then AMOUNT*-1 else   AMOUNT end AMOUNT  
 FROM TR_SPOT_POSITION_DEALS A
LEFT JOIN C8PF B ON  B.C8CCY = A.CCY
) GROUP BY EQU_ACCT_TYPE,CCY   having SUM(AMOUNT)<>0
 ) order by EQU_ACCT_TYPE,CCY;

 
 
 TRUNCATE TABLE PREMOCK_TREASURY_RECON;
insert into PREMOCK_TREASURY_RECON
SELECT nvl(SCAB,'0780'),
       SCAN,
       SCAS,
       NEEAN EXTERNAL_NO,
       CCY CURRENCY,
       SCCTP,
       EQU_ACCT_TYPE SCACT,
       SCACD,
       '' SCHEME_TYPE,
       '' SCHEME_CODE,
       substr(trim(ACCOUNT),6,5) GL_SUB_HEADCODE,
       ACCOUNT FIN_ACC_NUM,
       AMOUNT BALANCE,
       to_char(AMOUNT*C8RTE)  KWD_BALANCE,
       INDICATOR CREDIT_DEBIT_INDICATOR,
       trim(DEAL_IDENTIFIER) REFERENCE
  FROM (
SELECT DEAL_IDENTIFIER,MNEMONIC,'005'||CRNCY_ALIAS_NUM||TOD.CONTINGENT_ASSET_BACID ACCOUNT,CCY,'005' SOL_ID,'D' INDICATOR,ABS(FCY_AMOUNT)*-1 AMOUNT,EQU_ACCT_TYPE,'TREASURY OUTSTANDING BALANCE' PERTICULARS
FROM (select DEAL_IDENTIFIER,MNEMONIC,PRODUCT_TYPE,a.INDICATOR,CCY, FCY_AMOUNT ,EQU_ACCT_TYPE,CONTINGENT_ASSET_BACID from TREASURY_OPEN_DEALS a
left join treasury_product_mapping b  on trim(a.PRODUCT_TYPE) = trim(b.DEPT_NAME) and trim(a.SUBTYPE) = trim(b.SUBTYPE) and trim(a.INDICATOR) = trim(b.INDICATOR)) TOD 
LEFT JOIN TBAADM.CNC C ON CRNCY_CODE=CCY  AND BANK_ID='01'
WHERE CONTINGENT_ASSET_BACID IS NOT NULL and (PRODUCT_TYPE not in('MM','ISLAMIC') or EQU_ACCT_TYPE IN('R3','R4','R1'))
UNION ALL
SELECT DEAL_IDENTIFIER,MNEMONIC,'005'||CRNCY_ALIAS_NUM||TOD.CONTINGENT_ASSET_CONTRA_BACID ACCOUNT,CCY,'005' SOL_ID,CASE WHEN FCY_AMOUNT<0 THEN 'C' ELSE 'D' END INDICATOR,(FCY_AMOUNT)*-1 AMOUNT,case when TRIM(EQU_ACCT_TYPE) in('V1','V2','V7') THEN 'V5' 
            WHEN TRIM(EQU_ACCT_TYPE) in('V3','V4') THEN 'V6'
			WHEN TRIM(EQU_ACCT_TYPE) in('W1','W2') THEN 'W5'
            WHEN TRIM(EQU_ACCT_TYPE) in('W3','W4') THEN 'W6'
            WHEN TRIM(EQU_ACCT_TYPE) IN('R3','R4') THEN 'T2'
			WHEN TRIM(EQU_ACCT_TYPE) IN('R1') THEN 'T1'
            WHEN TRIM(EQU_ACCT_TYPE) in('S7') THEN 'S9'
            WHEN TRIM(EQU_ACCT_TYPE) in('S8') THEN 'S9' END,'TREASURY OUTSTANDING BALANCE' PERTICULARS
FROM (select DEAL_IDENTIFIER,MNEMONIC,PRODUCT_TYPE,a.INDICATOR,CCY, FCY_AMOUNT ,EQU_ACCT_TYPE,CONTINGENT_ASSET_CONTRA_BACID from TREASURY_OPEN_DEALS a
left join treasury_product_mapping b  on trim(a.PRODUCT_TYPE) = trim(b.DEPT_NAME) and trim(a.SUBTYPE) = trim(b.SUBTYPE) and trim(a.INDICATOR) = trim(b.INDICATOR)) TOD 
LEFT JOIN TBAADM.CNC C ON CRNCY_CODE=CCY  AND BANK_ID='01'
WHERE CONTINGENT_ASSET_CONTRA_BACID IS NOT NULL and (PRODUCT_TYPE not in('MM','ISLAMIC') or EQU_ACCT_TYPE IN('R3','R4','R1'))
UNION ALL
SELECT DEAL_IDENTIFIER,MNEMONIC,'005'||CRNCY_ALIAS_NUM||TOD.CONTINGENT_LIABILITY_BACID ACCOUNT,CCY,'005' SOL_ID,'C' INDICATOR,ABS(FCY_AMOUNT) AMOUNT,EQU_ACCT_TYPE,'TREASURY OUTSTANDING BALANCE' PERTICULARS
FROM (select DEAL_IDENTIFIER,MNEMONIC,PRODUCT_TYPE,a.INDICATOR,CCY,(FCY_AMOUNT) FCY_AMOUNT ,EQU_ACCT_TYPE,CONTINGENT_LIABILITY_BACID from TREASURY_OPEN_DEALS a
left join treasury_product_mapping b  on trim(a.PRODUCT_TYPE) = trim(b.DEPT_NAME) and trim(a.SUBTYPE) = trim(b.SUBTYPE) and trim(a.INDICATOR) = trim(b.INDICATOR)
) TOD 
LEFT JOIN TBAADM.CNC C ON CRNCY_CODE=CCY  AND BANK_ID='01'
WHERE CONTINGENT_LIABILITY_BACID IS NOT NULL and (PRODUCT_TYPE not in('MM','ISLAMIC') or EQU_ACCT_TYPE IN('R3','R4','R1'))
UNION ALL
SELECT DEAL_IDENTIFIER,MNEMONIC,'005'||CRNCY_ALIAS_NUM||TOD.CONTG_LIABILITY_CONTRA_BACID ACCOUNT,CCY,'005' SOL_ID,CASE WHEN FCY_AMOUNT<0 THEN 'C' ELSE 'D' END INDICATOR,(FCY_AMOUNT)*-1  AMOUNT,
       case when TRIM(EQU_ACCT_TYPE) in('V1','V2','V7') THEN 'V5' 
            WHEN TRIM(EQU_ACCT_TYPE) in('V3','V4') THEN 'V6'
			WHEN TRIM(EQU_ACCT_TYPE) in('W1','W2') THEN 'W5'
            WHEN TRIM(EQU_ACCT_TYPE) in('W3','W4') THEN 'W6'
            WHEN TRIM(EQU_ACCT_TYPE) IN('R3','R4') THEN 'T2'
			WHEN TRIM(EQU_ACCT_TYPE) IN('R1') THEN 'T1'
            WHEN TRIM(EQU_ACCT_TYPE) in('S7') THEN 'S9'
            WHEN TRIM(EQU_ACCT_TYPE) in('S8') THEN 'S9'  END,'TREASURY OUTSTANDING BALANCE' PERTICULARS
FROM (select DEAL_IDENTIFIER,MNEMONIC,PRODUCT_TYPE,a.INDICATOR,CCY,(FCY_AMOUNT) FCY_AMOUNT ,EQU_ACCT_TYPE,CONTG_LIABILITY_CONTRA_BACID from TREASURY_OPEN_DEALS a
left join treasury_product_mapping b  on trim(a.PRODUCT_TYPE) = trim(b.DEPT_NAME) and trim(a.SUBTYPE) = trim(b.SUBTYPE) and trim(a.INDICATOR) = trim(b.INDICATOR)
) TOD 
LEFT JOIN TBAADM.CNC C ON CRNCY_CODE=CCY  AND BANK_ID='01'
WHERE CONTG_LIABILITY_CONTRA_BACID IS NOT NULL and (PRODUCT_TYPE not in('MM','ISLAMIC') or EQU_ACCT_TYPE  IN('R3','R4','R1'))
UNION ALL
SELECT DEAL_IDENTIFIER,MNEMONIC,'005'||CRNCY_ALIAS_NUM||TOD.BORROWING_BACID ACCOUNT,CCY,'005' SOL_ID,'C' INDICATOR,ABS(FCY_AMOUNT) AMOUNT,EQU_ACCT_TYPE,'TREASURY OUTSTANDING BALANCE' PERTICULARS
FROM (select DEAL_IDENTIFIER,MNEMONIC,PRODUCT_TYPE,a.INDICATOR,CCY,(FCY_AMOUNT) FCY_AMOUNT ,EQU_ACCT_TYPE,BORROWING_BACID from TREASURY_OPEN_DEALS a
left join treasury_product_mapping b  on trim(a.PRODUCT_TYPE) = trim(b.DEPT_NAME) and trim(a.SUBTYPE) = trim(b.SUBTYPE) and trim(a.INDICATOR) = trim(b.INDICATOR)) TOD 
LEFT JOIN TBAADM.CNC C ON CRNCY_CODE=CCY  AND BANK_ID='01'
WHERE BORROWING_BACID IS NOT NULL and EQU_ACCT_TYPE NOT  IN('R3','R4','R1')
UNION ALL
SELECT DEAL_IDENTIFIER,MNEMONIC,'005'||CRNCY_ALIAS_NUM||TOD.PLACEMENT_BACID ACCOUNT,CCY,'005' SOL_ID,'D' INDICATOR,ABS(FCY_AMOUNT)*-1 AMOUNT,EQU_ACCT_TYPE,'TREASURY OUTSTANDING BALANCE' PERTICULARS
FROM (select DEAL_IDENTIFIER,MNEMONIC,PRODUCT_TYPE,a.INDICATOR,CCY,(FCY_AMOUNT) FCY_AMOUNT ,EQU_ACCT_TYPE,PLACEMENT_BACID from TREASURY_OPEN_DEALS a
left join treasury_product_mapping b  on trim(a.PRODUCT_TYPE) = trim(b.DEPT_NAME) and trim(a.SUBTYPE) = trim(b.SUBTYPE) and trim(a.INDICATOR) = trim(b.INDICATOR)) TOD 
LEFT JOIN TBAADM.CNC C ON CRNCY_CODE=CCY  AND BANK_ID='01'
WHERE PLACEMENT_BACID IS NOT NULL and EQU_ACCT_TYPE  NOT  IN('R3','R4','R1')
)
  left join c8pf on c8ccy = CCY
LEFT JOIN (
select TRIM(GFOCID) GFOCID ,SCAB,SCAN,SCAS,SCACT,SCCCY,SCCTP,SCACD,SCBAL/C8PWD SCBAL from scpf
LEFT JOIN GFPF ON  TRIM(SCAN) = TRIM(GFCPNC)
LEFT JOIN C8PF ON C8CCY =  SCCCY
where SCBAL <>0
) ON SCCCY = CCY AND SCACT = EQU_ACCT_TYPE AND GFOCID = TRIM(MNEMONIC)
LEFT JOIN NEPF ON NEAB||NEAN||NEAS = SCAB||SCAN||SCAS;

COMMIT;

UPDATE PREMOCK_TREASURY_RECON A SET FIN_ACC_NUM =( SELECT NEW_ACCOUNT FROM(
SELECT REFERENCE,FIN_ACC_NUM,SUBSTR(TRIM(FIN_ACC_NUM),1,5)||'10401000' NEW_ACCOUNT FROM PREMOCK_TREASURY_RECON WHERE TRIM(REFERENCE) IN(
SELECT TRIM(DEAL_IDENTIFIER) FROM COM_LOAN_O_TABLE WHERE DEPT_NAME='MM' AND SUBTYPE='BANK' AND SIDE_SIDE_ONE_LONG_OR_SHORT='LONG' AND COUNTERPARTY_STRING='CENTRALKWT'
)
) B WHERE TRIM(A.REFERENCE) = TRIM(B.REFERENCE)
),GL_SUB_HEADCODE='10401' WHERE TRIM(A.REFERENCE) IN(
SELECT TRIM(DEAL_IDENTIFIER) FROM COM_LOAN_O_TABLE WHERE DEPT_NAME='MM' AND SUBTYPE='BANK' AND SIDE_SIDE_ONE_LONG_OR_SHORT='LONG' AND COUNTERPARTY_STRING='CENTRALKWT'
);


update TREASURY_OPEN_DEALS set EQU_ACCT_TYPE='YA' where trim(DEAL_IDENTIFIER)='3019527';

--update TREASURY_OPEN_DEALS set EQU_ACCT_TYPE='V7' where trim(DEAL_IDENTIFIER)='1058374' and EQU_ACCT_TYPE='V2';

UPDATE PREMOCK_TREASURY_RECON SET SCACT='YA',SCAB='0781',SCAN='800225',SCAS='414',EXTERNAL_NO='0781800225414'  where trim(REFERENCE) in('3019527');

UPDATE PREMOCK_TREASURY_RECON SET SCACT='V7',SCAB='0781',SCAN='962035',SCAS='414',EXTERNAL_NO='0780962035414'  where trim(REFERENCE) in('1057577') AND TRIM(CURRENCY)='KWD' AND SCACT='V2';


COMMIT;

TRUNCATE TABLE PREMOCK_TREASURY_RECON_INVEST;

INSERT INTO PREMOCK_TREASURY_RECON_INVEST
SELECT '0780' SCAB,
       '' SCAN,
       '' SCAS,
       '' EXTERNAL_NO,
       CCY CURRENCY,
       '' SCCTP,
       EQU_ACCT_TYPE SCACT,
       '' SCACD,
       '' SCHEME_TYPE,
       '' SCHEME_CODE,
       GLSH GL_SUB_HEADCODE,
       '005'||CRNCY_ALIAS_NUM||BACID FIN_ACC_NUM,
       FCY_AMOUNT BALANCE,
       KWD_AMOUNT KWD_BALANCE,
       CASE WHEN FCY_AMOUNT < 0 THEN 'D' ELSE 'C' END CREDIT_DEBIT_INDICATOR,
       DEAL_IDENTIFIER||' '||SECID REFERENCE
  FROM TREASURY_OPEN_INV_DEASL
  LEFT JOIN TBAADM.CNC C ON CRNCY_CODE=CCY  AND BANK_ID='01'
  WHERE TRIM(SECID) NOT IN(SELECT TRIM(SECID) FROM TTUM_EXCEL_TREASURY_DEAL);
  COMMIT;
  
  INSERT INTO PREMOCK_TREASURY_RECON_INVEST
  SELECT '0780' SCAB,
       '' SCAN,
       '' SCAS,
       '' EXTERNAL_NO,
       CCY CURRENCY,
       '' SCCTP,
       LEG_ACCT_TYPE SCACT,
       '' SCACD,
       '' SCHEME_TYPE,
       '' SCHEME_CODE,
       substr(trim(account),6,5) GL_SUB_HEADCODE,
       ACCOUNT FIN_ACC_NUM,
       ROUND(AMOUNT,C8CED)  BALANCE,
       ROUND(TO_NUMBER(AMOUNT*c8rte),C8CED) KWD_BALANCE,
       INDICATOR CREDIT_DEBIT_INDICATOR,
       SECID REFERENCE
  FROM TTUM_EXCEL_TREASURY_DEAL
  left join c8pf on c8ccy = ccy
  WHERE NOT REGEXP_LIKE(ACCOUNT,'[A-Z]');
  
INSERT INTO PREMOCK_TREASURY_RECON
SELECT '0780' SCAB,
       '' SCAN,
       '' SCAS,
       '' EXTERNAL_NO,
       CCY CURRENCY,
       '' SCCTP,
       '' SCACT,
       '' SCACD,
       '' SCHEME_TYPE,
       '' SCHEME_CODE,
       substr(trim(account),6,5) GL_SUB_HEADCODE,
       ACCOUNT FIN_ACC_NUM,
       CASE WHEN INDICATOR='D' THEN -1*AMOUNT ELSE TO_NUMBER(AMOUNT) END  BALANCE,
       CASE WHEN INDICATOR='D' THEN -1*AMOUNT*c8rte ELSE TO_NUMBER(AMOUNT*c8rte) END  KWD_BALANCE,
       INDICATOR CREDIT_DEBIT_INDICATOR,
       '' REFERENCE
  FROM TTUM_EXCEL_TREASURY_FVR
  left join c8pf on c8ccy = ccy
  WHERE NOT REGEXP_LIKE(ACCOUNT,'[A-Z]');
  COMMIT;
  
  UPDATE PREMOCK_TREASURY_RECON_INVEST SET SCAB='0780',SCAN='843115',SCAS='414',EXTERNAL_NO='0780843115414' WHERE REFERENCE LIKE '%KTB%';
  
  UPDATE PREMOCK_TREASURY_RECON_INVEST SET SCAB='0780',SCAN='842515,842535',SCAS='414',EXTERNAL_NO='0780842515414,0780842535414' WHERE REFERENCE LIKE '%CBK%';
  
  
  UPDATE PREMOCK_TREASURY_RECON SET SCAB='0780',SCAN='846245',SCAS='840',EXTERNAL_NO='0780846245840',SCCTP='IB',SCACD='' WHERE TRIM(SCACT)='4D';
  
--  UPDATE PREMOCK_TREASURY_RECON SET SCAB='0780',SCAN='962035',SCAS='414',EXTERNAL_NO='0780962035414',SCCTP='IB',SCACD='ZB' WHERE TRIM(SCACT)='V7';---


update PREMOCK_TREASURY_RECON set scab='0780',scan='962030',scas='414',EXTERNAL_NO='0780962030414' ,SCCTP='IB',SCACD='ZB' where scact='V7' and BALANCE='-90651';

update PREMOCK_TREASURY_RECON set scab='0780',scan='962035',scas='414',EXTERNAL_NO='0780962035414' ,SCCTP='IB',SCACD='ZB' where scact='V7' and BALANCE='5061012.5';
  
  UPDATE PREMOCK_TREASURY_RECON SET SCAB='0780',SCAN='841005',SCAS='414',EXTERNAL_NO='0780841005414',SCCTP='IB',SCACD='DM' WHERE TRIM(SCACT)='NL';
  
  UPDATE PREMOCK_TREASURY_RECON SET SCAB='0781',SCAN='800225',SCAS='414',EXTERNAL_NO='0780846245840',SCCTP='IA',SCACD='DI' WHERE TRIM(SCACT)='YA';
  
  update PREMOCK_TREASURY_RECON set FIN_ACC_NUM='0050110201000',GL_SUB_HEADCODE='10201' where  trim(REFERENCE) like '%3019801%';
  
COMMIT;
  
INSERT INTO PREMOCK_TREASURY_RECON SELECT * FROM PREMOCK_TREASURY_RECON_INVEST;

COMMIT;



 SELECT SCACT,CURRENCY,SUM(BALANCE) FROM PREMOCK_TREASURY_RECON WHERE SCACT IS NOT NULL GROUP BY  SCACT,CURRENCY HAVING SUM(BALANCE) <> 0 ORDER BY 1
 
 
 SELECT SCACT,CURRENCY,SUM(BALANCE) FROM PREMOCK_TREASURY_RECON WHERE SCACT IS NULL GROUP BY  SCACT,CURRENCY HAVING SUM(BALANCE) <> 0 ORDER BY 1
 

SELECT SCCCY,SUM(SCBAL/C8PWD) FROM ALL_FINAL_TRIAL_BALANCE
LEFT JOIN C8PF ON C8CCY = SCCCY
 WHERE SCACT IN('TY','YM') AND GL_SUB_HEAD_CODE='TRY' AND SCBAL<>0 GROUP BY SCCCY

  --VALIDATION
 select sum(scbal/c8pwd) from scpf
left join c8pf on c8ccy = scccy
 where scact in('3A','3D','3G','3K','3W','3X','3Y','3Z','4A','4D','NL','NT','OT','R3','R4','T1','T2','D1','F1','F2','M1','M2','V2','V1','V7','V5','V4','V3','V6','VC','S8','S7','W1','W2','W3','W4','W5','W6','R1') 
 -- 943145215.147
 
   select sum(scbal/c8pwd) from scpf
left join c8pf on c8ccy = scccy
 where scact in('R1','R3','R4','T1','T2','D1','F1','F2','M1','M2','V2','V1','V7','V5','V4','V3','V6','VC','S8','S7','W1','W2','W3','W4','W5','W6') 
 -- 1735516398.886
 
 SELECT 1735516398.886-1725516398.886 FROM DUAL--10000000
 
  select sum(scbal/c8pwd) from scpf
left join c8pf on c8ccy = scccy
 where scact in('3A','3D','3G','3K','3W','3X','3Y','3Z','4A','4D','NL','NT','OT') 
 -- -792371183.739
 
 
      select scact,scccy,sum(scbal/c8pwd) from scpf
left join c8pf on c8ccy = scccy
 where scact in('R1','R3','R4','T1','T2','D1','F1','F2','M1','M2','V2','V1','V7','V5','V4','V3','V6','VC','S8','S7','W1','W2','W3','W4','W5','W6') 
 group by scact,scccy having sum(scbal/c8pwd) <> 0
 -- 1780010522.776
 
 select SCACT,CURRENCY,sum(BALANCE) BALANCE from PREMOCK_TREASURY_RECON group by SCACT,CURRENCY having sum(BALANCE) <> 0
 
   select scact,scccy,sum(scbal/c8pwd) from scpf
left join c8pf on c8ccy = scccy
 where scact in('3A','3D','3G','3K','3W','3X','3Y','3Z','4A','4D','NL','NT','OT') group by scact,scccy having sum(scbal/c8pwd) <> 0
 -- -792371183.739
 
 select SCACT,CURRENCY,sum(BALANCE) BALANCE from PREMOCK_TREASURY_RECON_INVEST group by SCACT,CURRENCY having sum(BALANCE) <> 0
 
  select scccy,sum(scbal/c8pwd) from scpf 
 left join c8pf on c8ccy = scccy
 where scact||scan in(
 'TY804930',
'TY804935',
'TY804950',
'TY804955',
'TY804960',
'TY804965',
'YM804225',
'YM804250'
) and scbal<>0
group by scccy


SELECT SUBSTR(ACCOUNT,6),CCY,SUM(CASE WHEN INDICATOR='D' THEN  -1*AMOUNT ELSE TO_NUMBER(AMOUNT) END) AMOUNT FROM ttum_excel_TREASURY WHERE NOT REGEXP_LIKE(ACCOUNT,'[A-Z]') GROUP BY SUBSTR(ACCOUNT,6),CCY

 