truncate table REFERENCE_RATE_O_TABLE;
insert into REFERENCE_RATE_O_TABLE
SELECT 
'' RESPONSE,
trim(RATECODE) "Rate Code",
SUBSTR(trim(RATECODE),3,3) "Rate Currency",
trim(INTRATE) "Rate Value",
TO_CHAR(TO_DATE(VERDATE,'YYYY-MM-DD'),'DD-Mon-YYYY') "Effective Date",
'' COMMENTS
FROM RHIS 
WHERE TO_DATE(TRIM(VERDATE),'YYYY-MM-DD') >= TO_DATE('01-01-2013','DD-MM-YYYY') and TO_DATE(TRIM(VERDATE),'YYYY-MM-DD') <=TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY');
--where trim(RATECODE) in ('LIUSD3M','LIUSD6M');
insert into REFERENCE_RATE_O_TABLE
SELECT 
'' RESPONSE,
trim(CONTRIBRATE) "Rate Code",
trim(CCY)"Rate Currency",
trim(MIDRATE_8) "Rate Value",
TO_CHAR(BPDATA,'DD-Mon-YYYY') "Effective Date",
'' COMMENTS
FROM YCRH WHERE TRIM(CONTRIBRATE) IN(SELECT CONTRIBRATE FROM YCRS WHERE BR=GET_PARAM('OPICS_BANK_ID') AND CONTRIBRATE LIKE '%+%') 
AND BPDATA >= TO_DATE('01-01-2013','DD-MM-YYYY');
commit;
exit; 
