TRUNCATE TABLE REPO_O_TABLE;
INSERT INTO REPO_O_TABLE
SELECT
'' Response,
D.DEALNO DEAL_IDENTIFIER,
CASE WHEN trim(D.PORT)='MMBK' THEN '/ABK/KUWAIT/BANKING/MM/CORPORATE' ELSE '/ABK/KUWAIT/BANKING/MM/INTERBANK' END TRADING_BOOK,---mapping required
CASE WHEN TRIM(D.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ENTITY_NAME,
'MM' DEPT_NAME, ---D.PRODUCT
CASE WHEN TRIM(D.PORT)='CORP' THEN 'REPCBK' ELSE 'REPBNK' END SUBTYPE,
trim(CMNE) COUNTERPARTY_STRING,
TO_CHAR(DEALDATE,'DD-Mon-YYYY')DEAL_DATE,
TO_CHAR(D.VDATE,'DD-Mon-YYYY') START_DATE,--***
TO_CHAR(D.MATDATE,'DD-Mon-YYYY') END_DATE,--***
CASE WHEN D.PS='S' THEN 'SHORT' ELSE 'LONG' END SIDE_SIDE_ONE_LONG_OR_SHORT,
CASE WHEN D.PS='S'  THEN 'FIX/DEPO'
     WHEN D.PS='P'  THEN 'FIX/LOAN'
END TYPE_STRING,
D.CCY CURRENCY_STRING,
R.COMMPROCAMT SIDE_SIDE_1_NOTNAL_AMT_VALUE,
SUBSTR(D.BASIS,1,1)||'/'||SUBSTR(D.BASIS,2) SIDE_SIDE_ONE_BASIS_CODE,
'BULLET' SIDE_SIDE_ONE_CREATION_FREQ,--INFY/BANK NEEDS TO GIVE CORRECT VALUE
D.REPORATE_8 SIDE_SIDE_ONE_FIX_RATE,
'' SIDE_SIDE_ONE_SPREAD_RATE,
'' "SIDE.$1.CASH_FLOW_SIDE_TYPE",
'' "SIDE.$1.REFERENCE_RATE",
'Auto' AUTO_OR_PENDING,
CASE WHEN TRIM(C.BIC) IS NOT NULL THEN 'SWIFT' ELSE '' END CONFIRM_METHOD,
'' SIDE_CURREC_SI_FLOW_PAY_SSI_ID,
CASE WHEN TRIM(D.MATCCYSMEANS)in('BRDGE','BRIDGE') THEN to_char('BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END) ELSE TO_CHAR(CASE WHEN D.PS='S' THEN D.MATCCYSACCT ELSE NULL END) END SIDE_CURREC_SI_FLOW_PAY_NOSTRO,--CASE WHEN D.PS='S' THEN D.MATCCYSACCT ELSE NULL END SIDE_CURREC_SI_FLOW_PAY_NOSTRO,
CASE WHEN D.PS='S' AND TRIM(D.MATCCYSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SIDE_CUR_SI_FLOW_PAY_SETT_MTHD,
'' SIDE_CUR_SI_FLOW_PAY_CPTY_AGNT,
'' SIDE_CURREC_SI_FLOW_REC_SSI_ID,
CASE WHEN TRIM(D.COMCCYSMEANS)in('BRDGE','BRIDGE') THEN to_char('BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END) ELSE TO_CHAR(CASE WHEN D.PS='S' THEN D.COMCCYSACCT ELSE NULL END) END SIDE_CURREC_SI_FLOW_REC_NOSTRO,--CASE WHEN D.PS='S' THEN D.COMCCYSACCT ELSE NULL END SIDE_CURREC_SI_FLOW_REC_NOSTRO,
CASE WHEN D.PS='S' AND TRIM(D.COMCCYSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SIDE_CUR_SI_FLOW_REC_SETT_MTHD,
'' SIDE_CUR_SI_FLOW_REC_CPTY_AGNT,
CASE WHEN TRIM(D.COMCCYSMEANS)in('BRDGE','BRIDGE') THEN to_char('BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END) ELSE TO_CHAR(CASE WHEN D.PS='S' THEN D.COMCCYSACCT ELSE NULL END) END SIFLOW_INTEREST_PAY_NOSTRO,--CASE WHEN D.PS='S' THEN D.COMCCYSACCT ELSE NULL END SIFLOW_INTEREST_PAY_NOSTRO,
CASE WHEN D.PS='S' AND TRIM(D.COMCCYSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SIFLOW_INT_PAY_SETT_METHOD,
'' SIFLOW_INTEREST_PAY_CPTY_AGENT,
CASE WHEN TRIM(D.MATCCYSMEANS)in('BRDGE','BRIDGE') THEN to_char('BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END) ELSE TO_CHAR(CASE WHEN D.PS='S' THEN TRIM(D.MATCCYSACCT) ELSE NULL END) END SIFLOW_INTEREST_RECIEVE_NOSTRO,--CASE WHEN D.PS='S' THEN TRIM(D.MATCCYSACCT) ELSE NULL END SIFLOW_INTEREST_RECIEVE_NOSTRO,
CASE WHEN D.PS='S' AND TRIM(D.MATCCYSMEANS)='NOS' THEN 'SWIFT' ELSE '' END SIFLOW_INT_RECIEVE_SETT_METHOD,
'' SIFLOW_INT_RECIEVE_CPTY_AGENT,
'' SIDE_SIDE_ONE_COMP_METHOD,
'' SIDE_SIDE_ONE_COMP_FREQUENCY,
'S' SIDE_SIDE_ONE_START_DD_CNVNTN, ---TO_CHAR(D.VDATE,'DD-Mon-YYYY')
'S' SIDE_SIDE_ONE_END_DD_CNVNTN, ---TO_CHAR(D.MATDATE,'DD-Mon-YYYY')
'S' SIDE_SIDE_1_CASH_FLW_D_CNVNTN
FROM RPRH D
LEFT JOIN CUST C ON TRIM(D.CNO)=TRIM(C.CNO)
LEFT JOIN RPDT R ON TRIM(D.DEALNO)=TRIM(R.DEALNO)
WHERE R.MDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(R.REVDATE) IS NULL;
COMMIT;
--UPDATE REPO_O_TABLE SET SIDE_CURREC_SI_FLOW_PAY_NOSTRO='SCBDLE' WHERE TRIM(SIDE_CURREC_SI_FLOW_PAY_NOSTRO)='SCBLDE';
--UPDATE REPO_O_TABLE SET SIDE_CURREC_SI_FLOW_REC_NOSTRO='SCBDLE' WHERE TRIM(SIDE_CURREC_SI_FLOW_REC_NOSTRO)='SCBLDE';
--UPDATE REPO_O_TABLE SET SIFLOW_INTEREST_PAY_NOSTRO='SCBDLE' WHERE TRIM(SIFLOW_INTEREST_PAY_NOSTRO)='SCBLDE';
--UPDATE REPO_O_TABLE SET SIFLOW_INTEREST_RECIEVE_NOSTRO='SCBDLE' WHERE TRIM(SIFLOW_INTEREST_RECIEVE_NOSTRO)='SCBLDE';
--COMMIT;
EXIT; 
