TRUNCATE TABLE SEC_BUY_SELL_O_TABLE;
INSERT INTO SEC_BUY_SELL_O_TABLE
SELECT 
'' RESPONSE,
DEALNO DEAL_IDENTIFIER,
TO_CHAR(DEALDATE,'DD-Mon-YYYY') DEAL_DATE,
TO_CHAR(SETTDATE,'DD-Mon-YYYY') SETTLEMENT_DATE,
trim(C.CMNE) COUNTERPARTY_STRING,--CASE WHEN trim(C.CMNE)='CENTRALKWT' THEN 'CBKUKW' ELSE trim(C.CMNE) END
--case when TRIM(s.SECID)='ABKBD  3.5 5/4/22' then '/ABK/KUWAIT/BANKING/FIS/HTM'  when INVTYPE='A' then '/ABK/KUWAIT/BANKING/FIS/AFS' when INVTYPE in('H') then '/ABK/KUWAIT/BANKING/FIS/HTM' when INVTYPE='T' then '/ABK/KUWAIT/BANKING/FIS/HFT' end TRADING_BOOK,
case when INVTYPE='I' then '/ABK/KUWAIT/BANKING/FIS/HTM'  when INVTYPE='A' then '/ABK/KUWAIT/BANKING/FIS/AFS' when INVTYPE in('H') then '/ABK/KUWAIT/BANKING/FIS/HTM' when INVTYPE='T' then '/ABK/KUWAIT/BANKING/FIS/HFT' end TRADING_BOOK,
'FIS' DEPT_NAME,
--case when TRIM(s.SECID)='ABKBD  3.5 5/4/22' then 'HTM'  when INVTYPE='A' then 'AFS' when INVTYPE in('H') then 'HTM' when INVTYPE='T' then 'HFT' end SUBTYPE,
case when INVTYPE in('I') then 'BONDIS'  when INVTYPE='A' then 'AFS' when INVTYPE in('H') then 'HTM' when INVTYPE='T' then 'HFT' end SUBTYPE,--ISSUE
case when PS='P' then 'BUY' else 'SELL' end BUY_OR_SELL,
'' MARKET,--UNLISTED
TRIM(s.SECID) SEC_DEFN_NAME,
S.PRICE_8 PRICE_STRING,--S.PRICE_8--CASE WHEN  PRODTYPE IN ('SB','TB') THEN FACEAMT/QTY ELSE round(COALESCE(TRIM(BID),TRIM(A.CLPRICE_8),TRIM(S.PRICE_8)),8) END
YIELD_8 YIELD,
FACEAMT QTY_TRADED,--QTY,FACEAMT
'' IS_INVESTMENT,--CASE WHEN INVTYPE='H' THEN 'T' ELSE 'F' END
'' CONFIRM_METHOD,--CASE WHEN TRIM(C.BIC) IS NOT NULL THEN 'SWIFT' ELSE '' END
CASE WHEN TRIM(PS)='P' THEN '' ELSE NULL END SI_FLOW_PAY_SSI_ID,
CASE WHEN TRIM(CCYSMEANS)in('BRDGE','BRIDGE') THEN to_char('BRIDGE_'||s.CCY||CASE WHEN TRIM(s.BR)='51' THEN '_ABKU' ELSE '_ABKK' END) ELSE TO_CHAR(CASE WHEN TRIM(PS)='P' THEN CCYSACCT ELSE NULL END) END SI_FLOW_PAY_NOSTRO,--CASE WHEN TRIM(PS)='P' THEN CCYSACCT ELSE NULL END SI_FLOW_PAY_NOSTRO,
CASE WHEN TRIM(PS)='P' AND TRIM(CCYSMEANS)='NOS' THEN 'SWIFT'  
     WHEN TRIM(PS)='P' AND TRIM(CCYSMEANS)!='NOS' THEN '' ELSE NULL END SI_FLOW_PAY_SETT_METHOD,
CASE WHEN TRIM(PS)='P' THEN '' ELSE NULL END SI_FLOW_PAY_CPTY_AGENT,
CASE WHEN TRIM(PS)='S' THEN '' ELSE NULL END SI_FLOW_REC_SSI_ID,
CASE WHEN TRIM(CCYSMEANS)in('BRDGE','BRIDGE') THEN to_char('BRIDGE_'||s.CCY||CASE WHEN TRIM(s.BR)='51' THEN '_ABKU' ELSE '_ABKK' END) ELSE TO_CHAR(CASE WHEN TRIM(PS)='S' THEN CCYSACCT ELSE NULL END) END SI_FLOW_REC_NOSTRO,--CASE WHEN TRIM(PS)='S' THEN CCYSACCT ELSE NULL END SI_FLOW_REC_NOSTRO,
CASE WHEN TRIM(PS)='S' AND TRIM(CCYSMEANS)='NOS' THEN 'SWIFT' 
     WHEN TRIM(PS)='S' AND TRIM(CCYSMEANS)!='NOS' THEN '' ELSE NULL END SI_FLOW_REC_SETT_METHOD,
CASE WHEN TRIM(PS)='S' THEN '' ELSE NULL END SI_FLOW_REC_CPTY_AGENT,
CASE WHEN TRIM(s.SECID) LIKE 'CBK%' OR TRIM(s.SECID) LIKE 'KTB%' THEN 'CBK' ELSE TRIM(CUSTODION) END BANK_CUSTODIAN_ACCT,
'DEF_COC' COST_OF_CARRY_REF_RATE_CODE
FROM SPSH S
inner join (SELECT trim(secid) secid,CLPRICE_8 FROM TR_EQU_AND_SEC_OUTSTANDING WHERE TRIM(TYPE)='Fixed Income Investments' AND TRIM(NETQTY) != 0 AND TRIM(NETQTY) IS NOT NULL
union all
select trim(secid),'' secid from secm where trim(PRODTYPE) in ('TB','SB')  and MDATE > to_date(get_param('EOD_DATE'),'dd-mm-yyyy')
union all
select trim(secid),'' from SPSH where INVTYPE='I'
) a on trim(s.secid) = trim(a.secid)
LEFT JOIN CUST C ON TRIM(C.CNO)=TRIM(S.CNO)
LEFT JOIN TREASURY_CUSTODION ON TRIM(SECURITY_OR_EQUITIES) = TRIM(s.SECID)
LEFT JOIN SECURITY_PRICES_O_TABLE ON to_date(BASE_DATE,'dd-mon-yyyy')=to_date(get_param('EOD_DATE'),'dd-mm-yyyy') AND TRIM(SECURITY) = TRIM(S.SECID)
where trim(S.REVDATE) is null ;
COMMIT;
--UPDATE SEC_BUY_SELL_O_TABLE SET SI_FLOW_PAY_NOSTRO='SCBDLE' WHERE TRIM(SI_FLOW_PAY_NOSTRO)='SCBLDE';
--UPDATE SEC_BUY_SELL_O_TABLE SET SI_FLOW_REC_NOSTRO='SCBDLE' WHERE TRIM(SI_FLOW_REC_NOSTRO)='SCBLDE';
--COMMIT;
UPDATE SEC_BUY_SELL_O_TABLE A SET SI_FLOW_PAY_SSI_ID= ( SELECT SSI_ID FROM(
SELECT distinct DEAL_IDENTIFIER,SSI_ID FROM SEC_BUY_SELL_O_TABLE
LEFT JOIN SECURITY_DEFN_O_TABLE ON TRIM(SEC_DEFN_NAME) = TRIM(NAME)
LEFT JOIN (SELECT B.* FROM TREASURY_PAY_SSI_O_TABLE B WHERE 
ROWID IN(SELECT  MIN(ROWID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) ) ON TRIM(COUNTERPARTY_STRING)=TRIM(CPTY_NAME) AND 
TRIM(NOSTRO_ID) = TRIM(SI_FLOW_PAY_NOSTRO) AND TRIM(ISSUE_CCY) =TRIM(CURRENCY)
) B WHERE TRIM(A.DEAL_IDENTIFIER) = TRIM(B.DEAL_IDENTIFIER)) ;
COMMIT;
UPDATE SEC_BUY_SELL_O_TABLE A SET SI_FLOW_REC_SSI_ID= ( SELECT SSI_ID FROM(SELECT distinct DEAL_IDENTIFIER,SSI_ID FROM SEC_BUY_SELL_O_TABLE
LEFT JOIN SECURITY_DEFN_O_TABLE ON TRIM(SEC_DEFN_NAME) = TRIM(NAME)
LEFT JOIN (SELECT * FROM TREASURY_REC_SSI_O_TABLE WHERE 
ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_REC_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY) 
UNION SELECT * FROM TREASURY_PAY_SSI_O_TABLE WHERE 
ROWID IN( SELECT  MIN(ROWID) FROM TREASURY_PAY_SSI_O_TABLE B WHERE SSI_TYPE='PRINCIPAL' GROUP BY  CPTY_NAME,NOSTRO_ID,CURRENCY)) ON TRIM(COUNTERPARTY_STRING)=TRIM(CPTY_NAME) AND 
TRIM(NOSTRO_ID) = TRIM(SI_FLOW_REC_NOSTRO) AND TRIM(ISSUE_CCY) =TRIM(CURRENCY)) B WHERE TRIM(A.DEAL_IDENTIFIER) = TRIM(B.DEAL_IDENTIFIER)) ;
COMMIT;
update SEC_BUY_SELL_O_TABLE set PRICE_STRING='100' where PRICE_STRING in('10000','50000');
commit;
exit;
 