
TRUNCATE TABLE SPOT_RATES_O_TABLE;
INSERT INTO SPOT_RATES_O_TABLE
 SELECT 
    ''Response,
    CASE WHEN TRIM(A.CCY) IN ('AUD','EUR','GBP','NZD') THEN A.CCY||'/USD' ELSE 'USD/'||A.CCY END Currency_Pair,  
    CASE WHEN TRIM(A.CCY) IN ('AUD','EUR','GBP','NZD') THEN TO_CHAR(A.CCY) ELSE 'USD' END Currency_One,  
    CASE WHEN TRIM(A.CCY) IN ('AUD','EUR','GBP','NZD') THEN 'USD' ELSE TO_CHAR(A.CCY) END Currency_Two,
    CASE WHEN TRIM(A.CCY) IN ('JPY') AND GET_PARAM('BANK_ID')='51' then  TO_CHAR(B.SPOTRATE_8*to_number(A.SPOTRATE_8),'999990.99999999') WHEN A.CCY IN ('AUD','EUR','GBP','NZD') THEN TO_CHAR(to_number(A.SPOTRATE_8)/B.SPOTRATE_8,'999990.99999999') ELSE TO_CHAR(B.SPOTRATE_8/to_number(A.SPOTRATE_8),'999990.99999999') END Bid,
    CASE WHEN TRIM(A.CCY) IN ('JPY') AND GET_PARAM('BANK_ID')='51' then  TO_CHAR(B.SPOTRATE_8*to_number(A.SPOTRATE_8),'999990.99999999') WHEN A.CCY IN ('AUD','EUR','GBP','NZD') THEN TO_CHAR(to_number(A.SPOTRATE_8)/B.SPOTRATE_8,'999990.99999999') ELSE TO_CHAR(B.SPOTRATE_8/to_number(A.SPOTRATE_8),'999990.99999999') END Offer ,
    TO_CHAR(TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY'),'DD-Mon-YYYY') Base_Date
 FROM REVP A
 LEFT JOIN REVP B ON B.CCY='USD'
 WHERE TRIM(A.CCY) NOT IN('LOC','USD','NOK','TND','CNY','KRW','MYR','CYP');
COMMIT;
TRUNCATE TABLE core_spot_rate;
INSERT INTO core_spot_rate
  SELECT 
    A.CCY FXD_CRNCY_CODE,
    B.CCY VAR_CRNCY_CODE,  
    TO_CHAR(A.SPOTRATE_8/to_number(B.SPOTRATE_8),'999990.99999999') MID_RATE,
    TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') Base_Date
 FROM tbaadm.rtm 
 LEFT JOIN REVP A ON TRIM(A.CCY) = TRIM(FXD_CRNCY_CODE) AND TRIM(A.BR)='01'
 LEFT JOIN REVP B ON TRIM(B.CCY) = TRIM(VAR_CRNCY_CODE) AND TRIM(B.BR)='01'
 where bank_id=GET_PARAM('BANK_ID') and RATECODE='MID' AND DEL_FLG='N' ;
 COMMIT;
EXIT;
 