TRUNCATE TABLE SPOT_POSITION_DEALS_O_TABLE;
DELETE FROM TR_SPOT_POSITION_DEALS WHERE AMOUNT='0';
COMMIT;
INSERT INTO TR_SPOT_POSITION_DEALS
SELECT 'USD' CCY,
       'SELL' BUY_SELL,
       '1000000' AMOUNT,
       'OPICS' BRANCH,
       TO_DATE (GET_PARAM ('EOD_DATE'), 'DD-MM-YYYY') DEAL_DATE
  FROM DUAL A
       LEFT JOIN TR_SPOT_POSITION_DEALS B ON 'USD' = TRIM(B.CCY) AND 'SELL' = TRIM(B.BUY_SELL) AND '1000000' = TRIM(B.AMOUNT) AND 'OPICS' = TRIM(B.BRANCH)
 WHERE B.CCY IS NULL  AND GET_PARAM('BANK_ID')='51';
 COMMIT;
INSERT INTO SPOT_POSITION_DEALS_O_TABLE
SELECT '' RESPONSE,
       'FX_OUTRIGHT_MARKET' PRODUCT_TYPE,
       TO_CHAR(DEAL_DATE,'DD-Mon-YYYY') DEAL_DATE,
       '/ABK/KUWAIT/BANKING/FX/NON_TREASURY' TRADING_BOOK,
       '/ABK/KUWAIT/BANKING/FX/NON_TREASURY' MAIN_LEG_SPOT_TRD_BOOK,
       '/ABK/KUWAIT/BANKING/FX/NON_TREASURY' MAIN_LEG_FWD_TRD_BOOK,
       'BANK' SUBTYPE,
       'FX' DEPT_NAME,
       CASE WHEN GET_PARAM('BANK_ID')='01' THEN 'ABKKWT' ELSE 'ABKUAE' END ENTITY_NAME,
       CASE WHEN GET_PARAM('BANK_ID')='01' THEN 'ABKKWT' ELSE 'ABKUAE' END MAIN_LEG_SPOT_RISK_ENTITY,
       CASE WHEN GET_PARAM('BANK_ID')='01' THEN 'ABKKWT' ELSE 'ABKUAE' END MAIN_LEG_FWD_RISK_ENTITY,
       TO_CHAR(TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY'),'DD-Mon-YYYY') MAIN_LEG_VALUE_DATE_ONE,
       '' ACCOUNTING_CODE,
       CASE WHEN GET_PARAM('BANK_ID')='01' THEN 'ABKKWT' ELSE 'ABKUAE' END MAIN_LEG_CPTY,
       CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN A.CCY||'/'||CASE WHEN GET_PARAM('BANK_ID')='01' THEN 'KWD' ELSE 'AED' END
            ELSE CASE WHEN GET_PARAM('BANK_ID')='01' THEN 'KWD' ELSE 'AED' END||'/'||A.CCY END  MAIN_LEG_CCY_PAIR,
       CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN BUY_SELL ELSE CASE WHEN BUY_SELL='BUY' THEN 'SELL' ELSE 'BUY' END END MAIN_LEG_FX_BUY_SELL,
       CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN AMOUNT ELSE AMOUNT*SPOTRATE_8 END MAIN_LEG_CCY_ONE_AMOUNT,
       CASE WHEN A.CCY='JPY' AND GET_PARAM('BANK_ID')='51' THEN CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN TO_CHAR(1/SPOTRATE_8,'99999990.99999999') ELSE TO_CHAR(SPOTRATE_8,'99999990.99999999') END 
            ELSE  CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN TO_CHAR(SPOTRATE_8,'99999990.99999999') ELSE TO_CHAR(1/SPOTRATE_8,'99999990.99999999') END  END MARKET_SPOT_RATE,
       CASE WHEN A.CCY='JPY' AND GET_PARAM('BANK_ID')='51' THEN CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN TO_CHAR(1/SPOTRATE_8,'99999990.99999999') ELSE TO_CHAR(SPOTRATE_8,'99999990.99999999') END 
            ELSE  CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN TO_CHAR(SPOTRATE_8,'99999990.99999999') ELSE TO_CHAR(1/SPOTRATE_8,'99999990.99999999') END  END MAIN_LEG_MARKET_SPOT_RATE,
       CASE WHEN A.CCY='JPY' AND GET_PARAM('BANK_ID')='51' THEN CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN TO_CHAR(1/SPOTRATE_8,'99999990.99999999') ELSE TO_CHAR(SPOTRATE_8,'99999990.99999999') END 
            ELSE  CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN TO_CHAR(SPOTRATE_8,'99999990.99999999') ELSE TO_CHAR(1/SPOTRATE_8,'99999990.99999999') END  END MAIN_LEG_MARKET_FWD_RATE,
       CASE WHEN A.CCY='JPY' AND GET_PARAM('BANK_ID')='51' THEN CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN TO_CHAR(1/SPOTRATE_8,'99999990.99999999') ELSE TO_CHAR(SPOTRATE_8,'99999990.99999999') END 
            ELSE  CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN TO_CHAR(SPOTRATE_8,'99999990.99999999') ELSE TO_CHAR(1/SPOTRATE_8,'99999990.99999999') END  END MAIN_LEG_CUSTOMER_SPOT_RATE,
       CASE WHEN A.CCY='JPY' AND GET_PARAM('BANK_ID')='51' THEN CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN TO_CHAR(1/SPOTRATE_8,'99999990.99999999') ELSE TO_CHAR(SPOTRATE_8,'99999990.99999999') END 
            ELSE  CASE WHEN CP.OPICS_CCY_PAIR IS NULL THEN TO_CHAR(SPOTRATE_8,'99999990.99999999') ELSE TO_CHAR(1/SPOTRATE_8,'99999990.99999999') END  END MAIN_LEG_CUSTOMER_FWD_RATE,
       '0' MAIN_LEG_MARKET_FWD_POINTS,
       '0' MAIN_LEG_CUSTOMER_FWD_POINTS,
       BRANCH MEMO_FIELD_1
  FROM TR_SPOT_POSITION_DEALS A
  LEFT JOIN REVP B ON  B.CCY = A.CCY
  LEFT JOIN TREASURY_QUOTED_CCY_PAIR CP ON CP.OPICS_CCY_PAIR = A.CCY||'/'||CASE WHEN GET_PARAM('BANK_ID')='01' THEN 'KWD' ELSE 'AED' END
  WHERE TO_NUMBER(AMOUNT) <> 0;
COMMIT;
EXIT;
/ 
