

--SWAP
select DEALNO,case when trim(SEQ)='001' then 'PAY' else 'REC' end SETTLEMENT_ACTION,SCHDSEQ,INTSTRTDTE,RATECODE,INTRATE_8 from SWDS where trim(DEALNO) in(select trim(s1.dealno) from SWDT S1  
INNER JOIN SWDH H ON trim(S1.DEALNO)=trim(H.DEALNO) AND TRIM(H.REVDATE) IS NULL
INNER JOIN CUST C ON C.CNO=H.CNO
WHERE S1.SEQ='001' AND S1.MATDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY'))
ORDER BY DEALNO,TO_NUMBER(SCHDSEQ);

--COM LOAN
select DEALNO,SCHDSEQ,INTSTRTDTE,RATECODE,INTRATE_8 from schd where trim(DEALNO) in(
SELECT TRIM(D.DEALNO) FROM DLDT D
INNER JOIN CUST C ON TRIM(D.CNO)=TRIM(C.CNO)  
WHERE D.MDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(D.REVDATE) IS NULL)
ORDER BY DEALNO,TO_NUMBER(SCHDSEQ);


--SECURITY
select SECID,SEQ,INTSTRTDTE,RATECODE,INTRATE_8 from SECS where TRIM(SECID) IN (SELECT trim(SECID) FROM TR_EQU_AND_SEC_OUTSTANDING WHERE TRIM(TYPE)='Fixed Income Investments' AND TRIM(NETQTY) != 0 AND TRIM(NETQTY) IS NOT NULL
union all
select trim(secid) secid from secm where trim(PRODTYPE) in ('TB','SB')  and MDATE > to_date(get_param('EOD_DATE'),'dd-mm-yyyy')) OR TRIM(SECID) IN(SELECT TRIM(SECID) FROM SPSH WHERE INVTYPE='I') 
ORDER BY SECID,TO_NUMBER(SEQ);



--------------------------------------------------



  SELECT BR,
         DEALNO,
         SEQ,
         PRODUCT,
         PRODTYPE,
         INTENDDTE,
         SCHDSEQ,
         SCHDTYPE,
         CCY,
         COMPOUND,
         TOTPAYAMT,
         PRINAMT,
         INTAMT,
         POSNINTAMT,
         INTSTRTDTE,
         IPAYDATE,
         AUTOMANPAY,
         lag(RATEREVDTE) over(partition by DEALNO order by TO_NUMBER (SCHDSEQ)) RATEREVDTE,--***
         lag(RATEFIXDTE) over(partition by DEALNO order by TO_NUMBER (SCHDSEQ)) RATEFIXDTE,--***
         SMEANS,
         SACCT,
         RATECODE,
         INTRATE_8,
         BASIS,
         SPREAD_8,
         REVDATE,
         VERDATE,
         MANPAYDTE,
         PPAYAMT,
         AL,
         LSTMNTDATE,
         BRPRCINDTE,
         NOTPRIN,
         WHTRATE_8,
         WHTBASIS,
         WHTAMT,
         WHTIND,
         VATAMT,
         VATRATE_8,
         FUNDRATE_8,
         FUNDBASIS,
         FUNDAMT,
         PPAYDATE,
         PAYAUTHDTE,
         PAYAUTHIND,
         INTCCY,
         INTEXCHARATE_8,
         TERMS,
         POSNFUNDAMT,
         INTSMEANS,
         INTSACCT,
         INTAUTHIND,
         INTAUTHOPER,
         INTAUTHDATE,
         CAPINTIND,
         CAPINTAMT,
         CAPTAXAMT,
         APPLIEDMONTHALL,
         POSNPRINAMT,
         RATEAMTINT,
         RATEAMTFUND,
         RATEAMTTAX1,
         RATEAMTTAX2,
         RATEAMTTAX3,
         TEXT1,
         TEXT2,
         DATE1,
         DATE2,
         NEXTAPPMONTHALL,
         AMOUNT2,
         INTOPER,
         PRINOPER,
         PRINAUTHOPER,
         NETSIIND,
         NETDEALNO,
         NETSEQ,
         CORPNETIND,
         PRINUSUALID,
         INTUSUALID,
         AMOUNT1,
         RATE1,
         RATE2,
         TAXSTATUSIND,
         STEPUPCORRRATE_8,
         STEPUPCORRINTAMT
    FROM SCHD
   WHERE TRIM (DEALNO) IN (SELECT TRIM (DEAL_IDENTIFIER) FROM COM_LOAN_O_TABLE)
ORDER BY DEALNO, TO_NUMBER (SCHDSEQ);

 SELECT BR,
         DEALNO,
         SEQ,
         DEALIND,
         PRODUCT,
         PRODTYPE,
         INTENDDTE,
         SCHDSEQ,
         SCHDTYPE,
         BASIS,
         BRPRCINDTE,
         CALCRULE,
         COMPOUND,
         FIXEDINTAMT,
         FIXFLOATIND,
         IMPLINTAMT,
         IMPLINTRATE_8,
         INTAMT,
         INTAUTHDATE,
         INTAUTHIND,
         INTAUTHOPER,
         INTCCY,
         INTEXCHRATE_8,
         INTEXCHTERMS,
         INTRATE_8,
         INTRATECAP_8,
         INTRATEFLOOR_8,
         INTSACCT,
         INTSMEANS,
         INTSTRTDTE,
         IPAYDATE,
         LSTMNTDTE,
         NETIPAY,
         PAYRECIND,
         POSNINTAMT,
         PPAYAMT,
         PPAYAUTHDTE,
         PPAYAUTHIND,
         PPAYAUTHOPER,
         PPAYCCY,
         PPAYDATE,
         PRINADJAMT,
         PRINAMT,
         PRINCCY,
         PRINCCYINTAMT,
         PRINRATECODE,
         RATECODE,
         lag(RATEFIXDTE) over(partition by DEALNO, seq order by TO_NUMBER (SCHDSEQ)) RATEFIXDTE,--***
         lag(RATEREVDTE) over(partition by DEALNO, seq order by TO_NUMBER (SCHDSEQ)) RATEREVDTE,--***
         REVDATE,
         RATEREVFRSTLST,
         SPREAD_8,
         STEPRATE_8,
         VERDATE,
         PVAMT,
         SPREADAMT,
         PVBAMT,
         PS,
         STRIKE_8,
         INDEX_8,
         PARTICPERC_8,
         COLLARIND,
         EXCHRATE_8,
         EXCHAMT,
         PRINSETTMEANS,
         PRINSETTACCT,
         LASTCOUPONDATE,
         EXCHRATEREVDATE,
         AMOUNT1,
         AMOUNT2,
         AMOUNT3,
         NVARCHAR21,
         NVARCHAR22,
         NVARCHAR23,
         DATE1,
         DATE2,
         FORMULAIND,
         RATE1_8,
         RATE2_8,
         FACTOR_12,
         FACTORDATE,
         FACTORFIXDATE,
         FLATINTCOMPAMT,
         SUMCOMPOUNDAMT,
         REMAININGPAY,
         SETTLE,
         FACTORREVDATE,
         MBSPAYDAY,
         INTDEAL,
         TAXDDEALNO,
         TAXDPRODUCT,
         TAXDPRODTYPE,
         TAXDSEQ,
         TAXAMT,
         INTERNALRATE_8,
         CORPSPREAD_8,
         CORPSPREADAMT,
         EXCHTERMS,
         FLAG2,
         FLAG3,
         RATE3_8,
         RATE4_8,
         DATE3,
         DATE4,
         AMOUNT4,
         AMOUNT5,
         ACCRINT,
         CCYTAX,
         CONVPRICE_12,
         PRICE_12,
         PRICEEXCHRATE_8,
         PRICEEXCHTERMS,
         INTNEGAUTHDTE,
         INTNEGAUTHIND,
         INTNEGAUTHOPER,
         INTNEGSACCT,
         INTNEGSMEANS,
         REPRICEDATE,
         RATEOFRETURN_12,
         DIVMKTMKTAMT,
         DIVPAYAMT,
         DIVPERCENT_8,
         DIVPAYDATEIND,
         EQUITYTYPE,
         BREAKDATE,
         UNDINTPAYAMT,
         UNADJINTENDDTE,
         UNADJINTSTRTDTE,
         GROUPID,
         FORMULAID,
         FIXINGOVERRIDE
    FROM SWDS
   WHERE TRIM (DEALNO) IN (SELECT TRIM (IDENTIFIER) FROM SWAP_O_TABLE)
 --  and dealno='8100027'
ORDER BY DEALNO, seq,TO_NUMBER (SCHDSEQ);

SELECT * FROM SECS WHERE TRIM(secid) IN(SELECT TRIM(NAME) FROM SECURITY_DEFN_O_TABLE) order by secid,to_number(seq); 
