truncate table TREASURY_PAY_SSI_TEMP_TABLE;
insert into TREASURY_PAY_SSI_TEMP_TABLE 
SELECT DISTINCT
       '' Response,
       TRIM(CCY)||'_'||SUBSTR(TRIM(CMNE),LENGTH(TRIM(CMNE))-3) SSI_ID,
       TRIM(CMNE) CPTY_NAME,
       'PAY' SSI_SETTLEMENT_ACTION,
       TRIM(CCY) CURRENCY,
       DEAL_TYPE,
       'YES' SSI_DEFAULT,
       '01-JAN-2000' EFFECTIVE_DATE,
       CASE WHEN TRIM(SMEANS)='NOS'then 'SWIFT' end SETT_METHOD,
       CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ENTITY_NAME,
       'ALL' SUBTYPE,
       'TRADE' CPTY_ROLE,
       TRIM(SSI_TYPE) SSI_TYPE,
       CASE WHEN TRIM(CPAW_BIC) IS NOT NULL THEN 'FORMAT A' ELSE 'FORMAT D' END AGENT_INST_FORMAT,
       TRIM(CPAW_BIC) AGENT_INST_BIC,
       TRIM(CPAW_ACCTNO) AGENT_INST_ID,
        CASE WHEN TRIM(SMEANS)='NOS' and TRIM(CPAW_BIC) IS NULL then A.AGENT_INST_ADDRESS end AGENT_INST_ADDRESS,
       CASE WHEN TRIM(SMEANS) in('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TRIM(SACCT) END NOSTRO_ID,
       '' DEPOSITORY,
       TRIM(CP_ACCTNO) ALT_BENEF_ID,
       CASE WHEN TRIM(CP_BIC) IS NOT NULL THEN 'FORMAT A' ELSE 'FORMAT D' END ALT_BENEF_FORMAT,
       TRIM(CP_BIC) ALT_BENEF_BIC,
       '' TYPE
FROM (
select CS.CCY,CU.CMNE,CS.SACCT,CS.BR,CP.TYPE,CPAW.BIC CPAW_BIC,CPAW.ACCTNO CPAW_ACCTNO,CP.ACCTNO CP_ACCTNO,CP.BIC CP_BIC,CS.SMEANS,
'All Deal Types' DEAL_TYPE,
'PRINCIPAL' SSI_TYPE,trim(trim(CP.C1)||' '||trim(CP.C2)||' '||trim(CP.C3)||' '||trim(CP.C4)) AGENT_INST_ADDRESS
from CPCI CP 
LEFT JOIN CSPI CS ON CS.CNO=CP.CNO AND CS.TYPE=CP.TYPE AND CS.PRODUCT=CP.PRODUCT AND CS.CCY=CP.CCY
INNER JOIN CUST CU ON TRIM(CS.CNO)=TRIM(CU.CNO)  AND TRIM(CU.BIC) IS NOT NULL
LEFT JOIN CPCI CPAW ON CP.CNO=CPAW.CNO AND CPAW.PCC='AW' AND CP.PRODUCT=CPAW.PRODUCT AND CPAW.CCY=CP.CCY AND CP.TYPE=CPAW.TYPE
WHERE CP.PCC='BE' and CP.PRODUCT != 'DEFSI'
UNION 
select CS.CCY,CU.CMNE,CS.SACCT,CS.BR,CP.TYPE,CPAW.BIC CPAW_BIC,CPAW.ACCTNO CPAW_ACCTNO,CP.ACCTNO CP_ACCTNO,CP.BIC CP_BIC,CS.SMEANS,
'All Deal Types' DEAL_TYPE,
'INT/COUPON' SSI_TYPE,trim(trim(CP.C1)||' '||trim(CP.C2)||' '||trim(CP.C3)||' '||trim(CP.C4)) AGENT_INST_ADDRESS
from CPCI CP 
inner JOIN CSPI CS ON CS.CNO=CP.CNO AND CS.TYPE=CP.TYPE AND CS.PRODUCT=CP.PRODUCT AND CS.CCY=CP.CCY
INNER JOIN CUST CU ON TRIM(CS.CNO)=TRIM(CU.CNO) AND TRIM(CU.BIC) IS NOT NULL
LEFT JOIN CPCI CPAW ON CP.CNO=CPAW.CNO AND CPAW.PCC='AW' AND CP.PRODUCT=CPAW.PRODUCT AND CPAW.CCY=CP.CCY AND CP.TYPE=CPAW.TYPE
WHERE CP.PCC='BE' and CP.PRODUCT = 'DPNL' 
) A
INNER JOIN SD_NOSTRO SD_NOS ON case when TRIM(SD_NOS.NAME)='SCBDLE' then 'SCBLDE' else TRIM(SD_NOS.NAME) end = CASE WHEN TRIM(SMEANS) in('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TRIM(SACCT) END
 where trim(SMEANS) in ('BRDGE','NOS') AND TRIM(CMNE) IN(
select TRIM(TREASURY_COUNTERPARTY_MNEMONIC)  TREASURY_COUNTERPARTY_MNEMONIC from corp_COREINTERFACE
union 
select TRIM(TREASURY_COUNTERPARTY_MNEMONIC) from RETAIL_COREINTERFACE
union 
select to_char(trim(NAME)) from tr_not_mig_cpty_core_o_table
UNION
SELECT TO_CHAR(TRIM(MNEMONIC)) FROM TREASURY_GROUP_O_TABLE
);
commit;
insert into TREASURY_PAY_SSI_TEMP_TABLE 
SELECT DISTINCT
       '' Response,
       TRIM(CCY)||'_'||SUBSTR(TRIM(CMNE),LENGTH(TRIM(CMNE))-3) SSI_ID,
       TRIM(CMNE) CPTY_NAME,
       'PAY' SSI_SETTLEMENT_ACTION,
       TRIM(CCY) CURRENCY,
       DEAL_TYPE,
       'YES' SSI_DEFAULT,
       '01-JAN-2000' EFFECTIVE_DATE,
       CASE WHEN TRIM(SMEANS)='NOS'then 'SWIFT' end SETT_METHOD,
       CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ENTITY_NAME,
       'ALL' SUBTYPE,
       'TRADE' CPTY_ROLE,
       TRIM(SSI_TYPE) SSI_TYPE,
       CASE WHEN TRIM(CPAW_BIC) IS NOT NULL THEN 'FORMAT A' ELSE 'FORMAT D' END AGENT_INST_FORMAT,
       TRIM(CPAW_BIC) AGENT_INST_BIC,
       TRIM(CPAW_ACCTNO) AGENT_INST_ID,
       A.AGENT_INST_ADDRESS AGENT_INST_ADDRESS,
       CASE WHEN TRIM(SMEANS) in('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TRIM(SACCT) END NOSTRO_ID,
       '' DEPOSITORY,
       TRIM(CP_ACCTNO) ALT_BENEF_ID,
       CASE WHEN TRIM(CP_BIC) IS NOT NULL THEN 'FORMAT A' ELSE '' END ALT_BENEF_FORMAT,
       TRIM(CP_BIC) ALT_BENEF_BIC,
       '' TYPE
FROM (
select CS.CCY,CU.CMNE,CS.SACCT,CS.BR,CP.TYPE,CPAW.BIC CPAW_BIC,CPAW.ACCTNO CPAW_ACCTNO,CP.ACCTNO CP_ACCTNO,CP.BIC CP_BIC,CS.SMEANS,
'All Deal Types' DEAL_TYPE,
'PRINCIPAL' SSI_TYPE,trim(trim(CP.C1)||' '||trim(CP.C2)||' '||trim(CP.C3)||' '||trim(CP.C4)) AGENT_INST_ADDRESS
from UPCI  CP 
INNER JOIN USPI  CS ON CS.CNO=CP.CNO AND CS.TYPE=CP.TYPE AND CS.PRODUCT=CP.PRODUCT AND CS.CCY=CP.CCY
INNER JOIN CUST CU ON TRIM(CS.CNO)=TRIM(CU.CNO) AND TRIM(CU.BIC) IS NOT NULL
LEFT JOIN UPCI  CPAW ON CP.CNO=CPAW.CNO AND CPAW.PCC='AW' AND CP.PRODUCT=CPAW.PRODUCT AND CPAW.CCY=CP.CCY AND CP.TYPE=CPAW.TYPE
WHERE CP.PCC='BE' and CP.PRODUCT != 'DEFSI'
UNION 
select CS.CCY,CU.CMNE,CS.SACCT,CS.BR,CP.TYPE,CPAW.BIC CPAW_BIC,CPAW.ACCTNO CPAW_ACCTNO,CP.ACCTNO CP_ACCTNO,CP.BIC CP_BIC,CS.SMEANS,
'All Deal Types' DEAL_TYPE,
'INT/COUPON' SSI_TYPE,trim(trim(CP.C1)||' '||trim(CP.C2)||' '||trim(CP.C3)||' '||trim(CP.C4)) AGENT_INST_ADDRESS
from UPCI  CP 
LEFT JOIN USPI  CS ON CS.CNO=CP.CNO AND CS.TYPE=CP.TYPE AND CS.PRODUCT=CP.PRODUCT AND CS.CCY=CP.CCY
INNER JOIN CUST CU ON TRIM(CS.CNO)=TRIM(CU.CNO) AND TRIM(CU.BIC) IS NOT NULL
LEFT JOIN UPCI  CPAW ON CP.CNO=CPAW.CNO AND CPAW.PCC='AW' AND CP.PRODUCT=CPAW.PRODUCT AND CPAW.CCY=CP.CCY AND CP.TYPE=CPAW.TYPE
WHERE CP.PCC='BE' and CP.PRODUCT = 'DPNL'  
) A
INNER JOIN SD_NOSTRO SD_NOS ON case when TRIM(SD_NOS.NAME)='SCBDLE' then 'SCBLDE' else TRIM(SD_NOS.NAME) end  = CASE WHEN TRIM(SMEANS) in('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TRIM(SACCT) END
 where trim(SMEANS) in ('BRDGE','NOS');
commit;
UPDATE TREASURY_PAY_SSI_TEMP_TABLE SET SUBTYPE='INTGRP' WHERE TRIM(CPTY_NAME)=CASE WHEN GET_PARAM('BANK_ID')='51' THEN 'AEAHLK' WHEN GET_PARAM('BANK_ID')='01' THEN 'ABKDXB' END and trim(DEAL_TYPE) ='COM_LOAN';
COMMIT;
DELETE FROM TREASURY_PAY_SSI_TEMP_TABLE WHERE TRIM(CPTY_NAME) NOT IN(
select TRIM(TREASURY_COUNTERPARTY_MNEMONIC)  TREASURY_COUNTERPARTY_MNEMONIC from corp_COREINTERFACE
union 
select TRIM(TREASURY_COUNTERPARTY_MNEMONIC) from RETAIL_COREINTERFACE
union 
select to_char(trim(NAME)) from tr_not_mig_cpty_core_o_table
UNION
SELECT TO_CHAR(TRIM(MNEMONIC)) FROM TREASURY_GROUP_O_TABLE
);
COMMIT;

--UPDATE TREASURY_PAY_SSI_TEMP_TABLE SET NOSTRO_ID='SCBDLE' WHERE TRIM(NOSTRO_ID)='SCBLDE';
--COMMIT;

--delete from TREASURY_PAY_SSI_O_TABLE where (trim(CPTY_NAME)='AESBTM' and trim(currency) in ('INR','JPY' )) or TRIM(NOSTRO_ID) IN('DEUTSH','NATWES','UBAFTY');
--commit;
exit; 
