
TRUNCATE TABLE TREASURY_REC_SSI_TEMP_TABLE;
INSERT INTO TREASURY_REC_SSI_TEMP_TABLE
SELECT DISTINCT 
       '' Response,
       TRIM(CCY)||'_'||SUBSTR(TRIM(CMNE),LENGTH(TRIM(CMNE))-3)  SSI_ID,
       TRIM(CMNE) CPTY_NAME,
       'REC' SSI_SETTLEMENT_ACTION,
       TRIM(CCY) CURRENCY,
       DEAL_TYPE,
       'YES' SSI_DEFAULT,
       '01-JAN-2000' EFFECTIVE_DATE,
       CASE WHEN TRIM(SMEANS)='NOS'then 'SWIFT' end SETT_METHOD,
       CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ENTITY_NAME,
       'ALL' SUBTYPE,
       'TRADE' CPTY_ROLE,
       TRIM(SSI_TYPE) SSI_TYPE,
       '' AGENT_INST_FORMAT,
       '' AGENT_INST_BIC,
       '' AGENT_INST_ID,
       A.AGENT_INST_ADDRESS AGENT_INST_ADDRESS,
       CASE WHEN TRIM(SMEANS) in('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TRIM(SACCT) END NOSTRO_ID,
       '' DEPOSITORY,
       '' ALT_BENEF_ID,
       '' ALT_BENEF_FORMAT,
       '' ALT_BENEF_BIC,
       '' TYPE
FROM (
    SELECT CS.CCY,CU.CMNE,CS.SACCT,CS.BR,CS.SMEANS,TYPE,'All Deal Types' DEAL_TYPE,'PRINCIPAL' SSI_TYPE,trim(trim(CS.C1)||' '||trim(CS.C2)||' '||trim(CS.C3)||' '||trim(CS.C4)) AGENT_INST_ADDRESS
    FROM CSRI CS
    INNER JOIN CUST CU ON TRIM(CS.CUST)=TRIM(CU.CNO)AND TRIM(CU.BIC) IS NOT NULL
    WHERE TRIM(SMEANS)!='EQ' and CS.PRODUCT != 'DEFSI'
    union
    SELECT CS.CCY,CU.CMNE,CS.SACCT,CS.BR,CS.SMEANS,TYPE,'All Deal Types' DEAL_TYPE,'INT/COUPON' SSI_TYPE,trim(trim(CS.C1)||' '||trim(CS.C2)||' '||trim(CS.C3)||' '||trim(CS.C4)) AGENT_INST_ADDRESS
    FROM CSRI CS
    INNER JOIN CUST CU ON TRIM(CS.CUST)=TRIM(CU.CNO)AND TRIM(CU.BIC) IS NOT NULL
    WHERE TRIM(SMEANS)!='EQ' and CS.PRODUCT = 'DPNL'
) A
INNER JOIN SD_NOSTRO SD_NOS ON TRIM(SD_NOS.NAME) = CASE WHEN TRIM(SMEANS) in('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TRIM(SACCT) END
  where trim(SMEANS) in ('BRDGE','NOS') AND TRIM(CMNE) IN (
select TRIM(TREASURY_COUNTERPARTY_MNEMONIC)  TREASURY_COUNTERPARTY_MNEMONIC from corp_COREINTERFACE
union 
select TRIM(TREASURY_COUNTERPARTY_MNEMONIC) from RETAIL_COREINTERFACE
union 
select to_char(trim(NAME)) from tr_not_mig_cpty_core_o_table
UNION
SELECT TO_CHAR(TRIM(MNEMONIC)) FROM TREASURY_GROUP_O_TABLE
);
COMMIT;
UPDATE TREASURY_REC_SSI_TEMP_TABLE SET SUBTYPE='INTGRP' WHERE TRIM(CPTY_NAME)=CASE WHEN GET_PARAM('BANK_ID')='51' THEN 'AEAHLK' WHEN GET_PARAM('BANK_ID')='01' THEN 'ABKDXB' END and trim(DEAL_TYPE) ='COM_LOAN';
COMMIT;


--UPDATE TREASURY_REC_SSI_TEMP_TABLE SET NOSTRO_ID='SCBDLE' WHERE TRIM(NOSTRO_ID)='SCBLDE';
--COMMIT;

--delete from TREASURY_REC_SSI_O_TABLE where (trim(CPTY_NAME)='AESBTM' and trim(currency) in ('INR','JPY' )) or TRIM(NOSTRO_ID) IN('DEUTSH','NATWES','UBAFTY');
--commit;
UPDATE TREASURY_PAY_SSI_TEMP_TABLE SET SSI_SETTLEMENT_ACTION='ALL' WHERE TRIM(DEAL_TYPE)|| TRIM(CPTY_NAME)|| TRIM(SSI_TYPE) || TRIM(NOSTRO_ID) || TRIM(CURRENCY)|| TRIM(SUBTYPE) IN (
SELECT TRIM(B.DEAL_TYPE)|| TRIM(B.CPTY_NAME)|| TRIM(B.SSI_TYPE) || TRIM(B.NOSTRO_ID) || TRIM(B.CURRENCY)|| TRIM(B.SUBTYPE) FROM TREASURY_PAY_SSI_TEMP_TABLE A
INNER JOIN TREASURY_REC_SSI_TEMP_TABLE B ON TRIM(A.DEAL_TYPE) = TRIM(B.DEAL_TYPE)  
AND TRIM(A.CPTY_NAME) = TRIM(B.CPTY_NAME) AND trim(A.SSI_TYPE) =  trim(B.SSI_TYPE )
AND TRIM(A.NOSTRO_ID) = TRIM(B.NOSTRO_ID) AND TRIM(A.CURRENCY) = TRIM(B.CURRENCY)  AND trim(A.SUBTYPE) = trim(B.SUBTYPE)
);
COMMIT;
DROP SEQUENCE TREASURY_SSI_SEQ;
CREATE SEQUENCE TREASURY_SSI_SEQ;
UPDATE TREASURY_PAY_SSI_TEMP_TABLE SET SSI_ID = SSI_ID||'_'||CASE WHEN SSI_SETTLEMENT_ACTION='ALL' THEN 'A' ELSE 'P' END||'_'||LPAD(TREASURY_SSI_SEQ.NEXTVAL,4,'0');
COMMIT;
TRUNCATE TABLE TREASURY_PAY_SSI_O_TABLE;
INSERT INTO TREASURY_PAY_SSI_O_TABLE
SELECT DISTINCT
RESPONSE             ,
SSI_ID               ,
CPTY_NAME            ,
SSI_SETTLEMENT_ACTION,
CURRENCY             ,
DEAL_TYPE            ,
SSI_DEFAULT          ,
EFFECTIVE_DATE       ,
SETT_METHOD          ,
ENTITY_NAME          ,
SUBTYPE              ,
CPTY_ROLE            ,
SSI_TYPE             ,
AGENT_INST_FORMAT    ,
AGENT_INST_BIC       ,
AGENT_INST_ID        ,
AGENT_INST_ADDRESS   ,
NOSTRO_ID            ,
DEPOSITORY           ,
ALT_BENEF_ID         ,
ALT_BENEF_FORMAT     ,
ALT_BENEF_BIC
 FROM TREASURY_PAY_SSI_TEMP_TABLE;
 COMMIT;
DELETE FROM TREASURY_REC_SSI_O_TABLE  WHERE TRIM(DEAL_TYPE)|| TRIM(CPTY_NAME)|| TRIM(SSI_TYPE) || TRIM(NOSTRO_ID) || TRIM(CURRENCY)|| TRIM(SUBTYPE) IN (
SELECT TRIM(B.DEAL_TYPE)|| TRIM(B.CPTY_NAME)|| TRIM(B.SSI_TYPE) || TRIM(B.NOSTRO_ID) || TRIM(B.CURRENCY)|| TRIM(B.SUBTYPE) FROM TREASURY_PAY_SSI_O_TABLE A
INNER JOIN TREASURY_REC_SSI_O_TABLE B ON TRIM(A.DEAL_TYPE) = TRIM(B.DEAL_TYPE)  
AND TRIM(A.CPTY_NAME) = TRIM(B.CPTY_NAME) AND trim(A.SSI_TYPE) =  trim(B.SSI_TYPE )
AND TRIM(A.NOSTRO_ID) = TRIM(B.NOSTRO_ID) AND TRIM(A.CURRENCY) = TRIM(B.CURRENCY) AND trim(A.SUBTYPE) = trim(B.SUBTYPE)
);
COMMIT;
DELETE FROM TREASURY_REC_SSI_TEMP_TABLE  WHERE TRIM(DEAL_TYPE)|| TRIM(CPTY_NAME)|| TRIM(SSI_TYPE) || TRIM(NOSTRO_ID) || TRIM(CURRENCY)|| TRIM(SUBTYPE) IN (
SELECT TRIM(B.DEAL_TYPE)|| TRIM(B.CPTY_NAME)|| TRIM(B.SSI_TYPE) || TRIM(B.NOSTRO_ID) || TRIM(B.CURRENCY)|| TRIM(B.SUBTYPE) FROM TREASURY_PAY_SSI_TEMP_TABLE A
INNER JOIN TREASURY_REC_SSI_TEMP_TABLE B ON TRIM(A.DEAL_TYPE) = TRIM(B.DEAL_TYPE)  
AND TRIM(A.CPTY_NAME) = TRIM(B.CPTY_NAME) AND trim(A.SSI_TYPE) =  trim(B.SSI_TYPE )
AND TRIM(A.NOSTRO_ID) = TRIM(B.NOSTRO_ID) AND TRIM(A.CURRENCY) = TRIM(B.CURRENCY) AND trim(A.SUBTYPE) = trim(B.SUBTYPE)
);
COMMIT;
UPDATE TREASURY_REC_SSI_TEMP_TABLE SET SSI_ID = SSI_ID||'_'||CASE WHEN SSI_SETTLEMENT_ACTION='ALL' THEN 'A' ELSE 'R' END||'_'||LPAD(TREASURY_SSI_SEQ.NEXTVAL,4,'0');
COMMIT;
TRUNCATE TABLE TREASURY_REC_SSI_O_TABLE;
INSERT INTO TREASURY_REC_SSI_O_TABLE
SELECT DISTINCT
RESPONSE             ,
SSI_ID               ,
CPTY_NAME            ,
SSI_SETTLEMENT_ACTION,
CURRENCY             ,
DEAL_TYPE            ,
SSI_DEFAULT          ,
EFFECTIVE_DATE       ,
SETT_METHOD          ,
ENTITY_NAME          ,
SUBTYPE              ,
CPTY_ROLE            ,
SSI_TYPE             ,
AGENT_INST_FORMAT    ,
AGENT_INST_BIC       ,
AGENT_INST_ID        ,
AGENT_INST_ADDRESS   ,
NOSTRO_ID            ,
DEPOSITORY           ,
ALT_BENEF_ID         ,
ALT_BENEF_FORMAT     ,
ALT_BENEF_BIC
 FROM TREASURY_REC_SSI_TEMP_TABLE;
 COMMIT;
 update TREASURY_REC_SSI_O_TABLE set SSI_SETTLEMENT_ACTION='ALL';
 commit;
 update TREASURY_PAY_SSI_O_TABLE set SSI_SETTLEMENT_ACTION='ALL';
 commit;
 UPDATE TREASURY_PAY_SSI_O_TABLE SET AGENT_INST_ADDRESS = (SELECT TRIM(SN)||' '||trim(BA1)||' '||trim(BA2)||' '||trim(ba3)||' '||trim(ba4)||' '||trim(ba5) FROM BICO WHERE  TRIM(BIC) = TRIM(AGENT_INST_BIC));
commit;
 UPDATE TREASURY_REC_SSI_O_TABLE SET AGENT_INST_ADDRESS = (SELECT TRIM(SN)||' '||trim(BA1)||' '||trim(BA2)||' '||trim(ba3)||' '||trim(ba4)||' '||trim(ba5) FROM BICO WHERE  TRIM(BIC) = TRIM(AGENT_INST_BIC));
 commit;
exit; 
