
TRUNCATE TABLE TREASURY_BIC_O_TABLE;
INSERT INTO TREASURY_BIC_O_TABLE
SELECT  ' ' RESPONSE,
       'FBO_SWIFT_BIC_CODE_DATA' FBO_TYPE,
       TRIM(BIC) BIC_CODE,
       TRIM(SN) DESCRIPTION
  FROM BICO a
  WHERE exists (select 1 from(
  SELECT TO_CHAR(TRIM(BIC)) BIC FROM CUST WHERE TRIM(CMNE) NOT LIKE 'AE%' AND TRIM(BIC) IS NOT NULL
  UNION
  SELECT TO_CHAR(TRIM(AGENT_INST_BIC)) FROM TREASURY_PAY_SSI_O_TABLE WHERE TRIM(AGENT_INST_BIC) IS NOT NULL
  UNION
  SELECT TO_CHAR(TRIM(ALT_BENEF_BIC)) FROM TREASURY_PAY_SSI_O_TABLE WHERE TRIM(ALT_BENEF_BIC) IS NOT NULL
  UNION
  SELECT TO_CHAR(TRIM(AGENT_INST_BIC)) FROM TREASURY_REC_SSI_O_TABLE WHERE TRIM(AGENT_INST_BIC) IS NOT NULL
  UNION
  SELECT TO_CHAR(TRIM(ALT_BENEF_BIC)) FROM TREASURY_REC_SSI_O_TABLE WHERE TRIM(ALT_BENEF_BIC) IS NOT NULL
  ) b where TRIM(a.BIC) = TRIM(b.BIC) );
COMMIT;
EXIT;  
