TRUNCATE TABLE CPTY_COUNTRY_LIMIT_O_TABLE;
INSERT INTO crlm_MIG
SELECT A.*
  FROM CRLM_GRP a
  LEFT JOIN crlm_MIG b ON a.br = b.br AND a.LIMITMEMBER = b.LIMITMEMBER AND a.PRODGROUPID = b.PRODGROUPID AND a.MTYDATE = b.MTYDATE
           AND a.CREQLIMAMT = b.CREQLIMAMT AND a.ccy = b.ccy
 WHERE b.br IS NULL;
 COMMIT;
 INSERT INTO crlm_MIG
 SELECT A.*
  FROM CRLM_CNTRY a
  LEFT JOIN crlm_MIG b ON a.br = b.br AND a.LIMITMEMBER = b.LIMITMEMBER AND a.PRODGROUPID = b.PRODGROUPID AND a.MTYDATE = b.MTYDATE
           AND a.CREQLIMAMT = b.CREQLIMAMT AND a.ccy = b.ccy
 WHERE b.br IS NULL;
 COMMIT;
INSERT INTO CPTY_COUNTRY_LIMIT_O_TABLE
  SELECT '' Response,
       'FBO_COUNTRY_LIMIT_INFO' FBO_TYPE,
       CASE WHEN TRIM(LM.PRODGROUPID)='FX DEALS' THEN 'FX_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='INVESTMENT' THEN 'IN_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='IRS DEALS' THEN 'IR_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='MM DEALS' THEN 'MM_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE ||'_'||BR
			WHEN TRIM(LM.PRODGROUPID)='ACIC' THEN 'ACIC_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE ||'_'||BR
       END  LIMIT_NAME,
       CASE WHEN TRIM(LM.PRODGROUPID)='FX DEALS' AND TRIM(MTYDATE)='DS'  THEN 'FX_LIMIT_DS_CTR' 
            WHEN TRIM(LM.PRODGROUPID)='MM DEALS' AND TRIM(MTYDATE)='DS'  THEN 'MM_LIMIT_DS_CTR'  
            WHEN TRIM(LM.PRODGROUPID)='FX DEALS' AND TRIM(MTYDATE)='TOT' THEN 'FX_CTR_LIMIT_NT' 
            WHEN TRIM(LM.PRODGROUPID)='ACIC' AND TRIM(MTYDATE)!='TOT' THEN 'ACIC_CTR_LIMIT' 
			WHEN TRIM(LM.PRODGROUPID)='ACIC' AND TRIM(MTYDATE)='TOT' THEN 'ACIC_CTR_LIMIT_NT' 
            WHEN TRIM(LM.PRODGROUPID)='FX DEALS' AND TRIM(MTYDATE)!='TOT' THEN 'FX_CTR_LIMIT' 
            WHEN TRIM(LM.PRODGROUPID)='INVESTMENT' AND TRIM(MTYDATE)='TOT' THEN 'INV_CTR_LIMIT_NT' 
            WHEN TRIM(LM.PRODGROUPID)='INVESTMENT' AND TRIM(MTYDATE)!='TOT' THEN 'INV_CTR_LIMIT' 
            WHEN TRIM(LM.PRODGROUPID)='IRS DEALS' AND TRIM(MTYDATE)='TOT' THEN 'IRS_CTR_LIMIT_NT'
            WHEN TRIM(LM.PRODGROUPID)='IRS DEALS' AND TRIM(MTYDATE)!='TOT' THEN 'IRS_CTR_LIMIT'
            WHEN TRIM(LM.PRODGROUPID)='MM DEALS' AND TRIM(MTYDATE)='TOT' THEN 'MM_CTR_LIMIT_NT'
            WHEN TRIM(LM.PRODGROUPID)='MM DEALS' AND TRIM(MTYDATE)!='TOT' THEN 'MM_CTR_LIMIT' 
       END USER_LIMIT_TYPE,
       'Country Limit' USER_LIMIT_TYPE_SYS_LIMIT_TYPE,
       LM.CCY LIMIT_CCY,
       CASE WHEN LM.CREQLIMAMT='0' THEN '0.1' ELSE TO_CHAR(LM.CREQLIMAMT) END LIMIT_AMOUNT,
       'Default Action' EXCESS_ACTION,
       'Absolute Level' BREACH_LEVEL_TYPE,
       'Net Long' USER_LIMIT_TYP_EXP_AGGR_METHOD,
       CASE WHEN TRIM(EXPDATE) IS NOT NULL THEN TO_CHAR(TO_DATE(EXPDATE,'YYYY-MM-DD'),'DD-MON-YYYY') ELSE TO_CHAR(TRIM(EXPDATE)) END EXPIRY_DATE,
       CASE WHEN BR='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ENTITY,
       '' SUBTYPE,
       '' DEPT_NAME,
       TRIM(LM.LIMITMEMBER) COUNTRY_CODE,-- need to put dynamic value
       'Country Of Incorporation' COUNTRY_RISK_TYPE,
       CASE WHEN BR='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ENTITY_NAME,
       '' ALERT_USER_GROUP,
       '' EXC_AUTH_PRIV_GROUP,
       '' REPORT_PRIV_GROUP,
       '' EMAIL_ID,
       CASE WHEN TRIM(MTYDATE ) in ('TOT','DS') THEN '7' ELSE '3'  END TENOR_START_CODE,
       '0' TENOR_START_YEARS,--CASE WHEN TRIM(MTYDATE)!='TOT' THEN '0' ELSE '' END
       '0' TENOR_START_MONTHS,--CASE WHEN TRIM(MTYDATE)!='TOT' THEN '0' ELSE '' END
       '0' TENOR_START_DAYS,--CASE WHEN TRIM(MTYDATE)!='TOT' THEN '0' ELSE '' END
       '7' TENOR_END_CODE,
       CASE WHEN TRIM(MTYDATE) IN ('TOT','DS') THEN '0' 
            WHEN SUBSTR(TRIM(MTYDATE),LENGTH(TRIM(MTYDATE)),1)='Y' THEN TO_CHAR(REPLACE(MTYDATE,'Y',''))
            ELSE '0' 
       END TENOR_END_YEARS,
       CASE WHEN TRIM(MTYDATE) IN ('TOT','DS') THEN '0' 
            WHEN SUBSTR(TRIM(MTYDATE),LENGTH(TRIM(MTYDATE)),1)='M' THEN TO_CHAR(REPLACE(MTYDATE,'M',''))
            ELSE '0' 
       END TENOR_END_MONTHS,
       CASE WHEN TRIM(MTYDATE) IN ('TOT','DS') THEN '0' 
            WHEN SUBSTR(TRIM(MTYDATE),LENGTH(TRIM(MTYDATE)),1)='D' THEN TO_CHAR(REPLACE(MTYDATE,'D',''))
            ELSE '0' 
       END TENOR_END_DAYS
  FROM crlm_MIG LM
 -- INNER JOIN CUST CU ON TRIM(LM.LIMITMEMBER) = TRIM(CU.CNO)
  WHERE LIMITTYPE IN ('U') AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy') OR TRIM(EXPDATE) IS NULL
  or (LIMITMEMBER,LIMITTYPE,PRODGROUPID,MTYDATE,to_date(EXPDATE,'YYYY-MM-DD')) in(select LIMITMEMBER,LIMITTYPE,PRODGROUPID,MTYDATE,max(to_date(EXPDATE,'YYYY-MM-DD')) EXPDATE  from crlm_MIG 
    where TO_DATE(EXPDATE,'YYYY-MM-DD')<=to_date(get_param('EOD_DATE'),'dd-mm-yyyy')
	and (LIMITMEMBER,LIMITTYPE,PRODGROUPID,MTYDATE) not in(select LIMITMEMBER,LIMITTYPE,PRODGROUPID,MTYDATE from crlm_MIG where TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy') OR TRIM(EXPDATE) IS NULL)
    group by  LIMITMEMBER,LIMITTYPE,PRODGROUPID,MTYDATE)
  )
  order by   LM.PRODGROUPID;
UPDATE CPTY_COUNTRY_LIMIT_O_TABLE SET TENOR_END_YEARS='0' WHERE TRIM(TENOR_END_YEARS) IS NULL;
UPDATE CPTY_COUNTRY_LIMIT_O_TABLE SET TENOR_END_MONTHS='0' WHERE TRIM(TENOR_END_MONTHS) IS NULL;
UPDATE CPTY_COUNTRY_LIMIT_O_TABLE SET TENOR_END_DAYS='0' WHERE TRIM(TENOR_END_DAYS) IS NULL;
COMMIT;
--update CPTY_COUNTRY_LIMIT_O_TABLE a set (LIMIT_CCY,LIMIT_AMOUNT) =( select b.LIMIT_CCY,b.LIMIT_AMOUNT from(
--select COUNTRY_CODE,LIMIT_CCY,LIMIT_AMOUNT from CPTY_COUNTRY_LIMIT_O_TABLE  where trim(USER_LIMIT_TYPE)='FX_LIMIT_DS_CTR'
--) b where a.COUNTRY_CODE = b.COUNTRY_CODE
--)
--where  trim(USER_LIMIT_TYPE)!='FX_LIMIT_DS_CTR' and trim(USER_LIMIT_TYPE) like 'FX%'
--and trim(COUNTRY_CODE) in (select trim(COUNTRY_CODE) from CPTY_COUNTRY_LIMIT_O_TABLE where trim(USER_LIMIT_TYPE)='FX_LIMIT_DS_CTR');
--commit;
--update CPTY_COUNTRY_LIMIT_O_TABLE a set LIMIT_AMOUNT = LIMIT_AMOUNT/10
--where  trim(USER_LIMIT_TYPE) like 'FX%' and LIMIT_AMOUNT!='0.1'
--and trim(COUNTRY_CODE) not in (select trim(COUNTRY_CODE) from CPTY_COUNTRY_LIMIT_O_TABLE where trim(USER_LIMIT_TYPE)='FX_LIMIT_DS_CTR');
--commit;
update CPTY_COUNTRY_LIMIT_O_TABLE a set LIMIT_AMOUNT = LIMIT_AMOUNT/10
where  trim(USER_LIMIT_TYPE) like 'FX%' and LIMIT_AMOUNT!='0.1'
and  trim(USER_LIMIT_TYPE)not in('FX_LIMIT_DS_CTR') --and LIMIT_NAME like '%_C_01'
 ;
commit;
EXIT;
 