
TRUNCATE TABLE CPTY_CUST_GROUP_LIMIT_TBL_BCK;
DROP TABLE CRLM_MIG;
create table CRLM_MIG as SELECT * FROM CRLM; 
INSERT INTO CRLM_MIG
SELECT A.*
  FROM CRLM_GRP a
  LEFT JOIN CRLM_MIG b ON a.br = b.br AND a.LIMITMEMBER = b.LIMITMEMBER AND a.PRODGROUPID = b.PRODGROUPID AND a.MTYDATE = b.MTYDATE
           AND a.CREQLIMAMT = b.CREQLIMAMT AND a.ccy = b.ccy
 WHERE b.br IS NULL;
 COMMIT;
 INSERT INTO CRLM_MIG
 SELECT A.*
  FROM CRLM_CNTRY a
  LEFT JOIN CRLM_MIG b ON a.br = b.br AND a.LIMITMEMBER = b.LIMITMEMBER AND a.PRODGROUPID = b.PRODGROUPID AND a.MTYDATE = b.MTYDATE
           AND a.CREQLIMAMT = b.CREQLIMAMT AND a.ccy = b.ccy
 WHERE b.br IS NULL;
 COMMIT;
--UPDATE CRLM A SET CREQLIMAMT = ( 
--SELECT CREQLIMAMT FROM(
--SELECT TRIM(LIMITMEMBER) LIMITMEMBER,CREQLIMAMT/10 CREQLIMAMT FROM CRLM WHERE LIMITTYPE='G' AND 
--PRODGROUPID='FX DEALS' AND TRIM(MTYDATE) not in('TOT','DS') AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL) and trim(STARTDATE) is null
--)B WHERE TRIM(A.LIMITMEMBER) = TRIM(B.LIMITMEMBER)
--) WHERE  TRIM(LIMITTYPE)='G' AND TRIM(MTYDATE)='DS' AND TRIM(PRODGROUPID)='FX DEALS' AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL);
--Update spot limit to forward fot forward limit is 10 times of spot limit
--UPDATE CRLM_MIG A SET CREQLIMAMT = ( 
--SELECT CREQLIMAMT FROM(
--SELECT TRIM(LIMITMEMBER) LIMITMEMBER,CREQLIMAMT CREQLIMAMT FROM CRLM_MIG WHERE PRODGROUPID='FX DEALS' AND TRIM(MTYDATE) in('TOT','DS') 
----AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL) and trim(STARTDATE) is null
--)B WHERE TRIM(A.LIMITMEMBER) = TRIM(B.LIMITMEMBER)
--) WHERE  TRIM(MTYDATE) NOT in('TOT','DS') AND TRIM(PRODGROUPID)='FX DEALS' 
----AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL)
--and LIMITMEMBER in(
--SELECT trim(LIMITMEMBER) FROM(
--select * from 
--(
--SELECT TRIM(LIMITMEMBER) LIMITMEMBER,CREQLIMAMT,CREQLIMAMT/10 CREQLIMAMT_FWD_10 ,'FORWARD' type FROM CRLM_MIG WHERE 
--PRODGROUPID='FX DEALS' AND TRIM(MTYDATE) not in('TOT','DS') 
----AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL) and trim(STARTDATE) is null
--) a
--inner join 
--(
--SELECT TRIM(LIMITMEMBER) LIMITMEMBER_1, CREQLIMAMT CREQLIMAMT_SPOT,'SPOT' type FROM CRLM_MIG WHERE 
--PRODGROUPID='FX DEALS' AND TRIM(MTYDATE) in('TOT','DS') AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL) and trim(STARTDATE) is null
--) b on a.LIMITMEMBER = b.LIMITMEMBER_1 
--) WHERE --CREQLIMAMT_FWD_10 = CREQLIMAMT_SPOT and 
--CREQLIMAMT_FWD_10 <>0
--);
--commit;
--UPDATE CRLM_MIG A SET EXPDATE = ( 
--SELECT EXPDATE_FWD FROM(
--select LIMITMEMBER,EXPDATE_FWD from 
--(
--SELECT TRIM(LIMITMEMBER) LIMITMEMBER,CREQLIMAMT,CREQLIMAMT/10 CREQLIMAMT_FWD_10 ,EXPDATE EXPDATE_FWD,'FORWARD' type FROM CRLM_MIG WHERE --LIMITTYPE='G' and
--PRODGROUPID='FX DEALS' AND TRIM(MTYDATE) not in('TOT','DS') 
----AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL) and trim(STARTDATE) is null
--) a
--inner join 
--(
--SELECT TRIM(LIMITMEMBER) LIMITMEMBER_1, CREQLIMAMT CREQLIMAMT_SPOT,EXPDATE EXPDATE_SPOT,'SPOT' type FROM CRLM_MIG WHERE --LIMITTYPE='G' and
--PRODGROUPID='FX DEALS' AND TRIM(MTYDATE) in('TOT','DS') 
----AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL) and trim(STARTDATE) is null
--) b on a.LIMITMEMBER = b.LIMITMEMBER_1 
--)  b where b.LIMITMEMBER = a.LIMITMEMBER 
--) where  TRIM(MTYDATE) in('TOT','DS') AND TRIM(PRODGROUPID)='FX DEALS' 
----AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL) --and LIMITTYPE='G'
--;
--commit;
--Make forward limit to 10 times lesser when DS not available
--update CRLM_MIG a set CREQLIMAMT = ( select CREQLIMAMT/10 from(
--SELECT * FROM CRLM_MIG WHERE  PRODGROUPID='FX DEALS' AND TRIM(MTYDATE) not in('TOT','DS') AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL)
--    and trim(STARTDATE) is null and TRIM(LIMITMEMBER) not in(
--    SELECT TRIM(LIMITMEMBER) FROM CRLM_MIG WHERE PRODGROUPID='FX DEALS' AND TRIM(MTYDATE) in('TOT','DS') 
--    --AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL) and trim(STARTDATE) is null
--) and CREQLIMAMT <>0
--) b where a.LIMITMEMBER = b.LIMITMEMBER and a.MTYDATE = b.MTYDATE and a.PRODUCT = b.PRODUCT and a.CREQLIMAMT = b.CREQLIMAMT)
--where a.LIMITMEMBER||a.MTYDATE||a.PRODUCT||a.CREQLIMAMT in(
--SELECT LIMITMEMBER||MTYDATE||PRODUCT||CREQLIMAMT FROM CRLM_MIG WHERE  PRODGROUPID='FX DEALS' AND TRIM(MTYDATE) not in('TOT','DS')
---- AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL)
--    and trim(STARTDATE) is null and TRIM(LIMITMEMBER) not in(
--    SELECT TRIM(LIMITMEMBER) FROM CRLM_MIG WHERE PRODGROUPID='FX DEALS' AND TRIM(MTYDATE) in('TOT','DS') AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL) and trim(STARTDATE) is null
--) and CREQLIMAMT <>0);
--commit;
INSERT INTO CPTY_CUST_GROUP_LIMIT_TBL_BCK
SELECT '' Response,
       'FBO_COUNTERPARTY_LIMIT_INFO' FBO_TYPE,
       CASE WHEN TRIM(LM.PRODGROUPID)='FX DEALS' AND LIMITTYPE ='C' THEN  'FX_'||nvl(TRIM(MC.FIN_CIF_ID),LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||LIMITTYPE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='INVESTMENT' AND LIMITTYPE ='C'  THEN 'IN_'||nvl(TRIM(MC.FIN_CIF_ID),LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||LIMITTYPE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='IRS DEALS' AND LIMITTYPE ='C'  THEN 'IR_'||nvl(TRIM(MC.FIN_CIF_ID),LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||LIMITTYPE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='MM DEALS' AND LIMITTYPE ='C'  THEN 'MM_'||nvl(TRIM(MC.FIN_CIF_ID),LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||LIMITTYPE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='ACIC' AND LIMITTYPE ='C'  THEN 'ACIC_'||nvl(TRIM(MC.FIN_CIF_ID),LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||LIMITTYPE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='FX DEALS' AND LIMITTYPE ='G'  THEN 'FX_'||trim(LIMITMEMBER)||'_'||LM.MTYDATE||'_'||LIMITTYPE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='INVESTMENT' AND LIMITTYPE ='G'  THEN 'IN_'||trim(LIMITMEMBER)||'_'||LM.MTYDATE||'_'||LIMITTYPE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='IRS DEALS' AND LIMITTYPE ='G'  THEN 'IR_'||trim(LIMITMEMBER)||'_'||LM.MTYDATE||'_'||LIMITTYPE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='MM DEALS' AND LIMITTYPE ='G'  THEN 'MM_'||trim(LIMITMEMBER)||'_'||LM.MTYDATE||'_'||LIMITTYPE||'_'||BR  
            WHEN TRIM(LM.PRODGROUPID)='ACIC' AND LIMITTYPE ='G'  THEN 'ACIC_'||trim(LIMITMEMBER)||'_'||LM.MTYDATE||'_'||LIMITTYPE||'_'||BR  
       END  LIMIT_NAME,
       CASE WHEN TRIM(LM.PRODGROUPID)='FX DEALS' AND TRIM(MTYDATE)='DS'  THEN 'FX CPTY DAILY SETT' 
            WHEN TRIM(LM.PRODGROUPID)='MM DEALS' AND TRIM(MTYDATE)='DS'  THEN 'MM_LIMIT_DS' 
            --WHEN TRIM(LM.PRODGROUPID)='FX DEALS' AND TRIM(MTYDATE)='TOT'  THEN 'FX CPTY PRE SETTLEMENT' 
			WHEN TRIM(LM.PRODGROUPID)='FX DEALS' AND TRIM(MTYDATE)='TOT'  THEN 'FX CPTY FORWARD TENOR LIMIT' 
            --WHEN TRIM(LM.PRODGROUPID)='FX DEALS' AND TRIM(MTYDATE)!='TOT'  THEN 'FX CPTY PRE SETTLEMENT' 
			WHEN TRIM(LM.PRODGROUPID)='FX DEALS' AND TRIM(MTYDATE)!='TOT' THEN 'FX CPTY FORWARD TENOR LIMIT' --CHANGED BASED ON MADAN CONFIRMATION ON 27-09-2017
            WHEN TRIM(LM.PRODGROUPID)='INVESTMENT' AND TRIM(MTYDATE)='TOT'  THEN 'INV_LIMIT_NT' 
            WHEN TRIM(LM.PRODGROUPID)='INVESTMENT' AND TRIM(MTYDATE)!='TOT' THEN 'INV_LIMIT' 
            WHEN TRIM(LM.PRODGROUPID)='IRS DEALS' AND TRIM(MTYDATE)='TOT'   THEN 'IRS_CPTY_LIMIT_NT'
            WHEN TRIM(LM.PRODGROUPID)='IRS DEALS' AND TRIM(MTYDATE)!='TOT'  THEN 'IRS_CPTY_LIMIT'
            WHEN TRIM(LM.PRODGROUPID)='ACIC' AND TRIM(MTYDATE)='TOT'   THEN 'ACIC_CPTY_LIMIT_NT'
            WHEN TRIM(LM.PRODGROUPID)='ACIC' AND TRIM(MTYDATE)!='TOT'  THEN 'ACIC_CPTY_LIMIT'
            WHEN TRIM(LM.PRODGROUPID)='MM DEALS' AND TRIM(MTYDATE)='TOT'  THEN 'MM_LIMIT_NT'
            WHEN TRIM(LM.PRODGROUPID)='MM DEALS' AND TRIM(MTYDATE)!='TOT'  THEN 'MM_LIMIT' 
       END USER_LIMIT_TYPE,
       'Counterparty Limit' USER_LIMIT_TYPE_SYS_LIMIT_TYPE,
       LM.CCY LIMIT_CCY,
       TO_CHAR(LM.CREQLIMAMT) LIMIT_AMOUNT,
       'Default Action' EXCESS_ACTION,
       'Absolute Level' BREACH_LEVEL_TYPE,
       'Net Long' USER_LIMIT_TYP_EXP_AGGR_METHOD,
       CASE WHEN TRIM(EXPDATE) IS NOT NULL THEN TO_CHAR(TO_DATE(EXPDATE,'YYYY-MM-DD'),'DD-MON-YYYY') ELSE TO_CHAR(TRIM(EXPDATE)) END EXPIRY_DATE,
       CASE WHEN BR='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ENTITY,
       '' SUBTYPE,
       '' DEPT_NAME,
       CASE WHEN LIMITTYPE ='C' THEN TO_CHAR(TRIM(CU.CMNE)) 
            WHEN LIMITTYPE ='G' THEN TO_CHAR(trim(LIMITMEMBER)) END COUNTERPARTY_STRING,
       CASE WHEN BR='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ENTITY_NAME,
       '' ALERT_USER_GROUP,
       '' EXC_AUTH_PRIV_GROUP,
       '' REPORT_PRIV_GROUP,
       '' EMAIL_ID,
       CASE WHEN TRIM(MTYDATE ) in ('TOT','DS') THEN '7' ELSE '3'  END TENOR_START_CODE,
       '0' TENOR_START_YEARS,--CASE WHEN TRIM(MTYDATE)!='TOT' THEN '0' ELSE '' END
       '0' TENOR_START_MONTHS,--CASE WHEN TRIM(MTYDATE)!='TOT' THEN '0' ELSE '' END
       '0' TENOR_START_DAYS,--CASE WHEN TRIM(MTYDATE)!='TOT' THEN '0' ELSE '' END
       CASE WHEN TRIM(MTYDATE) in ('TOT','DS') THEN '7' ELSE '7' END TENOR_END_CODE,
       CASE WHEN TRIM(MTYDATE) IN ('TOT','DS') THEN '0' 
            WHEN SUBSTR(TRIM(MTYDATE),LENGTH(TRIM(MTYDATE)),1)='Y' THEN TO_CHAR(REPLACE(MTYDATE,'Y',''))
            ELSE '0' 
       END TENOR_END_YEARS,
       CASE WHEN TRIM(MTYDATE) IN ('TOT','DS') THEN '0' 
            WHEN SUBSTR(TRIM(MTYDATE),LENGTH(TRIM(MTYDATE)),1)='M' THEN TO_CHAR(REPLACE(MTYDATE,'M',''))
            ELSE '0' 
       END TENOR_END_MONTHS,
       CASE WHEN TRIM(MTYDATE) IN ('TOT','DS') THEN '0' 
            WHEN SUBSTR(TRIM(MTYDATE),LENGTH(TRIM(MTYDATE)),1)='D' THEN TO_CHAR(REPLACE(MTYDATE,'D',''))
            ELSE '0' 
       END TENOR_END_DAYS
  FROM CRLM_MIG LM
left join crgm on trim(LM.LIMITMEMBER) = trim(crgm.GRPMEMBER)
LEFT JOIN CUST CU ON TRIM(LM.LIMITMEMBER) = TRIM(CU.CNO)
LEFT JOIN GFPF ON TRIM(GFPF.GFOCID) = TRIM(CU.CMNE)
LEFT JOIN MAP_CIF MC ON trim(MC.GFCUS)||trim(MC.GFCLC) = trim(GFPF.GFCUS)||trim(GFPF.GFCLC)
  WHERE LIMITTYPE IN ('C','G') AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy')  OR TRIM(EXPDATE) IS NULL
  or (LIMITMEMBER,LIMITTYPE,PRODGROUPID,MTYDATE,to_date(EXPDATE,'YYYY-MM-DD')) in(select LIMITMEMBER,LIMITTYPE,PRODGROUPID,MTYDATE,max(to_date(EXPDATE,'YYYY-MM-DD')) EXPDATE  from CRLM_MIG 
    where TO_DATE(EXPDATE,'YYYY-MM-DD')<=to_date(get_param('EOD_DATE'),'dd-mm-yyyy')
    and (LIMITMEMBER,LIMITTYPE,PRODGROUPID,MTYDATE) not in(select LIMITMEMBER,LIMITTYPE,PRODGROUPID,MTYDATE from CRLM_MIG where TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy') OR TRIM(EXPDATE) IS NULL)
    group by  LIMITMEMBER,LIMITTYPE,PRODGROUPID,MTYDATE))
  AND (CASE WHEN LIMITTYPE='C' AND trim(CU.CMNE) IS NULL THEN 0 ELSE 1 END =1)
  AND (CASE WHEN trim(LM.PRODGROUPID)='FX DEALS' and trim(LM.MTYDATE)='TOT'  AND trim(LM.CREQLIMAMT) ='0' THEN 0 ELSE 1 END =1)
  AND  TRIM(LIMITMEMBER) NOT IN(SELECT TRIM(GRPMEMBER) FROM crgm)
    ORDER BY LIMITTYPE DESC;
COMMIT; 
UPDATE CPTY_CUST_GROUP_LIMIT_TBL_BCK SET LIMIT_AMOUNT='0' WHERE TRIM(LIMIT_AMOUNT) IS NULL;
 DECLARE
   CURSOR c1
   IS
      SELECT * FROM CPTY_CUST_GROUP_LIMIT_TBL_BCK where LIMIT_NAME like '%_G_%';
   no_of_group_name_con_mne   VARCHAR2 (1) := 0;
BEGIN
   FOR l_record IN c1
   LOOP
      SELECT COUNT (*)
        INTO no_of_group_name_con_mne
        FROM cust
       WHERE trim(CMNE) LIKE l_record.COUNTERPARTY_STRING;
      IF (no_of_group_name_con_mne != 0)
      THEN
         UPDATE CPTY_CUST_GROUP_LIMIT_TBL_BCK
            SET LIMIT_NAME = replace(l_record.LIMIT_NAME,l_record.COUNTERPARTY_STRING,l_record.COUNTERPARTY_STRING || 'GRP'),COUNTERPARTY_STRING=l_record.COUNTERPARTY_STRING || 'GRP'
          WHERE LIMIT_NAME = l_record.LIMIT_NAME;
      END IF;
   END LOOP;
END;
/
DELETE FROM CPTY_CUST_GROUP_LIMIT_TBL_BCK WHERE (LIMIT_NAME,NVL(TO_DATE(EXPIRY_DATE,'DD-MON-YYYY'),SYSDATE)) NOT IN(
SELECT LIMIT_NAME,NVL(MAX(TO_DATE(EXPIRY_DATE,'DD-MON-YYYY')),SYSDATE) FROM CPTY_CUST_GROUP_LIMIT_TBL_BCK GROUP BY LIMIT_NAME
);
delete from CPTY_CUST_GROUP_LIMIT_TBL_BCK where trim(COUNTERPARTY_STRING) not in(
select TRIM(TREASURY_COUNTERPARTY_MNEMONIC)  TREASURY_COUNTERPARTY_MNEMONIC from corp_COREINTERFACE
union 
select TRIM(TREASURY_COUNTERPARTY_MNEMONIC) from RETAIL_COREINTERFACE
union 
select to_char(trim(NAME)) from tr_not_mig_cpty_core_o_table
UNION
SELECT TO_CHAR(TRIM(MNEMONIC)) FROM TREASURY_GROUP_O_TABLE
);
commit;
TRUNCATE TABLE CPTY_CUST_GROUP_LIMIT_O_TABLE ;
insert into CPTY_CUST_GROUP_LIMIT_O_TABLE
select distinct
a.RESPONSE                           ,
a.FBO_TYPE                           ,
a.LIMIT_NAME                         ,
a.USER_LIMIT_TYPE                    ,
a.USER_LIMIT_TYPE_SYS_LIMIT_TYPE     ,
a.LIMIT_CCY                          ,
b.SUM_LIMIT_AMOUNT                   ,
a.EXCESS_ACTION                      ,
a.BREACH_LEVEL_TYPE                  ,
a.USER_LIMIT_TYP_EXP_AGGR_METHOD     ,
a.EXPIRY_DATE                        ,
a.ENTITY                             ,
a.SUBTYPE                            ,
a.DEPT_NAME                          ,
a.COUNTERPARTY_STRING                ,
a.ENTITY_NAME                        ,
a.ALERT_USER_GROUP                   ,
a.EXC_AUTH_PRIV_GROUP                ,
a.REPORT_PRIV_GROUP                  ,
a.EMAIL_ID                           ,
a.TENOR_START_CODE                   ,
a.TENOR_START_YEARS                  ,
a.TENOR_START_MONTHS                 ,
a.TENOR_START_DAYS                   ,
a.TENOR_END_CODE                     ,
a.TENOR_END_YEARS                    ,
a.TENOR_END_MONTHS                   ,
a.TENOR_END_DAYS                     
 from CPTY_CUST_GROUP_LIMIT_TBL_BCK a
left join 
(select LIMIT_NAME,EXPIRY_DATE,sum(to_number(LIMIT_AMOUNT)) SUM_LIMIT_AMOUNT from CPTY_CUST_GROUP_LIMIT_TBL_BCK group by  LIMIT_NAME,EXPIRY_DATE) b on nvl(a.LIMIT_NAME,' ') = nvl(b.LIMIT_NAME,' ') and nvl(a.EXPIRY_DATE,' ')=nvl(b.EXPIRY_DATE,' ');
--IF SAME GROUP/CUSTOMER HAVE MULTIPLE LIMIT WITH ZERO LIMIT THEN ZERO LIMIT DATA
DELETE FROM CPTY_CUST_GROUP_LIMIT_O_TABLE WHERE SUBSTR(LIMIT_NAME,1,INSTR(LIMIT_NAME, '_', 1,3)-1) IN(
 SELECT SUBSTR(LIMIT_NAME,1,INSTR(LIMIT_NAME, '_', 1,3)-1) LIMIT_NAME  FROM CPTY_CUST_GROUP_LIMIT_O_TABLE 
WHERE LIMIT_NAME LIKE 'MM%' GROUP BY SUBSTR(LIMIT_NAME,1,INSTR(LIMIT_NAME, '_', 1,3)-1) HAVING COUNT(*)>1 AND AVG(LIMIT_AMOUNT) != 0)
AND LIMIT_AMOUNT = '0';
DELETE FROM CPTY_CUST_GROUP_LIMIT_O_TABLE WHERE ROWID NOT IN(
 SELECT MIN(ROWID)  FROM CPTY_CUST_GROUP_LIMIT_O_TABLE 
 WHERE LIMIT_NAME LIKE 'MM%' GROUP BY SUBSTR(LIMIT_NAME,1,INSTR(LIMIT_NAME, '_', 1,3)-1) HAVING COUNT(*)>1 AND AVG(LIMIT_AMOUNT) = 0) 
 AND SUBSTR(LIMIT_NAME,1,INSTR(LIMIT_NAME, '_', 1,3)-1) IN (SELECT SUBSTR(LIMIT_NAME,1,INSTR(LIMIT_NAME, '_', 1,3)-1) FROM CPTY_CUST_GROUP_LIMIT_O_TABLE 
 WHERE LIMIT_NAME LIKE 'MM%' GROUP BY SUBSTR(LIMIT_NAME,1,INSTR(LIMIT_NAME, '_', 1,3)-1) HAVING COUNT(*)>1 AND AVG(LIMIT_AMOUNT) = 0);
UPDATE CPTY_CUST_GROUP_LIMIT_O_TABLE SET  LIMIT_AMOUNT = '0.1' WHERE TRIM(LIMIT_AMOUNT)='0';
--VALIDATION 
--SELECT SUBSTR(LIMIT_NAME,1,INSTR(LIMIT_NAME, '_', 1,3)-1) LIMIT_NAME  FROM CPTY_CUST_GROUP_LIMIT_O_TABLE WHERE LIMIT_NAME LIKE 'MM%' GROUP BY SUBSTR(LIMIT_NAME,1,INSTR(LIMIT_NAME, '_', 1,3)-1) HAVING COUNT(*)>1
INSERT INTO CPTY_CUST_GROUP_LIMIT_O_TABLE 
SELECT RESPONSE,
       FBO_TYPE,
       SUBSTR(LIMIT_NAME,1,INSTR(LIMIT_NAME,'_',1,2)-1)||'_SPOT_LMT' LIMIT_NAME,
       'FX SPOT LIMIT' USER_LIMIT_TYPE,--FX_SPOT_LMT
       USER_LIMIT_TYPE_SYS_LIMIT_TYPE,
       LIMIT_CCY,
       LIMIT_AMOUNT,
       EXCESS_ACTION,
       BREACH_LEVEL_TYPE,
       USER_LIMIT_TYP_EXP_AGGR_METHOD,
       EXPIRY_DATE,
       ENTITY,
       SUBTYPE,
       DEPT_NAME,
       COUNTERPARTY_STRING,
       ENTITY_NAME,
       ALERT_USER_GROUP,
       EXC_AUTH_PRIV_GROUP,
       REPORT_PRIV_GROUP,
       EMAIL_ID,
       TENOR_START_CODE,
       TENOR_START_YEARS,
       TENOR_START_MONTHS,
       TENOR_START_DAYS,
       TENOR_END_CODE,
       TENOR_END_YEARS,
       TENOR_END_MONTHS,
       TENOR_END_DAYS
  FROM CPTY_CUST_GROUP_LIMIT_O_TABLE
 WHERE USER_LIMIT_TYPE = 'FX CPTY DAILY SETT' AND LIMIT_NAME NOT LIKE '%TOT%' AND TRIM(LIMIT_NAME) LIKE '%_G_01';
commit;
--update CPTY_CUST_GROUP_LIMIT_O_TABLE a set (LIMIT_CCY,LIMIT_AMOUNT) =( select b.LIMIT_CCY,b.LIMIT_AMOUNT from(
--select COUNTERPARTY_STRING,LIMIT_CCY,LIMIT_AMOUNT from CPTY_CUST_GROUP_LIMIT_O_TABLE  where trim(USER_LIMIT_TYPE)='FX CPTY DAILY SETT'
--) b where a.COUNTERPARTY_STRING = b.COUNTERPARTY_STRING
--)
--where  trim(USER_LIMIT_TYPE)!='FX CPTY DAILY SETT' and trim(USER_LIMIT_TYPE) like 'FX%'
--and trim(COUNTERPARTY_STRING) in (select trim(COUNTERPARTY_STRING) from CPTY_CUST_GROUP_LIMIT_O_TABLE where trim(USER_LIMIT_TYPE)='FX CPTY DAILY SETT');
--update CPTY_CUST_GROUP_LIMIT_O_TABLE a set LIMIT_AMOUNT = LIMIT_AMOUNT/10
--where  trim(USER_LIMIT_TYPE) like 'FX%' and LIMIT_AMOUNT!='0.1'
--and trim(COUNTERPARTY_STRING) not in (select trim(COUNTERPARTY_STRING) from CPTY_CUST_GROUP_LIMIT_O_TABLE where trim(USER_LIMIT_TYPE)='FX CPTY DAILY SETT');
--commit;
update CPTY_CUST_GROUP_LIMIT_O_TABLE a set LIMIT_AMOUNT = LIMIT_AMOUNT/10
where  trim(USER_LIMIT_TYPE) like 'FX%' and LIMIT_AMOUNT!='0.1'
and  trim(USER_LIMIT_TYPE)not in('FX CPTY DAILY SETT','FX SPOT LIMIT') --and LIMIT_NAME like '%_C_01'
 ;
commit;
EXIT;
--select * from CPTY_CUST_GROUP_LIMIT_O_TABLE where trim(COUNTERPARTY_STRING) in(
--select trim(CPTY_MNEMONIC) CPTY_MNEMONIC from tr_grp_and_cpty_map_o_table where trim(GRP_ID) in(
--select trim(COUNTERPARTY_STRING) from CPTY_CUST_GROUP_LIMIT_O_TABLE where LIMIT_NAME like '%_G_01'
--)
--) 
