TRUNCATE TABLE YIELD_CURVE_O_TABLE;
INSERT INTO YIELD_CURVE_O_TABLE
SELECT DISTINCT
'' Response,
SUBSTR(TRIM(CONTRIBRATE),1,3)||'-LIBOR' Curve_ID,
SUBSTR(TRIM(CONTRIBRATE),4,4) Type,
'S' Day_Convention,
CCY Calendar_Set,
' ' Base_Date,
'STANDARD' Curve_Type
FROM YCRS where BR=get_param('OPICS_BANK_ID')
;
COMMIT;
EXIT;