CREATE OR REPLACE VIEW V_PARTY_COMMON AS 
SELECT 'Invalid Party Type', COUNT(1) FROM O_PARTY_COMMON WHERE (PARTYTYPE <> '1062' AND PARTYTYPE <> '1063')
UNION
--SELECT 'Invalid Party Sub Type', COUNT(1) FROM O_PARTY_COMMON WHERE (PARTYSUBTYPE <> '1062' AND PARTYSUBTYPE <> '1063')
--UNION
SELECT 'Invalid Party Category', COUNT(1) FROM O_PARTY_COMMON WHERE (PARTYCATEGORY <> 'Full')
;


