
TRUNCATE TABLE LLT_NOTES_MIG;

INSERT INTO LLT_NOTES_MIG
SELECT B.BANK_ID,
       B.LIMIT_PREFIX,
       B.LIMIT_SUFFIX,
      'N' DEL_FLG,
      SYSDATE LCHG_TIME,
      'SYSTEM' LCHG_USER_ID,
      'SYSTEM' RCRE_USER_ID,
       SYSDATE RCRE_TIME,
      TRIM(NOTE1)||' '||TRIM(NOTE2)||' '||TRIM(NOTE3) NOTES,
      MIN_STIP_COVG FREE_FIELD1,
      '' FREE_FIELD2,
      '' FREE_FIELD3
  FROM LIMIT_CORE_INFY_TABLE B
  LEFT JOIN LIMIT_CORE_NOTES_O_TABLE A  ON A.LIMIT_PREFIX = B.LIMIT_PREFIX
  LEFT JOIN (SELECT DISTINCT c.LIMIT_PREFIX,c.LIMIT_SUFFIX,MIN_STIP_COVG FROM COLL_LIM_LINKAGE_TMP A
  INNER JOIN COL_CUSTOM_O_TABLE B ON A.SECU_SRL_NUM= B.SECU_SRL_NUM
  inner join LIMIT_CORE_INFY_TABLE c on c.LIMIT_PREFIX = a.LIMIT_PREFIX ) C ON  B.LIMIT_PREFIX = C.LIMIT_PREFIX AND B.LIMIT_SUFFIX = C.LIMIT_SUFFIX
  ;
  
COMMIT; 
  
--INSERT INTO LLT_NOTES_MIG
--SELECT '01' BANK_ID,
--      LIMIT_PREFIX,
--      LIMIT_SUFFIX,
--      'N' DEL_FLG,
--      SYSDATE LCHG_TIME,
--      'SYSTEM' LCHG_USER_ID,
--      'SYSTEM' RCRE_USER_ID,
--       SYSDATE RCRE_TIME,
--      '' NOTES,
--      MIN_STIP_COVG FREE_FIELD1,
--      '' FREE_FIELD2,
--      '' FREE_FIELD3
--  FROM (SELECT DISTINCT c.LIMIT_PREFIX,c.LIMIT_SUFFIX,MIN_STIP_COVG FROM COLL_LIM_LINKAGE_TMP A
--  INNER JOIN COL_CUSTOM_O_TABLE B ON A.SECU_SRL_NUM= B.SECU_SRL_NUM
--    inner join LIMIT_CORE_INFY_TABLE c on c.LIMIT_PREFIX = a.LIMIT_PREFIX
--  WHERE c.LIMIT_PREFIX NOT IN(SELECT LIMIT_PREFIX FROM LLT_NOTES_MIG))
--  ;
--COMMIT;  
EXIT; 
