TRUNCATE TABLE SMS_ALERTS_REG_O_TABLE;
INSERT INTO SMS_ALERTS_REG_O_TABLE
SELECT 'A' REC_IDENTIFIER,
       '' SUB_DEL_IDENTIFIER,
       '01' BANK_ID,
       M.FIN_CIF_ID CUST_ID,
       M.FIN_CIF_ID CORP_ID,
       M.FIN_CIF_ID RELATED_PARTY_ID,
       'GLOBAL' HOST_ID,
       nvl(CASE WHEN LENGTH(REPLACE(A.CUST_FIRST_NAME,'','.'))=1 THEN CONVERT_CODES('ALPHABET','Y') ELSE TO_CHAR(A.CUST_FIRST_NAME) END,'.') CUST_FIRST_NAME,
       nvl(CASE WHEN LENGTH(REPLACE(NVL(A.CUST_MIDDLE_NAME,' '),'','.'))=1 THEN CONVERT_CODES('ALPHABET','Y') ELSE TO_CHAR(A.CUST_MIDDLE_NAME) END,'.') CUST_MID_NAME,
       nvl(CASE WHEN LENGTH(REPLACE(A.CUST_LAST_NAME,'','.'))=1 THEN CONVERT_CODES('ALPHABET','Y') ELSE TO_CHAR(A.CUST_LAST_NAME) END,'.') CUST_LAST_NAME,
       'E' USER_TYPE,--"E - External Customer I - Internal Customer"
       case when individual = 'Y' then 'R' else 'C' end USER_SUB_TYPE,
       CASE WHEN S.CU01_LANG='EN' THEN 'EN_US' WHEN S.CU01_LANG='AR' THEN 'AR_KW' END LANG_CODE,
       '' ALT_LANG_CODE,
       upper(S.CU01_MOBPR) PREF_TIME_ZONE,
       '' DND_DATE_FROM,
       '' DND_DATE_TO,
       '' DND_TIME_FROM,
       '' DND_TIME_TO,
       CASE WHEN S.CU01_INDR='Y' THEN S.CU01_BEAN END BUSINESS_UNIT_ID,
       A.ADDRESS_LINE1 C_ADDR1,
       A.ADDRESS_LINE2 C_ADDR2,
       CASE when A.CITY !='ZZZ' and trim(A.CITY)!='.' THEN A.CITY END  C_CITY,
       CASE when A.STATE !='ZZZ' and trim(A.STATE)!='.' THEN A.STATE END  C_STATE,
       CASE when A.COUNTRY !='ZZZ' and trim(A.COUNTRY)!='.' THEN A.COUNTRY END C_COUNTRY,
       A.ZIP C_ZIP,
       '' C_PHONE_NO,
       '965'||S.CU01_MOBPN C_MOBILE_NO,
       '' C_FAX_NO,
       A.EMAIL C_EMAIL_ID,--***
       '' CHANNEL_ADDR5,
       '' CHANNEL_ADDR6,
       '' CHANNEL_ADDR7,
       '' CHANNEL_ADDR8,
       '' CHANNEL_ADDR9,
       '' CHANNEL_ADDR10,
       ''  DEBIT_ACCOUNT_ID,
       CASE WHEN S.CU01_INDR='Y' THEN M.FIN_SOL_ID END DEBIT_BRANCH_ID,
       '' DATE_FORMAT,
       '' AMOUNT_FORMAT,
       CASE WHEN individual = 'N' then 'CORPORATE' when S.CU01_SFLAG='P' THEN 'PAID' WHEN S.CU01_SFLAG='L' THEN 'LIMITED' WHEN S.CU01_SFLAG='E' THEN 'EXEMPT' END USER_CATEGORY_NAME,
       TO_CHAR(SYSDATE,'DD/MON/YYYY') SUBSCRIPTION_START_DATE,--TO_CHAR(SYSDATE,'DD/MON/YYYY') NVL(TO_CHAR(CONV_TO_VALID_DATE(TRIM(CU01_DTEN),'YYYYMMDD'),'DD/MON/YYYY'),TO_CHAR(SYSDATE,'DD/MON/YYYY'))
       to_char(CONV_TO_VALID_DATE(TRIM(CU01_DTER),'YYYYMMDD'),'DD/MON/YYYY') SCHEME_SUBSCRIPTION_END_DATE,--CASE WHEN S.CU01_SFLAG='P' THEN to_char(add_months(sysdate,12),'DD/MON/YYYY') else '31/DEC/2099' END
       '' SERVICE_PROVIDER
  FROM  YSMSCUPF01 s
INNER JOIN map_cif M ON GFCLC =CU01_CLC and GFCUS =CU01_CUS AND IS_JOINT <>'Y'
       INNER JOIN CRMUSER.ACCOUNTS A ON A.ORGKEY = M.fin_cif_id
 WHERE --individual = 'Y' AND 
 a.bank_id = get_param ('BANK_ID') 
AND S.CU01_STS ='A'
and CONV_TO_VALID_DATE(TRIM(CU01_DTER),'YYYYMMDD') > TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY')
;
update  SMS_ALERTS_REG_O_TABLE set SCHEME_SUBSCRIPTION_END_DATE = to_char(sysdate+1,'dd/MON/yyyy') where to_date(SCHEME_SUBSCRIPTION_END_DATE,'dd/mon/yyyy') <= trunc(sysdate);
COMMIT;
EXIT;
 