select '0'||gfclc||gfcus LEG_CUST_NO,c.limit_prefix FIN_CUST_NO, CASE WHEN '0'||TRIM(gfclc||gfcus) =TRIM(c.limit_prefix) THEN 'TRUE' ELSE 'FALSE' END MATCH_CUST_NO,
HYCLP leg_col_TYPE,
CLTRL_CODE mapped_col_code,SECU_CODE fin_col_code, CASE WHEN TRIM(CLTRL_CODE) =TRIM(SECU_CODE) THEN 'TRUE' ELSE 'FALSE' END MATCH_CUST_NO,
 SECU_TYPE_IND FIN_COL_TYPE, 
a.SECU_SRL_NUM FIN_COLLATERAL_NUM,
HYCLR leg_collateral_reference,COL_REF fin_collateral_reference, CASE WHEN TRIM(HYCLR) =TRIM(COL_REF)  THEN 'TRUE' ELSE 'FALSE' END MATCH_collateral_reference,
ROUND(to_number((hypf.hyclv)/power(10,c8ced)),2) leg_col_value,ROUND(SECU_VALUE,2) fin_col_value, CASE WHEN ROUND(to_number((hypf.hyclv)/power(10,c8ced)),2) = ROUND(SECU_VALUE,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_collateral_VALUE,
ROUND(FORACID_COLL_VALUE,2) leg_APPORTIONED_VALUE,ROUND(APPORTIONED_VALUE,2) fin_APPORTIONED_VALUE, CASE WHEN ROUND(FORACID_COLL_VALUE,2) = ROUND(APPORTIONED_VALUE,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_APPORTIONED_VALUE,
A.LIMIT_PREFIX,A.LIMIT_SUFFIX,LIMIT_SUFFIX_DESC
 from COLL_LIM_LINKAGE_TMP a
left join (
select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLGUARANTEE
                   UNION ALL
                   select COLLATERAL_TYPE,COLLATERAL_CODE,COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLIMMOV
                   UNION ALL
                   select COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLTRADE
                   UNION ALL
                   select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLOTHERS
                   UNION ALL
                   select COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.COLL_MUTUAL_FUND
                   UNION ALL
                   select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLDEPOSITS
) b on a.SECU_SRL_NUM = b.SECU_SRL_NUM 
left join hypf on (case when trim(hyclp)!='021' and nvl(TRIM(COL_REF),' ') = nvl(TRIM(HYCLR),' ') then 1 when  trim(hyclp)='021' and TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR) = TRIM(COL_REF) then 1 else 0 end = 1)
left join c8pf on trim(c8ccy) = trim(HYCCY)
left join map_cif on fin_cif_id  = LIMIT_PREFIX and IS_JOINT <>'Y'
left join (
select limit_prefix,limit_suffix,c.* from  tbaadm.sdr c
left join tbaadm.scmt on scmt.SECU_SRL_NUM = c.SECU_SRL_NUM and scmt.bank_id='01'
left join tbaadm.llt d on d.LIMIT_B2KID = c.LIMIT_B2KID and d.bank_id='01'
where c.bank_id='01'
) c on c.SECU_SRL_NUM = a.SECU_SRL_NUM and a.limit_prefix = c.limit_prefix and c.limit_suffix = a.limit_suffix
left join LIMIT_SUFFIX_CODE_AND_DESC on trim(A.LIMIT_SUFFIX) = trim(LIMIT_SUFFIX_CODE)



select '0'||gfclc||gfcus LEG_CUST_NO,c.limit_prefix FIN_CUST_NO, CASE WHEN '0'||TRIM(gfclc||gfcus) =TRIM(c.limit_prefix) THEN 'TRUE' ELSE 'FALSE' END MATCH_CUST_NO,
CLTRL_CODE mapped_col_code,SECU_CODE fin_col_code, CASE WHEN TRIM(CLTRL_CODE) =TRIM(SECU_CODE) THEN 'TRUE' ELSE 'FALSE' END MATCH_CUST_NO,
 SECU_TYPE_IND FIN_COL_TYPE, 
a.SECU_SRL_NUM FIN_COLLATERAL_NUM,
COL_REF leg_collateral_reference,COL_REF fin_collateral_reference, CASE WHEN TRIM(COL_REF) =TRIM(COL_REF)  THEN 'TRUE' ELSE 'FALSE' END MATCH_collateral_reference,
ROUND(COLL_VALUE,2) leg_col_value,ROUND(SECU_VALUE,2) fin_col_value, CASE WHEN ROUND(COLL_VALUE,2) = ROUND(SECU_VALUE,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_collateral_VALUE,
ROUND(FORACID_COLL_VALUE,2) leg_APPORTIONED_VALUE,ROUND(APPORTIONED_VALUE,2) fin_APPORTIONED_VALUE, CASE WHEN ROUND(FORACID_COLL_VALUE,2) = ROUND(APPORTIONED_VALUE,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_APPORTIONED_VALUE,
A.LIMIT_PREFIX,A.LIMIT_SUFFIX,LIMIT_SUFFIX_DESC
 from COLL_LIM_LINKAGE_TMP a
left join (
select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLGUARANTEE
                   UNION ALL
                   select COLLATERAL_TYPE,COLLATERAL_CODE,COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLIMMOV
                   UNION ALL
                   select COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLTRADE
                   UNION ALL
                   select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLOTHERS
                   UNION ALL
                   select COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.COLL_MUTUAL_FUND
                   UNION ALL
                   select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLDEPOSITS
) b on a.SECU_SRL_NUM = b.SECU_SRL_NUM 
left join map_cif on fin_cif_id  = LIMIT_PREFIX and IS_JOINT <>'Y'
left join (
select limit_prefix,limit_suffix,c.* from  tbaadm.sdr c
left join tbaadm.scmt on scmt.SECU_SRL_NUM = c.SECU_SRL_NUM and scmt.bank_id='01'
left join tbaadm.llt d on d.LIMIT_B2KID = c.LIMIT_B2KID and d.bank_id='01'
where c.bank_id='01'
) c on c.SECU_SRL_NUM = a.SECU_SRL_NUM and a.limit_prefix = c.limit_prefix and c.limit_suffix = a.limit_suffix
left join LIMIT_SUFFIX_CODE_AND_DESC on trim(A.LIMIT_SUFFIX) = trim(LIMIT_SUFFIX_CODE)


select '0'||gfclc||gfcus LEG_CUST_NO,c.limit_prefix FIN_CUST_NO, CASE WHEN '0'||TRIM(gfclc||gfcus) =TRIM(c.limit_prefix) THEN 'TRUE' ELSE 'FALSE' END MATCH_CUST_NO,
CLTRL_CODE mapped_col_code,SECU_CODE fin_col_code, CASE WHEN TRIM(CLTRL_CODE) =TRIM(SECU_CODE) THEN 'TRUE' ELSE 'FALSE' END MATCH_CUST_NO,
 SECU_TYPE_IND FIN_COL_TYPE, 
a.SECU_SRL_NUM FIN_COLLATERAL_NUM,
COL_REF leg_collateral_reference,COL_REF fin_collateral_reference, CASE WHEN TRIM(COL_REF) =TRIM(COL_REF)  THEN 'TRUE' ELSE 'FALSE' END MATCH_collateral_reference,
--ROUND(COLL_VALUE,2) leg_col_value,ROUND(SECU_VALUE,2) fin_col_value, CASE WHEN ROUND(COLL_VALUE,2) = ROUND(SECU_VALUE,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_collateral_VALUE,
ROUND(FORACID_COLL_VALUE,2) leg_APPORTIONED_VALUE,ROUND(APPORTIONED_VALUE,2) fin_APPORTIONED_VALUE, CASE WHEN ROUND(FORACID_COLL_VALUE,2) = ROUND(APPORTIONED_VALUE,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_APPORTIONED_VALUE,
A.LIMIT_PREFIX,A.LIMIT_SUFFIX,LIMIT_SUFFIX_DESC,
FREE_FIELD1 MINIMUM_LIMIT_COVARAGE
 from COLL_LIM_LINKAGE_TMP a
left join (
select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLGUARANTEE
                   UNION ALL
                   select COLLATERAL_TYPE,COLLATERAL_CODE,COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLIMMOV
                   UNION ALL
                   select COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLTRADE
                   UNION ALL
                   select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLOTHERS
                   UNION ALL
                   select COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.COLL_MUTUAL_FUND
                   UNION ALL
                   select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLDEPOSITS
) b on a.SECU_SRL_NUM = b.SECU_SRL_NUM 
left join map_cif on fin_cif_id  = LIMIT_PREFIX and IS_JOINT <>'Y'
LEFT join (
select limit_prefix,limit_suffix,c.* from  tbaadm.sdr c
left join tbaadm.scmt on scmt.SECU_SRL_NUM = c.SECU_SRL_NUM and scmt.bank_id='01'
left join tbaadm.llt d on d.LIMIT_B2KID = c.LIMIT_B2KID and d.bank_id='01'
where c.bank_id='01'
) c on c.SECU_SRL_NUM = a.SECU_SRL_NUM and a.limit_prefix = c.limit_prefix and c.limit_suffix = a.limit_suffix AND ROUND(C.APPORTIONED_VALUE,0) = ROUND(FORACID_COLL_VALUE,0)
left join LIMIT_SUFFIX_CODE_AND_DESC on trim(A.LIMIT_SUFFIX) = trim(LIMIT_SUFFIX_CODE)
LEFT JOIN (SELECT LIMIT_PREFIX,LIMIT_SUFFIX,FREE_FIELD1 FROM CUSTOM.C_LLT_NOTES WHERE BANK_ID='01' AND TRIM(FREE_FIELD1) IS NOT NULL) LLT ON LLT.LIMIT_PREFIX=A.LIMIT_PREFIX AND LLT.LIMIT_SUFFIX=A.LIMIT_SUFFIX 
