DROP TABLE COL_NOT_MIGRATED_REPORT;

CREATE TABLE COL_NOT_MIGRATED_REPORT AS
SELECT HYCUS CUSTOMER_MNEMONIC,
       HYCLC CUSTOMER_LOCATION,
       HYDLP DEAL_TYPE,
       HYDLR DEAL_REFERENCE,
       HYDBNM DEAL_BRANCH,
       HYAB ACCOUNT_BRANCH,
       HYAN BASIC_PART_OF_ACCOUNT_NUMBE,
       HYAS ACCOUNT_SUFFIX,
       HYCLP COLLATERAL_TYPE,
       HYCLR COLLATERAL_REFERENCE,
       HYCCM COLLATERAL_COMPLETE,
       HYCNA COLLATERAL_COUNTRY,
       HYCLO COLLATERAL_LOCATION,
       HYDPC DEPARTMENT_CODE,
       HYCPI CAPITALISE_INTEREST,
       HYCXD COLLATERAL_EXPIRY_DATE,
       HYLRD LAST_REVIEW_DATE,
       HYFRQ REVIEW_FREQUENCY,
       HYNRD NEXT_REVIEW_DATE,
       HYNOU NUMBER_OF_UNITS,
       HYUNP UNIT_PRICE,
       HYCCY COLLATERAL_CURRENCY,
       HYCLV/ C8PWD  COLLATERAL_VALUE,
       HYSVM SPECIAL_VALUATION_MARGIN,
       HYMCV MAXIMUM_COLLATERAL_VALUE,
       HYBKV/ C8PWD  BANK_VALUATION,
       HYTOTA TOTAL_ASSIGNED,
       HYISV/ C8PWD  INSURANCE_VALUATION,
       HYIXD INSURANCE_EXPIRY_DATE,
       HYNR1 NARRATIVE_LINE_1,
       HYNR2 NARRATIVE_LINE_2,
       HYNR3 NARRATIVE_LINE_3,
       HYNR4 NARRATIVE_LINE_4,
       HYCLV / C8PWD FCY_AMOUNT,
       (HYCLV / C8PWD) * C8RTE KWD_AMOUNT,
       CASE
          WHEN MAP_CIF.FIN_CIF_ID IS NULL THEN 'Customer not migrated in core'
          WHEN TRIM (HYCLP) = '021' AND MAP_ACC.FIN_ACC_NUM IS NULL THEN 'Deposit account number not migrated to core'
          WHEN (HYPF.HYCLV) / POWER (10, C8CED) = 0 THEN 'Zero collateral amount'
          WHEN CONV_TO_VALID_DATE (GET_DATE_FM_BTRV (HYCXD), 'YYYYMMDD') < TO_DATE (GET_PARAM ('EOD_DATE'), 'dd-mm-yyyy') THEN 'Expired collateral'
       END REASON_FOR_NOT_MIGRATED,
       GFPF.GFACO LEG_RM_CODE,
       CONV_TO_VALID_DATE (GET_DATE_FM_BTRV (V5MDT), 'YYYYMMDD') DEPOSIT_MATURITY_DATE,
       CASE
          WHEN CONV_TO_VALID_DATE (GET_DATE_FM_BTRV (TRIM(V5MDT)), 'YYYYMMDD') < TO_DATE (GET_PARAM ('EOD_DATE'), 'dd-mm-yyyy') THEN 'Yes'
          WHEN V5MDT IS NOT NULL THEN 'No'
       END IS_MATURED_DEPOSIT
  FROM HYPF
LEFT JOIN C8PF ON TRIM(C8CCY) = TRIM(HYCCY)
LEFT JOIN GFPF ON TRIM(GFPF.GFCUS)= TRIM(HYCUS) AND NVL(TRIM(GFPF.GFCLC),' ') = NVL(TRIM(HYCLC),' ')
LEFT JOIN MAP_CIF ON TRIM(HYCUS)=TRIM(MAP_CIF.GFCUS) AND NVL(TRIM(HYCLC),' ')=NVL(TRIM(MAP_CIF.GFCLC),' ') AND  IS_JOINT <>'Y'
LEFT JOIN MAP_ACC ON TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR)=LEG_ACC_NUM
LEFT JOIN V5PF ON TRIM(V5BRNM)||TRIM(V5DLP)||TRIM(V5DLR) = TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR)
LEFT JOIN (
    SELECT COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF FROM COL_G_INFY_TABLE
    UNION ALL
    SELECT COLLATERAL_TYPE,COLLATERAL_CODE,COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF FROM COL_IP_RE_INFY_TABLE
    UNION ALL
    SELECT COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF FROM COL_TRADEABLE_INFY_TABLE
    UNION ALL
    SELECT COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF FROM COL_OTHERS_INFY_TABLE
    UNION ALL
    SELECT COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF FROM COL_MUTUAL_FUND_INFY_TABLE
    UNION ALL
    SELECT COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF FROM COL_DEP_INFY_TABLE
) B ON (case when trim(hyclp)!='021' and nvl(TRIM(COL_REF),' ') = nvl(TRIM(HYCLR),' ') then 1 when  trim(hyclp)='021' and TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR) = TRIM(COL_REF) then 1 else 0 end = 1)
and round(hyclv/c8pwd,1) = round(coll_value,1)
WHERE CIF_ID IS NULL; 
