SELECT A.COLLATERAL_TYPE,LEG_COUNT,FIN_COUNT FROM (
select 'COLLATERAL_DEPOSIT' COLLATERAL_TYPE,count(*) LEG_COUNT from COL_DEP_INFY_TABLE
union all
select 'COLLATERAL_GUARENTY' COLLATERAL_TYPE,count(*) from COL_G_INFY_TABLE
union all
select 'COLLATERAL_IMMOVABLE' COLLATERAL_TYPE,count(*) from COL_IP_RE_INFY_TABLE
union all
select 'COLLATERAL_MUTUAL_FUND' COLLATERAL_TYPE,count(*) from COL_MUTUAL_FUND_INFY_TABLE
union all
select 'COLLATERAL_OTHERS' COLLATERAL_TYPE,count(*) from COL_OTHERS_INFY_TABLE
union all
select 'COLLATERAL_TRADABLE' COLLATERAL_TYPE,count(*) from COL_TRADEABLE_INFY_TABLE
) A
LEFT JOIN (
select case when SECU_TYPE_IND ='D' then 'COLLATERAL_DEPOSIT'
when SECU_TYPE_IND ='R' then 'COLLATERAL_GUARENTY'
when SECU_TYPE_IND ='I' then 'COLLATERAL_IMMOVABLE'
when SECU_TYPE_IND ='U' then 'COLLATERAL_MUTUAL_FUND'
when SECU_TYPE_IND ='O' then 'COLLATERAL_OTHERS'
when SECU_TYPE_IND ='S' then 'COLLATERAL_TRADABLE' end COLLATERAL_TYPE
,FIN_COUNT from (
select SECU_TYPE_IND,count(*) FIN_COUNT from tbaadm.scmt where bank_id='01' group by SECU_TYPE_IND
)
)  B ON A.COLLATERAL_TYPE = B.COLLATERAL_TYPE;




SELECT case when a.COLTRLTYPE ='D' then 'COLLATERAL_DEPOSIT'
when a.COLTRLTYPE ='R' then 'COLLATERAL_GUARENTY'
when a.COLTRLTYPE ='I' then 'COLLATERAL_IMMOVABLE'
when a.COLTRLTYPE ='U' then 'COLLATERAL_MUTUAL_FUND'
when a.COLTRLTYPE ='O' then 'COLLATERAL_OTHERS'
when a.COLTRLTYPE ='S' then 'COLLATERAL_TRADABLE' end COLLATERAL_TYPE,COLTRLCODE COLLATERAL_CODE,CRNCY_CODE,COLLATERAL_AMOUNT LEG_COLLATERAL_AMOUNT,FIN_COLLATERAL_AMOUNT FROM (
SELECT COLTRLTYPE,COLTRLCODE,SUM(COLL_VALUE) COLLATERAL_AMOUNT FROM COL_DEP_INFY_TABLE GROUP BY COLTRLTYPE,COLTRLCODE
union all
SELECT COLTRLTYPE,COLTRLCODE,SUM(COLL_VALUE) FROM COL_G_INFY_TABLE GROUP BY COLTRLTYPE,COLTRLCODE
union all
SELECT COLLATERAL_TYPE,COLLATERAL_CODE,SUM(MARKET_VALUE) FROM COL_IP_RE_INFY_TABLE GROUP BY COLLATERAL_TYPE,COLLATERAL_CODE
union all
SELECT COLLATERAL_TYPE,COLLATERAL_CODE,SUM(TOTAL_COLLATERAL_VALUE) FROM COL_MUTUAL_FUND_INFY_TABLE GROUP BY  COLLATERAL_TYPE,COLLATERAL_CODE
union all
SELECT COLTRLTYPE,COLTRLCODE,SUM(COLL_VALUE) FROM COL_OTHERS_INFY_TABLE GROUP BY COLTRLTYPE,COLTRLCODE
union all
SELECT COLLATERAL_TYPE,COLLATERAL_CODE,SUM(TOTAL_COLLATERAL_VALUE) FROM COL_TRADEABLE_INFY_TABLE GROUP BY  COLLATERAL_TYPE,COLLATERAL_CODE
) A
LEFT JOIN (SELECT SECU_TYPE_IND COLTRLTYPE,CRNCY_CODE,SECU_CODE,SUM(SECU_VALUE) FIN_COLLATERAL_AMOUNT FROM TBAADM.SCMT WHERE BANK_ID='01' GROUP BY SECU_TYPE_IND,CRNCY_CODE,SECU_CODE
)  B ON trim(A.COLTRLTYPE) = trim(B.COLTRLTYPE) and trim(a.COLTRLCODE) = trim(b.SECU_CODE) ;




--------------------------------------------------------


SELECT A.COLLATERAL_TYPE,LEG_COUNT,FIN_COUNT FROM (
select 'COLLATERAL_DEPOSIT' COLLATERAL_TYPE,count(*) LEG_COUNT from hypf where hyclp ='021'
union all
select 'COLLATERAL_GUARENTY' COLLATERAL_TYPE,count(*) from hypf where hyclp ='002'
union all
select 'COLLATERAL_IMMOVABLE' COLLATERAL_TYPE,count(*) from hypf where hyclp in('010','011','025')
union all
select 'COLLATERAL_MUTUAL_FUND' COLLATERAL_TYPE,count(*) from hypf where hyclp in('003','004') and substr(HYCLR,10,3) in('ABG','ABK')
union all
select 'COLLATERAL_OTHERS' COLLATERAL_TYPE,count(*) from hypf where (HYCLP in ('003','004') and SUBSTR(HYCLR,32,4) in('QUOT','UNQT','CASH')) or (HYCLP IN('022','026'))
union all
select 'COLLATERAL_TRADABLE' COLLATERAL_TYPE,count(*) from hypf where hyclp in('003','004') and substr(HYCLR,10,3) not in('ABG','ABK') and SUBSTR(HYCLR,32,4) not in('QUOT','UNQT','CASH')
) A
LEFT JOIN (
select case when SECU_TYPE_IND ='D' then 'COLLATERAL_DEPOSIT'
when SECU_TYPE_IND ='R' then 'COLLATERAL_GUARENTY'
when SECU_TYPE_IND ='I' then 'COLLATERAL_IMMOVABLE'
when SECU_TYPE_IND ='U' then 'COLLATERAL_MUTUAL_FUND'
when SECU_TYPE_IND ='O' then 'COLLATERAL_OTHERS'
when SECU_TYPE_IND ='S' then 'COLLATERAL_TRADABLE' end COLLATERAL_TYPE
,FIN_COUNT from (
select SECU_TYPE_IND,count(*) FIN_COUNT from tbaadm.scmt where bank_id='01' group by SECU_TYPE_IND
)
)  B ON A.COLLATERAL_TYPE = B.COLLATERAL_TYPE;


select COLLATERAL_TYPE, CRNCY_CODE, sum(LEG_COLLATERAL_AMOUNT/c8pwd) LEG_COLLATERAL_AMOUNT, sum(nvl(FIN_COLLATERAL_AMOUNT,0)) from (
SELECT COLLATERAL_TYPE,trim(hyccy) CRNCY_CODE,hyclv LEG_COLLATERAL_AMOUNT,FIN_COLLATERAL_AMOUNT FROM 
(
select 'COLLATERAL_DEPOSIT' COLLATERAL_TYPE,TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR) deal_num ,hyclp,hyclr,hyclv,hyccy from hypf where hyclp ='021'
union all
select 'COLLATERAL_GUARENTY' COLLATERAL_TYPE,TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR) deal_num ,hyclp,hyclr,hyclv,hyccy from hypf where hyclp ='002'
union all
select 'COLLATERAL_IMMOVABLE' COLLATERAL_TYPE,TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR) deal_num ,hyclp,hyclr,hyclv,hyccy from hypf where hyclp in('010','011','025')
union all
select 'COLLATERAL_MUTUAL_FUND' COLLATERAL_TYPE,TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR) deal_num ,hyclp,hyclr,hyclv,hyccy from hypf where hyclp in('003','004') and substr(HYCLR,10,3) in('ABG','ABK')
union all
select 'COLLATERAL_OTHERS' COLLATERAL_TYPE,TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR) deal_num ,hyclp,hyclr,hyclv,hyccy from hypf where (HYCLP in ('003','004') and SUBSTR(HYCLR,32,4) in('QUOT','UNQT','CASH')) or (HYCLP IN('022','026'))
union all
select 'COLLATERAL_TRADABLE' COLLATERAL_TYPE,TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR) deal_num ,hyclp,hyclr,hyclv,hyccy from hypf where hyclp in('003','004') and substr(HYCLR,10,3) not in('ABG','ABK') and SUBSTR(HYCLR,32,4) not in('QUOT','UNQT','CASH')
)c
left join
(
select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLGUARANTEE
UNION ALL
select COLLATERAL_TYPE,COLLATERAL_CODE,COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLIMMOV
UNION ALL
select COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLTRADE
UNION ALL
select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLOTHERS
UNION ALL
select COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.COLL_MUTUAL_FUND
UNION ALL
select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLDEPOSITS                   
) A on trim(c.hyclr) = trim(a.COL_REF) or trim(a.COL_REF) = deal_num
LEFT JOIN (SELECT SECU_SRL_NUM,SECU_TYPE_IND COLTRLTYPE,CRNCY_CODE,SECU_CODE,(SECU_VALUE) FIN_COLLATERAL_AMOUNT FROM TBAADM.SCMT WHERE BANK_ID='01' 
)  B ON trim(A.COLTRLTYPE) = trim(B.COLTRLTYPE) and trim(a.COLTRLCODE) = trim(b.SECU_CODE) and a.SECU_SRL_NUM = b.SECU_SRL_NUM 
) x
left join c8pf y on trim(c8ccy) = trim(CRNCY_CODE)
group by COLLATERAL_TYPE, CRNCY_CODE
;