========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
com_loan_flows_report.sql 

--ALL CASH FLOWS
select 
DEALNO OPICS_DEALNO,deal_identifier FIN_DEAL_IDENTIFIER,CASE WHEN DEALNO = deal_identifier THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
deal_num FIN_DEAL_NUM,
SCHDSEQ OPICS_SCHEDULE_SEQ,SIDE_SEQUENCE FIN_SCHEDULE_SEQ,CASE WHEN TO_NUMBER(SCHDSEQ) = SIDE_SEQUENCE THEN 'TRUE' ELSE 'FALSE' END MATCH_SEQUENCE,
CCY OPICS_CCY,NOTIONAL_AMOUNT_CCY FIN_CCY,CASE WHEN CCY = NOTIONAL_AMOUNT_CCY THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
INTSTRTDTE OPICS_START_DATE ,fin_flow.START_DATE FIN_START_DATE ,CASE WHEN INTSTRTDTE = fin_flow.START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
INTENDDTE OPICS_END_DATE,fin_flow.END_DATE FIN_END_DATE,CASE WHEN INTENDDTE = fin_flow.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
RATECODE OPICS_RATECODE,RATE_CODE FIN_RATECODE,CASE WHEN nvl(RATECODE,' ') = nvl(RATE_CODE,' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_RATE_CODE,
INTRATE_8 OPICS_INTRATE,NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100) FIN_INTRATE,CASE WHEN to_number(INTRATE_8) = NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100) THEN 'TRUE' ELSE 'FALSE' END MATCH_INTRATE,
SPREAD_8 OPICS_SPREAD_RATE ,fin_flow.SPREAD_RATE*100 FIN_SPREAD_RATE,CASE WHEN to_number(SPREAD_8) = NVL(fin_flow.SPREAD_RATE*100,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_SPREAD_RATE
 from schd
left join tt_com_loan@ftmig on deal_identifier = dealno 
left join (select reset_date,REFERENCE_RATE_FBO_ID_NUM,CASH_FLOW_TYPE,parent_fbo_id_num,BASIS_CODE,START_DATE,END_DATE,NOTIONAL_AMOUNT_CCY,NOTIONAL_AMOUNT_VALUE,SPREAD_RATE,MARGIN,FIX_RATE,SIDE_SEQUENCE,PARENT_FBO_ID_VER from  TT_CMLOAN_CASH_FLOWS@ftmig) fin_flow on PARENT_FBO_ID_NUM  = deal_num and PARENT_FBO_ID_VER='999999' and SIDE_SEQUENCE = to_number(SCHDSEQ)
LEFT JOIN (
SELECT  A.REF_RATE_FBO_ID_NUM,RATE_CODE,RATE_CCY,RATE_VALUE,EFFECTIVE_DATE FROM SD_REF_RATE_VALUE@FTMIG A
LEFT JOIN SD_REF_RATE@FTMIG B ON B.FBO_ID_NUM = A.REF_RATE_FBO_ID_NUM
) REF_RATE ON REF_RATE.REF_RATE_FBO_ID_NUM = REFERENCE_RATE_FBO_ID_NUM AND reset_date = EFFECTIVE_DATE
where TRIM(DEALNO) IN(SELECT TRIM(DEAL_IDENTIFIER) FROM COM_LOAN_O_TABLE)
order by DEALNO,to_number(SCHDSEQ);

select 
DEALNO OPICS_DEALNO,deal_identifier FIN_DEAL_IDENTIFIER,CASE WHEN DEALNO = deal_identifier THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
deal_num FIN_DEAL_NUM,
SCHDSEQ OPICS_SCHEDULE_SEQ,SIDE_SEQUENCE+1 FIN_SCHEDULE_SEQ,CASE WHEN TO_NUMBER(SCHDSEQ) = SIDE_SEQUENCE+1 THEN 'TRUE' ELSE 'FALSE' END MATCH_SEQUENCE,
CCY OPICS_CCY,NOTIONAL_AMOUNT_CCY FIN_CCY,CASE WHEN CCY = NOTIONAL_AMOUNT_CCY THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
INTSTRTDTE OPICS_START_DATE ,fin_flow.START_DATE FIN_START_DATE ,CASE WHEN INTSTRTDTE = fin_flow.START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
INTENDDTE OPICS_END_DATE,fin_flow.END_DATE FIN_END_DATE,CASE WHEN INTENDDTE = fin_flow.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
RATECODE OPICS_RATECODE,RATE_CODE FIN_RATECODE,CASE WHEN nvl(case when RATECODE like 'LI%' then RATECODE end,' ') = nvl(RATE_CODE,' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_RATE_CODE,
INTRATE_8 OPICS_INTRATE,NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100) FIN_INTRATE,CASE WHEN round(to_number(INTRATE_8),12) = round(nvl(NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100),0),12) THEN 'TRUE' ELSE 'FALSE' END MATCH_INTRATE,
SPREAD_8 OPICS_SPREAD_RATE ,fin_flow.SPREAD_RATE*100 FIN_SPREAD_RATE,CASE WHEN to_number(SPREAD_8) = NVL(fin_flow.SPREAD_RATE*100,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_SPREAD_RATE
 from schd
left join tt_com_loan@ftmig on deal_identifier = dealno 
left join (select reset_date,REFERENCE_RATE_FBO_ID_NUM,CASH_FLOW_TYPE,parent_fbo_id_num,BASIS_CODE,START_DATE,END_DATE,NOTIONAL_AMOUNT_CCY,NOTIONAL_AMOUNT_VALUE,SPREAD_RATE,MARGIN,FIX_RATE,SIDE_SEQUENCE,PARENT_FBO_ID_VER from  TT_CMLOAN_CASH_FLOWS@ftmig where SUBTYPE='MAIN' ) fin_flow on PARENT_FBO_ID_NUM  = deal_num and PARENT_FBO_ID_VER='999999' and SIDE_SEQUENCE+1 = to_number(SCHDSEQ)
LEFT JOIN (
SELECT  A.REF_RATE_FBO_ID_NUM,RATE_CODE,RATE_CCY,RATE_VALUE,EFFECTIVE_DATE FROM SD_REF_RATE_VALUE@FTMIG A
LEFT JOIN SD_REF_RATE@FTMIG B ON B.FBO_ID_NUM = A.REF_RATE_FBO_ID_NUM
) REF_RATE ON REF_RATE.REF_RATE_FBO_ID_NUM = REFERENCE_RATE_FBO_ID_NUM AND reset_date = EFFECTIVE_DATE
where TRIM(DEALNO) IN(SELECT TRIM(DEAL_IDENTIFIER) FROM COM_LOAN_O_TABLE)
and SCHDTYPE!='V'
and dealno not in(SELECT DEALNO FROM SCHD WHERE  TRIM(DEALNO) IN(SELECT TRIM(DEAL_IDENTIFIER) FROM COM_LOAN_O_TABLE) group by DEALNO having count(*) > 2)
order by DEALNO,to_number(SCHDSEQ);


select * from schd where dealno in(SELECT DEALNO FROM SCHD WHERE  TRIM(DEALNO) IN(SELECT TRIM(DEAL_IDENTIFIER) FROM COM_LOAN_O_TABLE) group by DEALNO having count(*) > 2)

select deal_identifier,TT_CMLOAN_CASH_FLOWS.* from  TT_CMLOAN_CASH_FLOWS@ftmig
inner join (
select distinct deal_num,deal_identifier from schd 
left join tt_com_loan@ftmig on deal_identifier = dealno 
where dealno in(SELECT DEALNO FROM SCHD WHERE  TRIM(DEALNO) IN(SELECT TRIM(DEAL_IDENTIFIER) FROM COM_LOAN_O_TABLE) group by DEALNO having count(*) > 2)) on PARENT_FBO_ID_NUM = deal_num
 where   PARENT_FBO_ID_VER='999999' 

-------------------------------------------------------------------------------------------------------------------------------------------
--CURRENT CASH FLOWS
select 
DEALNO OPICS_DEALNO,deal_identifier FIN_DEAL_IDENTIFIER,CASE WHEN DEALNO = deal_identifier THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
deal_num FIN_DEAL_NUM,
SCHDSEQ OPICS_SCHEDULE_SEQ,SIDE_SEQUENCE FIN_SCHEDULE_SEQ,CASE WHEN TO_NUMBER(SCHDSEQ) = SIDE_SEQUENCE THEN 'TRUE' ELSE 'FALSE' END MATCH_SEQUENCE,
CCY OPICS_CCY,NOTIONAL_AMOUNT_CCY FIN_CCY,CASE WHEN CCY = NOTIONAL_AMOUNT_CCY THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
INTSTRTDTE OPICS_START_DATE ,fin_flow.START_DATE FIN_START_DATE ,CASE WHEN INTSTRTDTE = fin_flow.START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
INTENDDTE OPICS_END_DATE,fin_flow.END_DATE FIN_END_DATE,CASE WHEN INTENDDTE = fin_flow.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
RATECODE OPICS_RATECODE,RATE_CODE FIN_RATECODE,CASE WHEN nvl(RATECODE,' ') = nvl(RATE_CODE,' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_RATE_CODE,
INTRATE_8 OPICS_INTRATE,NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100) FIN_INTRATE,CASE WHEN to_number(INTRATE_8) = NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100) THEN 'TRUE' ELSE 'FALSE' END MATCH_INTRATE,
SPREAD_8 OPICS_SPREAD_RATE ,fin_flow.SPREAD_RATE*100 FIN_SPREAD_RATE,CASE WHEN to_number(SPREAD_8) = NVL(fin_flow.SPREAD_RATE*100,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_SPREAD_RATE
 from schd
left join tt_com_loan@ftmig on deal_identifier = dealno 
left join (select reset_date,REFERENCE_RATE_FBO_ID_NUM,CASH_FLOW_TYPE,parent_fbo_id_num,BASIS_CODE,START_DATE,END_DATE,NOTIONAL_AMOUNT_CCY,NOTIONAL_AMOUNT_VALUE,SPREAD_RATE,MARGIN,FIX_RATE,SIDE_SEQUENCE,PARENT_FBO_ID_VER from  TT_CMLOAN_CASH_FLOWS@ftmig) fin_flow on PARENT_FBO_ID_NUM  = deal_num and PARENT_FBO_ID_VER='999999' and SIDE_SEQUENCE = to_number(SCHDSEQ)
LEFT JOIN (
SELECT  A.REF_RATE_FBO_ID_NUM,RATE_CODE,RATE_CCY,RATE_VALUE,EFFECTIVE_DATE FROM SD_REF_RATE_VALUE@FTMIG A
LEFT JOIN SD_REF_RATE@FTMIG B ON B.FBO_ID_NUM = A.REF_RATE_FBO_ID_NUM
) REF_RATE ON REF_RATE.REF_RATE_FBO_ID_NUM = REFERENCE_RATE_FBO_ID_NUM AND reset_date = EFFECTIVE_DATE
where TRIM(DEALNO) IN(SELECT TRIM(DEAL_IDENTIFIER) FROM COM_LOAN_O_TABLE)
AND INTSTRTDTE <= TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND  INTENDDTE > TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY')
order by DEALNO,to_number(SCHDSEQ);


select 
DEALNO OPICS_DEALNO,deal_identifier FIN_DEAL_IDENTIFIER,CASE WHEN DEALNO = deal_identifier THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
deal_num FIN_DEAL_NUM,
SCHDSEQ OPICS_SCHEDULE_SEQ,SIDE_SEQUENCE+1 FIN_SCHEDULE_SEQ,CASE WHEN TO_NUMBER(SCHDSEQ) = SIDE_SEQUENCE+1 THEN 'TRUE' ELSE 'FALSE' END MATCH_SEQUENCE,
CCY OPICS_CCY,NOTIONAL_AMOUNT_CCY FIN_CCY,CASE WHEN CCY = NOTIONAL_AMOUNT_CCY THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
INTSTRTDTE OPICS_START_DATE ,fin_flow.START_DATE FIN_START_DATE ,CASE WHEN INTSTRTDTE = fin_flow.START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
INTENDDTE OPICS_END_DATE,fin_flow.END_DATE FIN_END_DATE,CASE WHEN INTENDDTE = fin_flow.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
RATECODE OPICS_RATECODE,RATE_CODE FIN_RATECODE,CASE WHEN nvl(case when RATECODE like 'LI%' then RATECODE end,' ') = nvl(RATE_CODE,' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_RATE_CODE,
INTRATE_8 OPICS_INTRATE,NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100) FIN_INTRATE,CASE WHEN to_number(INTRATE_8) = nvl(NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100),0) THEN 'TRUE' ELSE 'FALSE' END MATCH_INTRATE,
SPREAD_8 OPICS_SPREAD_RATE ,fin_flow.SPREAD_RATE*100 FIN_SPREAD_RATE,CASE WHEN to_number(SPREAD_8) = NVL(fin_flow.SPREAD_RATE*100,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_SPREAD_RATE
 from schd
left join tt_com_loan@ftmig on deal_identifier = dealno 
left join (select reset_date,REFERENCE_RATE_FBO_ID_NUM,CASH_FLOW_TYPE,parent_fbo_id_num,BASIS_CODE,START_DATE,END_DATE,NOTIONAL_AMOUNT_CCY,NOTIONAL_AMOUNT_VALUE,SPREAD_RATE,MARGIN,FIX_RATE,SIDE_SEQUENCE,PARENT_FBO_ID_VER from  TT_CMLOAN_CASH_FLOWS@ftmig where SUBTYPE='MAIN' ) fin_flow on PARENT_FBO_ID_NUM  = deal_num and PARENT_FBO_ID_VER='999999' and SIDE_SEQUENCE+1 = to_number(SCHDSEQ)
LEFT JOIN (
SELECT  A.REF_RATE_FBO_ID_NUM,RATE_CODE,RATE_CCY,RATE_VALUE,EFFECTIVE_DATE FROM SD_REF_RATE_VALUE@FTMIG A
LEFT JOIN SD_REF_RATE@FTMIG B ON B.FBO_ID_NUM = A.REF_RATE_FBO_ID_NUM
) REF_RATE ON REF_RATE.REF_RATE_FBO_ID_NUM = REFERENCE_RATE_FBO_ID_NUM AND reset_date = EFFECTIVE_DATE
where TRIM(DEALNO) IN(SELECT TRIM(DEAL_IDENTIFIER) FROM COM_LOAN_O_TABLE)
and SCHDTYPE!='V'
AND INTSTRTDTE <= TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND  INTENDDTE > TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY')
and dealno not in(SELECT DEALNO FROM SCHD WHERE  TRIM(DEALNO) IN(SELECT TRIM(DEAL_IDENTIFIER) FROM COM_LOAN_O_TABLE) group by DEALNO having count(*) > 2)
order by DEALNO,to_number(SCHDSEQ); 
