========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
com_loan_report.sql 

select DISTINCT 
D.DEALNO OPICS_DEALNO, FIN_COM_LOAN.DEAL_IDENTIFIER FINACLE_DEAL_IDENTIFIER, CASE WHEN TRIM(D.DEALNO) = TRIM(FIN_COM_LOAN.DEAL_IDENTIFIER) THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
D.PORT OPICS_PORT,SDTRBK.NAME FINACLE_TRADING_BOOK,CASE WHEN CASE WHEN trim(D.PORT)='PORT' THEN 'CORPORATE' ELSE 'INTERBANK' END like  SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK,
D.BR OPICS_BR,SDENT.NAME FINACLE_ENTITY_NAME,CASE WHEN CASE WHEN TRIM(D.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END like  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY_NAME,
--D.PORT OPICS_PORT,SDSBTY.NAME FINACLE_SUBTYPE,
C.CMNE OPICS_CMNE,SDCP.NAME FINACLE_COUNTERPARTY_STRING,CASE WHEN TRIM(C.CMNE) = TRIM(SDCP.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_COUNTERPARTY_STRING,
D.DEALDATE OPICS_DEALDATE,FIN_COM_LOAN.DEAL_DATE FINACLE_DEAL_DATE ,CASE WHEN D.DEALDATE = FIN_COM_LOAN.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALDATE,
D.VDATE OPICS_VDATE , FIN_COM_LOAN.START_DATE FINACLE_START_DATE,CASE WHEN D.VDATE =  FIN_COM_LOAN.START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
D.MDATE OPICS_MDATE,FIN_COM_LOAN.END_DATE FINACLE_END_DATE,CASE WHEN D.MDATE = FIN_COM_LOAN.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
D.AL OPICS_AL , LONG_OR_SHORT FINACLE_LONG_OR_SHORT,CASE WHEN CASE WHEN D.AL='L' THEN 'S' ELSE 'L' END=LONG_OR_SHORT THEN 'TRUE' ELSE 'FALSE' END MATCH_LONG_OR_SHORT,
--D.AL OPICS_AL,D.RATECODE OPICS_RATECODE,TYPE_STRING FINACLE_TYPE_STRING ,--***
D.CCY OPICS_CCY,FIN_COM_LOAN.CURRENCY_LIST FINACLE_CURRENCY_LIST,CASE WHEN D.CCY=FIN_COM_LOAN.CURRENCY_LIST THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
D.CCYAMT OPICS_CCYAMT,TTCMFL.NOTIONAL_AMOUNT_VALUE FINACLE_NOTIONAL_AMOUNT_VALUE,CASE WHEN D.CCYAMT=TTCMFL.NOTIONAL_AMOUNT_VALUE THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYAMT,
D.BASIS OPICS_BASIS,TTCMFL.BASIS_CODE OPICS_BASIS_CODE,CASE WHEN SUBSTR(D.BASIS,1,1)||'/'||SUBSTR(D.BASIS,2,3)=TTCMFL.BASIS_CODE THEN 'TRUE' ELSE 'FALSE' END MATCH_BASIS,
to_number(D.INTRATE) OPICS_INTRATE,TTCMFL.SETTLEMENT_RATE*100 FINACLE_SETTLEMENT_RATE,CASE WHEN D.INTRATE=TTCMFL.SETTLEMENT_RATE*100 THEN 'TRUE' ELSE 'FALSE' END MATCH_INTRATE,
D.SPREAD_8 OPICS_SPREAD_8,TTCMFL.SPREAD_RATE*100 FINACLE_SPREAD_RATE,CASE WHEN D.SPREAD_8=TTCMFL.SPREAD_RATE*100 THEN 'TRUE' ELSE 'FALSE' END MATCH_SPREAD_RATE
,D.RATECODE OPICS_RATECODE,TTCMFL.CASH_FLOW_TYPE FINACLE_CASH_FLOW_TYPE,CASE WHEN CASE WHEN D.RATECODE LIKE 'LI%' THEN 'FLOAT' ELSE 'FIXED'  END=TTCMFL.CASH_FLOW_TYPE  THEN 'TRUE' ELSE 'FALSE' END MATCH_SPREAD_RATE
--C.BIC OPICS_BIC, FIN_COM_LOAN.CONFIRM_METHOD FINACLE_CONFIRM_METHOD
FROM DLDT D 
INNER JOIN CUST C ON TRIM(D.CNO)=TRIM(C.CNO)
LEFT JOIN SCHD S ON TRIM(D.DEALNO)=TRIM(S.DEALNO) AND S.SCHDSEQ='001' AND D.BR=S.BR 
LEFT JOIN TT_COM_LOAN@ftuat FIN_COM_LOAN ON TRIM(D.DEALNO)=TRIM(FIN_COM_LOAN.DEAL_IDENTIFIER) AND FIN_COM_LOAN.SUBTYPE_FBO_ID_NUM NOT IN (SELECT FBO_ID_NUM FROM SD_SUBTYPE@ftuat WHERE TRIM(DESCRIPTION) IN ('REPO deal with Banks','REPO deal with Central Banks'))
LEFT JOIN SD_TRADING_BOOK@ftuat SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_COM_LOAN.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftuat SDENT ON SDENT.FBO_ID_NUM = FIN_COM_LOAN.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftuat SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_COM_LOAN.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftuat SDCP ON SDCP.FBO_ID_NUM= FIN_COM_LOAN.CPTY_FBO_ID_NUM
LEFT JOIN TT_CMLOAN_CASH_FLOWS@ftuat TTCMFL ON TRIM(TTCMFL.PARENT_FBO_ID_NUM) = TRIM(FIN_COM_LOAN.DEAL_NUM) and SIDE_SEQUENCE='1' and TTCMFL.SETTLEMENT_RATE is not null
--AND TRIM(TTCMFL.CASH_FLOW_LABEL) IS not NULL and  TRIM(TTCMFL.REFERENCE_RATE_VALUE) IS not  NULL 
WHERE D.MDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(D.REVDATE) IS NULL;



select DISTINCT 
TRIM(D.DEALNO)||'-'||D.PORT||'-'||D.BR||'-'||TRIM(C.CMNE)||'-'||D.DEALDATE||'-'||D.VDATE ||'-'||D.MDATE||'-'||D.AL ||'-'||D.CCY||'-'||D.CCYAMT||'-'||
D.BASIS||'-'||to_number(D.INTRATE)||'-'||D.SPREAD_8 ||'-'||D.RATECODE OPICS_DATA,
TRIM(D.DEALNO)||'-'||CASE WHEN trim(D.PORT)='PORT' THEN 'CORPORATE' ELSE 'INTERBANK' END||'-'||CASE WHEN TRIM(D.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END
||'-'||TRIM(C.CMNE)||'-'||D.DEALDATE||'-'||D.VDATE ||'-'||D.MDATE||'-'||CASE WHEN D.AL='L' THEN 'S' ELSE 'L' END ||'-'||D.CCY||'-'||D.CCYAMT||'-'||
SUBSTR(D.BASIS,1,1)||'/'||SUBSTR(D.BASIS,2,3)||'-'||to_number(D.INTRATE)||'-'||D.SPREAD_8 ||'-'||CASE WHEN D.RATECODE LIKE 'LI%' THEN 'FLOAT' ELSE 'FIXED'  END OPICS_CONV_DATA,
FIN_COM_LOAN.DEAL_IDENTIFIER||'-'||TRIM(SDTRBK.NAME)||'-'||TRIM(SDENT.NAME)||'-'||TRIM(SDCP.NAME)||'-'||FIN_COM_LOAN.DEAL_DATE||'-'||FIN_COM_LOAN.START_DATE||'-'||FIN_COM_LOAN.END_DATE ||'-'||
LONG_OR_SHORT ||'-'||FIN_COM_LOAN.CURRENCY_LIST||'-'||TTCMFL.NOTIONAL_AMOUNT_VALUE||'-'||TTCMFL.BASIS_CODE||'-'||TTCMFL.SETTLEMENT_RATE*100||'-'||TTCMFL.SPREAD_RATE*100||'-'||TTCMFL.CASH_FLOW_TYPE FIN_DATA,
CASE WHEN TRIM(D.DEALNO)||'-'||CASE WHEN trim(D.PORT)='PORT' THEN 'CORPORATE' ELSE 'INTERBANK' END||'-'||CASE WHEN TRIM(D.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END
||'-'||TRIM(C.CMNE)||'-'||D.DEALDATE||'-'||D.VDATE ||'-'||D.MDATE||'-'||CASE WHEN D.AL='L' THEN 'S' ELSE 'L' END ||'-'||D.CCY||'-'||D.CCYAMT||'-'||
SUBSTR(D.BASIS,1,1)||'/'||SUBSTR(D.BASIS,2,3)||'-'||to_number(D.INTRATE)||'-'||D.SPREAD_8 ||'-'||CASE WHEN D.RATECODE LIKE 'LI%' THEN 'FLOAT' ELSE 'FIXED'  END = FIN_COM_LOAN.DEAL_IDENTIFIER||'-'||TRIM(SDTRBK.NAME)||'-'||TRIM(SDENT.NAME)||'-'||TRIM(SDCP.NAME)||'-'||FIN_COM_LOAN.DEAL_DATE||'-'||FIN_COM_LOAN.START_DATE||'-'||FIN_COM_LOAN.END_DATE ||'-'||
LONG_OR_SHORT ||'-'||FIN_COM_LOAN.CURRENCY_LIST||'-'||TTCMFL.NOTIONAL_AMOUNT_VALUE||'-'||TTCMFL.BASIS_CODE||'-'||TTCMFL.SETTLEMENT_RATE*100||'-'||TTCMFL.SPREAD_RATE*100||'-'||TTCMFL.CASH_FLOW_TYPE THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM DLDT D 
INNER JOIN CUST C ON TRIM(D.CNO)=TRIM(C.CNO)
LEFT JOIN SCHD S ON TRIM(D.DEALNO)=TRIM(S.DEALNO) AND S.SCHDSEQ='001' AND D.BR=S.BR 
LEFT JOIN TT_COM_LOAN@FTMIG FIN_COM_LOAN ON TRIM(D.DEALNO)=TRIM(FIN_COM_LOAN.DEAL_IDENTIFIER) AND FIN_COM_LOAN.SUBTYPE_FBO_ID_NUM NOT IN (SELECT FBO_ID_NUM FROM SD_SUBTYPE@FTMIG WHERE TRIM(DESCRIPTION) IN ('REPO deal with Banks','REPO deal with Central Banks'))
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_COM_LOAN.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_COM_LOAN.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_COM_LOAN.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_COM_LOAN.CPTY_FBO_ID_NUM
LEFT JOIN TT_CMLOAN_CASH_FLOWS@FTMIG TTCMFL ON TRIM(TTCMFL.PARENT_FBO_ID_NUM) = TRIM(FIN_COM_LOAN.DEAL_NUM) and SIDE_SEQUENCE='1' --and TTCMFL.SETTLEMENT_RATE is not null
--AND TRIM(TTCMFL.CASH_FLOW_LABEL) IS not NULL and  TRIM(TTCMFL.REFERENCE_RATE_VALUE) IS not  NULL 
WHERE D.MDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(D.REVDATE) IS NULL

SELECT DISTINCT 
TRIM(D.DEALNO) OPICS_DEALNO,TRIM(FIN_COM_LOAN.DEAL_IDENTIFIER) FIN_DEALNO, CASE WHEN TRIM(D.DEALNO) = TRIM(FIN_COM_LOAN.DEAL_IDENTIFIER) THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
D.BR OPICS_BR, CASE WHEN TRIM(D.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN CASE WHEN TRIM(D.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
D.PORT OPICS_PORT ,CASE WHEN TRIM(D.PORT)='PORT' THEN 'CORPORATE' ELSE 'INTERBANK' END MAPPED_TRADING_BOOK,TRIM(SDTRBK.NAME) FIN_TRADING_BOOK, CASE WHEN CASE WHEN TRIM(D.PORT)='PORT' THEN 'CORPORATE' ELSE 'INTERBANK' END = TRIM(SDTRBK.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK,
D.PRODTYPE OPICS_PRODTYPE ,CASE when trim(C.CMNE)='CENTRALKWT' then 'CBKPLA' WHEN TRIM(C.CMNE)= 'ABKDXB' THEN 'INTGRP' WHEN D.BR='01' AND TRIM(D.PRODTYPE) IN ('LC','BC') THEN 'CORP' WHEN D.BR='01' AND TRIM(D.PRODTYPE) IN ('BB','LB') THEN 'BANK'
     WHEN D.BR='01' THEN 'ISLAMC'  WHEN D.BR='51' THEN CASE WHEN TRIM(D.PRODTYPE) IN ('LC','BC') THEN 'CORP' ELSE 'BANK' END END  MAPPED_SUBTYPE,TRIM(SDSBTY.NAME) FIN_SUBTYPE, 
CASE WHEN CASE when trim(C.CMNE)='CENTRALKWT' then 'CBKPLA' WHEN TRIM(C.CMNE)= 'ABKDXB' THEN 'INTGRP' WHEN D.BR='01' AND TRIM(D.PRODTYPE) IN ('LC','BC') THEN 'CORP' WHEN D.BR='01' AND TRIM(D.PRODTYPE) IN ('BB','LB') THEN 'BANK'
     WHEN D.BR='01' THEN 'ISLAMC'  WHEN D.BR='51' THEN CASE WHEN TRIM(D.PRODTYPE) IN ('LC','BC') THEN 'CORP' ELSE 'BANK' END END = TRIM(SDSBTY.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
D.DEALDATE OPICS_DEAL_DATE,FIN_COM_LOAN.DEAL_DATE,CASE WHEN D.DEALDATE  = FIN_COM_LOAN.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
D.VDATE OPICS_START_DATE,FIN_COM_LOAN.START_DATE FIN_START_DATE,CASE WHEN D.VDATE = FIN_COM_LOAN.START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
D.MDATE OPICS_END_DATE,FIN_COM_LOAN.END_DATE FIN_END_DATE ,CASE WHEN D.MDATE = FIN_COM_LOAN.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
D.BASIS OPICS_BASIS,SUBSTR(D.BASIS,1,1)||'/'||SUBSTR(D.BASIS,2,3) MAPPED_BASIS,TTCMFL.BASIS_CODE FIN_BASIS,CASE WHEN SUBSTR(D.BASIS,1,1)||'/'||SUBSTR(D.BASIS,2,3) = TTCMFL.BASIS_CODE THEN 'TRUE' ELSE 'FALSE' END MATCH_BASIS,
D.CCY OPICS_CCY,FIN_COM_LOAN.CURRENCY_LIST FIN_CCY ,CASE WHEN D.CCY = FIN_COM_LOAN.CURRENCY_LIST THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
D.AL OPICS_AL,CASE WHEN D.AL='L' THEN 'SHORT' ELSE 'LONG' END MAPPED_LONG_SHORT,CASE WHEN LONG_OR_SHORT='S' THEN 'SHORT' ELSE 'LONG' END FIN_LONG_SHORT ,CASE WHEN CASE WHEN D.AL='L' THEN 'SHORT' ELSE 'LONG' END  = CASE WHEN LONG_OR_SHORT='S' THEN 'SHORT' ELSE 'LONG' END THEN 'TRUE' ELSE 'FALSE' END MATCH_LONG_SHORT,
D.RATECODE OPICS_RATECODE,CASE WHEN D.AL='L' AND SUBSTR(D.RATECODE,1,2)='FI' THEN 'FIX/DEPO'
     WHEN D.AL='L' AND SUBSTR(D.RATECODE,1,2)!='FI' THEN 'FLT/DEPO'
     WHEN D.AL='A' AND SUBSTR(D.RATECODE,1,2)='FI' THEN 'FIX/LOAN'
     WHEN D.AL='A' AND SUBSTR(D.RATECODE,1,2)!='FI' THEN 'FLT/LOAN'
END  MAPPED_TYPE_STRING ,TYPE_STRING FIN_TYPE_STRING, CASE WHEN CASE WHEN D.AL='L' AND SUBSTR(D.RATECODE,1,2)='FI' THEN 'FIX/DEPO'
     WHEN D.AL='L' AND SUBSTR(D.RATECODE,1,2)!='FI' THEN 'FLT/DEPO'
     WHEN D.AL='A' AND SUBSTR(D.RATECODE,1,2)='FI' THEN 'FIX/LOAN'
     WHEN D.AL='A' AND SUBSTR(D.RATECODE,1,2)!='FI' THEN 'FLT/LOAN'
END= TYPE_STRING THEN 'TRUE' ELSE 'FALSE' END MATCH_TYPE_STRING,
D.CCYAMT OPICS_AMOUNT,TTCMFL.NOTIONAL_AMOUNT_VALUE FIN_AMOUNT,CASE WHEN ROUND(D.CCYAMT,3) = ROUND(TTCMFL.NOTIONAL_AMOUNT_VALUE,3) THEN 'TRUE' ELSE 'FALSE' END MATCH_AMOUNT,
CASE WHEN TRIM(D.RATECODE) like 'FIX%' THEN D.INTRATE END OPICS_RATE,CASE WHEN TRIM(D.RATECODE)like 'FIX%' THEN TTCMFL.SETTLEMENT_RATE*100 END  FIN_RATE,CASE WHEN ROUND(TRIM(CASE WHEN TRIM(D.RATECODE)like 'FIX%'THEN TO_NUMBER(D.INTRATE) ELSE 0 END ),8) =ROUND(CASE WHEN TRIM(D.RATECODE) like 'FIX%' THEN TTCMFL.SETTLEMENT_RATE*100 ELSE 0 END ,8) THEN 'TRUE' ELSE 'FALSE' END MATCH_RATE,
CASE WHEN TRIM(S.SMEANS)='BRDGE' THEN 'BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TO_CHAR(S.SACCT) END OPICS_PAY_NOSTRO,NOS.pay_nos,CASE WHEN nvl(CASE WHEN TRIM(S.SMEANS)='BRDGE' THEN 'BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TO_CHAR(S.SACCT) END,' ') = nvl(NOS.pay_nos,' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_PAY_NOSTRO,
CASE WHEN TRIM(S.SMEANS)='BRDGE' THEN 'BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TO_CHAR(S.SACCT) END OPICS_RECIEVE_NOSTRO,NOS.rec_nos,CASE WHEN nvl(CASE WHEN TRIM(S.SMEANS)='BRDGE' THEN 'BRIDGE_'||D.CCY||CASE WHEN TRIM(D.BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE TO_CHAR(S.SACCT) END,' ') = nvl(NOS.REC_nos,' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_REC_NOSTRO,
TRIM(D.DEALNO)||'-'||CASE WHEN TRIM(D.PORT)='PORT' THEN 'CORPORATE' ELSE 'INTERBANK' END||'-'||CASE WHEN TRIM(D.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END
||'-'||TRIM(C.CMNE)||'-'||D.DEALDATE||'-'||D.VDATE ||'-'||D.MDATE||'-'||CASE WHEN D.AL='L' THEN 'S' ELSE 'L' END ||'-'||D.CCY||'-'||D.CCYAMT||'-'||
SUBSTR(D.BASIS,1,1)||'/'||SUBSTR(D.BASIS,2,3)||'-'||TO_NUMBER(D.INTRATE)||'-'||D.SPREAD_8 ||'-'||CASE WHEN D.RATECODE LIKE 'LI%' THEN 'FLOAT' ELSE 'FIXED'  END OPICS_CONV_DATA,
FIN_COM_LOAN.DEAL_IDENTIFIER||'-'||TRIM(SDTRBK.NAME)||'-'||TRIM(SDENT.NAME)||'-'||TRIM(SDCP.NAME)||'-'||FIN_COM_LOAN.DEAL_DATE||'-'||FIN_COM_LOAN.START_DATE||'-'||FIN_COM_LOAN.END_DATE ||'-'||
LONG_OR_SHORT ||'-'||FIN_COM_LOAN.CURRENCY_LIST||'-'||TTCMFL.NOTIONAL_AMOUNT_VALUE||'-'||TTCMFL.BASIS_CODE||'-'||TTCMFL.SETTLEMENT_RATE*100||'-'||TTCMFL.SPREAD_RATE*100||'-'||TTCMFL.CASH_FLOW_TYPE FIN_DATA,
CASE WHEN TRIM(D.DEALNO)||'-'||CASE WHEN TRIM(D.PORT)='PORT' THEN 'CORPORATE' ELSE 'INTERBANK' END||'-'||CASE WHEN TRIM(D.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END
||'-'||TRIM(C.CMNE)||'-'||D.DEALDATE||'-'||D.VDATE ||'-'||D.MDATE||'-'||CASE WHEN D.AL='L' THEN 'S' ELSE 'L' END ||'-'||D.CCY||'-'||D.CCYAMT||'-'||
SUBSTR(D.BASIS,1,1)||'/'||SUBSTR(D.BASIS,2,3)||'-'||TO_NUMBER(D.INTRATE)||'-'||D.SPREAD_8 ||'-'||CASE WHEN D.RATECODE LIKE 'LI%' THEN 'FLOAT' ELSE 'FIXED'  END = FIN_COM_LOAN.DEAL_IDENTIFIER||'-'||TRIM(SDTRBK.NAME)||'-'||TRIM(SDENT.NAME)||'-'||TRIM(SDCP.NAME)||'-'||FIN_COM_LOAN.DEAL_DATE||'-'||FIN_COM_LOAN.START_DATE||'-'||FIN_COM_LOAN.END_DATE ||'-'||
LONG_OR_SHORT ||'-'||FIN_COM_LOAN.CURRENCY_LIST||'-'||TTCMFL.NOTIONAL_AMOUNT_VALUE||'-'||TTCMFL.BASIS_CODE||'-'||TTCMFL.SETTLEMENT_RATE*100||'-'||TTCMFL.SPREAD_RATE*100||'-'||TTCMFL.CASH_FLOW_TYPE THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM DLDT D 
INNER JOIN CUST C ON TRIM(D.CNO)=TRIM(C.CNO)
LEFT JOIN SCHD S ON TRIM(D.DEALNO)=TRIM(S.DEALNO) AND S.SCHDSEQ='001' AND D.BR=S.BR 
LEFT JOIN TT_COM_LOAN@FTMIG FIN_COM_LOAN ON TRIM(D.DEALNO)=TRIM(FIN_COM_LOAN.DEAL_IDENTIFIER) AND FIN_COM_LOAN.SUBTYPE_FBO_ID_NUM NOT IN (SELECT FBO_ID_NUM FROM SD_SUBTYPE@FTMIG WHERE TRIM(DESCRIPTION) IN ('REPO deal with Banks','REPO deal with Central Banks'))
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_COM_LOAN.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_COM_LOAN.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_COM_LOAN.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_COM_LOAN.CPTY_FBO_ID_NUM
LEFT JOIN TT_CMLOAN_CASH_FLOWS@FTMIG TTCMFL ON TRIM(TTCMFL.PARENT_FBO_ID_NUM) = TRIM(FIN_COM_LOAN.DEAL_NUM) AND SIDE_SEQUENCE='1' --and TTCMFL.SETTLEMENT_RATE is not null
--AND TRIM(TTCMFL.CASH_FLOW_LABEL) IS not NULL and  TRIM(TTCMFL.REFERENCE_RATE_VALUE) IS not  NULL 
LEFT JOIN (SELECT * FROM (
  SELECT distinct a.PARENT_FBO_ID_NUM,a.PARENT_FBO_ID_TYPE,A.IQ_CURRENCY PAY_CCY,a.NAME pay_nos ,B.IQ_CURRENCY REC_CCY,b.NAME rec_nos  FROM (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT') A
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT') B ON A.PARENT_FBO_ID_TYPE = B.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM
  )) NOS ON NOS.PARENT_FBO_ID_NUM = FIN_COM_LOAN.DEAL_NUM AND NOS.PARENT_FBO_ID_TYPE = FIN_COM_LOAN.DEAL_TYPE
WHERE D.MDATE>TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND TRIM(D.REVDATE) IS NULL 
