SELECT distinct a.LIMIT_PREFIX LEG_LIMIT_PREFIX,b.LIMIT_PREFIX FIN_LIMIT_PREFIX,CASE WHEN a.LIMIT_PREFIX = b.LIMIT_PREFIX THEN 'TRUE' ELSE 'FALSE' END MATCH_LIMIT_PREFIX,
 NOTE1||NOTE2||NOTE3 LEG_LIMIT_NOTES ,NOTES FIN_LIMIT_NOTES,CASE WHEN TRIM(NOTE1||NOTE2||NOTE3) = TRIM(NOTES) THEN 'TRUE' ELSE 'FALSE' END MATCH_LIMIT_NOTES FROM LIMIT_CORE_NOTES_O_TABLE a
left join CUSTOM.C_LLT_NOTES b on trim(a.LIMIT_PREFIX) = trim(b.LIMIT_PREFIX); 
