select ENTITY_ID LEG_ENTITY_ID,CHILDGROUPCODE FIN_ENTITY_ID, CASE WHEN  ENTITY_ID=CHILDGROUPCODE THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY_ID,
ENTITY_NAME LEG_ENTITY_NAME,CHILDGROUPNAME FIN_ENTITY_NAME, CASE WHEN ENTITY_NAME=CHILDGROUPNAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY_NAME,
GROUP_ID LEG_GROUP_ID,PARENTGROUPCODE FIN_GROUP_ID, CASE WHEN GROUP_ID = PARENTGROUPCODE THEN 'TRUE' ELSE 'FALSE' END MATCH_GROUP_ID,
GROUP_NAME LEG_GROUP_NAME,PARENTGROUPNAME FIN_GROUP_NAME, CASE WHEN GROUP_NAME=PARENTGROUPNAME THEN 'TRUE' ELSE 'FALSE' END MATCH_GROUP_NAME
from LIMIT_ENTITY_AND_GROUP_MAP a
left join CRMUSER.GROUPMAPPING b on a.ENTITY_ID = b.CHILDGROUPCODE and a.GROUP_ID = b.PARENTGROUPCODE; 
