========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
CustomerPayee_not.sql 
select DISTINCT
--NXT_PAYEE_LIST_ID01.NEXTVAL "PAYEE_LIST_ID",FIN_CP.PAYEE_LIST_ID,
       NVL(TRIM(O.USERID),CONVERT_CODES('ALPHABET','Y')) LEG_USERID,FIN_CP.USER_ID FIN_USER_ID,CASE WHEN TRIM(O.USERID) = FIN_CP.USER_ID THEN 'TRUE' ELSE 'FALSE' END MATCH_USERID,
       NVL(TRIM(IP.CUSTOMER_NO),CONVERT_CODES('ALPHABET','Y')) LEG_CUSTOMER_NO,FIN_CP.CORP_ID FIN_CORP_ID,CASE WHEN TRIM(IP.CUSTOMER_NO) = FIN_CP.CORP_ID THEN 'TRUE' ELSE 'FALSE' END MATCH_CUSTOMER_NO,
     --  NVL(PM.BNF_ID,CONVERT_CODES('DIGIT','Y')) LEG_BNF_ID,FIN_CP.BNF_ID FIN_BNF_ID,
       TRIM(IP.PAYEE_NAME) LEG_PAYEE_NAME,FIN_CP.BNF_NIC_NAME FIN_BNF_NIC_NAME,CASE WHEN NVL(TRIM(IP.PAYEE_NAME),CONVERT_CODES('ALPHABET','Y')) = FIN_CP.BNF_NIC_NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_PAYEE_NAME
     --  CB.CITY LEG_CITY,FIN_CP.FREE_FIELD_1 FIN_FREE_FIELD_1,
     --  CB.COUNTRY_CODE LEG_COUNTRY_CODE,FIN_CP.FREE_FIELD_2 FIN_FREE_FIELD_2
       FROM
(SELECT DISTINCT IP.* FROM INTERNET_PAYEE IP INNER JOIN( SELECT CUSTOMER_NO,TRIM(PAYEE_ACCOUNT) PAYEE_ACCOUNT,max(to_date(substr(DATE_AUTHORISED,1,19),
 'YYYY-MM-DD HH24:MI:SS')) MAX_DATE_AUTHORISED FROM 
 INTERNET_PAYEE where status='A' and IS_DELETED='0' GROUP BY CUSTOMER_NO,TRIM(PAYEE_ACCOUNT)) IP1 ON IP.CUSTOMER_NO=IP1.CUSTOMER_NO AND TRIM(IP.PAYEE_ACCOUNT)=TRIM(IP1.PAYEE_ACCOUNT)
 AND to_date(substr(IP.DATE_AUTHORISED,1,19),'YYYY-MM-DD HH24:MI:SS')  = IP1.MAX_DATE_AUTHORISED) IP 
  LEFT JOIN ( SELECT * FROM CORRESPONDENT_BANK WHERE ROWID IN (
  SELECT MAX(ROWID) FROM CORRESPONDENT_BANK GROUP BY UPPER(NAME),UPPER(CITY)
  )) CB ON UPPER(IP.PAYEE_BANK) = UPPER(CB.NAME) AND UPPER(IP.PAYEE_BRANCH) = UPPER(CB.CITY)
 -- LEFT JOIN PAYEE_MASTER_O_TABLE PM ON PM.CORP_ID = IP.CUSTOMER_NO AND PM.BNF_NAME = TRIM(IP.PAYEE_NAME)
  LEFT JOIN ONLINE_BANK_CUST_DTLS_UNQ_DATA O ON  O.CUSTOMER_NO=IP.CUSTOMER_NO 
  LEFT JOIN ECECUSER.CUSTOMER_PAYEE@EBUAT_DBLINK FIN_CP ON upper(trim(FIN_CP.USER_ID)) = upper(TRIM(O.USERID))AND trim(FIN_CP.CORP_ID) = TRIM(IP.CUSTOMER_NO)
   AND REPLACE(FIN_CP.BNF_NIC_NAME,PAYEE_LIST_ID,'') = TRIM(IP.PAYEE_NAME) AND FIN_CP.BANK_ID='01'
  WHERE   O.STATUS='A' AND TRIM(O.USERID) !='*CyberStar*' 
