========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
equity_defn_report.sql 
SELECT 
SECID OPICS_NAME,EQDN.NAME FINACLE_NAME,CASE WHEN TRIM(SECID) = TRIM(EQDN.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_SECID,
SECID OPICS_SECID,EQDN.INSTRUMENT_TYPE FINACLE_INSTRUMENT_TYPE,
SECID OPICS_SECID,EQDN.INSTRUMENT_SUBTYPE FINACLE_INSTRUMENT_SUBTYPE,
C.CMNE ISSUER_STRING,--@@@@@@@@
PRODTYPE ,SECID INSTRUMENT_CLASS_DATA_NAME,--
CCY OPICS_CCY,EQDN.ISSUE_CCY FINACLE_ISSUE_CCY,CASE WHEN CCY = EQDN.ISSUE_CCY THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
DESCR OPICS_DESCR,EQDN.DESCRIPTION FINACLE_DESCRIPTION,CASE WHEN TRIM(DESCR) = TRIM(EQDN.DESCRIPTION) THEN 'TRUE' ELSE 'FALSE' END MATCH_DESCR,
DENOM OPICS_DENOM,EQDN.MARKET_LOT FINACLE_MARKET_LOT,CASE WHEN TO_NUMBER(DENOM) = TO_NUMBER(EQDN.MARKET_LOT) THEN 'TRUE' ELSE 'FALSE' END MATCH_MARKET_LOT,
PARAMT OPICS_PARAMT,EQDN.FACE_VALUE FINACLE_FACE_VALUE,CASE WHEN TO_NUMBER(PARAMT) = TO_NUMBER(EQDN.FACE_VALUE) THEN 'TRUE' ELSE 'FALSE' END MATCH_FACE_VALUE,
MDATE  OPICS_MDATE,EQDN.DATE_TO_REALISE FINACLE_DATE_TO_REALISE,
C.UCCODE ,ISSUANCE_DATA_COI_FBO_ID_NUM--
FROM  SECM S
INNER JOIN CUST C ON TRIM(S.ISSUER)=TRIM(C.CNO)
LEFT JOIN FTABKBPD.SD_EQUITY_MF_DEFN@FTFC EQDN ON TRIM(S.SECID) = TRIM(EQDN.NAME)
WHERE S.PRODTYPE NOT IN ('F1','F2','FI','SB','TB','TL');




select TRIM(EQ_DEF.NAME) ||'-'||EQ_DEF.INSTRUMENT_TYPE ||'-'||TRIM(ISSUER_STRING) ||'-'||EQ_DEF.INSTRUMENT_SUBTYPE ||'-'||INSTRUMENT_CLASS_DATA_NAME ||'-'||
EQ_DEF.ISSUE_CCY ||'-'||EQ_DEF.FACE_VALUE OPICS_DATA,
EQDN.NAME ||'-'||EQDN.INSTRUMENT_TYPE ||'-'||SDCP.NAME ||'-'||EQDN.INSTRUMENT_SUBTYPE ||'-'||INCL.NAME ||'-'||
EQDN.ISSUE_CCY ||'-'||EQDN.FACE_VALUE FIN_DATA,
CASE WHEN TRIM(EQ_DEF.NAME) ||'-'||EQ_DEF.INSTRUMENT_TYPE ||'-'||TRIM(ISSUER_STRING) ||'-'||EQ_DEF.INSTRUMENT_SUBTYPE ||'-'||INSTRUMENT_CLASS_DATA_NAME ||'-'||
EQ_DEF.ISSUE_CCY ||'-'||EQ_DEF.FACE_VALUE = 
EQDN.NAME ||'-'||EQDN.INSTRUMENT_TYPE ||'-'||SDCP.NAME ||'-'||EQDN.INSTRUMENT_SUBTYPE ||'-'||INCL.NAME ||'-'||
EQDN.ISSUE_CCY ||'-'||EQDN.FACE_VALUE  THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
 from EQUITY_DEFN_O_TABLE EQ_DEF
LEFT JOIN SD_EQUITY_MF_DEFN@ftmig EQDN ON TRIM(EQ_DEF.NAME) LIKE TRIM(EQDN.NAME)||'%'
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= EQDN.ISSUER_FBO_ID_NUM
LEFT JOIN SD_INSTRUMENT_CLASS@FTMIG  INCL ON INCL.FBO_ID_NUM = INSTRUMENT_CLASS_FBO_ID_NUM



select distinct TRIM(EQ_DEF.NAME) ||'-'||EQ_DEF.INSTRUMENT_TYPE ||'-'||TRIM(ISSUER_STRING) ||'-'||EQ_DEF.INSTRUMENT_SUBTYPE ||'-'||INSTRUMENT_CLASS_DATA_NAME ||'-'||
EQ_DEF.ISSUE_CCY ||'-'||EQ_DEF.FACE_VALUE OPICS_DATA,
EQDN.NAME ||'-'||EQDN.INSTRUMENT_TYPE ||'-'||trim(SDCP.NAME) ||'-'||EQDN.INSTRUMENT_SUBTYPE ||'-'||INCL.NAME ||'-'||
EQDN.ISSUE_CCY ||'-'||EQDN.FACE_VALUE FIN_DATA,
CASE WHEN trim(
trim(substr(TRIM(EQ_DEF.NAME),1,15))  ||'-'||EQ_DEF.INSTRUMENT_TYPE ||'-'||TRIM(ISSUER_STRING) ||'-'||EQ_DEF.INSTRUMENT_SUBTYPE ||'-'||INSTRUMENT_CLASS_DATA_NAME ||'-'||
EQ_DEF.ISSUE_CCY ||'-'||EQ_DEF.FACE_VALUE
)
 = 
trim(
EQDN.NAME ||'-'||EQDN.INSTRUMENT_TYPE ||'-'||trim(SDCP.NAME) ||'-'||EQDN.INSTRUMENT_SUBTYPE ||'-'||INCL.NAME ||'-'||
EQDN.ISSUE_CCY ||'-'||EQDN.FACE_VALUE
)
  THEN 'TRUE' ELSE 'FALSE' END
 MATCH_DATA
 from EQUITY_DEFN_O_TABLE EQ_DEF
LEFT JOIN SD_EQUITY_MF_DEFN@ftmig EQDN ON replace(TRIM(EQ_DEF.DESCRIPTION),' ','') LIKE replace(TRIM(EQDN.DESCRIPTION),' ','')||'%'
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= EQDN.ISSUER_FBO_ID_NUM
LEFT JOIN SD_INSTRUMENT_CLASS@FTMIG  INCL ON INCL.FBO_ID_NUM = INSTRUMENT_CLASS_FBO_ID_NUM


select DISTINCT 
TRIM(EQ_DEF.NAME) OPICS_SECID ,EQDN.NAME FIN_SECID,CASE WHEN TRIM(EQ_DEF.NAME) = EQDN.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SECID,
TRIM(EQ_DEF.DESCRIPTION) OPICS_DESCRIPTION ,EQDN.DESCRIPTION FIN_DESCRIPTION,CASE WHEN TRIM(EQ_DEF.DESCRIPTION) = EQDN.DESCRIPTION THEN 'TRUE' ELSE 'FALSE' END MATCH_DESCRIPTION,
EQ_DEF.INSTRUMENT_TYPE MAPPED_INSTRUMENT_TYPE ,EQDN.INSTRUMENT_TYPE FIN_INSTRUMENT_TYPE,CASE WHEN EQ_DEF.INSTRUMENT_TYPE  = EQDN.INSTRUMENT_TYPE THEN 'TRUE' ELSE 'FALSE' END MATCH_INSTRUMENT_TYPE,
TRIM(ISSUER_STRING) OPICS_CPTY,trim(SDCP.NAME) FIN_CPTY,CASE WHEN TRIM(ISSUER_STRING) = trim(SDCP.NAME)THEN 'TRUE' ELSE 'FALSE' END MATCH_CPTY,
PORT OPICS_PORT,EQ_DEF.INSTRUMENT_SUBTYPE MAPPED_INSTRUMENT_SUBTYPEE,EQDN.INSTRUMENT_SUBTYPE FIN_INSTRUMENT_SUBTYPE,CASE WHEN EQ_DEF.INSTRUMENT_SUBTYPE = EQDN.INSTRUMENT_SUBTYPE THEN 'TRUE' ELSE 'FALSE' END MATCH_INSTRUMENT_SUBTYPE,
INSTRUMENT_CLASS_DATA_NAME MAPPED_NSTRUMENT_CLASS ,INCL.NAME FIN_NSTRUMENT_CLASS ,CASE WHEN INSTRUMENT_CLASS_DATA_NAME = INCL.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_NSTRUMENT_CLASS,
EQ_DEF.ISSUE_CCY OPICS_CCY,EQDN.ISSUE_CCY FIN_CCY,CASE WHEN EQ_DEF.ISSUE_CCY = EQDN.ISSUE_CCY THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
EQ_DEF.FACE_VALUE OPICS_QTY,EQDN.FACE_VALUE FIN_QTY,CASE WHEN EQ_DEF.FACE_VALUE = EQDN.FACE_VALUE THEN 'TRUE' ELSE 'FALSE' END MATCH_QTY,
TRIM(EQ_DEF.NAME) ||'-'||EQ_DEF.INSTRUMENT_TYPE ||'-'||TRIM(ISSUER_STRING) ||'-'||EQ_DEF.INSTRUMENT_SUBTYPE ||'-'||INSTRUMENT_CLASS_DATA_NAME ||'-'||
EQ_DEF.ISSUE_CCY ||'-'||EQ_DEF.FACE_VALUE OPICS_DATA,
EQDN.NAME ||'-'||EQDN.INSTRUMENT_TYPE ||'-'||trim(SDCP.NAME) ||'-'||EQDN.INSTRUMENT_SUBTYPE ||'-'||INCL.NAME ||'-'||
EQDN.ISSUE_CCY ||'-'||EQDN.FACE_VALUE FIN_DATA,
CASE WHEN trim(
trim(substr(TRIM(EQ_DEF.NAME),1,15))  ||'-'||EQ_DEF.INSTRUMENT_TYPE ||'-'||TRIM(ISSUER_STRING) ||'-'||EQ_DEF.INSTRUMENT_SUBTYPE ||'-'||INSTRUMENT_CLASS_DATA_NAME ||'-'||
EQ_DEF.ISSUE_CCY ||'-'||EQ_DEF.FACE_VALUE
)
 = 
trim(
EQDN.NAME ||'-'||EQDN.INSTRUMENT_TYPE ||'-'||trim(SDCP.NAME) ||'-'||EQDN.INSTRUMENT_SUBTYPE ||'-'||INCL.NAME ||'-'||
EQDN.ISSUE_CCY ||'-'||EQDN.FACE_VALUE
)
  THEN 'TRUE' ELSE 'FALSE' END
 MATCH_DATA
 from EQUITY_DEFN_O_TABLE EQ_DEF
LEFT JOIN SD_EQUITY_MF_DEFN@ftmig EQDN ON replace(TRIM(EQ_DEF.DESCRIPTION),' ','') LIKE replace(TRIM(EQDN.DESCRIPTION),' ','')||'%' and ACTION!='DLT'
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= EQDN.ISSUER_FBO_ID_NUM
LEFT JOIN SD_INSTRUMENT_CLASS@FTMIG  INCL ON INCL.FBO_ID_NUM = INSTRUMENT_CLASS_FBO_ID_NUM
LEFT JOIN(SELECT * FROM TR_EQU_AND_SEC_OUTSTANDING WHERE TRIM(TYPE)='Investments' AND TRIM(NETQTY) != 0 AND TRIM(NETQTY) IS NOT NULL AND CASE WHEN TRIM(SECID)='ABK TREASURY' 
AND TRIM(PORT) !='TS' THEN 0 ELSE 1  END = 1) E ON TRIM(E.SECID) =  TRIM(EQ_DEF.NAME) 
