========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
equity_deal.sql 

SELECT EQ_DEAL.DEAL_IDENTIFIER ||'-'||EQ_DEAL.EQUITY_MF_DEFN_NAME ||'-'||TRIM(ENTITY_NAME) ||'-'||EQ_DEAL.SUBTYPE ||'-'||TRIM(EQ_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(EQ_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||EQ_DEAL.BUY_OR_SELL ||'-'||
EQ_DEAL.CURRENCY_STRING ||'-'||ROUND(EQ_DEAL.PRICE_STRING,5) ||'-'||EQ_DEAL.QTY_TRADED OPICS_DATA,
EQDL.DEAL_IDENTIFIER ||'-'||trim(EQDEF.NAME) ||'-'||trim(SDENT.NAME) ||'-'||trim(SDSBTY.NAME) ||'-'||trim(SDCP.NAME) ||'-'||EQDL.DEAL_DATE||'-'||CASE WHEN EQDL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||EQDL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(EQDL.PRICE_STRING,',',''),5) ||'-'||EQDL.QTY_TRADED FIN_DATA,
CASE WHEN trim(
EQ_DEAL.DEAL_IDENTIFIER ||'-'||trim(substr(EQ_DEAL.EQUITY_MF_DEFN_NAME,1,15)) ||'-'||TRIM(ENTITY_NAME) ||'-'||EQ_DEAL.SUBTYPE ||'-'||TRIM(EQ_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(EQ_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||
EQ_DEAL.BUY_OR_SELL ||'-'||EQ_DEAL.CURRENCY_STRING ||'-'||ROUND(EQ_DEAL.PRICE_STRING,5) ||'-'||EQ_DEAL.QTY_TRADED
) 
=
trim(
EQDL.DEAL_IDENTIFIER ||'-'||trim(EQDEF.NAME) ||'-'||trim(SDENT.NAME) ||'-'||trim(SDSBTY.NAME) ||'-'||trim(SDCP.NAME) ||'-'||EQDL.DEAL_DATE||'-'||CASE WHEN EQDL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||EQDL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(EQDL.PRICE_STRING,',',''),5) ||'-'||EQDL.QTY_TRADED
)
 THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM EQUITY_MF_O_TABLE EQ_DEAL
LEFT JOIN TT_EQUITY_MF@FTMIG EQDL ON TRIM(EQ_DEAL.DEAL_IDENTIFIER) = TRIM(EQDL.DEAL_IDENTIFIER)
LEFT JOIN SD_EQUITY_MF_DEFN@FTMIG EQDEF ON EQUITY_MF_DEFN_FBO_ID_NUM = FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = EQDL.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = EQDL.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM= EQDL.CPTY_FBO_ID_NUM


SELECT 
EQ_DEAL.DEAL_IDENTIFIER MAPPED_DEALNO,EQDL.DEAL_IDENTIFIER FIN_DEALNO, CASE WHEN EQ_DEAL.DEAL_IDENTIFIER = EQDL.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
EQ_DEAL.EQUITY_MF_DEFN_NAME OPICS_SECID,trim(EQDEF.NAME) FIN_SECID, CASE WHEN EQ_DEAL.EQUITY_MF_DEFN_NAME  = trim(EQDEF.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_SECID,
CASE WHEN TRIM(ENTITY_NAME)='ABKKWT' THEN '51' ELSE '01' END OPICS_ENTITY,TRIM(SDENT.NAME) MAPPED_ENTITY, TRIM(SDENT.NAME) FIN_ENTITY, CASE WHEN  TRIM(ENTITY_NAME) = TRIM(SDENT.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
PORT OPICS_PORT,EQ_DEAL.SUBTYPE MAPPED_SUBTYPE,trim(SDSBTY.NAME) FIN_SUBTYPE ,CASE WHEN  TRIM(EQ_DEAL.SUBTYPE) = trim(SDSBTY.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
COUNTERPARTY_STRING OPICS_COUNTERPARTY,trim(SDCP.NAME) FIN_COUNTERPARTY,CASE WHEN  TRIM(COUNTERPARTY_STRING) = trim(SDCP.NAME)  THEN 'TRUE' ELSE 'FALSE' END MATCH_COUNTERPARTY,
TO_DATE(EQ_DEAL.DEAL_DATE,'DD-MM-YYYY') MAPPED_DEAL_DATE,EQDL.DEAL_DATE FIN_DEAL_DATE,CASE WHEN TO_DATE(EQ_DEAL.DEAL_DATE,'DD-MM-YYYY')  = EQDL.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
EQ_DEAL.BUY_OR_SELL OPICS_BUY_OR_SELL,CASE WHEN EQDL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END FIN_BUY_OR_SELL ,CASE WHEN EQ_DEAL.BUY_OR_SELL  =CASE WHEN EQDL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END THEN 'TRUE' ELSE 'FALSE' END MATCH_BUY_OR_SELL,
ROUND(EQ_DEAL.PRICE_STRING,5) OPICS_AVG_PRICE,ROUND(REPLACE(EQDL.PRICE_STRING,',',''),5) FIN_PRICE,CASE WHEN ROUND(EQ_DEAL.PRICE_STRING,5)  = ROUND(REPLACE(EQDL.PRICE_STRING,',',''),5) THEN 'TRUE' ELSE 'FALSE' END MATCH_PRICE,
EQ_DEAL.QTY_TRADED OPICS_QTY, EQDL.QTY_TRADED FIN_QTY,CASE WHEN  EQ_DEAL.QTY_TRADED =  EQDL.QTY_TRADED  THEN 'TRUE' ELSE 'FALSE' END MATCH_QTY,
EQ_DEAL.DEAL_IDENTIFIER ||'-'||EQ_DEAL.EQUITY_MF_DEFN_NAME ||'-'||TRIM(ENTITY_NAME) ||'-'||EQ_DEAL.SUBTYPE ||'-'||TRIM(EQ_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(EQ_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||EQ_DEAL.BUY_OR_SELL ||'-'||
EQ_DEAL.CURRENCY_STRING ||'-'||ROUND(EQ_DEAL.PRICE_STRING,5) ||'-'||EQ_DEAL.QTY_TRADED OPICS_DATA,
EQDL.DEAL_IDENTIFIER ||'-'||trim(EQDEF.NAME) ||'-'||trim(SDENT.NAME) ||'-'||trim(SDSBTY.NAME) ||'-'||trim(SDCP.NAME) ||'-'||EQDL.DEAL_DATE||'-'||CASE WHEN EQDL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||EQDL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(EQDL.PRICE_STRING,',',''),5) ||'-'||EQDL.QTY_TRADED FIN_DATA,
CASE WHEN trim(
EQ_DEAL.DEAL_IDENTIFIER ||'-'||trim(substr(EQ_DEAL.EQUITY_MF_DEFN_NAME,1,15)) ||'-'||TRIM(ENTITY_NAME) ||'-'||EQ_DEAL.SUBTYPE ||'-'||TRIM(EQ_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(EQ_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||
EQ_DEAL.BUY_OR_SELL ||'-'||EQ_DEAL.CURRENCY_STRING ||'-'||ROUND(EQ_DEAL.PRICE_STRING,5) ||'-'||EQ_DEAL.QTY_TRADED
) 
=
trim(
EQDL.DEAL_IDENTIFIER ||'-'||trim(EQDEF.NAME) ||'-'||trim(SDENT.NAME) ||'-'||trim(SDSBTY.NAME) ||'-'||trim(SDCP.NAME) ||'-'||EQDL.DEAL_DATE||'-'||CASE WHEN EQDL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||EQDL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(EQDL.PRICE_STRING,',',''),5) ||'-'||EQDL.QTY_TRADED
)
 THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM EQUITY_MF_O_TABLE EQ_DEAL
LEFT JOIN TT_EQUITY_MF@FTMIG EQDL ON TRIM(EQ_DEAL.DEAL_IDENTIFIER) = TRIM(EQDL.DEAL_IDENTIFIER)
LEFT JOIN SD_EQUITY_MF_DEFN@FTMIG EQDEF ON EQUITY_MF_DEFN_FBO_ID_NUM = FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = EQDL.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = EQDL.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM= EQDL.CPTY_FBO_ID_NUM
LEFT JOIN(SELECT * FROM TR_EQU_AND_SEC_OUTSTANDING WHERE TRIM(TYPE)='Investments' AND TRIM(NETQTY) != 0 AND TRIM(NETQTY) IS NOT NULL AND CASE WHEN TRIM(SECID)='ABK TREASURY' 
AND TRIM(PORT) !='TS' THEN 0 ELSE 1  END = 1) E ON TRIM(E.SECID) =  TRIM(EQ_DEAL.EQUITY_MF_DEFN_NAME)


SELECT 
EQ_DEAL.DEAL_IDENTIFIER MAPPED_DEALNO,EQDL.DEAL_IDENTIFIER FIN_DEALNO, CASE WHEN EQ_DEAL.DEAL_IDENTIFIER = EQDL.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
EQ_DEAL.EQUITY_MF_DEFN_NAME OPICS_SECID,trim(EQDEF.NAME) FIN_SECID, CASE WHEN EQ_DEAL.EQUITY_MF_DEFN_NAME  = trim(EQDEF.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_SECID,
CASE WHEN TRIM(ENTITY_NAME)='ABKKWT' THEN '51' ELSE '01' END OPICS_ENTITY,TRIM(SDENT.NAME) MAPPED_ENTITY, TRIM(SDENT.NAME) FIN_ENTITY, CASE WHEN  TRIM(ENTITY_NAME) = TRIM(SDENT.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
PORT OPICS_PORT,EQ_DEAL.SUBTYPE MAPPED_SUBTYPE,trim(SDSBTY.NAME) FIN_SUBTYPE ,CASE WHEN  TRIM(EQ_DEAL.SUBTYPE) = trim(SDSBTY.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
COUNTERPARTY_STRING OPICS_COUNTERPARTY,trim(SDCP.NAME) FIN_COUNTERPARTY,CASE WHEN  TRIM(COUNTERPARTY_STRING) = trim(SDCP.NAME)  THEN 'TRUE' ELSE 'FALSE' END MATCH_COUNTERPARTY,
TO_DATE(EQ_DEAL.DEAL_DATE,'DD-MM-YYYY') MAPPED_DEAL_DATE,EQDL.DEAL_DATE FIN_DEAL_DATE,CASE WHEN TO_DATE(EQ_DEAL.DEAL_DATE,'DD-MM-YYYY')  = EQDL.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
EQ_DEAL.BUY_OR_SELL OPICS_BUY_OR_SELL,CASE WHEN EQDL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END FIN_BUY_OR_SELL ,CASE WHEN EQ_DEAL.BUY_OR_SELL  =CASE WHEN EQDL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END THEN 'TRUE' ELSE 'FALSE' END MATCH_BUY_OR_SELL,
ROUND(EQ_DEAL.PRICE_STRING,5) OPICS_AVG_PRICE,ROUND(REPLACE(EQDL.PRICE_STRING,',',''),5) FIN_PRICE,CASE WHEN ROUND(EQ_DEAL.PRICE_STRING,5)  = ROUND(REPLACE(EQDL.PRICE_STRING,',',''),5) THEN 'TRUE' ELSE 'FALSE' END MATCH_PRICE,
nvl(EQ_DEAL.QTY_TRADED,round(EQ_DEAL.SETTLEMENT/EQ_DEAL.PRICE_STRING,0)) OPICS_QTY, EQDL.QTY_TRADED FIN_QTY,CASE WHEN  nvl(EQ_DEAL.QTY_TRADED,round(EQ_DEAL.SETTLEMENT/EQ_DEAL.PRICE_STRING,0)) =  EQDL.QTY_TRADED  THEN 'TRUE' ELSE 'FALSE' END MATCH_QTY,
EQ_DEAL.DEAL_IDENTIFIER ||'-'||EQ_DEAL.EQUITY_MF_DEFN_NAME ||'-'||TRIM(ENTITY_NAME) ||'-'||EQ_DEAL.SUBTYPE ||'-'||TRIM(EQ_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(EQ_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||EQ_DEAL.BUY_OR_SELL ||'-'||
EQ_DEAL.CURRENCY_STRING ||'-'||ROUND(EQ_DEAL.PRICE_STRING,5) ||'-'||nvl(EQ_DEAL.QTY_TRADED,round(EQ_DEAL.SETTLEMENT/EQ_DEAL.PRICE_STRING,0)) OPICS_DATA,
EQDL.DEAL_IDENTIFIER ||'-'||trim(EQDEF.NAME) ||'-'||trim(SDENT.NAME) ||'-'||trim(SDSBTY.NAME) ||'-'||trim(SDCP.NAME) ||'-'||EQDL.DEAL_DATE||'-'||CASE WHEN EQDL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||EQDL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(EQDL.PRICE_STRING,',',''),5) ||'-'||EQDL.QTY_TRADED FIN_DATA,
CASE WHEN trim(
EQ_DEAL.DEAL_IDENTIFIER ||'-'||trim(substr(EQ_DEAL.EQUITY_MF_DEFN_NAME,1,15)) ||'-'||TRIM(ENTITY_NAME) ||'-'||EQ_DEAL.SUBTYPE ||'-'||TRIM(EQ_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(EQ_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||
EQ_DEAL.BUY_OR_SELL ||'-'||EQ_DEAL.CURRENCY_STRING ||'-'||ROUND(EQ_DEAL.PRICE_STRING,5) ||'-'||nvl(EQ_DEAL.QTY_TRADED,round(EQ_DEAL.SETTLEMENT/EQ_DEAL.PRICE_STRING,0))
) 
=
trim(
EQDL.DEAL_IDENTIFIER ||'-'||trim(EQDEF.NAME) ||'-'||trim(SDENT.NAME) ||'-'||trim(SDSBTY.NAME) ||'-'||trim(SDCP.NAME) ||'-'||EQDL.DEAL_DATE||'-'||CASE WHEN EQDL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||EQDL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(EQDL.PRICE_STRING,',',''),5) ||'-'||EQDL.QTY_TRADED
)
 THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM EQUITY_MF_O_TABLE EQ_DEAL
LEFT JOIN TT_EQUITY_MF@FTMIG EQDL ON  TRIM(EQDL.DEAL_IDENTIFIER) like TRIM(EQ_DEAL.DEAL_IDENTIFIER) ||'%'  
LEFT JOIN SD_EQUITY_MF_DEFN@FTMIG EQDEF ON EQUITY_MF_DEFN_FBO_ID_NUM = FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = EQDL.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = EQDL.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM= EQDL.CPTY_FBO_ID_NUM
LEFT JOIN(SELECT * FROM TR_EQU_AND_SEC_OUTSTANDING WHERE TRIM(TYPE)='Investments' AND TRIM(NETQTY) != 0 AND TRIM(NETQTY) IS NOT NULL AND CASE WHEN TRIM(SECID)='ABK TREASURY' 
AND TRIM(PORT) !='TS' THEN 0 ELSE 1  END = 1) E ON TRIM(E.SECID) =  TRIM(EQ_DEAL.EQUITY_MF_DEFN_NAME) 
