========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
fx_outright_deals_report.sql 
select 
F.DEALDATE OPICS_DEALDATE,FIN_FX_OUTRIGHT.DEAL_DATE FINACLE_DEAL_DATE ,CASE WHEN TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD') = FIN_FX_OUTRIGHT.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALDATE,
F.DEALNO OPICS_DEALNO, FIN_FX_OUTRIGHT.DEAL_IDENTIFIER FINACLE_DEAL_IDENTIFIER, CASE WHEN TRIM(F.DEALNO) = TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER) THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
F.PORT OPICS_PORT,SDTRBK.NAME FINACLE_TRADING_BOOK, CASE WHEN CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK, 
F.PORT OPICS_PORT,SDSBTY.NAME FINACLE_SUBTYPE, CASE WHEN CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
F.BR OPICS_BR,SDENT.NAME FINACLE_ENTITY_NAME,CASE WHEN CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END like  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY_NAME,
C.CMNE OPICS_CMNE,SDCP.name FINACLE_MAIN_LEG_CPTY,CASE WHEN TRIM(C.CMNE) = TRIM(SDCP.name) THEN 'TRUE' ELSE 'FALSE' END MATCH_MAIN_LEG_CPTY,
F.CCYTERMS OPICS_CCYTERMS ,F.CCY OPICS_CCY,F.CTRCCY OPICS_CTRCCY,TTFXL.CCY_PAIR FINACLE_MAIN_LEG_CCY_PAIR,CASE when case when F.CCYTERMS='M' then F.CCY||'/'||F.CTRCCY else F.CTRCCY||'/'||F.CCY end = TTFXL.CCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR,
--F.DISAGGCCY OPICS_DISAGGCCY, FIN_FX_OUTRIGHT.DCO_CURRENCY,
--F.PS OPICS_PS,--F.CCYTERMS,FIN_FX_SPOT.MAIN_LEG_FX_BUY_SELL,--*****
F.CCYTERMS OPICS_CCYTERMS,F.CCYAMT OPICS_CCYAMT,case when F.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end  FIN_MAIN_LEG_CCY_ONE_AMOUNT,
    CASE WHEN abs(round(F.CCYAMT,2)) = round(case when F.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_AMOUNT,
F.CCYRATE_8 OPICS_CCYRATE_8,TTFXFL.RATE FIN_MAIN_LEG_MARKET_FWD_RATE,CASE WHEN F.CCYRATE_8 = TTFXFL.RATE THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYRATE,
F.CCYTERMS OPICS_CCYTERMS,F.CTRAMT OPICS_CCYAMT,case when F.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end  FIN_MAIN_LEG_CCY_TWO_AMOUNT,
    CASE WHEN abs(round(F.CTRAMT,2)) = round(case when F.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTR_AMOUNT,
F.VDATE,TTFXFL.VALUE_DATE_ONE FIN_MAIN_LEG_VALUE_DATE_ONE,CASE WHEN TO_DATE(TRIM(F.VDATE),'YYYY-MM-DD') = TTFXFL.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END FIN_MAIN_LEG_VALUE_DATE_ONE
from FXDH F  
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(F.CUST)
LEFT JOIN TT_FXP_DEAL@ftuat FIN_FX_OUTRIGHT on  TRIM(f.DEALNO) = TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER) AND FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@ftuat SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftuat SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftuat SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftuat SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@ftuat TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM
LEFT JOIN (SELECT * FROM (
  SELECT * FROM  TT_FXP_LEG@ftuat A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@ftuat GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM)
  )) TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(PRODCODE)!='CCS' AND TRIM(REVDATE) IS NULL AND TRIM(SWAPDEAL)='0' AND  SPOTFWDIND='F'
AND TRIM(C.CMNE)!='CCIRS' and trim(PORT)!='EQFX'
;



select distinct 
F.DEALDATE||'-'||F.DEALNO ||'-'||F.PORT||'-'||F.PORT||'-'||F.BR||'-'||C.CMNE||'-'||F.CCYTERMS ||'-'||F.CCY||'-'||F.CTRCCY||'-'||F.CCYTERMS||'-'||F.CCYAMT||'-'||F.CCYRATE_8||'-'||
F.CCYTERMS||'-'||F.CTRAMT||'-'||F.VDATE OPICS_DATA,
TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(F.DEALNO) ||'-'||CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||
CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end||'-'||CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||
TRIM(C.CMNE)||'-'||case when F.CCYTERMS='M' then F.CCY||'/'||F.CTRCCY else F.CTRCCY||'/'||F.CCY end||'-'||abs(round(F.CCYAMT,2))||'-'||ROUND(F.CCYRATE_8,3)||'-'||abs(round(F.CTRAMT,2))||'-'||TO_DATE(TRIM(F.VDATE),'YYYY-MM-DD') CONV_OPICS_DATA,
FIN_FX_OUTRIGHT.DEAL_DATE ||'-'||TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME ||'-'||TRIM(SDCP.name)||'-'||
TTFXL.CCY_PAIR ||'-'||ROUND(case when F.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2)||'-'|| ROUND(case when TTFXL.CCY_PAIR='JPY/KWD' THEN (TTFXL.MARKET_SPOT_RATE*100) ELSE TTFXL.MARKET_SPOT_RATE END,3)||'-'||
 ROUND(case when F.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2)||'-'|| TTFXFL.VALUE_DATE_ONE FIN_DATA,
 CASE WHEN TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(F.DEALNO) ||'-'||CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||
CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end||'-'||CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||
TRIM(C.CMNE)||'-'||case when F.CCYTERMS='M' then F.CCY||'/'||F.CTRCCY else F.CTRCCY||'/'||F.CCY end||'-'||abs(round(F.CCYAMT,2))||'-'||ROUND(F.CCYRATE_8,3)||'-'||abs(round(F.CTRAMT,2))||'-'||TO_DATE(TRIM(F.VDATE),'YYYY-MM-DD') = 
FIN_FX_OUTRIGHT.DEAL_DATE ||'-'||TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME ||'-'||TRIM(SDCP.name)||'-'||
TTFXL.CCY_PAIR ||'-'||ROUND(case when F.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2)||'-'|| ROUND(case when TTFXL.CCY_PAIR='JPY/KWD' THEN (TTFXL.MARKET_SPOT_RATE*100) ELSE TTFXL.MARKET_SPOT_RATE END,3) ||'-'||
 ROUND(case when F.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2)||'-'|| TTFXFL.VALUE_DATE_ONE
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
from FXDH F  
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(F.CUST)
LEFT JOIN TT_FXP_DEAL@FTMIG FIN_FX_OUTRIGHT on  TRIM(f.DEALNO) = TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER) AND FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM and PARENT_FBO_ID_VER='1' and PARENT_FBO_MIN_VER='1'
LEFT JOIN (SELECT * FROM (
  SELECT * FROM  TT_FXP_LEG@FTMIG A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@FTMIG GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM)
  )) TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(PRODCODE)!='CCS' AND TRIM(REVDATE) IS NULL AND TRIM(SWAPDEAL)='0' AND  SPOTFWDIND='F'
AND TRIM(C.CMNE)!='CCIRS' and trim(PORT)!='EQFX'
;


select distinct
F.DEALDATE||'-'||F.DEALNO ||'-'||F.PORT||'-'||F.PORT||'-'||F.BR||'-'||C.CMNE||'-'||F.CCYTERMS ||'-'||F.CCY||'-'||F.CTRCCY||'-'||F.CCYTERMS||'-'||F.CCYAMT||'-'||F.CCYRATE_8||'-'||
F.CCYTERMS||'-'||F.CTRAMT||'-'||F.VDATE OPICS_DATA,
TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(F.DEALNO) ||'-'||CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||
CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end||'-'||CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||
TRIM(C.CMNE)||'-'||case when F.CCYTERMS='M' then F.CCY||'/'||F.CTRCCY else F.CTRCCY||'/'||F.CCY end||'-'||abs(round(F.CCYAMT,2))||'-'||ROUND(F.CCYRATE_8,3)||'-'||abs(round(F.CTRAMT,2))||'-'||TO_DATE(TRIM(F.VDATE),'YYYY-MM-DD') CONV_OPICS_DATA,
FIN_FX_OUTRIGHT.DEAL_DATE ||'-'||TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME ||'-'||TRIM(SDCP.name)||'-'||
TTFXL.CCY_PAIR ||'-'||ROUND(case when F.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2)||'-'|| ROUND(case when TTFXL.CCY_PAIR='JPY/KWD' THEN (TTFXL.MARKET_SPOT_RATE) ELSE TTFXL.MARKET_SPOT_RATE END,3)||'-'||
 ROUND(case when F.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2)||'-'|| TTFXFL.VALUE_DATE_ONE FIN_DATA,
 CASE WHEN TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(F.DEALNO) ||'-'||CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||
CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end||'-'||CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||
TRIM(C.CMNE)||'-'||case when F.CCYTERMS='M' then F.CCY||'/'||F.CTRCCY else F.CTRCCY||'/'||F.CCY end||'-'||abs(round(F.CCYAMT,2))||'-'||ROUND(F.CCYRATE_8,3)||'-'||abs(round(F.CTRAMT,2))||'-'||TO_DATE(TRIM(F.VDATE),'YYYY-MM-DD') = 
FIN_FX_OUTRIGHT.DEAL_DATE ||'-'||TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME ||'-'||TRIM(SDCP.name)||'-'||
TTFXL.CCY_PAIR ||'-'||ROUND(case when F.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2)||'-'|| ROUND(case when TTFXL.CCY_PAIR='JPY/KWD' THEN (TTFXL.MARKET_SPOT_RATE) ELSE TTFXL.MARKET_SPOT_RATE END,3) ||'-'||
 ROUND(case when F.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2)||'-'|| TTFXFL.VALUE_DATE_ONE
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
from FXDH F  
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(F.CUST)
LEFT JOIN TT_FXP_DEAL@FTMIG FIN_FX_OUTRIGHT on  TRIM(f.DEALNO) = TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER) AND FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM and PARENT_FBO_ID_VER='1' and PARENT_FBO_MIN_VER='1'
LEFT JOIN (SELECT * FROM (
  SELECT * FROM  TT_FXP_LEG@FTMIG A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@FTMIG GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM)
  )) TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(PRODCODE)!='CCS' AND TRIM(REVDATE) IS NULL AND TRIM(SWAPDEAL)='0' AND  SPOTFWDIND='F'
AND TRIM(C.CMNE)!='CCIRS' and trim(PORT)!='EQFX'
;

SELECT DISTINCT 
F.DEALNO OPICS_DEALNO ,FIN_FX_OUTRIGHT.DEAL_IDENTIFIER FIN_DEAL_IDENTIFIER, CASE WHEN TRIM(F.DEALNO) = FIN_FX_OUTRIGHT.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,TO_CHAR(FIN_FX_OUTRIGHT.DEAL_NUM) FIN_DEAL_NUM,
F.BR OPICS_BR, CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD') OPICS_DEAL_DATE ,FIN_FX_OUTRIGHT.DEAL_DATE FIN_DEAL_DATE,CASE WHEN TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD') = FIN_FX_OUTRIGHT.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
F.PORT OPICS_PORT,CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END MAPPED_TRADING_BOOK,SDTRBK.NAME FIN_TRADING_BOOK,CASE WHEN CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK,
CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END MAPPED_SUBTYPE ,SDSBTY.NAME FIN_SUBTYPE,CASE WHEN CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
TRIM(C.CMNE) OPICS_CPTY ,TRIM(SDCP.NAME) FIN_CPTY ,CASE WHEN TRIM(C.CMNE) = TRIM(SDCP.NAME)THEN 'TRUE' ELSE 'FALSE' END MATCH_CPTY,
CCYTERMS OPICS_CCYTERMS, CCY OPICS_CCY,CTRCCY OPICS_CTRCCY, CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END MAPPED_CCY_PAIR, TTFXL.CCY_PAIR  FIN_CCY_PAIR ,CASE WHEN CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END = TTFXL.CCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR ,
TRIM(DISAGGCCY) OPICS_DCO_CURRENCY,DCO_CURRENCY FIN_DCO_CURRENCY,CASE WHEN NVL(TRIM(DISAGGCCY),' ') =NVL(DCO_CURRENCY,' ')  THEN 'TRUE' ELSE 'FALSE' END MATCH_DCO_CURRENCY,
PS OPICS_PS,CASE WHEN PS='P' AND CCYTERMS='M' THEN 'BUY'     WHEN PS='S' AND CCYTERMS='M' THEN 'SELL'     WHEN PS='P' AND CCYTERMS='D' THEN 'SELL'     WHEN PS='S' AND CCYTERMS='D' THEN 'BUY'     END MAPPED_BUY_SELL,
CASE WHEN FX_BUY_SELL='S' THEN 'SELL' ELSE 'BUY' END FIN_BUY_SELL,CASE WHEN CASE WHEN PS='P' AND CCYTERMS='M' THEN 'BUY' WHEN PS='S' AND CCYTERMS='M' THEN 'SELL' WHEN PS='P' AND CCYTERMS='D' THEN 'SELL' WHEN PS='S' AND CCYTERMS='D' THEN 'BUY'     END = CASE WHEN FX_BUY_SELL='S' THEN 'SELL' ELSE 'BUY' END THEN 'TRUE' ELSE 'FALSE' END MATCH_BUY_SELL,
ABS(ROUND(F.CCYAMT,2)) OPICS_CCY_AMT,  ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2) FIN_CCY_AMT,CASE WHEN ABS(ROUND(F.CCYAMT,2)) =  ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_AMT,
ABS(ROUND(F.CTRAMT,2)) OPICS_CTR_AMT,ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2) FIN_CTR_AMT,CASE WHEN ABS(ROUND(F.CTRAMT,2)) = ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTR_AMT,
ROUND(CCYRATE_8,5) MAPPED_RATE,ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((TTFXL.MARKET_SPOT_RATE+TTFXL.SPOT_MARGIN_POINTS)*100) ELSE TTFXL.MARKET_SPOT_RATE+TTFXL.SPOT_MARGIN_POINTS END,5) FIN_RATE, CASE WHEN ROUND(CCYRATE_8,5) = ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((TTFXL.MARKET_SPOT_RATE+TTFXL.SPOT_MARGIN_POINTS)*100) ELSE TTFXL.MARKET_SPOT_RATE+TTFXL.SPOT_MARGIN_POINTS END,5) THEN 'TRUE' ELSE 'FALSE' END MATCH_RATE,
CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
END OPICS_PAY_NOSTRO,pay_nos FIN_PAY_NOSTRO,CASE WHEN trim(CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
END) = trim(pay_nos) THEN 'TRUE' ELSE 'FALSE' END MATCH_PAY_NOSTRO,
CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
END OPICS_REC_NOSTRO,rec_nos FIN_REC_NOSTRO,CASE WHEN   trim(CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
END) = trim(rec_nos) THEN 'TRUE' ELSE 'FALSE' END MATCH_REC_NOSTRO,
TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(F.DEALNO) ||'-'||CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||
CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END||'-'||CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||
TRIM(C.CMNE)||'-'||CASE WHEN F.CCYTERMS='M' THEN F.CCY||'/'||F.CTRCCY ELSE F.CTRCCY||'/'||F.CCY END||'-'||ABS(ROUND(F.CCYAMT,2))||'-'||ROUND(CCYRATE_8-CASE WHEN TRIM(F.PORT) ='CORP' THEN F.CORPSPREAD_8 ELSE 0 END,5)||'-'||ABS(ROUND(F.CTRAMT,2))||'-'||TO_DATE(TRIM(F.VDATE),'YYYY-MM-DD') CONV_OPICS_DATA, 
FIN_FX_OUTRIGHT.DEAL_DATE ||'-'||TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME ||'-'||TRIM(SDCP.NAME)||'-'||
TTFXL.CCY_PAIR ||'-'||ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2)||'-'|| ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((TTFXL.MARKET_SPOT_RATE-TTFXL.SPOT_MARGIN_POINTS)*100) ELSE TTFXL.MARKET_SPOT_RATE-TTFXL.SPOT_MARGIN_POINTS END,5)||'-'||
 ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2)||'-'|| TTFXFL.VALUE_DATE_ONE FIN_DATA,
 CASE WHEN TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(F.DEALNO) ||'-'||CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||
CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END||'-'||CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||
TRIM(C.CMNE)||'-'||CASE WHEN F.CCYTERMS='M' THEN F.CCY||'/'||F.CTRCCY ELSE F.CTRCCY||'/'||F.CCY END||'-'||ABS(ROUND(F.CCYAMT,2))||'-'||ROUND(CCYRATE_8-CASE WHEN TRIM(F.PORT) ='CORP' THEN F.CORPSPREAD_8 ELSE 0 END,5)||'-'||ABS(ROUND(F.CTRAMT,2))||'-'||TO_DATE(TRIM(F.VDATE),'YYYY-MM-DD')
=
FIN_FX_OUTRIGHT.DEAL_DATE ||'-'||TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME ||'-'||TRIM(SDCP.NAME)||'-'||
TTFXL.CCY_PAIR ||'-'||ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2)||'-'|| ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((TTFXL.MARKET_SPOT_RATE-TTFXL.SPOT_MARGIN_POINTS)*100) ELSE TTFXL.MARKET_SPOT_RATE-TTFXL.SPOT_MARGIN_POINTS END,5)||'-'||
 ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2)||'-'|| TTFXFL.VALUE_DATE_ONE
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM FXDH F  
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(F.CUST)
LEFT JOIN TT_FXP_DEAL@FTMIG FIN_FX_OUTRIGHT ON  TRIM(F.DEALNO) = TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER) AND FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND PARENT_FBO_ID_VER='1' AND PARENT_FBO_MIN_VER='1'
LEFT JOIN (SELECT * FROM (
  SELECT * FROM  TT_FXP_LEG@FTMIG A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@FTMIG GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM)
  )) TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
left join (
  SELECT distinct a.PARENT_FBO_ID_NUM,a.PARENT_FBO_ID_TYPE,A.IQ_CURRENCY PAY_CCY,a.NAME pay_nos ,B.IQ_CURRENCY REC_CCY,b.NAME rec_nos  FROM (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT') A
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT') B ON A.PARENT_FBO_ID_TYPE = B.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM
  ) NOS on NOS.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM  
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND TRIM(PRODCODE)!='CCS' AND TRIM(REVDATE) IS NULL AND TRIM(SWAPDEAL)='0' AND  SPOTFWDIND='F'
AND TRIM(C.CMNE)!='CCIRS' AND TRIM(PORT)!='EQFX'




SELECT DISTINCT 
F.DEALNO OPICS_DEALNO ,FIN_FX_OUTRIGHT.DEAL_IDENTIFIER FIN_DEAL_IDENTIFIER, CASE WHEN TRIM(F.DEALNO) = FIN_FX_OUTRIGHT.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,TO_CHAR(FIN_FX_OUTRIGHT.DEAL_NUM) FIN_DEAL_NUM,
F.BR OPICS_BR, CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD') OPICS_DEAL_DATE ,FIN_FX_OUTRIGHT.DEAL_DATE FIN_DEAL_DATE,CASE WHEN TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD') = FIN_FX_OUTRIGHT.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
F.PORT OPICS_PORT,CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END MAPPED_TRADING_BOOK,SDTRBK.NAME FIN_TRADING_BOOK,CASE WHEN CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK,
CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END MAPPED_SUBTYPE ,SDSBTY.NAME FIN_SUBTYPE,CASE WHEN CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
TRIM(C.CMNE) OPICS_CPTY ,TRIM(SDCP.NAME) FIN_CPTY ,CASE WHEN TRIM(C.CMNE) = TRIM(SDCP.NAME)THEN 'TRUE' ELSE 'FALSE' END MATCH_CPTY,
CCYTERMS OPICS_CCYTERMS, CCY OPICS_CCY,CTRCCY OPICS_CTRCCY, CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END MAPPED_CCY_PAIR, TTFXL.CCY_PAIR  FIN_CCY_PAIR ,CASE WHEN CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END = TTFXL.CCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR ,
TRIM(DISAGGCCY) OPICS_DCO_CURRENCY,DCO_CURRENCY FIN_DCO_CURRENCY,CASE WHEN NVL(TRIM(DISAGGCCY),' ') =NVL(DCO_CURRENCY,' ')  THEN 'TRUE' ELSE 'FALSE' END MATCH_DCO_CURRENCY,
PS OPICS_PS,CASE WHEN PS='P' AND CCYTERMS='M' THEN 'BUY'     WHEN PS='S' AND CCYTERMS='M' THEN 'SELL'     WHEN PS='P' AND CCYTERMS='D' THEN 'SELL'     WHEN PS='S' AND CCYTERMS='D' THEN 'BUY'     END MAPPED_BUY_SELL,
CASE WHEN FX_BUY_SELL='S' THEN 'SELL' ELSE 'BUY' END FIN_BUY_SELL,CASE WHEN CASE WHEN PS='P' AND CCYTERMS='M' THEN 'BUY' WHEN PS='S' AND CCYTERMS='M' THEN 'SELL' WHEN PS='P' AND CCYTERMS='D' THEN 'SELL' WHEN PS='S' AND CCYTERMS='D' THEN 'BUY'     END = CASE WHEN FX_BUY_SELL='S' THEN 'SELL' ELSE 'BUY' END THEN 'TRUE' ELSE 'FALSE' END MATCH_BUY_SELL,
ABS(ROUND(F.CCYAMT,2)) OPICS_CCY_AMT,  ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2) FIN_CCY_AMT,CASE WHEN ABS(ROUND(F.CCYAMT,2)) =  ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_AMT,
ABS(ROUND(F.CTRAMT,2)) OPICS_CTR_AMT,ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2) FIN_CTR_AMT,CASE WHEN ABS(ROUND(F.CTRAMT,2)) = ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTR_AMT,
ROUND(CCYRATE_8,5) MAPPED_RATE,ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((MARKET_FWD_RATE+FWD_MARGIN_POINTS)) ELSE MARKET_FWD_RATE+FWD_MARGIN_POINTS END,5) FIN_RATE, CASE WHEN ROUND(CCYRATE_8,5) = ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((MARKET_FWD_RATE+FWD_MARGIN_POINTS)) ELSE MARKET_FWD_RATE+FWD_MARGIN_POINTS END,5) THEN 'TRUE' ELSE 'FALSE' END MATCH_RATE,
CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
END OPICS_PAY_NOSTRO,pay_nos FIN_PAY_NOSTRO,CASE WHEN trim(CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
END) = trim(pay_nos) THEN 'TRUE' ELSE 'FALSE' END MATCH_PAY_NOSTRO,
CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
END OPICS_REC_NOSTRO,rec_nos FIN_REC_NOSTRO,CASE WHEN   trim(CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
END) = trim(rec_nos) THEN 'TRUE' ELSE 'FALSE' END MATCH_REC_NOSTRO,
TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(F.DEALNO) ||'-'||CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||
CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END||'-'||CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||
TRIM(C.CMNE)||'-'||CASE WHEN F.CCYTERMS='M' THEN F.CCY||'/'||F.CTRCCY ELSE F.CTRCCY||'/'||F.CCY END||'-'||ABS(ROUND(F.CCYAMT,2))||'-'||ROUND(CCYRATE_8,5)||'-'||ABS(ROUND(F.CTRAMT,2))||'-'||TO_DATE(TRIM(F.VDATE),'YYYY-MM-DD') CONV_OPICS_DATA, 
FIN_FX_OUTRIGHT.DEAL_DATE ||'-'||TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME ||'-'||TRIM(SDCP.NAME)||'-'||
TTFXL.CCY_PAIR ||'-'||ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2)||'-'|| ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((MARKET_FWD_RATE+FWD_MARGIN_POINTS)) ELSE MARKET_FWD_RATE+FWD_MARGIN_POINTS END,5)||'-'||
 ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2)||'-'|| TTFXFL.VALUE_DATE_ONE FIN_DATA,
 CASE WHEN TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(F.DEALNO) ||'-'||CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||
CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END||'-'||CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||
TRIM(C.CMNE)||'-'||CASE WHEN F.CCYTERMS='M' THEN F.CCY||'/'||F.CTRCCY ELSE F.CTRCCY||'/'||F.CCY END||'-'||ABS(ROUND(F.CCYAMT,2))||'-'||ROUND(CCYRATE_8,5)||'-'||ABS(ROUND(F.CTRAMT,2))||'-'||TO_DATE(TRIM(F.VDATE),'YYYY-MM-DD')
=
FIN_FX_OUTRIGHT.DEAL_DATE ||'-'||TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME ||'-'||TRIM(SDCP.NAME)||'-'||
TTFXL.CCY_PAIR ||'-'||ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2)||'-'|| ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((MARKET_FWD_RATE+FWD_MARGIN_POINTS)) ELSE MARKET_FWD_RATE+FWD_MARGIN_POINTS END,5)||'-'||
 ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2)||'-'|| TTFXFL.VALUE_DATE_ONE
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM FXDH F  
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(F.CUST)
LEFT JOIN TT_FXP_DEAL@FTMIG FIN_FX_OUTRIGHT ON   TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER) like TRIM(F.DEALNO)||'%' AND FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND PARENT_FBO_ID_VER='1' AND PARENT_FBO_MIN_VER='1'
LEFT JOIN (SELECT * FROM (
  SELECT * FROM  TT_FXP_LEG@FTMIG A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@FTMIG GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM)
  )) TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
left join (
  SELECT distinct a.PARENT_FBO_ID_NUM,a.PARENT_FBO_ID_TYPE,A.IQ_CURRENCY PAY_CCY,a.NAME pay_nos ,B.IQ_CURRENCY REC_CCY,b.NAME rec_nos  FROM (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT') A
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT') B ON A.PARENT_FBO_ID_TYPE = B.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM
  ) NOS on NOS.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM  
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND TRIM(PRODCODE)!='CCS' AND TRIM(REVDATE) IS NULL AND TRIM(SWAPDEAL)='0' AND  SPOTFWDIND='F'
AND TRIM(C.CMNE)!='CCIRS' AND TRIM(PORT)!='EQFX'


SELECT DISTINCT 
F.DEALNO OPICS_DEALNO ,FIN_FX_OUTRIGHT.DEAL_IDENTIFIER FIN_DEAL_IDENTIFIER, CASE WHEN TRIM(F.DEALNO) = FIN_FX_OUTRIGHT.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,TO_CHAR(FIN_FX_OUTRIGHT.DEAL_NUM) FIN_DEAL_NUM,
F.BR OPICS_BR, CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD') OPICS_DEAL_DATE ,FIN_FX_OUTRIGHT.DEAL_DATE FIN_DEAL_DATE,CASE WHEN TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD') = FIN_FX_OUTRIGHT.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
TO_DATE(VDATE,'YYYY-MM-DD') OPICS_END_DATE,TTFXL.VALUE_DATE_ONE FIN_END_DATE,CASE WHEN TO_DATE(TRIM(VDATE),'YYYY-MM-DD') =TTFXL.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
F.PORT OPICS_PORT,CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END MAPPED_TRADING_BOOK,SDTRBK.NAME FIN_TRADING_BOOK,CASE WHEN CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK,
CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END MAPPED_SUBTYPE ,SDSBTY.NAME FIN_SUBTYPE,CASE WHEN CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
TRIM(C.CMNE) OPICS_CPTY ,TRIM(SDCP.NAME) FIN_CPTY ,CASE WHEN TRIM(C.CMNE) = TRIM(SDCP.NAME)THEN 'TRUE' ELSE 'FALSE' END MATCH_CPTY,
CCYTERMS OPICS_CCYTERMS, CCY OPICS_CCY,CTRCCY OPICS_CTRCCY, CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END MAPPED_CCY_PAIR, TTFXL.CCY_PAIR  FIN_CCY_PAIR ,CASE WHEN CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END = TTFXL.CCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR ,
TRIM(DISAGGCCY) OPICS_DCO_CURRENCY,DCO_CURRENCY FIN_DCO_CURRENCY,CASE WHEN NVL(TRIM(DISAGGCCY),' ') =NVL(DCO_CURRENCY,' ')  THEN 'TRUE' ELSE 'FALSE' END MATCH_DCO_CURRENCY,
PS OPICS_PS,CASE WHEN PS='P' AND CCYTERMS='M' THEN 'BUY'     WHEN PS='S' AND CCYTERMS='M' THEN 'SELL'     WHEN PS='P' AND CCYTERMS='D' THEN 'SELL'     WHEN PS='S' AND CCYTERMS='D' THEN 'BUY'     END MAPPED_BUY_SELL,
CASE WHEN FX_BUY_SELL='S' THEN 'SELL' ELSE 'BUY' END FIN_BUY_SELL,CASE WHEN CASE WHEN PS='P' AND CCYTERMS='M' THEN 'BUY' WHEN PS='S' AND CCYTERMS='M' THEN 'SELL' WHEN PS='P' AND CCYTERMS='D' THEN 'SELL' WHEN PS='S' AND CCYTERMS='D' THEN 'BUY'     END = CASE WHEN FX_BUY_SELL='S' THEN 'SELL' ELSE 'BUY' END THEN 'TRUE' ELSE 'FALSE' END MATCH_BUY_SELL,
ABS(ROUND(F.CCYAMT,2)) OPICS_CCY_AMT,  ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2) FIN_CCY_AMT,CASE WHEN ABS(ROUND(F.CCYAMT,2)) =  ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_AMT,
ABS(ROUND(F.CTRAMT,2)) OPICS_CTR_AMT,ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2) FIN_CTR_AMT,CASE WHEN ABS(ROUND(F.CTRAMT,2)) = ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTR_AMT,
ROUND(CCYRATE_8,5) MAPPED_RATE,ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((MARKET_FWD_RATE+FWD_MARGIN_POINTS)) ELSE MARKET_FWD_RATE+FWD_MARGIN_POINTS END,5) FIN_RATE, CASE WHEN ROUND(CCYRATE_8,5) = ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((MARKET_FWD_RATE+FWD_MARGIN_POINTS)) ELSE MARKET_FWD_RATE+FWD_MARGIN_POINTS END,5) THEN 'TRUE' ELSE 'FALSE' END MATCH_RATE,
CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
END OPICS_PAY_NOSTRO,pay_nos FIN_PAY_NOSTRO,CASE WHEN trim(CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
END) = trim(pay_nos) THEN 'TRUE' ELSE 'FALSE' END MATCH_PAY_NOSTRO,
CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
END OPICS_REC_NOSTRO,rec_nos FIN_REC_NOSTRO,CASE WHEN   trim(CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
END) = trim(rec_nos) THEN 'TRUE' ELSE 'FALSE' END MATCH_REC_NOSTRO,
TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(F.DEALNO) ||'-'||CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||
CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END||'-'||CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||
TRIM(C.CMNE)||'-'||CASE WHEN F.CCYTERMS='M' THEN F.CCY||'/'||F.CTRCCY ELSE F.CTRCCY||'/'||F.CCY END||'-'||ABS(ROUND(F.CCYAMT,2))||'-'||ROUND(CCYRATE_8,5)||'-'||ABS(ROUND(F.CTRAMT,2))||'-'||TO_DATE(TRIM(F.VDATE),'YYYY-MM-DD') CONV_OPICS_DATA, 
FIN_FX_OUTRIGHT.DEAL_DATE ||'-'||TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME ||'-'||TRIM(SDCP.NAME)||'-'||
TTFXL.CCY_PAIR ||'-'||ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2)||'-'|| ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((MARKET_FWD_RATE+FWD_MARGIN_POINTS)) ELSE MARKET_FWD_RATE+FWD_MARGIN_POINTS END,5)||'-'||
 ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2)||'-'|| TTFXFL.VALUE_DATE_ONE FIN_DATA,
 CASE WHEN TO_DATE(TRIM(F.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(F.DEALNO) ||'-'||CASE WHEN TRIM(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN TRIM(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||
CASE WHEN TRIM(PORT) = 'CORP' THEN 'CORP' WHEN TRIM(PORT) != 'CORP' THEN 'BANK' END||'-'||CASE WHEN TRIM(F.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||
TRIM(C.CMNE)||'-'||CASE WHEN F.CCYTERMS='M' THEN F.CCY||'/'||F.CTRCCY ELSE F.CTRCCY||'/'||F.CCY END||'-'||ABS(ROUND(F.CCYAMT,2))||'-'||ROUND(CCYRATE_8,5)||'-'||ABS(ROUND(F.CTRAMT,2))||'-'||TO_DATE(TRIM(F.VDATE),'YYYY-MM-DD')
=
FIN_FX_OUTRIGHT.DEAL_DATE ||'-'||TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME ||'-'||TRIM(SDCP.NAME)||'-'||
TTFXL.CCY_PAIR ||'-'||ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_ONE_AMOUNT_VALUE ELSE TTFXL.CCY_TWO_AMOUNT_VALUE END,2)||'-'|| ROUND(CASE WHEN TTFXL.CCY_PAIR='JPY/KWD' THEN ((MARKET_FWD_RATE+FWD_MARGIN_POINTS)) ELSE MARKET_FWD_RATE+FWD_MARGIN_POINTS END,5)||'-'||
 ROUND(CASE WHEN F.CCYTERMS='M' THEN TTFXL.CCY_TWO_AMOUNT_VALUE ELSE TTFXL.CCY_ONE_AMOUNT_VALUE END,2)||'-'|| TTFXFL.VALUE_DATE_ONE
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM FXDH F  
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(F.CUST)
LEFT JOIN TT_FXP_DEAL@FTMIG FIN_FX_OUTRIGHT ON   TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER) like TRIM(F.DEALNO)||'%' AND FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND PARENT_FBO_ID_VER='1' AND PARENT_FBO_MIN_VER='1'
LEFT JOIN (SELECT * FROM (
  SELECT * FROM  TT_FXP_LEG@FTMIG A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@FTMIG where PARENT_FBO_ID_VER='999999' and LEG_IDENTIFIER='MNLG' GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM)
  )) TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
left join (
  SELECT distinct a.PARENT_FBO_ID_NUM,a.PARENT_FBO_ID_TYPE,A.IQ_CURRENCY PAY_CCY,a.NAME pay_nos ,B.IQ_CURRENCY REC_CCY,b.NAME rec_nos  FROM (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT') A
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT') B ON A.PARENT_FBO_ID_TYPE = B.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM
  ) NOS on NOS.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM 
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND TRIM(PRODCODE)!='CCS' AND TRIM(REVDATE) IS NULL AND TRIM(SWAPDEAL)='0' AND  SPOTFWDIND='F'
AND TRIM(C.CMNE)!='CCIRS' AND TRIM(PORT)!='EQFX' 
