========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
fx_spot_deals_report.sql 
SELECT 
B.DEALDATE OPICS_DEALDATE,FIN_FX_SPOT.DEAL_DATE FINACLE_DEAL_DATE ,CASE WHEN TO_DATE(TRIM(B.DEALDATE),'YYYY-MM-DD') = FIN_FX_SPOT.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALDATE,
B.DEALNO OPICS_DEALNO, FIN_FX_SPOT.DEAL_IDENTIFIER FINACLE_DEAL_IDENTIFIER, CASE WHEN TRIM(B.DEALNO) = TRIM(FIN_FX_SPOT.DEAL_IDENTIFIER) THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
B.PORT OPICS_PORT,SDTRBK.NAME FINACLE_TRADING_BOOK, CASE WHEN CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK, 
B.PORT OPICS_PORT,SDSBTY.NAME FINACLE_SUBTYPE, CASE WHEN CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
B.BR OPICS_BR,SDENT.NAME FINACLE_ENTITY_NAME,CASE WHEN CASE WHEN TRIM(B.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END like  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY_NAME,--CASE WHEN CASE WHEN TRIM(B.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END = TRIM(SDENT.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY_NAME,
C.CMNE OPICS_CMNE,SDCP.NAME FINACLE_MAIN_LEG_CPTY,CASE WHEN TRIM(C.CMNE) = TRIM(SDCP.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_MAIN_LEG_CPTY,
B.CCYTERMS OPICS_CCYTERMS ,B.CCY OPICS_CCY,B.CTRCCY OPICS_CTRCCY,TTFXL.CCY_PAIR FINACLE_MAIN_LEG_CCY_PAIR,CASE when case when B.CCYTERMS='M' then B.CCY||'/'||B.CTRCCY else B.CTRCCY||'/'||B.CCY end = TTFXL.CCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR,
B.CCYTERMS OPICS_CCYTERMS,B.CCYAMT OPICS_CCYAMT,case when B.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end  FIN_MAIN_LEG_CCY_ONE_AMOUNT,
    CASE WHEN abs(round(B.CCYAMT,2)) = round(case when B.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_AMOUNT,
B.CCYRATE_8 OPICS_CCYRATE_8,TTFXFL.RATE FIN_MAIN_LEG_MARKET_FWD_RATE,CASE WHEN B.CCYRATE_8 = TTFXFL.RATE THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYRATE,
B.CCYTERMS OPICS_CCYTERMS,B.CTRAMT OPICS_CCYAMT,case when B.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end  FIN_MAIN_LEG_CCY_TWO_AMOUNT,
    CASE WHEN abs(round(B.CTRAMT,2)) = round(case when B.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTR_AMOUNT,
B.VDATE,TTFXFL.VALUE_DATE_ONE FIN_MAIN_LEG_VALUE_DATE_ONE,CASE WHEN TO_DATE(TRIM(B.VDATE),'YYYY-MM-DD') = TTFXFL.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END FIN_MAIN_LEG_VALUE_DATE_ONE
FROM FXDH B 
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(B.CUST)
LEFT JOIN  TT_FXP_DEAL@ftuat FIN_FX_SPOT ON trim(B.DEALNO) = trim(FIN_FX_SPOT.DEAL_IDENTIFIER) AND FIN_FX_SPOT.DEAL_TYPE='FXPLSP' AND FIN_FX_SPOT.DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@ftuat SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_SPOT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftuat SDENT ON SDENT.FBO_ID_NUM = FIN_FX_SPOT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftuat SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_SPOT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftuat SDCP ON FIN_FX_SPOT.CPTY_FBO_ID_NUM=SDCP.FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@ftuat TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_SPOT.DEAL_NUM
LEFT JOIN (SELECT * FROM (
  SELECT * FROM  TT_FXP_LEG@ftuat A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@ftuat GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM)
  )) TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_SPOT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_SPOT.DEAL_TYPE
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')
AND SPOTFWDIND='S' AND TRIM(SWAPDEAL)='0' AND TRIM(REVDATE) IS NULL 
AND TRIM(C.CMNE)!='CCIRS' and trim(port) !='EQFX'
;

SELECT 
B.DEALDATE||'-'|| B.DEALNO ||'-'||B.PORT  ||'-'||B.PORT||'-'||B.BR ||'-'||C.CMNE ||'-'||B.CCYTERMS||'-'||B.CCY ||'-'||B.CTRCCY||'-'||B.CCYAMT||'-'||ROUND(B.CCYRATE_8,2) ||'-'||B.CTRAMT||'-'||B.VDATE OPICS_DATA,
TO_DATE(TRIM(B.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(B.DEALNO)||'-'||CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end ||'-'||
CASE WHEN TRIM(B.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ||'-'||TRIM(C.CMNE) ||'-'||case when B.CCYTERMS='M' then B.CCY||'/'||B.CTRCCY else B.CTRCCY||'/'||B.CCY end||'-'||abs(round(B.CCYAMT,2))||'-'||round(B.CCYRATE_8,5)||'-'||
abs(round(B.CTRAMT,2))||'-'||TO_DATE(TRIM(B.VDATE),'YYYY-MM-DD') CONV_OPICS_DATA,
FIN_FX_SPOT.DEAL_DATE||'-'||TRIM(FIN_FX_SPOT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME||'-'||TRIM(SDCP.NAME) ||'-'||TTFXL.CCY_PAIR||'-'||round(case when B.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2)||'-'|| 
ROUND(TTFXFL.RATE,5)||'-'|| round(case when B.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2) ||'-'|| TTFXFL.VALUE_DATE_ONE FIN_DATA,
CASE WHEN TO_DATE(TRIM(B.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(B.DEALNO)||'-'||CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end ||'-'||
CASE WHEN TRIM(B.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ||'-'||TRIM(C.CMNE) ||'-'||case when B.CCYTERMS='M' then B.CCY||'/'||B.CTRCCY else B.CTRCCY||'/'||B.CCY end||'-'||abs(round(B.CCYAMT,2))||'-'||ROUND(B.CCYRATE_8,5)||'-'||
abs(round(B.CTRAMT,2))||'-'||TO_DATE(TRIM(B.VDATE),'YYYY-MM-DD')=
FIN_FX_SPOT.DEAL_DATE||'-'||TRIM(FIN_FX_SPOT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME||'-'||TRIM(SDCP.NAME) ||'-'||TTFXL.CCY_PAIR||'-'||round(case when B.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2)||'-'|| 
ROUND(TTFXFL.RATE,5)||'-'|| round(case when B.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2) ||'-'|| TTFXFL.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM FXDH B 
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(B.CUST)
LEFT JOIN  TT_FXP_DEAL@FTMIG FIN_FX_SPOT ON trim(B.DEALNO) = trim(FIN_FX_SPOT.DEAL_IDENTIFIER) AND FIN_FX_SPOT.DEAL_TYPE='FXPLSP' AND FIN_FX_SPOT.DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_SPOT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_SPOT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_SPOT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON FIN_FX_SPOT.CPTY_FBO_ID_NUM=SDCP.FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_SPOT.DEAL_NUM and TTFXFL.PARENT_FBO_ID_VER='1'--NEED TO CHECK PARENT_FBO_ID_VER 
LEFT JOIN (SELECT * FROM (
  SELECT * FROM  TT_FXP_LEG@FTMIG A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@FTMIG GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM)
  )) TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_SPOT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_SPOT.DEAL_TYPE
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')
AND SPOTFWDIND='S' AND TRIM(SWAPDEAL)='0' AND TRIM(REVDATE) IS NULL 
AND TRIM(C.CMNE)!='CCIRS' and trim(port) !='EQFX'
;


SELECT 
B.DEALNO ,FIN_FX_SPOT.DEAL_IDENTIFIER,CASE WHEN TRIM(B.DEALNO) = FIN_FX_SPOT.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
B.BR OPICS_BR, CASE WHEN TRIM(B.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN CASE WHEN TRIM(B.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
TO_DATE(TRIM(B.DEALDATE),'YYYY-MM-DD') OPICS_DEAL_DATE ,FIN_FX_SPOT.DEAL_DATE FIN_DEAL_DATE,CASE WHEN TO_DATE(TRIM(B.DEALDATE),'YYYY-MM-DD') = FIN_FX_SPOT.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
TO_DATE(VDATE,'YYYY-MM-DD') OPICS_END_DATE,TTFXL.VALUE_DATE_ONE FIN_END_DATE,CASE WHEN TO_DATE(TRIM(VDATE),'YYYY-MM-DD') =TTFXL.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
B.PORT OPICS_PORT,CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END MAPPED_TRADING_BOOK,SDTRBK.NAME FIN_TRADING_BOOK,CASE WHEN CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK,
CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end MAPPED_SUBTYPE ,SDSBTY.NAME FIN_SUBTYPE,CASE WHEN CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
TRIM(C.CMNE) OPICS_CPTY ,TRIM(SDCP.name) FIN_CPTY ,CASE WHEN TRIM(C.CMNE) = TRIM(SDCP.name)THEN 'TRUE' ELSE 'FALSE' END MATCH_CPTY,
CCYTERMS OPICS_CCYTERMS, CCY OPICS_CCY,CTRCCY OPICS_CTRCCY, CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END MAPPED_CCY_PAIR, TTFXL.CCY_PAIR  FIN_CCY_PAIR ,CASE WHEN CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END = TTFXL.CCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR ,
PS OPICS_PS,CASE WHEN PS='P' AND CCYTERMS='M' THEN 'BUY'     WHEN PS='S' AND CCYTERMS='M' THEN 'SELL'     WHEN PS='P' AND CCYTERMS='D' THEN 'SELL'     WHEN PS='S' AND CCYTERMS='D' THEN 'BUY'     END MAPPED_BUY_SELL,
CASE WHEN FX_BUY_SELL='S' THEN 'SELL' ELSE 'BUY' END FIN_BUY_SELL,CASE WHEN CASE WHEN PS='P' AND CCYTERMS='M' THEN 'BUY' WHEN PS='S' AND CCYTERMS='M' THEN 'SELL' WHEN PS='P' AND CCYTERMS='D' THEN 'SELL' WHEN PS='S' AND CCYTERMS='D' THEN 'BUY'     END = CASE WHEN FX_BUY_SELL='S' THEN 'SELL' ELSE 'BUY' END THEN 'TRUE' ELSE 'FALSE' END MATCH_BUY_SELL,
abs(round(B.CCYAMT,2)) OPICS_CCY_AMT,  ROUND(case when B.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2) FIN_CCY_AMT,CASE WHEN abs(round(B.CCYAMT,2)) =  ROUND(case when B.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_AMT,
abs(round(B.CTRAMT,2)) OPICS_CTR_AMT,ROUND(case when B.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2) FIN_CTR_AMT,CASE WHEN abs(round(B.CTRAMT,2)) = ROUND(case when B.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTR_AMT,
ROUND(CCYRATE_8,5) OPICS_RATE,ROUND(case when TTFXL.CCY_PAIR='JPY/KWD' THEN ((TTFXL.MARKET_SPOT_RATE+TTFXL.SPOT_MARGIN_POINTS)*100) ELSE TTFXL.MARKET_SPOT_RATE+TTFXL.SPOT_MARGIN_POINTS END,5) FIN_RATE, CASE WHEN ROUND(CCYRATE_8,5) = ROUND(case when TTFXL.CCY_PAIR='JPY/KWD' THEN ((TTFXL.MARKET_SPOT_RATE+TTFXL.SPOT_MARGIN_POINTS)*100) ELSE TTFXL.MARKET_SPOT_RATE+TTFXL.SPOT_MARGIN_POINTS END,5) THEN 'TRUE' ELSE 'FALSE' END MATCH_RATE, 
CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
END OPICS_PAY_NOSTRO,pay_nos FIN_PAY_NOSTRO,CASE WHEN nvl(trim(CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
END),' ') = nvl(trim(pay_nos),' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_PAY_NOSTRO,
CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
END OPICS_REC_NOSTRO,rec_nos FIN_REC_NOSTRO,CASE WHEN   nvl(trim(CASE WHEN PS='P' AND CCYTERMS='M' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END  
     WHEN PS='S' AND CCYTERMS='M' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END
     WHEN PS='P' AND CCYTERMS='D' THEN CASE WHEN TRIM(CCYSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CCYSACCT  END 
     WHEN PS='S' AND CCYTERMS='D' THEN CASE WHEN TRIM(CTRSMEANS) in ('BRDGE','BRIDGE') THEN 'BRIDGE_'||TRIM(CTRCCY)||CASE WHEN TRIM(BR)='51' THEN '_ABKU' ELSE '_ABKK' END ELSE CTRSACCT END  
END),' ') = nvl(trim(rec_nos),' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_REC_NOSTRO,
TO_DATE(TRIM(B.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(B.DEALNO)||'-'||CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end ||'-'||
CASE WHEN TRIM(B.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ||'-'||TRIM(C.CMNE) ||'-'||case when B.CCYTERMS='M' then B.CCY||'/'||B.CTRCCY else B.CTRCCY||'/'||B.CCY end||'-'||abs(round(B.CCYAMT,2))||'-'||round(B.CCYRATE_8,5)||'-'||
abs(round(B.CTRAMT,2))||'-'||TO_DATE(TRIM(B.VDATE),'YYYY-MM-DD') CONV_OPICS_DATA,
FIN_FX_SPOT.DEAL_DATE||'-'||TRIM(FIN_FX_SPOT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME||'-'||TRIM(SDCP.NAME) ||'-'||TTFXL.CCY_PAIR||'-'||round(case when B.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2)||'-'|| 
ROUND(TTFXFL.RATE,5)||'-'|| round(case when B.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2) ||'-'|| TTFXFL.VALUE_DATE_ONE FIN_DATA,
CASE WHEN TO_DATE(TRIM(B.DEALDATE),'YYYY-MM-DD')||'-'||TRIM(B.DEALNO)||'-'||CASE WHEN trim(PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(PORT) IN('FXTR','PORT') THEN 'DEALER1' END||'-'||CASE WHEN trim(PORT) = 'CORP' THEN 'CORP' WHEN trim(PORT) != 'CORP' THEN 'BANK' end ||'-'||
CASE WHEN TRIM(B.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END ||'-'||TRIM(C.CMNE) ||'-'||case when B.CCYTERMS='M' then B.CCY||'/'||B.CTRCCY else B.CTRCCY||'/'||B.CCY end||'-'||abs(round(B.CCYAMT,2))||'-'||ROUND(B.CCYRATE_8,5)||'-'||
abs(round(B.CTRAMT,2))||'-'||TO_DATE(TRIM(B.VDATE),'YYYY-MM-DD')=
FIN_FX_SPOT.DEAL_DATE||'-'||TRIM(FIN_FX_SPOT.DEAL_IDENTIFIER)||'-'||SDTRBK.NAME||'-'||SDSBTY.NAME||'-'||SDENT.NAME||'-'||TRIM(SDCP.NAME) ||'-'||TTFXL.CCY_PAIR||'-'||round(case when B.CCYTERMS='M' then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end,2)||'-'|| 
ROUND(TTFXFL.RATE,5)||'-'|| round(case when B.CCYTERMS='M' then TTFXL.CCY_TWO_AMOUNT_VALUE else TTFXL.CCY_ONE_AMOUNT_VALUE end,2) ||'-'|| TTFXFL.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM FXDH B 
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(B.CUST)
LEFT JOIN  TT_FXP_DEAL@FTMIG FIN_FX_SPOT ON trim(B.DEALNO) = trim(FIN_FX_SPOT.DEAL_IDENTIFIER) AND FIN_FX_SPOT.DEAL_TYPE='FXPLSP' AND FIN_FX_SPOT.DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_SPOT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_SPOT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_SPOT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON FIN_FX_SPOT.CPTY_FBO_ID_NUM=SDCP.FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_SPOT.DEAL_NUM and TTFXFL.PARENT_FBO_ID_VER='1'--NEED TO CHECK PARENT_FBO_ID_VER 
LEFT JOIN (SELECT * FROM (
  SELECT * FROM  TT_FXP_LEG@FTMIG A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@FTMIG GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM)
  )) TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_SPOT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_SPOT.DEAL_TYPE
 left join (
  SELECT distinct a.PARENT_FBO_ID_NUM,a.PARENT_FBO_ID_TYPE,A.IQ_CURRENCY PAY_CCY,a.NAME pay_nos ,B.IQ_CURRENCY REC_CCY,b.NAME rec_nos  FROM (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT') A
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT') B ON A.PARENT_FBO_ID_TYPE = B.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM
  ) NOS on NOS.PARENT_FBO_ID_NUM = FIN_FX_SPOT.DEAL_NUM  
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')
AND SPOTFWDIND='S' AND TRIM(SWAPDEAL)='0' AND TRIM(REVDATE) IS NULL 
AND TRIM(C.CMNE)!='CCIRS' and trim(port) !='EQFX'
; 
