========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
fx_swap_report.sql 

select distinct
A.DEALDATE OPICS_DEALDATE,fin_fx_swap.DEAL_DATE FINACLE_DEAL_DATE ,CASE WHEN TO_DATE(TRIM(A.DEALDATE),'YYYY-MM-DD') = fin_fx_swap.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALDATE,
a.DEALNO OPICS_DEALNO, fin_fx_swap.DEAL_IDENTIFIER FINACLE_DEAL_IDENTIFIER, CASE WHEN TRIM(a.DEALNO) = TRIM(fin_fx_swap.DEAL_IDENTIFIER) THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
A.PORT OPICS_PORT,SDTRBK.NAME FINACLE_TRADING_BOOK, CASE WHEN CASE WHEN trim(A.PORT) IN('MMBK','CORP','FXBK') THEN 'TREASURY' WHEN trim(A.PORT) IN('FXTR','PORT') THEN 'DEALER1' END = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK, 
A.PORT OPICS_PORT,SDSBTY.NAME FINACLE_SUBTYPE, CASE WHEN CASE WHEN trim(A.PORT) = 'CORP' THEN 'CORP' WHEN trim(A.PORT) != 'CORP' THEN 'BANK' end = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
A.BR OPICS_BR,SDENT.NAME FINACLE_ENTITY_NAME,CASE WHEN CASE WHEN TRIM(A.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END like  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY_NAME,
C.CMNE OPICS_CMNE,SDCP.name FINACLE_MAIN_LEG_CPTY,CASE WHEN TRIM(C.CMNE) = TRIM(SDCP.name) THEN 'TRUE' ELSE 'FALSE' END MATCH_MAIN_LEG_CPTY,
A.CCYTERMS OPICS_CCYTERMS ,A.CCY OPICS_CCY,A.CTRCCY OPICS_CTRCCY,TTFXL_NL.CCY_PAIR FINACLE_MAIN_LEG_CCY_PAIR,CASE when case when A.CCYTERMS='M' then A.CCY||'/'||A.CTRCCY else A.CTRCCY||'/'||A.CCY end = TTFXL_NL.CCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR,
A.CCYTERMS OPICS_CCYTERMS,A.CCYAMT OPICS_CCYAMT,case when A.CCYTERMS='M' then TTFXL_NL.CCY_ONE_AMOUNT_VALUE else TTFXL_NL.CCY_TWO_AMOUNT_VALUE end  FIN_MAIN_LEG_CCY_ONE_AMNT_NLEG,
    CASE WHEN abs(round(A.CCYAMT,2)) = round(case when A.CCYTERMS='M' then TTFXL_NL.CCY_ONE_AMOUNT_VALUE else TTFXL_NL.CCY_TWO_AMOUNT_VALUE end,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_AMOUNT_NLEG,
A.CCYRATE_8 OPICS_CCYRATE_8, TTFXL_NL.MARKET_SPOT_RATE FIN_MAIN_LEG_MARKET_FWD_RATE,CASE WHEN A.CCYRATE_8 =  TTFXL_NL.MARKET_SPOT_RATE THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYRATE,
A.CCYTERMS OPICS_CCYTERMS,A.CTRAMT OPICS_CCYAMT,case when A.CCYTERMS='M' then TTFXL_NL.CCY_TWO_AMOUNT_VALUE else TTFXL_NL.CCY_ONE_AMOUNT_VALUE end  FIN_MAIN_LEG_CCY_TWO_AMNT_NLEG,
    CASE WHEN abs(round(A.CTRAMT,2)) = round(case when A.CCYTERMS='M' then TTFXL_NL.CCY_TWO_AMOUNT_VALUE else TTFXL_NL.CCY_ONE_AMOUNT_VALUE end,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTR_AMOUNT_NLEG,
A.VDATE OPICS_VDATE,TTFXL_NL.VALUE_DATE_ONE FINACLE_VALUE_DATE_ONE,CASE WHEN TO_DATE(A.VDATE,'YYYY-MM-DD') = TTFXL_NL.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END FIN_NEAR_LEG_VALUE_DATE_ONE,--A.VDATE,fin_fx_swap.NEAR_LEG_VALUE_DATE_ONE,--***
C.CMNE OPICS_CMNE,SDCP.name FINACLE_FAR_LEG_CPTY,CASE WHEN TRIM(C.CMNE) = TRIM(SDCP.name) THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_LEG_CPTY,--C.CMNE, fin_fx_swap.FAR_LEG_CPTY,--***
B.CCYTERMS OPICS_CCYTERMS,B.CCYAMT OPICS_CCYAMT,case when B.CCYTERMS='M' then TTFXL_NL.CCY_ONE_AMOUNT_VALUE else TTFXL_NL.CCY_TWO_AMOUNT_VALUE end  FIN_MAIN_LEG_CCY_ONE_AMNT_NLEG,
    CASE WHEN abs(round(B.CCYAMT,2)) = round(case when B.CCYTERMS='M' then TTFXL_NL.CCY_ONE_AMOUNT_VALUE else TTFXL_NL.CCY_TWO_AMOUNT_VALUE end,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_AMOUNT_NLEG,
--B.CCYRATE_8 OPICS_CCYRATE_8,TTFXL_FL.MARKET_SPOT_RATE FIN_MAIN_LEG_MARKET_FWD_RATE,CASE WHEN B.CCYRATE_8 = TTFXL_FL.MARKET_SPOT_RATE THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYRATE,
B.CCYTERMS OPICS_CCYTERMS,B.CTRAMT OPICS_CCYAMT,case when B.CCYTERMS='M' then TTFXL_NL.CCY_TWO_AMOUNT_VALUE else TTFXL_NL.CCY_ONE_AMOUNT_VALUE end  FIN_MAIN_LEG_CCY_TWO_AMNT_NLEG,
    CASE WHEN abs(round(B.CTRAMT,2)) = round(case when B.CCYTERMS='M' then TTFXL_NL.CCY_TWO_AMOUNT_VALUE else TTFXL_NL.CCY_ONE_AMOUNT_VALUE end,2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTR_AMOUNT_NLEG,
B.VDATE,TTFXL_FL.VALUE_DATE_ONE FINACLE_VALUE_DATE_ONE,CASE WHEN TO_DATE(TRIM(B.VDATE),'YYYY-MM-DD') = TTFXL_FL.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END FIN_FAR_LEG_VALUE_DATE_ONE
from FXDH A 
INNER JOIN CUST C ON TRIM(A.CUST)=TRIM(C.CNO)
INNER JOIN FXDH B ON A.SWAPDEAL=B.DEALNO AND B.FARNEARIND='F' AND TO_DATE(B.VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')  AND A.BR=B.BR
LEFT JOIN TT_FXP_DEAL@ftuat fin_fx_swap on TRIM(A.DEALNO) = TRIM(fin_fx_swap.DEAL_IDENTIFIER) AND  DEAL_TYPE='FXPLSW' AND fin_fx_swap.DEAL_STATE!='DLTD' 
LEFT JOIN SD_TRADING_BOOK@ftuat SDTRBK ON SDTRBK.FBO_ID_NUM = fin_fx_swap.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftuat SDENT ON SDENT.FBO_ID_NUM = fin_fx_swap.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftuat SDSBTY ON SDSBTY.FBO_ID_NUM = fin_fx_swap.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftuat SDCP ON SDCP.FBO_ID_NUM= fin_fx_swap.CPTY_FBO_ID_NUM
--LEFT JOIN TT_FXP_FLOW@ftuat TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM  AND TTFXFL.FXP_FLOW_REFERENCE = '1'
LEFT JOIN (SELECT * FROM (SELECT * FROM  TT_FXP_LEG@ftuat A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@ftuat GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM AND LEG_IDENTIFIER='NELG'))) TTFXL_NL ON  TTFXL_NL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXL_NL.PARENT_FBO_ID_TYPE = fin_fx_swap.DEAL_TYPE
LEFT JOIN (SELECT * FROM (SELECT * FROM  TT_FXP_LEG@ftuat A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@ftuat GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM AND LEG_IDENTIFIER='FALG'))) TTFXL_FL ON  TTFXL_FL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXL_FL.PARENT_FBO_ID_TYPE = fin_fx_swap.DEAL_TYPE
AND TO_DATE(TRIM(B.VDATE),'YYYY-MM-DD') = TTFXL_FL.VALUE_DATE_ONE 
WHERE  A.SWAPDEAL>0 AND TRIM(A.REVDATE) IS NULL and A.PRODCODE!='CCS' AND TRIM(C.CMNE)!='CCIRS' AND TRIM(A.PORT)!='EQFX' AND TRIM(B.PORT)!='EQFX'





select 
TRIM(OP_SW.DEAL_IDENTIFIER)||'-'||TO_DATE(OP_SW.DEAL_DATE,'DD-MON-YYYY')||'-'||OP_SW.SUBTYPE||'-'||OP_SW.ENTITY_NAME||'-'||OP_SW.NEAR_LEG_CCY_PAIR||'-'||TRIM(OP_SW.NEAR_LEG_CPTY)||'-'||TRIM(ROUND(NEAR_LEG_CCY_ONE_AMOUNT,0))||'-'||
ROUND(TRIM(NEAR_LEG_MARKET_SPOT_RATE),3)||'-'||TRIM(ROUND(NEAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')||'-'||TRIM(ROUND(FAR_LEG_CCY_ONE_AMOUNT,0))||'-'||ROUND(TRIM(FAR_LEG_MARKET_FWD_RATE),3)||'-'||
TRIM(ROUND(FAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(FAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY') opics_data,
fin_fx_swap.DEAL_IDENTIFIER||'-'||fin_fx_swap.DEAL_DATE||'-'||SDSBTY.NAME||'-'||SDENT.NAME||'-'||TTFXL_NL.CCY_PAIR||'-'||trim(SDCP.name) ||'-'||ROUND(TTFXL_NL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_NL.MARKET_SPOT_RATE,3)||'-'||
ROUND(TTFXL_NL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_NL.VALUE_DATE_ONE||'-'||ROUND(TTFXL_FL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_FL.MARKET_FWD_RATE,3)||'-'||
ROUND(TTFXL_FL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_FL.VALUE_DATE_ONE fin_data,
CASE WHEN TRIM(OP_SW.DEAL_IDENTIFIER)||'-'||TO_DATE(OP_SW.DEAL_DATE,'DD-MON-YYYY')||'-'||OP_SW.SUBTYPE||'-'||OP_SW.ENTITY_NAME||'-'||OP_SW.NEAR_LEG_CCY_PAIR||'-'||TRIM(OP_SW.NEAR_LEG_CPTY)||'-'||TRIM(ROUND(NEAR_LEG_CCY_ONE_AMOUNT,0))||'-'||
ROUND(TRIM(NEAR_LEG_MARKET_SPOT_RATE),3)||'-'||TRIM(ROUND(NEAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')||'-'||TRIM(ROUND(FAR_LEG_CCY_ONE_AMOUNT,0))||'-'||ROUND(TRIM(FAR_LEG_MARKET_FWD_RATE),3)||'-'||
TRIM(ROUND(FAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(FAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY') = 
fin_fx_swap.DEAL_IDENTIFIER||'-'||fin_fx_swap.DEAL_DATE||'-'||SDSBTY.NAME||'-'||SDENT.NAME||'-'||TTFXL_NL.CCY_PAIR||'-'||trim(SDCP.name) ||'-'||ROUND(TTFXL_NL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_NL.MARKET_SPOT_RATE,3)||'-'||
ROUND(TTFXL_NL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_NL.VALUE_DATE_ONE||'-'||ROUND(TTFXL_FL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_FL.MARKET_FWD_RATE,3)||'-'||
ROUND(TTFXL_FL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_FL.VALUE_DATE_ONE
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
from FX_SWAP_O_TABLE OP_SW
LEFT JOIN TT_FXP_DEAL@ftmig fin_fx_swap on TRIM(OP_SW.DEAL_IDENTIFIER) = TRIM(fin_fx_swap.DEAL_IDENTIFIER) AND  DEAL_TYPE='FXPLSW' AND fin_fx_swap.DEAL_STATE!='DLTD' 
LEFT JOIN SD_TRADING_BOOK@ftmig SDTRBK ON SDTRBK.FBO_ID_NUM = fin_fx_swap.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = fin_fx_swap.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = fin_fx_swap.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM= fin_fx_swap.CPTY_FBO_ID_NUM
--LEFT JOIN TT_FXP_FLOW@ftmig TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM  AND TTFXFL.FXP_FLOW_REFERENCE = '1'
LEFT JOIN (SELECT * FROM (SELECT * FROM  TT_FXP_LEG@ftmig A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@ftmig GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM AND LEG_IDENTIFIER='NELG'))) TTFXL_NL ON  TTFXL_NL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXL_NL.PARENT_FBO_ID_TYPE = fin_fx_swap.DEAL_TYPE
LEFT JOIN (SELECT * FROM (SELECT * FROM  TT_FXP_LEG@ftmig A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@ftmig GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM AND LEG_IDENTIFIER='FALG'))) TTFXL_FL ON  TTFXL_FL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXL_FL.PARENT_FBO_ID_TYPE = fin_fx_swap.DEAL_TYPE
  
  
  
select 
TRIM(OP_SW.DEAL_IDENTIFIER) OPICS_DEALNO ,fin_fx_swap.DEAL_IDENTIFIER FIN_DEAL_IDENTIFIER,CASE WHEN TRIM(OP_SW.DEAL_IDENTIFIER) = fin_fx_swap.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
ENTITY_NAME MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN ENTITY_NAME =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
SUBSTR(TRADING_BOOK,INSTR(TRADING_BOOK,'/',1,4)+1) MAPPED_TRADING_BOOK,SDTRBK.NAME FIN_TRADING_BOOK,CASE WHEN SUBSTR(TRADING_BOOK,INSTR(TRADING_BOOK,'/',1,4)+1) = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK,
SUBTYPE MAPPED_SUBTYPE ,SDSBTY.NAME FIN_SUBTYPE,CASE WHEN SUBTYPE = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
TO_DATE(OP_SW.DEAL_DATE,'DD-MON-YYYY') OPICS_DEAL_DATE ,fin_fx_swap.DEAL_DATE FIN_DEAL_DATE,CASE WHEN TO_DATE(OP_SW.DEAL_DATE,'DD-MON-YYYY') = fin_fx_swap.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
NEAR_LEG_CCY_PAIR MAPPED_CCY_PAIR ,TTFXL_NL.CCY_PAIR FIN_CCY_PAIR,CASE WHEN NEAR_LEG_CCY_PAIR = TTFXL_NL.CCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR,
NEAR_LEG_CPTY OPICS_NEAR_LEG_CPTY ,TRIM(SDCP.name) FIN_NEAR_LEG_CPTY ,CASE WHEN NEAR_LEG_CPTY = TRIM(SDCP.name)THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_LEG_CPTY,
TRIM(ROUND(NEAR_LEG_CCY_ONE_AMOUNT,0)) OPICS_NEAR_LEG_CCY_ONE_AMOUNT ,ROUND(TTFXL_NL.CCY_ONE_AMOUNT_VALUE,0) FIN_NEAR_LEG_CCY_ONE_AMOUNT,CASE WHEN TRIM(ROUND(NEAR_LEG_CCY_ONE_AMOUNT,0)) = ROUND(TTFXL_NL.CCY_ONE_AMOUNT_VALUE,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_LEG_CCY_ONE_AMOUNT,
ROUND(TRIM(NEAR_LEG_MARKET_SPOT_RATE),3) OPICS_NEAR_LEG_MAK_SPOT_RATE ,ROUND(TTFXL_NL.MARKET_SPOT_RATE,3) FIN_NEAR_LEG_MAK_SPOT_RATE,CASE WHEN ROUND(TRIM(NEAR_LEG_MARKET_SPOT_RATE),3) = ROUND(TTFXL_NL.MARKET_SPOT_RATE,3) THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_LEG_MAK_SPOT_RATE,
TRIM(ROUND(NEAR_LEG_CCY_TWO_AMOUNT,0)) OPICS_NEAR_LEG_CCY_TWO_AMOUNT ,ROUND(TTFXL_NL.CCY_TWO_AMOUNT_VALUE,0) FIN_NEAR_LEG_CCY_TWO_AMOUNT,CASE WHEN TRIM(ROUND(NEAR_LEG_CCY_TWO_AMOUNT,0)) = ROUND(TTFXL_NL.CCY_TWO_AMOUNT_VALUE,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_LEG_CCY_TWO_AMOUNT,
TRIM(ROUND(FAR_LEG_CCY_ONE_AMOUNT,0)) OPICS_FAR_LEG_CCY_ONE_AMOUNT,ROUND(TTFXL_FL.CCY_ONE_AMOUNT_VALUE,0) FIN_FAR_LEG_CCY_ONE_AMOUNT,CASE WHEN TRIM(ROUND(FAR_LEG_CCY_ONE_AMOUNT,0)) = ROUND(TTFXL_FL.CCY_ONE_AMOUNT_VALUE,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_LEG_CCY_ONE_AMOUNT,
ROUND(TRIM(FAR_LEG_MARKET_FWD_RATE),3) OPICS_FAR_LEG_MAK_FWD_RATE ,ROUND(TTFXL_FL.MARKET_SPOT_RATE,3) FIN_FAR_LEG_MAK_FWD_RATE,CASE WHEN ROUND(TRIM(FAR_LEG_MARKET_FWD_RATE),3) = ROUND(TTFXL_FL.MARKET_SPOT_RATE,3) THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_LEG_MAK_FWD_RATE,
TRIM(ROUND(FAR_LEG_CCY_TWO_AMOUNT,0)) OPICS_FAR_LEG_CCY_TWO_AMOUNT,ROUND(TTFXL_FL.CCY_TWO_AMOUNT_VALUE,0) FIN_FAR_LEG_CCY_TWO_AMOUNT,CASE WHEN TRIM(ROUND(FAR_LEG_CCY_TWO_AMOUNT,0)) = ROUND(TTFXL_FL.CCY_TWO_AMOUNT_VALUE,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_LEG_CCY_TWO_AMOUNT,
TO_DATE(OP_SW.NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')  OPICS_NEAR_VALUE_DATE,TTFXL_NL.VALUE_DATE_ONE FIN_NEAR_VALUE_DATE ,CASE WHEN TO_DATE(OP_SW.NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')  = TTFXL_NL.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_VALUE_DATE,
SI_FLOW_PAY_NOSTRO OPICS_NEAR_PAY_NOSTRO,NEAR_pay_nos FIN_NEAR_PAY_NOSTRO, CASE WHEN nvl(TRIM(SI_FLOW_PAY_NOSTRO),' ') =nvl(TRIM(NEAR_pay_nos),' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_PAY_NOSTRO ,
SI_FLOW_REC_NOSTRO OPICS_NEAR_REC_NOSTRO,NEAR_REC_nos FIN_NEAR_REC_NOSTRO ,CASE WHEN nvl(TRIM(SI_FLOW_REC_NOSTRO),' ') = nvl(TRIM(NEAR_REC_nos),' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_REC_NOSTRO ,
SI_FLOW_FAR_PAY_NOSTRO OPICS_FAR_PAY_NOSTRO,FAR_pay_nos FIN_FAR_PAY_NOSTRO,CASE WHEN nvl(TRIM(SI_FLOW_FAR_PAY_NOSTRO),' ') = nvl(TRIM(FAR_pay_nos),' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_PAY_NOSTRO ,
SI_FLOW_FAR_REC_NOSTRO OPICS_FAR_REC_NOSTRO,FAR_REC_NOS FIN_FAR_REC_NOSTRO,CASE WHEN nvl(TRIM(SI_FLOW_FAR_REC_NOSTRO),' ') = nvl(TRIM(FAR_REC_NOS),' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_REC_NOSTRO ,
TRIM(OP_SW.DEAL_IDENTIFIER)||'-'||TO_DATE(OP_SW.DEAL_DATE,'DD-MON-YYYY')||'-'||OP_SW.SUBTYPE||'-'||OP_SW.ENTITY_NAME||'-'||OP_SW.NEAR_LEG_CCY_PAIR||'-'||TRIM(OP_SW.NEAR_LEG_CPTY)||'-'||TRIM(ROUND(NEAR_LEG_CCY_ONE_AMOUNT,0))||'-'||
ROUND(TRIM(NEAR_LEG_MARKET_SPOT_RATE),3)||'-'||TRIM(ROUND(NEAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')||'-'||TRIM(ROUND(FAR_LEG_CCY_ONE_AMOUNT,0))||'-'||ROUND(TRIM(FAR_LEG_MARKET_FWD_RATE),3)||'-'||
TRIM(ROUND(FAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(FAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY') opics_data,
fin_fx_swap.DEAL_IDENTIFIER||'-'||fin_fx_swap.DEAL_DATE||'-'||SDSBTY.NAME||'-'||SDENT.NAME||'-'||TTFXL_NL.CCY_PAIR||'-'||trim(SDCP.name) ||'-'||ROUND(TTFXL_NL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_NL.MARKET_SPOT_RATE,3)||'-'||
ROUND(TTFXL_NL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_NL.VALUE_DATE_ONE||'-'||ROUND(TTFXL_FL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_FL.MARKET_FWD_RATE,3)||'-'||
ROUND(TTFXL_FL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_FL.VALUE_DATE_ONE fin_data,
CASE WHEN TRIM(OP_SW.DEAL_IDENTIFIER)||'-'||TO_DATE(OP_SW.DEAL_DATE,'DD-MON-YYYY')||'-'||OP_SW.SUBTYPE||'-'||OP_SW.ENTITY_NAME||'-'||OP_SW.NEAR_LEG_CCY_PAIR||'-'||TRIM(OP_SW.NEAR_LEG_CPTY)||'-'||TRIM(ROUND(NEAR_LEG_CCY_ONE_AMOUNT,0))||'-'||
ROUND(TRIM(NEAR_LEG_MARKET_SPOT_RATE),3)||'-'||TRIM(ROUND(NEAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')||'-'||TRIM(ROUND(FAR_LEG_CCY_ONE_AMOUNT,0))||'-'||ROUND(TRIM(FAR_LEG_MARKET_FWD_RATE),3)||'-'||
TRIM(ROUND(FAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(FAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY') = 
fin_fx_swap.DEAL_IDENTIFIER||'-'||fin_fx_swap.DEAL_DATE||'-'||SDSBTY.NAME||'-'||SDENT.NAME||'-'||TTFXL_NL.CCY_PAIR||'-'||trim(SDCP.name) ||'-'||ROUND(TTFXL_NL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_NL.MARKET_SPOT_RATE,3)||'-'||
ROUND(TTFXL_NL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_NL.VALUE_DATE_ONE||'-'||ROUND(TTFXL_FL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_FL.MARKET_FWD_RATE,3)||'-'||
ROUND(TTFXL_FL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_FL.VALUE_DATE_ONE
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
from FX_SWAP_O_TABLE OP_SW
LEFT JOIN TT_FXP_DEAL@ftmig fin_fx_swap on TRIM(OP_SW.DEAL_IDENTIFIER) = TRIM(fin_fx_swap.DEAL_IDENTIFIER) AND  DEAL_TYPE='FXPLSW' AND fin_fx_swap.DEAL_STATE!='DLTD' 
LEFT JOIN SD_TRADING_BOOK@ftmig SDTRBK ON SDTRBK.FBO_ID_NUM = fin_fx_swap.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = fin_fx_swap.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = fin_fx_swap.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM= fin_fx_swap.CPTY_FBO_ID_NUM
--LEFT JOIN TT_FXP_FLOW@ftmig TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM  AND TTFXFL.FXP_FLOW_REFERENCE = '1'
LEFT JOIN (SELECT * FROM (SELECT * FROM  TT_FXP_LEG@ftmig A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@ftmig GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM AND LEG_IDENTIFIER='NELG'))) TTFXL_NL ON  TTFXL_NL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXL_NL.PARENT_FBO_ID_TYPE = fin_fx_swap.DEAL_TYPE
LEFT JOIN (SELECT * FROM (SELECT * FROM  TT_FXP_LEG@ftmig A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@ftmig GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM AND LEG_IDENTIFIER='FALG'))) TTFXL_FL ON  TTFXL_FL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXL_FL.PARENT_FBO_ID_TYPE = fin_fx_swap.DEAL_TYPE
  LEFT JOIN(SELECT distinct a.PARENT_FBO_ID_NUM,a.PARENT_FBO_ID_TYPE,A.IQ_CURRENCY NEAR_PAY_CCY,a.NAME NEAR_pay_nos ,B.IQ_CURRENCY NEAR_REC_CCY,b.NAME NEAR_rec_nos,C.IQ_CURRENCY FAR_PAY_CCY,C.NAME FAR_pay_nos ,D.IQ_CURRENCY FAR_REC_CCY,D.NAME FAR_rec_nos  FROM (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='1') A
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='1') B ON A.PARENT_FBO_ID_TYPE = B.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM
   LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='2') C ON A.PARENT_FBO_ID_TYPE = C.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = C.PARENT_FBO_ID_NUM
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='2') D ON A.PARENT_FBO_ID_TYPE = D.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = D.PARENT_FBO_ID_NUM
  ) NOS ON NOS.PARENT_FBO_ID_NUM =fin_fx_swap.DEAL_NUM  AND NOS.PARENT_FBO_ID_TYPE =fin_fx_swap.DEAL_TYPE
  
   select 
TRIM(OP_SW.DEAL_IDENTIFIER) OPICS_DEALNO ,fin_fx_swap.DEAL_IDENTIFIER FIN_DEAL_IDENTIFIER,CASE WHEN TRIM(OP_SW.DEAL_IDENTIFIER) = fin_fx_swap.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
ENTITY_NAME MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN ENTITY_NAME =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
SUBSTR(TRADING_BOOK,INSTR(TRADING_BOOK,'/',1,4)+1) MAPPED_TRADING_BOOK,SDTRBK.NAME FIN_TRADING_BOOK,CASE WHEN SUBSTR(TRADING_BOOK,INSTR(TRADING_BOOK,'/',1,4)+1) = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK,
SUBTYPE MAPPED_SUBTYPE ,SDSBTY.NAME FIN_SUBTYPE,CASE WHEN SUBTYPE = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
TO_DATE(OP_SW.DEAL_DATE,'DD-MON-YYYY') OPICS_DEAL_DATE ,fin_fx_swap.DEAL_DATE FIN_DEAL_DATE,CASE WHEN TO_DATE(OP_SW.DEAL_DATE,'DD-MON-YYYY') = fin_fx_swap.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
NEAR_LEG_CCY_PAIR MAPPED_CCY_PAIR ,TTFXL_NL.CCY_PAIR FIN_CCY_PAIR,CASE WHEN NEAR_LEG_CCY_PAIR = TTFXL_NL.CCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR,
NEAR_LEG_CPTY OPICS_NEAR_LEG_CPTY ,TRIM(SDCP.name) FIN_NEAR_LEG_CPTY ,CASE WHEN NEAR_LEG_CPTY = TRIM(SDCP.name)THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_LEG_CPTY,
TRIM(ROUND(NEAR_LEG_CCY_ONE_AMOUNT,0)) OPICS_NEAR_LEG_CCY_ONE_AMOUNT ,ROUND(TTFXL_NL.CCY_ONE_AMOUNT_VALUE,0) FIN_NEAR_LEG_CCY_ONE_AMOUNT,CASE WHEN TRIM(ROUND(NEAR_LEG_CCY_ONE_AMOUNT,0)) = ROUND(TTFXL_NL.CCY_ONE_AMOUNT_VALUE,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_LEG_CCY_ONE_AMOUNT,
ROUND(TRIM(NEAR_LEG_MARKET_SPOT_RATE),4) OPICS_NEAR_LEG_MAK_SPOT_RATE ,ROUND(TTFXL_NL.MARKET_SPOT_RATE,4) FIN_NEAR_LEG_MAK_SPOT_RATE,CASE WHEN ROUND(TRIM(NEAR_LEG_MARKET_SPOT_RATE),4) = ROUND(TTFXL_NL.MARKET_SPOT_RATE,4) THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_LEG_MAK_SPOT_RATE,
TRIM(ROUND(NEAR_LEG_CCY_TWO_AMOUNT,0)) OPICS_NEAR_LEG_CCY_TWO_AMOUNT ,ROUND(TTFXL_NL.CCY_TWO_AMOUNT_VALUE,0) FIN_NEAR_LEG_CCY_TWO_AMOUNT,CASE WHEN TRIM(ROUND(NEAR_LEG_CCY_TWO_AMOUNT,0)) = ROUND(TTFXL_NL.CCY_TWO_AMOUNT_VALUE,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_LEG_CCY_TWO_AMOUNT,
TRIM(ROUND(FAR_LEG_CCY_ONE_AMOUNT,0)) OPICS_FAR_LEG_CCY_ONE_AMOUNT,ROUND(TTFXL_FL.CCY_ONE_AMOUNT_VALUE,0) FIN_FAR_LEG_CCY_ONE_AMOUNT,CASE WHEN TRIM(ROUND(FAR_LEG_CCY_ONE_AMOUNT,0)) = ROUND(TTFXL_FL.CCY_ONE_AMOUNT_VALUE,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_LEG_CCY_ONE_AMOUNT,
ROUND(TRIM(FAR_LEG_MARKET_FWD_RATE),4) OPICS_FAR_LEG_MAK_FWD_RATE ,ROUND(TTFXL_FL.MARKET_FWD_RATE+TTFXL_FL.FWD_MARGIN_POINTS,4) FIN_FAR_LEG_MAK_FWD_RATE,CASE WHEN ROUND(TRIM(FAR_LEG_MARKET_FWD_RATE),4) = ROUND(TTFXL_FL.MARKET_FWD_RATE+TTFXL_FL.FWD_MARGIN_POINTS,4) THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_LEG_MAK_FWD_RATE,
TRIM(ROUND(FAR_LEG_CCY_TWO_AMOUNT,0)) OPICS_FAR_LEG_CCY_TWO_AMOUNT,ROUND(TTFXL_FL.CCY_TWO_AMOUNT_VALUE,0) FIN_FAR_LEG_CCY_TWO_AMOUNT,CASE WHEN TRIM(ROUND(FAR_LEG_CCY_TWO_AMOUNT,0)) = ROUND(TTFXL_FL.CCY_TWO_AMOUNT_VALUE,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_LEG_CCY_TWO_AMOUNT,
TO_DATE(OP_SW.NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')  OPICS_NEAR_VALUE_DATE,TTFXL_NL.VALUE_DATE_ONE FIN_NEAR_VALUE_DATE ,CASE WHEN TO_DATE(OP_SW.NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')  = TTFXL_NL.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_VALUE_DATE,
TO_DATE(OP_SW.FAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')  OPICS_FAR_VALUE_DATE,TTFXL_FL.VALUE_DATE_ONE FIN_FAR_VALUE_DATE ,CASE WHEN TO_DATE(OP_SW.FAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')  =TTFXL_FL.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_VALUE_DATE,
SI_FLOW_PAY_NOSTRO OPICS_NEAR_PAY_NOSTRO,NEAR_pay_nos FIN_NEAR_PAY_NOSTRO, CASE WHEN nvl(TRIM(SI_FLOW_PAY_NOSTRO),' ') =nvl(TRIM(NEAR_pay_nos),' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_PAY_NOSTRO ,
SI_FLOW_REC_NOSTRO OPICS_NEAR_REC_NOSTRO,NEAR_REC_nos FIN_NEAR_REC_NOSTRO ,CASE WHEN nvl(TRIM(SI_FLOW_REC_NOSTRO),' ') = nvl(TRIM(NEAR_REC_nos),' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_NEAR_REC_NOSTRO ,
SI_FLOW_FAR_PAY_NOSTRO OPICS_FAR_PAY_NOSTRO,FAR_pay_nos FIN_FAR_PAY_NOSTRO,CASE WHEN nvl(TRIM(SI_FLOW_FAR_PAY_NOSTRO),' ') = nvl(TRIM(FAR_pay_nos),' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_PAY_NOSTRO ,
SI_FLOW_FAR_REC_NOSTRO OPICS_FAR_REC_NOSTRO,FAR_REC_NOS FIN_FAR_REC_NOSTRO,CASE WHEN nvl(TRIM(SI_FLOW_FAR_REC_NOSTRO),' ') = nvl(TRIM(FAR_REC_NOS),' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_FAR_REC_NOSTRO ,
TRIM(OP_SW.DEAL_IDENTIFIER)||'-'||TO_DATE(OP_SW.DEAL_DATE,'DD-MON-YYYY')||'-'||OP_SW.SUBTYPE||'-'||OP_SW.ENTITY_NAME||'-'||OP_SW.NEAR_LEG_CCY_PAIR||'-'||TRIM(OP_SW.NEAR_LEG_CPTY)||'-'||TRIM(ROUND(NEAR_LEG_CCY_ONE_AMOUNT,0))||'-'||
ROUND(TRIM(NEAR_LEG_MARKET_SPOT_RATE),4)||'-'||TRIM(ROUND(NEAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')||'-'||TRIM(ROUND(FAR_LEG_CCY_ONE_AMOUNT,0))||'-'||ROUND(TRIM(FAR_LEG_MARKET_FWD_RATE),4)||'-'||
TRIM(ROUND(FAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(FAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY') opics_data,
fin_fx_swap.DEAL_IDENTIFIER||'-'||fin_fx_swap.DEAL_DATE||'-'||SDSBTY.NAME||'-'||SDENT.NAME||'-'||TTFXL_NL.CCY_PAIR||'-'||trim(SDCP.name) ||'-'||ROUND(TTFXL_NL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_NL.MARKET_SPOT_RATE,4)||'-'||
ROUND(TTFXL_NL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_NL.VALUE_DATE_ONE||'-'||ROUND(TTFXL_FL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_FL.MARKET_FWD_RATE+TTFXL_FL.FWD_MARGIN_POINTS,4)||'-'||
ROUND(TTFXL_FL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_FL.VALUE_DATE_ONE fin_data,
CASE WHEN TRIM(OP_SW.DEAL_IDENTIFIER)||'-'||TO_DATE(OP_SW.DEAL_DATE,'DD-MON-YYYY')||'-'||OP_SW.SUBTYPE||'-'||OP_SW.ENTITY_NAME||'-'||OP_SW.NEAR_LEG_CCY_PAIR||'-'||TRIM(OP_SW.NEAR_LEG_CPTY)||'-'||TRIM(ROUND(NEAR_LEG_CCY_ONE_AMOUNT,0))||'-'||
ROUND(TRIM(NEAR_LEG_MARKET_SPOT_RATE),4)||'-'||TRIM(ROUND(NEAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(NEAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY')||'-'||TRIM(ROUND(FAR_LEG_CCY_ONE_AMOUNT,0))||'-'||ROUND(TRIM(FAR_LEG_MARKET_FWD_RATE),4)||'-'||
TRIM(ROUND(FAR_LEG_CCY_TWO_AMOUNT,0))||'-'||TO_DATE(FAR_LEG_VALUE_DATE_ONE,'DD-MON-YYYY') = 
fin_fx_swap.DEAL_IDENTIFIER||'-'||fin_fx_swap.DEAL_DATE||'-'||SDSBTY.NAME||'-'||SDENT.NAME||'-'||TTFXL_NL.CCY_PAIR||'-'||trim(SDCP.name) ||'-'||ROUND(TTFXL_NL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_NL.MARKET_SPOT_RATE,4)||'-'||
ROUND(TTFXL_NL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_NL.VALUE_DATE_ONE||'-'||ROUND(TTFXL_FL.CCY_ONE_AMOUNT_VALUE,0)||'-'||ROUND(TTFXL_FL.MARKET_FWD_RATE+TTFXL_FL.FWD_MARGIN_POINTS,4)||'-'||
ROUND(TTFXL_FL.CCY_TWO_AMOUNT_VALUE,0)||'-'||TTFXL_FL.VALUE_DATE_ONE
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
from FX_SWAP_O_TABLE OP_SW
LEFT JOIN TT_FXP_DEAL@ftmig fin_fx_swap on TRIM(OP_SW.DEAL_IDENTIFIER) = TRIM(fin_fx_swap.DEAL_IDENTIFIER) AND  DEAL_TYPE='FXPLSW' AND fin_fx_swap.DEAL_STATE!='DLTD' 
LEFT JOIN SD_TRADING_BOOK@ftmig SDTRBK ON SDTRBK.FBO_ID_NUM = fin_fx_swap.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = fin_fx_swap.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = fin_fx_swap.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM= fin_fx_swap.CPTY_FBO_ID_NUM
--LEFT JOIN TT_FXP_FLOW@ftmig TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM  AND TTFXFL.FXP_FLOW_REFERENCE = '1'
LEFT JOIN (SELECT * FROM (SELECT * FROM  TT_FXP_LEG@ftmig A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@ftmig GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM AND LEG_IDENTIFIER='NELG'))) TTFXL_NL ON  TTFXL_NL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXL_NL.PARENT_FBO_ID_TYPE = fin_fx_swap.DEAL_TYPE
LEFT JOIN (SELECT * FROM (SELECT * FROM  TT_FXP_LEG@ftmig A WHERE EXISTS(
  SELECT * FROM (SELECT PARENT_FBO_ID_NUM,FX_BUY_SELL,MAX(FBO_ID_NUM) FBO_ID_NUM FROM  TT_FXP_LEG@ftmig GROUP BY PARENT_FBO_ID_NUM,FX_BUY_SELL) B WHERE A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM AND A.FX_BUY_SELL =B.FX_BUY_SELL AND 
  A.FBO_ID_NUM = B.FBO_ID_NUM AND LEG_IDENTIFIER='FALG'))) TTFXL_FL ON  TTFXL_FL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXL_FL.PARENT_FBO_ID_TYPE = fin_fx_swap.DEAL_TYPE
  LEFT JOIN(SELECT distinct a.PARENT_FBO_ID_NUM,a.PARENT_FBO_ID_TYPE,A.IQ_CURRENCY NEAR_PAY_CCY,a.NAME NEAR_pay_nos ,B.IQ_CURRENCY NEAR_REC_CCY,b.NAME NEAR_rec_nos,C.IQ_CURRENCY FAR_PAY_CCY,C.NAME FAR_pay_nos ,D.IQ_CURRENCY FAR_REC_CCY,D.NAME FAR_rec_nos  FROM (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='1') A
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='1') B ON A.PARENT_FBO_ID_TYPE = B.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM
   LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='2') C ON A.PARENT_FBO_ID_TYPE = C.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = C.PARENT_FBO_ID_NUM
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='2') D ON A.PARENT_FBO_ID_TYPE = D.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = D.PARENT_FBO_ID_NUM
  ) NOS ON NOS.PARENT_FBO_ID_NUM =fin_fx_swap.DEAL_NUM  AND NOS.PARENT_FBO_ID_TYPE =fin_fx_swap.DEAL_TYPE 
