========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
internal_deals_report.sql 
select FX_BUY_SELL,
TRIM(DEALNO)||'-'||DEALDATE||'-'||VDATE||'-'||
MDATE||'-'||CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END||'-'||
trim(CCYNEARRATE_8)||'-'||ABS(round(CCYPRINAMT,2))||'-'||ABS(round(CTRPRINAMT,2))||'-'||ABS(round(CTRAMT,2))||'-'||trim(ABS(round(CCYAMT,2)))||'-'||trim(abs(CCYFARRATE_8))||'-'||
trim(abs(CCYINTRATE_8))||'-'||trim(abs(CTRINTRATE_8)) CONV_OPICS_DATA,
FIN_FX.deal_identifier||'-'||DEAL_DATE||'-'||START_DATE||'-'||END_DATE||'-'||SDENT.name||'-'||FIN_FX.CURRENCY_PAIR||'-'||FIN_FX.CONTRACT_RATE||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2)  else ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) end||'-'||abs(to_number(FWD_CONTRACT_RATE))||'-'||
round(TO_NUMBER(abs(DEPO_RATE)*100),8)||'-'||round(TO_NUMBER( abs(LOAN_RATE)*100),8) FIN_DATA,
CASE WHEN TRIM(DEALNO)||'-'||DEALDATE||'-'||VDATE||'-'||
MDATE||'-'||CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END||'-'||
trim(CCYNEARRATE_8)||'-'||ABS(round(CCYPRINAMT,2))||'-'||ABS(round(CTRPRINAMT,2))||'-'||ABS(round(CTRAMT,2))||'-'||trim(ABS(round(CCYAMT,2)))||'-'||trim(abs(CCYFARRATE_8))||'-'||
trim(abs(CCYINTRATE_8))||'-'||trim(abs(CTRINTRATE_8)) = 
FIN_FX.deal_identifier||'-'||DEAL_DATE||'-'||START_DATE||'-'||END_DATE||'-'||SDENT.name||'-'||FIN_FX.CURRENCY_PAIR||'-'||FIN_FX.CONTRACT_RATE||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2)  else ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) end||'-'||abs(FWD_CONTRACT_RATE)||'-'||
round(TO_NUMBER(abs(DEPO_RATE)*100),8)||'-'||round(TO_NUMBER( abs(LOAN_RATE)*100),8) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
 from  FXIH
LEFT JOIN SPOT_RATES_O_TABLE ON CURRENCY_PAIR = CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END
LEFT JOIN TT_FX_ARB@ftmig FIN_FX ON TRIM(DEALNO) = TRIM(FIN_FX.DEAL_IDENTIFIER) and DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@ftmig SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = FIN_FX.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM = FIN_FX.CPTY_FBO_ID_NUM
WHERE MDATE > to_date(get_param('EOD_DATE'),'dd-mm-yyyy') AND BR = '01'AND REVDATE IS NULL



select FX_BUY_SELL,
TRIM(DEALNO)||'-'||DEALDATE||'-'||VDATE||'-'||
MDATE||'-'||CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END||'-'||
CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END||'-'||
trim(CCYNEARRATE_8)||'-'||ABS(round(CCYPRINAMT,2))||'-'||ABS(round(CTRPRINAMT,2))||'-'||ABS(round(CTRAMT,2))||'-'||trim(ABS(round(CCYAMT,2)))||'-'||trim(abs(CCYFARRATE_8))||'-'||
trim(abs(CCYINTRATE_8))||'-'||trim(abs(CTRINTRATE_8)) CONV_OPICS_DATA,
FIN_FX.deal_identifier||'-'||DEAL_DATE||'-'||START_DATE||'-'||END_DATE||'-'||SDENT.name||'-'||FIN_FX.CURRENCY_PAIR||'-'||
 CASE WHEN FX_BUY_SELL='B' THEN 'BUY' WHEN FX_BUY_SELL='S' THEN 'SELL' END||'-'||
FIN_FX.CONTRACT_RATE||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2)  else ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) end||'-'||abs(to_number(FWD_CONTRACT_RATE))||'-'||
round(TO_NUMBER(abs(DEPO_RATE)*100),8)||'-'||round(TO_NUMBER( abs(LOAN_RATE)*100),8) FIN_DATA,
CASE WHEN TRIM(DEALNO)||'-'||DEALDATE||'-'||VDATE||'-'||
MDATE||'-'||CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END||'-'||
CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END||'-'||
trim(CCYNEARRATE_8)||'-'||ABS(round(CCYPRINAMT,2))||'-'||ABS(round(CTRPRINAMT,2))||'-'||ABS(round(CTRAMT,2))||'-'||trim(ABS(round(CCYAMT,2)))||'-'||trim(abs(CCYFARRATE_8))||'-'||
trim(abs(CCYINTRATE_8))||'-'||trim(abs(CTRINTRATE_8)) = 
FIN_FX.deal_identifier||'-'||DEAL_DATE||'-'||START_DATE||'-'||END_DATE||'-'||SDENT.name||'-'||FIN_FX.CURRENCY_PAIR||'-'||
CASE WHEN FX_BUY_SELL='B' THEN 'BUY' WHEN FX_BUY_SELL='S' THEN 'SELL' END||'-'||FIN_FX.CONTRACT_RATE||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2)  else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end||'-'||abs(FWD_CONTRACT_RATE)||'-'||
round(TO_NUMBER(abs(DEPO_RATE)*100),8)||'-'||round(TO_NUMBER( abs(LOAN_RATE)*100),8) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
 from  FXIH
LEFT JOIN SPOT_RATES_O_TABLE ON CURRENCY_PAIR = CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END
LEFT JOIN TT_FX_ARB@ftmig FIN_FX ON TRIM(DEALNO) = TRIM(FIN_FX.DEAL_IDENTIFIER) and DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@ftmig SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = FIN_FX.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM = FIN_FX.CPTY_FBO_ID_NUM
WHERE MDATE > to_date(get_param('EOD_DATE'),'dd-mm-yyyy') AND BR = '01'AND REVDATE IS NULL






select FX_BUY_SELL,
TRIM(DEALNO)||'-'||DEALDATE||'-'||VDATE||'-'||
MDATE||'-'||CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END||'-'||
CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END||'-'||
trim(CCYNEARRATE_8)||'-'||ABS(round(CCYPRINAMT,2))||'-'||ABS(round(CTRPRINAMT,2))||'-'||ABS(round(CTRAMT,2))||'-'||trim(ABS(round(CCYAMT,2)))||'-'||trim(abs(CCYFARRATE_8))||'-'||
trim(abs(CCYINTRATE_8))||'-'||trim(abs(CTRINTRATE_8)) CONV_OPICS_DATA,
FIN_FX.deal_identifier||'-'||DEAL_DATE||'-'||START_DATE||'-'||END_DATE||'-'||SDENT.name||'-'||FIN_FX.CURRENCY_PAIR||'-'||
 CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END||'-'||FIN_FX.CONTRACT_RATE||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2)  else ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) end||'-'||abs(to_number(FWD_CONTRACT_RATE))||'-'||
round(TO_NUMBER(abs(DEPO_RATE)*100),8)||'-'||round(TO_NUMBER( abs(LOAN_RATE)*100),8) FIN_DATA,
CASE WHEN TRIM(DEALNO)||'-'||DEALDATE||'-'||VDATE||'-'||
MDATE||'-'||CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END||'-'||
CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END||'-'||
trim(CCYNEARRATE_8)||'-'||ABS(round(CCYPRINAMT,2))||'-'||ABS(round(CTRPRINAMT,2))||'-'||ABS(round(CTRAMT,2))||'-'||trim(ABS(round(CCYAMT,2)))||'-'||trim(abs(CCYFARRATE_8))||'-'||
trim(abs(CCYINTRATE_8))||'-'||trim(abs(CTRINTRATE_8)) = 
FIN_FX.deal_identifier||'-'||DEAL_DATE||'-'||START_DATE||'-'||END_DATE||'-'||SDENT.name||'-'||FIN_FX.CURRENCY_PAIR||'-'||
 CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END||'-'||FIN_FX.CONTRACT_RATE||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2)  else ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) end||'-'||abs(FWD_CONTRACT_RATE)||'-'||
round(TO_NUMBER(abs(DEPO_RATE)*100),8)||'-'||round(TO_NUMBER( abs(LOAN_RATE)*100),8) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
 from  FXIH
LEFT JOIN SPOT_RATES_O_TABLE ON CURRENCY_PAIR = CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END
LEFT JOIN TT_FX_ARB@ftmig FIN_FX ON TRIM(DEALNO) = TRIM(FIN_FX.DEAL_IDENTIFIER) and DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@ftmig SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = FIN_FX.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM = FIN_FX.CPTY_FBO_ID_NUM
WHERE MDATE > to_date(get_param('EOD_DATE'),'dd-mm-yyyy') AND BR = '01'AND REVDATE IS NULL


--POST MOCK5A

select 
DEALNO OPICS_DEALNO ,FIN_FX.DEAL_IDENTIFIER FIN_DEAL_IDENTIFIER,CASE WHEN TRIM(DEALNO) = FIN_FX.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
BR OPICS_BR, CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
DEALDATE OPICS_DEAL_DATE ,FIN_FX.DEAL_DATE FIN_DEAL_DATE,CASE WHEN DEALDATE= FIN_FX.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
'TREASURY' MAPPED_TRADING_BOOK,SDTRBK.NAME FIN_TRADING_BOOK,CASE WHEN 'TREASURY' = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK,
'ARBTRG' MAPPED_SUBTYPE ,SDSBTY.NAME FIN_SUBTYPE,CASE WHEN 'ARBTRG' = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
VDATE OPICS_START_DATE ,START_DATE FIN_START_DATE,CASE WHEN VDATE = START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
MDATE OPICS_END_DATE ,END_DATE FIN_END_DATE,CASE WHEN MDATE = END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END MAPPED_CCY_PAIR ,FIN_FX.CURRENCY_PAIR FINCCY_PAIR,CASE WHEN CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END = FIN_FX.CURRENCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR,
PS OPICS_PS,CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END MAPPED_BUY_SELL,CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END FIN_BUY_SELL,CASE WHEN CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END = CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END THEN 'TRUE' ELSE 'FALSE' END MATCH_BUY_SELL,
trim(CCYNEARRATE_8) OPICS_CCYNEAR_RATE,FIN_FX.CONTRACT_RATE FIN_CCYNEAR_RATE,CASE WHEN trim(CCYNEARRATE_8) = FIN_FX.CONTRACT_RATE THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYNEAR_RATE,
ABS(round(CCYPRINAMT,2)) OPICS_CCYPRINAMT,case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end FIN_CCYPRINAMT,CASE WHEN ABS(round(CCYPRINAMT,2)) = case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYPRINAMT,
ABS(round(CTRPRINAMT,2)) OPICS_CTRPRINAMT,case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end FIN_CTRPRINAMT,CASE WHEN ABS(round(CTRPRINAMT,2)) = case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end THEN 'TRUE' ELSE 'FALSE' END MATCH_CTRPRINAMT,
ABS(round(CTRAMT,2)) OPICS_CTRAMT,case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end FIN_CTRAMT,CASE WHEN ABS(round(CTRAMT,2)) = case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end THEN 'TRUE' ELSE 'FALSE' END MATCH_CTRAMT,
trim(ABS(round(CCYAMT,2))) OPICS_CCYAMT,case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end FIN_CCYAMT,CASE WHEN trim(ABS(round(CCYAMT,2))) = case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYAMT,
trim(abs(CCYFARRATE_8)) OPICS_CCY_FAR_RATE,abs(to_number(FWD_CONTRACT_RATE)) FIN_CCY_FAR_RATE,CASE WHEN trim(abs(CCYFARRATE_8)) = abs(to_number(FWD_CONTRACT_RATE)) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_FAR_RATE,
trim(abs(CCYINTRATE_8)) OPICS_CCY_INT_RATE,round(TO_NUMBER(abs(DEPO_RATE)*100),8) FIN_CCY_INT_RATE,CASE WHEN trim(abs(CCYINTRATE_8)) = round(TO_NUMBER(abs(DEPO_RATE)*100),8) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_INT_RATE,
trim(abs(CTRINTRATE_8)) OPICS_CTR_INT_RATE,round(TO_NUMBER( abs(LOAN_RATE)*100),8) FIN_CTR_INT_RATE,CASE WHEN trim(abs(CTRINTRATE_8)) = round(TO_NUMBER( abs(LOAN_RATE)*100),8) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTR_INT_RATE,
TRIM(DEALNO)||'-'||DEALDATE||'-'||VDATE||'-'||
MDATE||'-'||CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END||'-'||
CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END||'-'||
trim(CCYNEARRATE_8)||'-'||ABS(round(CCYPRINAMT,2))||'-'||ABS(round(CTRPRINAMT,2))||'-'||ABS(round(CTRAMT,2))||'-'||trim(ABS(round(CCYAMT,2)))||'-'||trim(abs(CCYFARRATE_8))||'-'||
trim(abs(CCYINTRATE_8))||'-'||trim(abs(CTRINTRATE_8)) CONV_OPICS_DATA,
FIN_FX.deal_identifier||'-'||DEAL_DATE||'-'||START_DATE||'-'||END_DATE||'-'||SDENT.name||'-'||FIN_FX.CURRENCY_PAIR||'-'||
 CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END||'-'||FIN_FX.CONTRACT_RATE||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2)  else ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) end||'-'||abs(to_number(FWD_CONTRACT_RATE))||'-'||
round(TO_NUMBER(abs(DEPO_RATE)*100),8)||'-'||round(TO_NUMBER( abs(LOAN_RATE)*100),8) FIN_DATA,
CASE WHEN TRIM(DEALNO)||'-'||DEALDATE||'-'||VDATE||'-'||
MDATE||'-'||CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END||'-'||
CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END||'-'||
trim(CCYNEARRATE_8)||'-'||ABS(round(CCYPRINAMT,2))||'-'||ABS(round(CTRPRINAMT,2))||'-'||ABS(round(CTRAMT,2))||'-'||trim(ABS(round(CCYAMT,2)))||'-'||trim(abs(CCYFARRATE_8))||'-'||
trim(abs(CCYINTRATE_8))||'-'||trim(abs(CTRINTRATE_8)) = 
FIN_FX.deal_identifier||'-'||DEAL_DATE||'-'||START_DATE||'-'||END_DATE||'-'||SDENT.name||'-'||FIN_FX.CURRENCY_PAIR||'-'||
 CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END||'-'||FIN_FX.CONTRACT_RATE||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2)  else ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) end||'-'||abs(FWD_CONTRACT_RATE)||'-'||
round(TO_NUMBER(abs(DEPO_RATE)*100),8)||'-'||round(TO_NUMBER( abs(LOAN_RATE)*100),8) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
 from  FXIH
LEFT JOIN SPOT_RATES_O_TABLE ON CURRENCY_PAIR = CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END
LEFT JOIN TT_FX_ARB@ftmig FIN_FX ON TRIM(DEALNO) = TRIM(FIN_FX.DEAL_IDENTIFIER) and DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@ftmig SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = FIN_FX.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM = FIN_FX.CPTY_FBO_ID_NUM
WHERE MDATE > to_date(get_param('EOD_DATE'),'dd-mm-yyyy') AND BR = '01'AND REVDATE IS NULL


--MOCK FODS2

select 
DEALNO OPICS_DEALNO ,FIN_FX.DEAL_IDENTIFIER FIN_DEAL_IDENTIFIER,CASE WHEN TRIM(DEALNO) = FIN_FX.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
BR OPICS_BR, CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
DEALDATE OPICS_DEAL_DATE ,FIN_FX.DEAL_DATE FIN_DEAL_DATE,CASE WHEN DEALDATE= FIN_FX.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
'TREASURY' MAPPED_TRADING_BOOK,SDTRBK.NAME FIN_TRADING_BOOK,CASE WHEN 'TREASURY' = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK,
'ARBTRG' MAPPED_SUBTYPE ,SDSBTY.NAME FIN_SUBTYPE,CASE WHEN 'ARBTRG' = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
VDATE OPICS_START_DATE ,START_DATE FIN_START_DATE,CASE WHEN VDATE = START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
MDATE OPICS_END_DATE ,END_DATE FIN_END_DATE,CASE WHEN MDATE = END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END MAPPED_CCY_PAIR ,FIN_FX.CURRENCY_PAIR FINCCY_PAIR,CASE WHEN CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END = FIN_FX.CURRENCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR,
PS OPICS_PS,CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END MAPPED_BUY_SELL,CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END FIN_BUY_SELL,CASE WHEN CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END = CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END THEN 'TRUE' ELSE 'FALSE' END MATCH_BUY_SELL,
trim(CCYNEARRATE_8) OPICS_CCYNEAR_RATE,FIN_FX.CONTRACT_RATE FIN_CCYNEAR_RATE,CASE WHEN trim(CCYNEARRATE_8) = FIN_FX.CONTRACT_RATE THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYNEAR_RATE,
ABS(round(CCYPRINAMT,2)) OPICS_CCYPRINAMT,ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) FIN_CCYPRINAMT,CASE WHEN ABS(round(CCYPRINAMT,2)) = ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2)  THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYPRINAMT,
ABS(round(CTRPRINAMT,2)) OPICS_CTRPRINAMT,ROUND(ABS(FIN_FX.CCY_two_AMOUNT_VALUE),2) FIN_CTRPRINAMT,CASE WHEN ABS(round(CTRPRINAMT,2)) = ROUND(ABS(FIN_FX.CCY_two_AMOUNT_VALUE),2)  THEN 'TRUE' ELSE 'FALSE' END MATCH_CTRPRINAMT,
ABS(round(CTRAMT,2)) OPICS_CTRAMT,ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) FIN_CTRAMT,CASE WHEN ABS(round(CTRAMT,2)) = ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTRAMT,
trim(ABS(round(CCYAMT,2))) OPICS_CCYAMT,ROUND(ABS(FIN_FX.CCY_one_SWAP_AMOUNT_VALUE),2) FIN_CCYAMT,CASE WHEN trim(ABS(round(CCYAMT,2))) = ROUND(ABS(FIN_FX.CCY_one_SWAP_AMOUNT_VALUE),2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYAMT,
trim(abs(CCYFARRATE_8)) OPICS_CCY_FAR_RATE,abs(to_number(FWD_CONTRACT_RATE)) FIN_CCY_FAR_RATE,CASE WHEN trim(abs(CCYFARRATE_8)) = abs(to_number(FWD_CONTRACT_RATE)) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_FAR_RATE,
trim(abs(CCYINTRATE_8)) OPICS_CCY_INT_RATE,round(TO_NUMBER(abs(DEPO_RATE)*100),8) FIN_CCY_INT_RATE,CASE WHEN trim(abs(CCYINTRATE_8)) = round(TO_NUMBER(abs(DEPO_RATE)*100),8) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_INT_RATE,
trim(abs(CTRINTRATE_8)) OPICS_CTR_INT_RATE,round(TO_NUMBER( abs(LOAN_RATE)*100),8) FIN_CTR_INT_RATE,CASE WHEN trim(abs(CTRINTRATE_8)) = round(TO_NUMBER( abs(LOAN_RATE)*100),8) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTR_INT_RATE,
TRIM(DEALNO)||'-'||DEALDATE||'-'||VDATE||'-'||
MDATE||'-'||CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END||'-'||
CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END||'-'||
trim(CCYNEARRATE_8)||'-'||ABS(round(CCYPRINAMT,2))||'-'||ABS(round(CTRPRINAMT,2))||'-'||ABS(round(CTRAMT,2))||'-'||trim(ABS(round(CCYAMT,2)))||'-'||trim(abs(CCYFARRATE_8))||'-'||
trim(abs(CCYINTRATE_8))||'-'||trim(abs(CTRINTRATE_8)) CONV_OPICS_DATA,
FIN_FX.deal_identifier||'-'||DEAL_DATE||'-'||START_DATE||'-'||END_DATE||'-'||SDENT.name||'-'||FIN_FX.CURRENCY_PAIR||'-'||
 CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END||'-'||FIN_FX.CONTRACT_RATE||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2)  else ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) end||'-'||abs(to_number(FWD_CONTRACT_RATE))||'-'||
round(TO_NUMBER(abs(DEPO_RATE)*100),8)||'-'||round(TO_NUMBER( abs(LOAN_RATE)*100),8) FIN_DATA,
CASE WHEN TRIM(DEALNO)||'-'||DEALDATE||'-'||VDATE||'-'||
MDATE||'-'||CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END||'-'||
CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END||'-'||
trim(CCYNEARRATE_8)||'-'||ABS(round(CCYPRINAMT,2))||'-'||ABS(round(CTRPRINAMT,2))||'-'||ABS(round(CTRAMT,2))||'-'||trim(ABS(round(CCYAMT,2)))||'-'||trim(abs(CCYFARRATE_8))||'-'||
trim(abs(CCYINTRATE_8))||'-'||trim(abs(CTRINTRATE_8)) = 
FIN_FX.deal_identifier||'-'||DEAL_DATE||'-'||START_DATE||'-'||END_DATE||'-'||SDENT.name||'-'||FIN_FX.CURRENCY_PAIR||'-'||
 CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END||'-'||FIN_FX.CONTRACT_RATE||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_TWO_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) else ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) end||'-'||
case when FX_BUY_SELL='S' then ROUND(ABS(FIN_FX.CCY_ONE_SWAP_AMOUNT_VALUE),2)  else ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) end||'-'||abs(FWD_CONTRACT_RATE)||'-'||
round(TO_NUMBER(abs(DEPO_RATE)*100),8)||'-'||round(TO_NUMBER( abs(LOAN_RATE)*100),8) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
 from  FXIH
LEFT JOIN SPOT_RATES_O_TABLE ON CURRENCY_PAIR = CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END
LEFT JOIN TT_FX_ARB@ftmig FIN_FX ON TRIM(DEALNO) = TRIM(FIN_FX.DEAL_IDENTIFIER) and DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@ftmig SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = FIN_FX.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM = FIN_FX.CPTY_FBO_ID_NUM
WHERE MDATE > to_date(get_param('EOD_DATE'),'dd-mm-yyyy') AND BR = '01'AND REVDATE IS NULL


select 
DEALNO OPICS_DEALNO ,FIN_FX.DEAL_IDENTIFIER FIN_DEAL_IDENTIFIER,CASE WHEN TRIM(DEALNO) = FIN_FX.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
BR OPICS_BR, CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN CASE WHEN TRIM(BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
DEALDATE OPICS_DEAL_DATE ,FIN_FX.DEAL_DATE FIN_DEAL_DATE,CASE WHEN DEALDATE= FIN_FX.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
'TREASURY' MAPPED_TRADING_BOOK,SDTRBK.NAME FIN_TRADING_BOOK,CASE WHEN 'TREASURY' = SDTRBK.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_TRADING_BOOK,
'ARBTRG' MAPPED_SUBTYPE ,SDSBTY.NAME FIN_SUBTYPE,CASE WHEN 'ARBTRG' = SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
VDATE OPICS_START_DATE ,START_DATE FIN_START_DATE,CASE WHEN VDATE = START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
MDATE OPICS_END_DATE ,END_DATE FIN_END_DATE,CASE WHEN MDATE = END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END MAPPED_CCY_PAIR ,FIN_FX.CURRENCY_PAIR FINCCY_PAIR,CASE WHEN CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END = FIN_FX.CURRENCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR,
PS OPICS_PS,CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END MAPPED_BUY_SELL,CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END FIN_BUY_SELL,CASE WHEN CASE WHEN PS='P' THEN 'BUY' WHEN PS='S' THEN 'SELL' END = CASE WHEN FX_BUY_SELL='B' THEN 'SELL' WHEN FX_BUY_SELL='S' THEN 'BUY' END THEN 'TRUE' ELSE 'FALSE' END MATCH_BUY_SELL,
trim(CCYNEARRATE_8) OPICS_CCYNEAR_RATE,FIN_FX.CONTRACT_RATE FIN_CCYNEAR_RATE,CASE WHEN trim(CCYNEARRATE_8) = FIN_FX.CONTRACT_RATE THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYNEAR_RATE,
ABS(round(CCYPRINAMT,2)) OPICS_CCYPRINAMT,ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2) FIN_CCYPRINAMT,CASE WHEN ABS(round(CCYPRINAMT,2)) = ROUND(ABS(FIN_FX.CCY_one_AMOUNT_VALUE),2)  THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYPRINAMT,
ABS(round(CTRPRINAMT,2)) OPICS_CTRPRINAMT,ROUND(ABS(FIN_FX.CCY_two_AMOUNT_VALUE),2) FIN_CTRPRINAMT,CASE WHEN ABS(round(CTRPRINAMT,2)) = ROUND(ABS(FIN_FX.CCY_two_AMOUNT_VALUE),2)  THEN 'TRUE' ELSE 'FALSE' END MATCH_CTRPRINAMT,
ABS(round(CTRAMT,2)) OPICS_CTRAMT,ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) FIN_CTRAMT,CASE WHEN ABS(round(CTRAMT,2)) = ROUND(ABS(FIN_FX.CCY_two_SWAP_AMOUNT_VALUE),2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CTRAMT,
trim(ABS(round(CCYAMT,2))) OPICS_CCYAMT,ROUND(ABS(FIN_FX.CCY_one_SWAP_AMOUNT_VALUE),2) FIN_CCYAMT,CASE WHEN trim(ABS(round(CCYAMT,2))) = ROUND(ABS(FIN_FX.CCY_one_SWAP_AMOUNT_VALUE),2) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCYAMT,
trim(abs(CCYFARRATE_8)) OPICS_CCY_FAR_RATE,abs(to_number(FWD_CONTRACT_RATE)) FIN_CCY_FAR_RATE,CASE WHEN trim(abs(CCYFARRATE_8)) = abs(to_number(FWD_CONTRACT_RATE)) THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_FAR_RATE,
trim(abs(CCYINTRATE_8)) OPICS_CCY_INT_RATE,CASE WHEN PS='P' THEN round(TO_NUMBER(abs(DEPO_RATE)*100),8) WHEN PS='S' THEN round(TO_NUMBER( abs(LOAN_RATE)*100),8) END  FIN_CCY_INT_RATE,CASE WHEN trim(abs(CCYINTRATE_8)) = CASE WHEN PS='P' THEN round(TO_NUMBER(abs(DEPO_RATE)*100),8) WHEN PS='S' THEN round(TO_NUMBER( abs(LOAN_RATE)*100),8) END THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_INT_RATE,
trim(abs(CTRINTRATE_8)) OPICS_CTR_INT_RATE,CASE WHEN PS='P' THEN round(TO_NUMBER( abs(LOAN_RATE)*100),8) WHEN PS='S' THEN  round(TO_NUMBER(abs(DEPO_RATE)*100),8) END  FIN_CTR_INT_RATE,CASE WHEN trim(abs(CTRINTRATE_8)) = CASE WHEN PS='P' THEN round(TO_NUMBER( abs(LOAN_RATE)*100),8) WHEN PS='S' THEN  round(TO_NUMBER(abs(DEPO_RATE)*100),8) END THEN 'TRUE' ELSE 'FALSE' END MATCH_CTR_INT_RATE
 from  FXIH
LEFT JOIN SPOT_RATES_O_TABLE ON CURRENCY_PAIR = CASE WHEN CCYTERMS='M' THEN TRIM(CCY)||'/'||TRIM(CTRCCY) ELSE TRIM(CTRCCY)||'/'||TRIM(CCY) END
LEFT JOIN TT_FX_ARB@ftmig FIN_FX ON TRIM(DEALNO) = TRIM(FIN_FX.DEAL_IDENTIFIER) and DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@ftmig SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftmig SDENT ON SDENT.FBO_ID_NUM = FIN_FX.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftmig SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftmig SDCP ON SDCP.FBO_ID_NUM = FIN_FX.CPTY_FBO_ID_NUM
WHERE MDATE > to_date(get_param('EOD_DATE'),'dd-mm-yyyy') AND BR = '01'AND REVDATE IS NULL 
