========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
missing_limit.sql 
select
TO_CHAR(
TRIM(RESPONSE                       ),
TRIM(FBO_TYPE                       ),
TRIM(LIMIT_NAME                     ),
TRIM(USER_LIMIT_TYPE                ),
TRIM(USER_LIMIT_TYPE_SYS_LIMIT_TYPE ),
TRIM(LIMIT_CCY                      ),
TRIM(LIMIT_AMOUNT                   ),
TRIM(EXCESS_ACTION                  ),
TRIM(BREACH_LEVEL_TYPE              ),
TRIM(USER_LIMIT_TYP_EXP_AGGR_METHOD ),
TRIM(EXPIRY_DATE                    ),
TRIM(ENTITY                         ),
TRIM(SUBTYPE                        ),
TRIM(DEPT_NAME                      ),
TRIM(COUNTERPARTY_STRING            ),
TRIM(ENTITY_NAME                    ),
TRIM(ALERT_USER_GROUP               ),
TRIM(EXC_AUTH_PRIV_GROUP            ),
TRIM(REPORT_PRIV_GROUP              ),
TRIM(EMAIL_ID                       ),
TRIM(TENOR_START_CODE               ),
TRIM(TENOR_START_YEARS              ),
TRIM(TENOR_START_MONTHS             ),
TRIM(TENOR_START_DAYS               ),
TRIM(TENOR_END_CODE                 ),
TRIM(TENOR_END_YEARS                ),
TRIM(TENOR_END_MONTHS               ),
TRIM(TENOR_END_DAYS                 )
)
from CPTY_CUST_GROUP_LIMIT_O_TABLE WHERE LIMIT_NAME IN(
select LIMIT_NAME from (SELECT CPTY_GROUP_LIMIT.LIMIT_NAME,CPTY_GROUP_LIMIT.COUNTERPARTY_STRING,CPTY_GROUP_LIMIT.ENTITY||'-'||CPTY_GROUP_LIMIT.COUNTERPARTY_STRING||'-'||CPTY_GROUP_LIMIT.LIMIT_NAME||'-'||CPTY_GROUP_LIMIT.LIMIT_CCY||'-'||CPTY_GROUP_LIMIT.LIMIT_AMOUNT||'-'||
TO_DATE(CPTY_GROUP_LIMIT.EXPIRY_DATE,'DD-MON-YYYY')||'-'||CPTY_GROUP_LIMIT.TENOR_END_YEARS||'-'||CPTY_GROUP_LIMIT.TENOR_END_MONTHS||'-'||CPTY_GROUP_LIMIT.TENOR_END_DAYS OPICS_DATA,
SDENT.NAME||'-'||SDCP.NAME||'-'||CPTY_LIMIT.LIMIT_NAME||'-'||CPTY_LIMIT.LIMIT_CCY||'-'||CPTY_LIMIT.LIMIT_AMOUNT||'-'||CPTY_LIMIT.EXPIRY_DATE||'-'||CPTY_LIMIT.TENOR_END_YEARS||'-'||
CPTY_LIMIT.TENOR_END_MONTHS||'-'||CPTY_LIMIT.TENOR_END_DAYS FIN_DATA,
CASE WHEN CPTY_GROUP_LIMIT.ENTITY||'-'||CPTY_GROUP_LIMIT.COUNTERPARTY_STRING||'-'||CPTY_GROUP_LIMIT.LIMIT_NAME||'-'||CPTY_GROUP_LIMIT.LIMIT_CCY||'-'||CPTY_GROUP_LIMIT.LIMIT_AMOUNT||'-'||
TO_DATE(CPTY_GROUP_LIMIT.EXPIRY_DATE,'DD-MON-YYYY')||'-'||CPTY_GROUP_LIMIT.TENOR_END_YEARS||'-'||CPTY_GROUP_LIMIT.TENOR_END_MONTHS||'-'||CPTY_GROUP_LIMIT.TENOR_END_DAYS = 
SDENT.NAME||'-'||SDCP.NAME||'-'||CPTY_LIMIT.LIMIT_NAME||'-'||CPTY_LIMIT.LIMIT_CCY||'-'||CPTY_LIMIT.LIMIT_AMOUNT||'-'||CPTY_LIMIT.EXPIRY_DATE||'-'||CPTY_LIMIT.TENOR_END_YEARS||'-'||
CPTY_LIMIT.TENOR_END_MONTHS||'-'||CPTY_LIMIT.TENOR_END_DAYS
 THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
 FROM CPTY_CUST_GROUP_LIMIT_O_TABLE CPTY_GROUP_LIMIT
LEFT JOIN SD_CPTY_LIMIT_INFO@FTMIG CPTY_LIMIT ON TRIM(CPTY_LIMIT.LIMIT_NAME) =TRIM(CPTY_GROUP_LIMIT.LIMIT_NAME)
       LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= CPTY_LIMIT.COUNTERPARTY_FBO_ID_NUM
       LEFT JOIN sd_user_limit_type@FTMIG ULT ON ULT.FBO_ID_NUM = CPTY_LIMIT.USER_LIMIT_TYPE_FBO_ID_NUM
       LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = CPTY_LIMIT.ENTITY_NAME_FBO_ID_NUM ) where MATCH_DATA='FALSE' and FIN_DATA='--------'
) AND  TRIM(COUNTERPARTY_STRING) IN(
select trim(TREASURY_COUNTERPARTY_MNEMONIC) from (
select TRIM(TREASURY_COUNTERPARTY_MNEMONIC)  TREASURY_COUNTERPARTY_MNEMONIC from corp_COREINTERFACE
union 
select TRIM(TREASURY_COUNTERPARTY_MNEMONIC) from RETAIL_COREINTERFACE
union 
select to_char(trim(NAME)) from tr_not_mig_cpty_core_o_table
UNION
SELECT TO_CHAR(TRIM(MNEMONIC)) FROM TREASURY_GROUP_O_TABLE
)
) 
