SELECT   HM.HMCLC,HM.HMCUS,LOT.LIMIT_PREFIX fin_customer_num,LOT.LIMIT_SUFFIX,HMLC,
TO_NUMBER(HN.HNAMT)/C8.C8PWD LIMIT_AMOUNT,HM.HMCCY LIMIT_CCY, HN.HNAB,HN.HNAN,HN.HNAS,aftb.SCHEME_TYPE,LOT.LIMIT_EXPIRY_DATE--,HN.HNAMT
  FROM  LIMIT_CORE_o_TABLE LOT
  left join (select LIMIT_LINE,CASE WHEN TRIM(LM.level_7) IS NOT NULL THEN TRIM(LM.level_7)
            WHEN TRIM(LM.level_7) IS NULL AND TRIM(LM.level_6) IS NOT NULL THEN TRIM(LM.level_6)
            WHEN TRIM(LM.level_7) IS NULL AND TRIM(LM.level_6) IS NULL AND TRIM(LM.level_5) IS NOT NULL THEN TRIM(LM.level_5)
            WHEN TRIM(LM.level_7) IS NULL AND TRIM(LM.level_6) IS NULL AND TRIM(LM.level_5) IS NULL AND TRIM(LM.level_4) IS NOT NULL THEN TRIM(LM.level_4) END limit_node from limit_mapping lm) LM on LM.limit_node=LOT.limit_suffix
left join map_cif on  map_cif.FIN_CIF_ID=LOT.BORROWER_NAME       
  INNER JOIN HMPF HM ON (HM.HMCLC||HM.HMCUS = map_cif.GFCLC||map_cif.GFCUS or LOT.BORROWER_NAME = HM.HMGRP) AND LM.LIMIT_LINE=HM.HMLC
INNER JOIN HNPF HN ON HM.HMSEQ=HN.HNSEQ
inner join 
(select HNAB,HNAN,HNAS,max(HNSEQ) HNSEQ from HMPF HM 
INNER JOIN HNPF HN ON HM.HMSEQ=HN.HNSEQ
group by HNAB,HNAN,HNAS) HN1  on  HN1.HNSEQ = HN.HNSEQ
LEFT JOIN C8PF C8 ON C8.C8CCY = HM.HMCCY
LEFT JOIN (select * from MAP_ACC where schm_type<>'OOO')map_Acc on LEG_BRANCH_ID||LEG_SCAN||LEG_SCAS=HN.HNAB||HN.HNAN||HN.HNAS --and map_Acc.fin_Acc_num is not null
left join ALL_FINAL_TRIAL_BALANCE aftb on SCAB||SCAN||SCAS = HN.HNAB||HN.HNAN||HN.HNAS
WHERE  trim(map_Acc.FIN_ACC_NUM) is  null and HN.HNAMT <>0 AND HM.HMLC IS NOT NULL; 
