========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
Parent_Child_Mapping_Report.sql 
select distinct 
gh.GRPID,FIN_P_C_MAP.FIN_GROUP_ID, CASE WHEN trim(gh.GRPID) = trim(FIN_P_C_MAP.FIN_GROUP_ID) THEN 'TRUE' ELSE 'FALSE' END MATCH_GROUP_ID,
cu.cmne, FIN_P_C_MAP.FIN_GROUP_MEMBER, CASE WHEN trim(cu.cmne) = trim(FIN_P_C_MAP.FIN_GROUP_MEMBER) THEN 'TRUE' ELSE 'FALSE' END MATCH_GROUP_MEMBER
from crgh gh
INNER JOIN crgm c ON TRIM (c.grpid) = TRIM (gh.grpid)
INNER JOIN cust cu ON TRIM (cu.cno) = TRIM (c.GRPMEMBER)
left join (select PRCP.MNEMONIC FIN_GROUP_ID,CHCP.NAME FIN_GROUP_MEMBER
 from SD_CPTY_PARENT@FTMIG PCM
LEFT JOIN sd_cpty@FTMIG PRCP ON PRCP.FBO_ID_NUM = PCM.PARENT_ID_NUM
LEFT JOIN sd_cpty@FTMIG CHCP ON CHCP.FBO_ID_NUM = PCM.CPTY_ID_NUM) FIN_P_C_MAP ON trim(FIN_P_C_MAP.FIN_GROUP_ID) LIKE trim(gh.GRPID)||'%' AND trim(FIN_P_C_MAP.FIN_GROUP_MEMBER) = trim(cu.cmne)
where gh.grptype='C' ;




select distinct 
trim(gh.GRPID)||'-'||TRIM(cu.cmne) OPICS_DATA,
 trim(FIN_P_C_MAP.FIN_GROUP_ID)||'-'||trim(FIN_P_C_MAP.FIN_GROUP_MEMBER) FIN_DATA,
 CASE WHEN trim(gh.GRPID)||'-'||TRIM(cu.cmne) = trim(FIN_P_C_MAP.FIN_GROUP_ID)||'-'||trim(FIN_P_C_MAP.FIN_GROUP_MEMBER) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
from crgh gh
INNER JOIN crgm c ON TRIM (c.grpid) = TRIM (gh.grpid)
INNER JOIN cust cu ON TRIM (cu.cno) = TRIM (c.GRPMEMBER)
left join (select PRCP.MNEMONIC FIN_GROUP_ID,CHCP.NAME FIN_GROUP_MEMBER
 from SD_CPTY_PARENT@FTMIG PCM
LEFT JOIN sd_cpty@FTMIG PRCP ON PRCP.FBO_ID_NUM = PCM.PARENT_ID_NUM
LEFT JOIN sd_cpty@FTMIG CHCP ON CHCP.FBO_ID_NUM = PCM.CPTY_ID_NUM) FIN_P_C_MAP ON trim(FIN_P_C_MAP.FIN_GROUP_ID) LIKE trim(gh.GRPID)||'%' AND trim(FIN_P_C_MAP.FIN_GROUP_MEMBER) = trim(cu.cmne)
where gh.grptype='C' ;

select distinct 
trim(a.GRP_ID)||'-'||TRIM(a.CPTY_MNEMONIC) OPICS_DATA,
 trim(FIN_P_C_MAP.FIN_GROUP_ID)||'-'||trim(FIN_P_C_MAP.FIN_GROUP_MEMBER) FIN_DATA,
 CASE WHEN trim(a.GRP_ID)||'-'||TRIM(a.CPTY_MNEMONIC)  = trim(FIN_P_C_MAP.FIN_GROUP_ID)||'-'||trim(FIN_P_C_MAP.FIN_GROUP_MEMBER) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
from tr_grp_and_cpty_map_o_table a
left join (select PRCP.MNEMONIC FIN_GROUP_ID,CHCP.NAME FIN_GROUP_MEMBER
 from SD_CPTY_PARENT@FTMIG PCM
LEFT JOIN sd_cpty@FTMIG PRCP ON PRCP.FBO_ID_NUM = PCM.PARENT_ID_NUM
LEFT JOIN sd_cpty@FTMIG CHCP ON CHCP.FBO_ID_NUM = PCM.CPTY_ID_NUM) FIN_P_C_MAP ON trim(FIN_P_C_MAP.FIN_GROUP_ID) LIKE trim(a.GRP_ID) AND trim(FIN_P_C_MAP.FIN_GROUP_MEMBER) = trim(a.CPTY_MNEMONIC)


SELECT DISTINCT
TRIM(A.GRP_ID) OPICS_GROUP_ID, TRIM(FIN_P_C_MAP.FIN_GROUP_ID) FIN_GROUP_ID, CASE WHEN  TRIM(A.GRP_ID) = TRIM(FIN_P_C_MAP.FIN_GROUP_ID) THEN 'TRUE' ELSE 'FALSE' END MATCH_GROUP_ID,
TRIM(A.CPTY_MNEMONIC) OPICS_CPTY_MNEMONIC, TRIM(FIN_P_C_MAP.FIN_GROUP_MEMBER) FIN_CPTY_MNEMONIC, CASE WHEN  TRIM(A.CPTY_MNEMONIC) = TRIM(FIN_P_C_MAP.FIN_GROUP_MEMBER) THEN 'TRUE' ELSE 'FALSE' END MATCH_CPTY_MNEMONIC,
TRIM(A.GRP_ID)||'-'||TRIM(A.CPTY_MNEMONIC) OPICS_DATA,
 TRIM(FIN_P_C_MAP.FIN_GROUP_ID)||'-'||TRIM(FIN_P_C_MAP.FIN_GROUP_MEMBER) FIN_DATA,
 CASE WHEN TRIM(A.GRP_ID)||'-'||TRIM(A.CPTY_MNEMONIC)  = TRIM(FIN_P_C_MAP.FIN_GROUP_ID)||'-'||TRIM(FIN_P_C_MAP.FIN_GROUP_MEMBER) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM TR_GRP_AND_CPTY_MAP_O_TABLE A
LEFT JOIN (SELECT PRCP.MNEMONIC FIN_GROUP_ID,CHCP.NAME FIN_GROUP_MEMBER
 FROM SD_CPTY_PARENT@FTMIG PCM
LEFT JOIN SD_CPTY@FTMIG PRCP ON PRCP.FBO_ID_NUM = PCM.PARENT_ID_NUM
LEFT JOIN SD_CPTY@FTMIG CHCP ON CHCP.FBO_ID_NUM = PCM.CPTY_ID_NUM) FIN_P_C_MAP ON TRIM(FIN_P_C_MAP.FIN_GROUP_ID) LIKE TRIM(A.GRP_ID) AND TRIM(FIN_P_C_MAP.FIN_GROUP_MEMBER) = TRIM(A.CPTY_MNEMONIC)
 
