========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
security_defn_report.sql 
select S.SECID OPICS_SECID, SEDF.DESCRIPTION FINACLE_DESCRIPTION, CASE WHEN TRIM(S.SECID) = TRIM(SEDF.DESCRIPTION) THEN 'TRUE' ELSE 'FALSE' END MATCH_SECID, 
S.CCY OPICS_ISSUE_CCY,SEDF.ISSUE_CCY FINACLE_ISSUE_CCY,CASE WHEN TRIM(S.CCY) = TRIM(SEDF.ISSUE_CCY) THEN 'TRUE' ELSE 'FALSE' END MATCH_ISSUE_CCY, 
PRODTYPE OPICS_PRODTYPE,TYPE FINACLE_A_TYPE,
PRODTYPE OPICS_PRODTYPE ,SEDF.SECURITY_TYPE FINACLE_SECURITY_TYPE,
BASIS OPICS_BASIS,SEDF.YIELD_BASIS FINACLE_YIELD_BASIS,
BASIS OPICS_BASIS,SEDF.EFFECTIVE_YIELD_BASIS FINACLE_EFFECTIVE_YIELD_BASIS,
DESCR OPICS_DESCR ,SEDF.ALT_ID1 FINACLE_ALT_ID1,CASE WHEN TRIM(DESCR) = TRIM(SEDF.ALT_ID1) THEN 'TRUE' ELSE 'FALSE' END MATCH_DESCR,
ISSDATE OPICS_ISSDATE ,SEDF.ISSUE_DATE FINACLE_ISSUE_DATE ,CASE WHEN ISSDATE = SEDF.ISSUE_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_ISSUE_DATE,
MDATE OPICS_MDATE,SEDF.MATURITY_DATE FINACLE_MATURITY_DATE,CASE WHEN MDATE = SEDF.MATURITY_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_MATURITY_DATE,
--RATECODE SIDE_$1_CASH_FLOW_SIDE_TYPE,--
--RATECODE,COUPRATE_8 SIDE_$1_FIX_RATE,--
--RATECODE SIDE_$1_REFERENCE_RATE,--
PARAMT OPICS_PARAMT,PARAMT FINACLE_REDEMPTION_VALUE,CASE WHEN PARAMT = PARAMT THEN 'TRUE' ELSE 'FALSE' END MATCH_REDEMPTION_VALUE,
C.CMNE OPICS_CMNE,CPTY.MNEMONIC ISSUER_STRING,CASE WHEN trim(C.CMNE) = trim(CPTY.MNEMONIC) THEN 'TRUE' ELSE 'FALSE' END MATCH_ISSUER_STRING,
MDATE OPICS_MDATE,SEDF.ACTIVE_STATUS FINACLE_ACTIVE_STATUS,
DENOM OPICS_DENOM,SEDF.MINIMUM_AMOUNT,CASE WHEN DENOM = SEDF.MINIMUM_AMOUNT THEN 'TRUE' ELSE 'FALSE' END MATCH_MINIMUM_AMOUNT,
DENOM OPICS_MDATE ,SEDF.QTY_MULTIPLE FINACLE_QTY_MULTIPLE,CASE WHEN DENOM = SEDF.QTY_MULTIPLE THEN 'TRUE' ELSE 'FALSE' END MATCH_QTY_MULTIPLE,
SECID OPICS_SECID ,SEDF.AMORT_APPLICABILITY FINACLE_AMORT_APPLICABILITY,
PARAMT OPICS_PARAMT,SEDF.ISSUE_PRICE FINACLE_ISSUE_PRICE ,CASE WHEN PARAMT =SEDF.ISSUE_PRICE  THEN 'TRUE' ELSE 'FALSE' END MATCH_ISSUE_PRICE,
PARAMT OPICS_PARAMT,SEDF.ISSUANCE_FACE FINACLE_ISSUANCE_FACE,CASE WHEN PARAMT =SEDF.ISSUANCE_FACE  THEN 'TRUE' ELSE 'FALSE' END MATCH_ISSUANCE_FACE,
PRICEDECS OPICS_PRICEDECS,SEDF.PRICE_ROUNDING_DIGITS FINACLE_PRICE_ROUNDING_DIGITS,CASE WHEN PRICEDECS =SEDF.PRICE_ROUNDING_DIGITS  THEN 'TRUE' ELSE 'FALSE' END MATCH_PRICE_ROUNDING_DIGITS,
CCY OPICS_CCY,SEDF.SETTLEMENT_CALENDAR_SET FIN_SETTLEMENT_CALENDAR_SET,CASE WHEN CCY =SEDF.SETTLEMENT_CALENDAR_SET  THEN 'TRUE' ELSE 'FALSE' END MATCH_SETTLEMENT_CALENDAR_SET,
SETTCCY OPICS_SETTCCY,SEDF.INDEX_SETT_CCY FINACLE_INDEX_SETT_CCY,CASE WHEN SETTCCY =SEDF.INDEX_SETT_CCY  THEN 'TRUE' ELSE 'FALSE' END MATCH_INDEX_SETT_CCY
FROM SECM S
INNER JOIN CUST C ON TRIM(S.ISSUER)=TRIM(C.CNO)
LEFT JOIN FTABKBPD.SD_SEC_DEFN@FTFC SEDF ON TRIM(SEDF.DESCRIPTION) = TRIM(S.SECID)
LEFT JOIN FTABKBPD.SD_CPTY@FTFC CPTY ON CPTY.FBO_ID_NUM=SEDF.ISSUER_FBO_ID_NUM
WHERE S.PRODTYPE IN ('F1','F2','FI','SB','TB') AND S.MDATE > TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY');



select 
replace(trim(SEC_DEF.NAME),'  ',' ') ||'-'||SEC_DEF.ISSUE_CCY||'-'||A_TYPE||'-'||TRIM(SEC_DEF.YIELD_BASIS)||'-'||to_date(SEC_DEF.ISSUE_DATE,'dd-mon-yyyy')||'-'||
to_date(SEC_DEF.MATURITY_DATE,'dd-mon-yyyy')||'-'||TRIM(ISSUER_STRING)||'-'||TRIM(SEC_DEF.MINIMUM_AMOUNT)||'-'||TRIM(SEC_DEF.QTY_MULTIPLE)||'-'||TRIM(SEC_DEF.ISSUE_PRICE) OPICS_DATA,
 replace(TRIM(EQDN.NAME),'  ',' ')||'-'|| EQDN.ISSUE_CCY||'-'|| EQDN.TYPE||'-'|| EQDN.YIELD_BASIS||'-'||EQDN.ISSUE_DATE||'-'||EQDN.MATURITY_DATE||'-'||SDCP.NAME||'-'||EQDN.MINIMUM_AMOUNT||'-'||
EQDN.QTY_MULTIPLE||'-'||EQDN.ISSUE_PRICE FIN_DATA,
CASE WHEN replace(trim(SEC_DEF.NAME),'  ',' ') ||'-'||SEC_DEF.ISSUE_CCY||'-'||A_TYPE||'-'||TRIM(SEC_DEF.YIELD_BASIS)||'-'||to_date(SEC_DEF.ISSUE_DATE,'dd-mon-yyyy')||'-'||
to_date(SEC_DEF.MATURITY_DATE,'dd-mon-yyyy')||'-'||TRIM(ISSUER_STRING)||'-'||TRIM(SEC_DEF.MINIMUM_AMOUNT)||'-'||TRIM(SEC_DEF.QTY_MULTIPLE)||'-'||TRIM(SEC_DEF.ISSUE_PRICE) =   replace(TRIM(EQDN.NAME),'  ',' ')||'-'|| EQDN.ISSUE_CCY||'-'|| EQDN.TYPE||'-'|| EQDN.YIELD_BASIS||'-'||EQDN.ISSUE_DATE||'-'||EQDN.MATURITY_DATE||'-'||SDCP.NAME||'-'||EQDN.MINIMUM_AMOUNT||'-'||
EQDN.QTY_MULTIPLE||'-'||EQDN.ISSUE_PRICE THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
  from SECURITY_DEFN_O_TABLE SEC_DEF
LEFT JOIN SD_SEC_DEFN@ftmig EQDN ON replace(SEC_DEF.NAME,'  ',' ') =replace( TRIM(EQDN.NAME),'  ',' ')
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= EQDN.ISSUER_FBO_ID_NUM;


select 
replace(trim(SEC_DEF.NAME),'  ',' ') ||'-'||SEC_DEF.ISSUE_CCY||'-'||A_TYPE||'-'||to_date(SEC_DEF.ISSUE_DATE,'dd-mon-yyyy')||'-'||
to_date(SEC_DEF.MATURITY_DATE,'dd-mon-yyyy')||'-'||TRIM(ISSUER_STRING)||'-'||TRIM(SEC_DEF.MINIMUM_AMOUNT)||'-'||TRIM(SEC_DEF.QTY_MULTIPLE)||'-'||TRIM(SEC_DEF.ISSUE_PRICE) OPICS_DATA,
 replace(TRIM(EQDN.NAME),'  ',' ')||'-'|| EQDN.ISSUE_CCY||'-'|| EQDN.TYPE||'-'||EQDN.ISSUE_DATE||'-'||EQDN.MATURITY_DATE||'-'||trim(SDCP.NAME)||'-'||EQDN.MINIMUM_AMOUNT||'-'||
EQDN.QTY_MULTIPLE||'-'||EQDN.ISSUE_PRICE FIN_DATA,
CASE WHEN replace(trim(SEC_DEF.NAME),'  ',' ') ||'-'||SEC_DEF.ISSUE_CCY||'-'||A_TYPE||'-'||to_date(SEC_DEF.ISSUE_DATE,'dd-mon-yyyy')||'-'||
to_date(SEC_DEF.MATURITY_DATE,'dd-mon-yyyy')||'-'||TRIM(ISSUER_STRING)||'-'||TRIM(SEC_DEF.MINIMUM_AMOUNT)||'-'||TRIM(SEC_DEF.QTY_MULTIPLE)||'-'||TRIM(SEC_DEF.ISSUE_PRICE) =   replace(TRIM(EQDN.NAME),'  ',' ')||'-'|| EQDN.ISSUE_CCY||'-'|| EQDN.TYPE||'-'||EQDN.ISSUE_DATE||'-'||EQDN.MATURITY_DATE||'-'||trim(SDCP.NAME)||'-'||EQDN.MINIMUM_AMOUNT||'-'||
EQDN.QTY_MULTIPLE||'-'||EQDN.ISSUE_PRICE THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
  from SECURITY_DEFN_O_TABLE SEC_DEF
LEFT JOIN SD_SEC_DEFN@ftmig EQDN ON replace(SEC_DEF.NAME,'  ',' ') =replace( TRIM(EQDN.NAME),'  ',' ')
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= EQDN.ISSUER_FBO_ID_NUM



select 
TRIM(SEC_DEF.NAME) OPICS_SECID ,EQDN.NAME FIN_SECID,CASE WHEN TRIM(SEC_DEF.NAME) = EQDN.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SECID,
SEC_DEF.A_TYPE MAPPED_INSTRUMENT_TYPE ,EQDN.TYPE FIN_INSTRUMENT_TYPE,CASE WHEN SEC_DEF.A_TYPE  = EQDN.TYPE THEN 'TRUE' ELSE 'FALSE' END MATCH_INSTRUMENT_TYPE,
INSTRUMENT_CLASS_DATA_NAME MAPPED_NSTRUMENT_CLASS ,INCL.NAME FIN_NSTRUMENT_CLASS ,CASE WHEN INSTRUMENT_CLASS_DATA_NAME = INCL.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_NSTRUMENT_CLASS,
SEC_DEF.ISSUE_CCY OPICS_CCY,EQDN.ISSUE_CCY FIN_CCY,CASE WHEN SEC_DEF.ISSUE_CCY = EQDN.ISSUE_CCY THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
TRIM(ISSUER_STRING) OPICS_CPTY,trim(SDCP.NAME) FIN_CPTY,CASE WHEN TRIM(ISSUER_STRING) = trim(SDCP.NAME)THEN 'TRUE' ELSE 'FALSE' END MATCH_CPTY,
to_date(SEC_DEF.ISSUE_DATE,'dd-mon-yyyy') OPICS_ISSUE_DATE,EQDN.ISSUE_DATE FIN_ISSUE_DATE,CASE WHEN to_date(SEC_DEF.ISSUE_DATE,'dd-mon-yyyy') = EQDN.ISSUE_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_ISSUE_DATE,
to_date(SEC_DEF.MATURITY_DATE,'dd-mon-yyyy') OPICS_MATURITY_DATE,EQDN.MATURITY_DATE FIN_MATURITY_DATE,CASE WHEN to_date(SEC_DEF.MATURITY_DATE,'dd-mon-yyyy') = EQDN.MATURITY_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_MATURITY_DATE,
SEC_DEF.MINIMUM_AMOUNT OPICS_MINIMUM_AMOUNT,EQDN.MINIMUM_AMOUNT FIN_MINIMUM_AMOUNT,CASE WHEN SEC_DEF.MINIMUM_AMOUNT = EQDN.MINIMUM_AMOUNT THEN 'TRUE' ELSE 'FALSE' END MATCH_MINIMUM_AMOUNT,
SEC_DEF.QTY_MULTIPLE OPICS_MINIMUM_AMOUNT,EQDN.QTY_MULTIPLE FIN_QTY_MULTIPLE,CASE WHEN SEC_DEF.QTY_MULTIPLE = EQDN.QTY_MULTIPLE THEN 'TRUE' ELSE 'FALSE' END MATCH_QTY_MULTIPLE,
replace(trim(SEC_DEF.NAME),'  ',' ') ||'-'||SEC_DEF.ISSUE_CCY||'-'||A_TYPE||'-'||to_date(SEC_DEF.ISSUE_DATE,'dd-mon-yyyy')||'-'||
to_date(SEC_DEF.MATURITY_DATE,'dd-mon-yyyy')||'-'||TRIM(ISSUER_STRING)||'-'||TRIM(SEC_DEF.MINIMUM_AMOUNT)||'-'||TRIM(SEC_DEF.QTY_MULTIPLE)||'-'||TRIM(SEC_DEF.ISSUE_PRICE) OPICS_DATA,
 replace(TRIM(EQDN.NAME),'  ',' ')||'-'|| EQDN.ISSUE_CCY||'-'|| EQDN.TYPE||'-'||EQDN.ISSUE_DATE||'-'||EQDN.MATURITY_DATE||'-'||trim(SDCP.NAME)||'-'||EQDN.MINIMUM_AMOUNT||'-'||
EQDN.QTY_MULTIPLE||'-'||EQDN.ISSUE_PRICE FIN_DATA,
CASE WHEN replace(trim(SEC_DEF.NAME),'  ',' ') ||'-'||SEC_DEF.ISSUE_CCY||'-'||A_TYPE||'-'||to_date(SEC_DEF.ISSUE_DATE,'dd-mon-yyyy')||'-'||
to_date(SEC_DEF.MATURITY_DATE,'dd-mon-yyyy')||'-'||TRIM(ISSUER_STRING)||'-'||TRIM(SEC_DEF.MINIMUM_AMOUNT)||'-'||TRIM(SEC_DEF.QTY_MULTIPLE)||'-'||TRIM(SEC_DEF.ISSUE_PRICE) =  
 replace(TRIM(EQDN.NAME),'  ',' ')||'-'|| EQDN.ISSUE_CCY||'-'|| EQDN.TYPE||'-'||EQDN.ISSUE_DATE||'-'||EQDN.MATURITY_DATE||'-'||trim(SDCP.NAME)||'-'||EQDN.MINIMUM_AMOUNT||'-'||
EQDN.QTY_MULTIPLE||'-'||EQDN.ISSUE_PRICE THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
  from SECURITY_DEFN_O_TABLE SEC_DEF
LEFT JOIN SD_SEC_DEFN@ftmig EQDN ON replace(SEC_DEF.NAME,'  ',' ') =replace( TRIM(EQDN.NAME),'  ',' ')
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= EQDN.ISSUER_FBO_ID_NUM
LEFT JOIN SD_INSTRUMENT_CLASS@FTMIG  INCL ON INCL.FBO_ID_NUM = INSTRUMENT_CLASS_FBO_ID_NUM 
