========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
security_deals_report.sql 
SELECT SEC_DEAL.DEAL_IDENTIFIER ||'-'||replace(SEC_DEAL.SEC_DEFN_NAME,'  ',' ') ||'-'||SEC_DEAL.SUBTYPE ||'-'||TRIM(SEC_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(SEC_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||SEC_DEAL.BUY_OR_SELL ||'-'||
SEC_D.ISSUE_CCY ||'-'||ROUND(SEC_DEAL.PRICE_STRING,5) ||'-'||SEC_DEAL.QTY_TRADED OPICS_DATA,
SECDEAL.DEAL_IDENTIFIER ||'-'||replace(SECD.NAME,'  ',' ')  ||'-'||SDSBTY.NAME ||'-'||trim(SDCP.NAME )||'-'||SECDEAL.DEAL_DATE||'-'||CASE WHEN SECDEAL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||SECDEAL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(SECDEAL.PRICE,',',''),5) ||'-'||abs(SECDEAL.QTY_TRADED) FIN_DATA,
CASE WHEN SEC_DEAL.DEAL_IDENTIFIER ||'-'||replace(SEC_DEAL.SEC_DEFN_NAME,'  ',' ') ||'-'||SEC_DEAL.SUBTYPE ||'-'||TRIM(SEC_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(SEC_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||SEC_DEAL.BUY_OR_SELL ||'-'||
SEC_D.ISSUE_CCY ||'-'||ROUND(SEC_DEAL.PRICE_STRING,5) ||'-'||SEC_DEAL.QTY_TRADED=
SECDEAL.DEAL_IDENTIFIER ||'-'||replace(SECD.NAME,'  ',' ')  ||'-'||SDSBTY.NAME ||'-'||trim(SDCP.NAME) ||'-'||SECDEAL.DEAL_DATE||'-'||CASE WHEN SECDEAL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||SECDEAL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(SECDEAL.PRICE,',',''),5) ||'-'||abs(SECDEAL.QTY_TRADED) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM SEC_BUY_SELL_O_TABLE SEC_DEAL
LEFT JOIN SECURITY_DEFN_O_TABLE SEC_D ON SEC_D.NAME = SEC_DEAL.SEC_DEFN_NAME
LEFT JOIN TT_SEC_BS@FTMIG SECDEAL ON SEC_DEAL.DEAL_IDENTIFIER = SECDEAL.DEAL_IDENTIFIER and DEAL_STATE!='DLTD'
LEFT JOIN SD_SEC_DEFN@FTMIG SECD ON SECD.FBO_ID_NUM = SECDEAL.SEC_DEFN_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = SECDEAL.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = SECDEAL.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= SECDEAL.CPTY_FBO_ID_NUM


SELECT 
SEC_DEAL.DEAL_IDENTIFIER MAPPED_DEALNO,SECDEAL.DEAL_IDENTIFIER FIN_DEALNO, CASE WHEN SEC_DEAL.DEAL_IDENTIFIER = SECDEAL.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
SEC_DEAL.SEC_DEFN_NAME OPICS_SECID,trim(SECD.NAME) FIN_SECID, CASE WHEN SEC_DEAL.SEC_DEFN_NAME  = trim(SECD.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_SECID,
SEC_DEAL.SUBTYPE MAPPED_SUBTYPE,trim(SDSBTY.NAME) FIN_SUBTYPE ,CASE WHEN  TRIM(SEC_DEAL.SUBTYPE) = trim(SDSBTY.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
COUNTERPARTY_STRING OPICS_COUNTERPARTY,trim(SDCP.NAME) FIN_COUNTERPARTY,CASE WHEN  TRIM(COUNTERPARTY_STRING) = trim(SDCP.NAME)  THEN 'TRUE' ELSE 'FALSE' END MATCH_COUNTERPARTY,
TO_DATE(SEC_DEAL.DEAL_DATE,'DD-MM-YYYY') MAPPED_DEAL_DATE,SECDEAL.DEAL_DATE FIN_DEAL_DATE,CASE WHEN TO_DATE(SEC_DEAL.DEAL_DATE,'DD-MM-YYYY')  = SECDEAL.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
SEC_DEAL.BUY_OR_SELL OPICS_BUY_OR_SELL,CASE WHEN SECDEAL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END FIN_BUY_OR_SELL ,CASE WHEN SEC_DEAL.BUY_OR_SELL  =CASE WHEN SECDEAL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END THEN 'TRUE' ELSE 'FALSE' END MATCH_BUY_OR_SELL,
ROUND(SEC_DEAL.PRICE_STRING,5) OPICS_AVG_PRICE,ROUND(REPLACE(SECDEAL.PRICE,',',''),5) FIN_PRICE,CASE WHEN ROUND(SEC_DEAL.PRICE_STRING,5)  = ROUND(REPLACE(SECDEAL.PRICE,',',''),5) THEN 'TRUE' ELSE 'FALSE' END MATCH_PRICE,
SEC_DEAL.QTY_TRADED OPICS_QTY, ABS(SECDEAL.QTY_TRADED) FIN_QTY,CASE WHEN  SEC_DEAL.QTY_TRADED =  ABS(SECDEAL.QTY_TRADED)  THEN 'TRUE' ELSE 'FALSE' END MATCH_QTY,
SI_FLOW_PAY_NOSTRO OPICS_PAY_NOSTRO,pay_nos FIN_PAY_NOSTRO,CASE WHEN trim(SI_FLOW_PAY_NOSTRO) = trim(pay_nos) THEN 'TRUE' ELSE 'FALSE' END MATCH_PAY_NOSTRO,
SI_FLOW_REC_NOSTRO OPICS_REC_NOSTRO,rec_nos FIN_REC_NOSTRO,CASE WHEN   trim(SI_FLOW_REC_NOSTRO) = trim(rec_nos) THEN 'TRUE' ELSE 'FALSE' END MATCH_REC_NOSTRO,
SEC_DEAL.DEAL_IDENTIFIER ||'-'||replace(SEC_DEAL.SEC_DEFN_NAME,'  ',' ') ||'-'||SEC_DEAL.SUBTYPE ||'-'||TRIM(SEC_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(SEC_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||SEC_DEAL.BUY_OR_SELL ||'-'||
SEC_D.ISSUE_CCY ||'-'||ROUND(SEC_DEAL.PRICE_STRING,5) ||'-'||SEC_DEAL.QTY_TRADED OPICS_DATA,
SECDEAL.DEAL_IDENTIFIER ||'-'||replace(SECD.NAME,'  ',' ')  ||'-'||SDSBTY.NAME ||'-'||trim(SDCP.NAME )||'-'||SECDEAL.DEAL_DATE||'-'||CASE WHEN SECDEAL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||SECDEAL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(SECDEAL.PRICE,',',''),5) ||'-'||abs(SECDEAL.QTY_TRADED) FIN_DATA,
CASE WHEN SEC_DEAL.DEAL_IDENTIFIER ||'-'||replace(SEC_DEAL.SEC_DEFN_NAME,'  ',' ') ||'-'||SEC_DEAL.SUBTYPE ||'-'||TRIM(SEC_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(SEC_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||SEC_DEAL.BUY_OR_SELL ||'-'||
SEC_D.ISSUE_CCY ||'-'||ROUND(SEC_DEAL.PRICE_STRING,5) ||'-'||SEC_DEAL.QTY_TRADED=
SECDEAL.DEAL_IDENTIFIER ||'-'||replace(SECD.NAME,'  ',' ')  ||'-'||SDSBTY.NAME ||'-'||trim(SDCP.NAME) ||'-'||SECDEAL.DEAL_DATE||'-'||CASE WHEN SECDEAL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||SECDEAL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(SECDEAL.PRICE,',',''),5) ||'-'||abs(SECDEAL.QTY_TRADED) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM SEC_BUY_SELL_O_TABLE SEC_DEAL
LEFT JOIN SECURITY_DEFN_O_TABLE SEC_D ON SEC_D.NAME = SEC_DEAL.SEC_DEFN_NAME
LEFT JOIN TT_SEC_BS@FTMIG SECDEAL ON  SECDEAL.DEAL_IDENTIFIER like SEC_DEAL.DEAL_IDENTIFIER||'%'and DEAL_STATE!='DLTD'
LEFT JOIN SD_SEC_DEFN@FTMIG SECD ON SECD.FBO_ID_NUM = SECDEAL.SEC_DEFN_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = SECDEAL.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = SECDEAL.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= SECDEAL.CPTY_FBO_ID_NUM
left join (
  SELECT distinct a.PARENT_FBO_ID_NUM,a.PARENT_FBO_ID_TYPE,A.IQ_CURRENCY PAY_CCY,a.NAME pay_nos ,B.IQ_CURRENCY REC_CCY,b.NAME rec_nos  FROM (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT') A
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT') B ON A.PARENT_FBO_ID_TYPE = B.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM
  ) NOS on NOS.PARENT_FBO_ID_NUM = SECDEAL.DEAL_NUM
  
  
  

SELECT 
SEC_DEAL.DEAL_IDENTIFIER MAPPED_DEALNO,SECDEAL.DEAL_IDENTIFIER FIN_DEALNO, CASE WHEN SEC_DEAL.DEAL_IDENTIFIER = SECDEAL.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
SEC_DEAL.SEC_DEFN_NAME OPICS_SECID,trim(SECD.NAME) FIN_SECID, CASE WHEN SEC_DEAL.SEC_DEFN_NAME  = trim(SECD.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_SECID,
SEC_DEAL.SUBTYPE MAPPED_SUBTYPE,trim(SDSBTY.NAME) FIN_SUBTYPE ,CASE WHEN  TRIM(SEC_DEAL.SUBTYPE) = trim(SDSBTY.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
COUNTERPARTY_STRING OPICS_COUNTERPARTY,trim(SDCP.NAME) FIN_COUNTERPARTY,CASE WHEN  TRIM(COUNTERPARTY_STRING) = trim(SDCP.NAME)  THEN 'TRUE' ELSE 'FALSE' END MATCH_COUNTERPARTY,
TO_DATE(SEC_DEAL.DEAL_DATE,'DD-MM-YYYY') MAPPED_DEAL_DATE,SECDEAL.DEAL_DATE FIN_DEAL_DATE,CASE WHEN TO_DATE(SEC_DEAL.DEAL_DATE,'DD-MM-YYYY')  = SECDEAL.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
SEC_DEAL.BUY_OR_SELL OPICS_BUY_OR_SELL,CASE WHEN SECDEAL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END FIN_BUY_OR_SELL ,CASE WHEN SEC_DEAL.BUY_OR_SELL  =CASE WHEN SECDEAL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END THEN 'TRUE' ELSE 'FALSE' END MATCH_BUY_OR_SELL,
ROUND(SEC_DEAL.PRICE_STRING,5) OPICS_AVG_PRICE,ROUND(REPLACE(SECDEAL.PRICE,',',''),5) FIN_PRICE,CASE WHEN ROUND(SEC_DEAL.PRICE_STRING,5)  = ROUND(REPLACE(SECDEAL.PRICE,',',''),5) THEN 'TRUE' ELSE 'FALSE' END MATCH_PRICE,
SEC_DEAL.QTY_TRADED OPICS_QTY, ABS(SECDEAL.QTY_TRADED) FIN_QTY,CASE WHEN  SEC_DEAL.QTY_TRADED =  ABS(SECDEAL.QTY_TRADED)  THEN 'TRUE' ELSE 'FALSE' END MATCH_QTY,
SI_FLOW_PAY_NOSTRO OPICS_PAY_NOSTRO,pay_nos FIN_PAY_NOSTRO,CASE WHEN trim(SI_FLOW_PAY_NOSTRO) = trim(pay_nos) THEN 'TRUE' ELSE 'FALSE' END MATCH_PAY_NOSTRO,
SI_FLOW_REC_NOSTRO OPICS_REC_NOSTRO,rec_nos FIN_REC_NOSTRO,CASE WHEN   trim(SI_FLOW_REC_NOSTRO) = trim(rec_nos) THEN 'TRUE' ELSE 'FALSE' END MATCH_REC_NOSTRO,
SEC_DEAL.DEAL_IDENTIFIER ||'-'||replace(SEC_DEAL.SEC_DEFN_NAME,'  ',' ') ||'-'||SEC_DEAL.SUBTYPE ||'-'||TRIM(SEC_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(SEC_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||SEC_DEAL.BUY_OR_SELL ||'-'||
SEC_D.ISSUE_CCY ||'-'||ROUND(SEC_DEAL.PRICE_STRING,5) ||'-'||SEC_DEAL.QTY_TRADED OPICS_DATA,
SECDEAL.DEAL_IDENTIFIER ||'-'||replace(SECD.NAME,'  ',' ')  ||'-'||SDSBTY.NAME ||'-'||trim(SDCP.NAME )||'-'||SECDEAL.DEAL_DATE||'-'||CASE WHEN SECDEAL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||SECDEAL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(SECDEAL.PRICE,',',''),5) ||'-'||abs(SECDEAL.QTY_TRADED) FIN_DATA,
CASE WHEN SEC_DEAL.DEAL_IDENTIFIER ||'-'||replace(SEC_DEAL.SEC_DEFN_NAME,'  ',' ') ||'-'||SEC_DEAL.SUBTYPE ||'-'||TRIM(SEC_DEAL.COUNTERPARTY_STRING) ||'-'||TO_DATE(SEC_DEAL.DEAL_DATE,'DD-MM-YYYY') ||'-'||SEC_DEAL.BUY_OR_SELL ||'-'||
SEC_D.ISSUE_CCY ||'-'||ROUND(SEC_DEAL.PRICE_STRING,5) ||'-'||SEC_DEAL.QTY_TRADED=
SECDEAL.DEAL_IDENTIFIER ||'-'||replace(SECD.NAME,'  ',' ')  ||'-'||SDSBTY.NAME ||'-'||trim(SDCP.NAME) ||'-'||SECDEAL.DEAL_DATE||'-'||CASE WHEN SECDEAL.BUY_OR_SELL='B' THEN 'BUY' ELSE 'SELL' END||'-'||SECDEAL.SETTLEMENT_CCY ||'-'||
ROUND(REPLACE(SECDEAL.PRICE,',',''),5) ||'-'||abs(SECDEAL.QTY_TRADED) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM SEC_BUY_SELL_O_TABLE SEC_DEAL
LEFT JOIN SECURITY_DEFN_O_TABLE SEC_D ON SEC_D.NAME = SEC_DEAL.SEC_DEFN_NAME
LEFT JOIN TT_SEC_BS@FTMIG SECDEAL ON  SECDEAL.DEAL_IDENTIFIER like SEC_DEAL.DEAL_IDENTIFIER||'%'and DEAL_STATE!='DLTD'
LEFT JOIN SD_SEC_DEFN@FTMIG SECD ON SECD.FBO_ID_NUM = SECDEAL.SEC_DEFN_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = SECDEAL.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = SECDEAL.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= SECDEAL.CPTY_FBO_ID_NUM
left join (
  SELECT distinct a.PARENT_FBO_ID_NUM,a.PARENT_FBO_ID_TYPE,A.IQ_CURRENCY PAY_CCY,a.NAME pay_nos ,B.IQ_CURRENCY REC_CCY,b.NAME rec_nos  FROM (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT' and PARENT_FBO_ID_VER='999999') A
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT'and PARENT_FBO_ID_VER='999999') B ON A.PARENT_FBO_ID_TYPE = B.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM
  ) NOS on NOS.PARENT_FBO_ID_NUM = SECDEAL.DEAL_NUM 
