========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
security_defn_flows_report.sql 
--ALL CASH FLOWS
select 
secid OPICS_SECID,name FIN_DEAL_SECID,CASE WHEN trim(secid) = trim(name) THEN 'TRUE' ELSE 'FALSE' END MATCH_secid,
seq OPICS_SCHEDULE_SEQ,SIDE_SEQUENCE FIN_SCHEDULE_SEQ,CASE WHEN TO_NUMBER(seq) = SIDE_SEQUENCE THEN 'TRUE' ELSE 'FALSE' END MATCH_SEQUENCE,
--INTCCY OPICS_CCY,NOTIONAL_AMOUNT_CCY FIN_CCY,CASE WHEN INTCCY = NOTIONAL_AMOUNT_CCY THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
INTSTRTDTE OPICS_START_DATE ,fin_flow.START_DATE FIN_START_DATE ,CASE WHEN INTSTRTDTE = fin_flow.START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
INTENDDTE OPICS_END_DATE,fin_flow.END_DATE FIN_END_DATE,CASE WHEN INTENDDTE = fin_flow.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
RATECODE OPICS_RATECODE,RATE_CODE FIN_RATECODE,CASE WHEN nvl(RATECODE,' ') = nvl(RATE_CODE,' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_RATE_CODE,
INTRATE_8 OPICS_INTRATE,NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100) FIN_INTRATE,CASE WHEN INTRATE_8 = NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100) THEN 'TRUE' ELSE 'FALSE' END MATCH_INTRATE,
SPREADRATE_8 OPICS_SPREAD_RATE ,fin_flow.SPREAD_RATE*100 FIN_SPREAD_RATE,CASE WHEN to_number(SPREADRATE_8) = NVL(fin_flow.SPREAD_RATE*100,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_SPREAD_RATE
 from SECS
left join SD_SEC_DEFN@ftmig on trim(secid) = trim(name) 
left join (select reset_date,REFERENCE_RATE_FBO_ID_NUM,CASH_FLOW_TYPE,parent_fbo_id_num,BASIS_CODE,START_DATE,END_DATE,NOTIONAL_AMOUNT_CCY,NOTIONAL_AMOUNT_VALUE,SPREAD_RATE,
MARGIN,FIX_RATE,SIDE_SEQUENCE,PARENT_FBO_ID_VER from  TT_SECDEFN_CASH_FLOWS@ftmig) fin_flow on PARENT_FBO_ID_NUM  = SD_SEC_DEFN.FBO_ID_NUM and PARENT_FBO_ID_VER='999999' and SIDE_SEQUENCE = to_number(seq)
LEFT JOIN (
SELECT  A.REF_RATE_FBO_ID_NUM,RATE_CODE,RATE_CCY,RATE_VALUE,EFFECTIVE_DATE FROM SD_REF_RATE_VALUE@FTMIG A
LEFT JOIN SD_REF_RATE@FTMIG B ON B.FBO_ID_NUM = A.REF_RATE_FBO_ID_NUM
) REF_RATE ON REF_RATE.REF_RATE_FBO_ID_NUM = REFERENCE_RATE_FBO_ID_NUM AND reset_date = EFFECTIVE_DATE
where TRIM(secid) IN(SELECT TRIM(name) FROM SECURITY_DEFN_O_TABLE)
order by secid,to_number(seq)

--CURRENT CASH FLOWS
select 
secid OPICS_SECID,name FIN_DEAL_SECID,CASE WHEN trim(secid) = trim(name) THEN 'TRUE' ELSE 'FALSE' END MATCH_secid,
seq OPICS_SCHEDULE_SEQ,SIDE_SEQUENCE FIN_SCHEDULE_SEQ,CASE WHEN TO_NUMBER(seq) = SIDE_SEQUENCE THEN 'TRUE' ELSE 'FALSE' END MATCH_SEQUENCE,
--INTCCY OPICS_CCY,NOTIONAL_AMOUNT_CCY FIN_CCY,CASE WHEN INTCCY = NOTIONAL_AMOUNT_CCY THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
INTSTRTDTE OPICS_START_DATE ,fin_flow.START_DATE FIN_START_DATE ,CASE WHEN INTSTRTDTE = fin_flow.START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
INTENDDTE OPICS_END_DATE,fin_flow.END_DATE FIN_END_DATE,CASE WHEN INTENDDTE = fin_flow.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
RATECODE OPICS_RATECODE,RATE_CODE FIN_RATECODE,CASE WHEN nvl(RATECODE,' ') = nvl(RATE_CODE,' ') THEN 'TRUE' ELSE 'FALSE' END MATCH_RATE_CODE,
INTRATE_8 OPICS_INTRATE,NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100) FIN_INTRATE,CASE WHEN INTRATE_8 = NVL(fin_flow.FIX_RATE*100,RATE_VALUE*100) THEN 'TRUE' ELSE 'FALSE' END MATCH_INTRATE,
SPREADRATE_8 OPICS_SPREAD_RATE ,fin_flow.SPREAD_RATE*100 FIN_SPREAD_RATE,CASE WHEN to_number(SPREADRATE_8) = NVL(fin_flow.SPREAD_RATE*100,0) THEN 'TRUE' ELSE 'FALSE' END MATCH_SPREAD_RATE
 from SECS
left join SD_SEC_DEFN@ftmig on trim(secid) = trim(name) 
left join (select reset_date,REFERENCE_RATE_FBO_ID_NUM,CASH_FLOW_TYPE,parent_fbo_id_num,BASIS_CODE,START_DATE,END_DATE,NOTIONAL_AMOUNT_CCY,NOTIONAL_AMOUNT_VALUE,SPREAD_RATE,
MARGIN,FIX_RATE,SIDE_SEQUENCE,PARENT_FBO_ID_VER from  TT_SECDEFN_CASH_FLOWS@ftmig) fin_flow on PARENT_FBO_ID_NUM  = SD_SEC_DEFN.FBO_ID_NUM and PARENT_FBO_ID_VER='999999' and SIDE_SEQUENCE = to_number(seq)
LEFT JOIN (
SELECT  A.REF_RATE_FBO_ID_NUM,RATE_CODE,RATE_CCY,RATE_VALUE,EFFECTIVE_DATE FROM SD_REF_RATE_VALUE@FTMIG A
LEFT JOIN SD_REF_RATE@FTMIG B ON B.FBO_ID_NUM = A.REF_RATE_FBO_ID_NUM
) REF_RATE ON REF_RATE.REF_RATE_FBO_ID_NUM = REFERENCE_RATE_FBO_ID_NUM AND reset_date = EFFECTIVE_DATE
where TRIM(secid) IN(SELECT TRIM(name) FROM SECURITY_DEFN_O_TABLE)
AND INTSTRTDTE <= TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND  INTENDDTE > TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY')
order by secid,to_number(seq) 
