========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
SMSUserReport_not.sql 
select 
       S.CU01_CLC||S.CU01_CUS LEG_CUST_ID,FIN_IU.CUST_ID FIN_CUST_ID,CASE WHEN S.CU01_CLC||S.CU01_CUS = FIN_IU.CUST_ID THEN 'TRUE' ELSE 'FALSE' END MATCH_CUSTOMER_NO ,
        '' LEG_CORP_USER,FIN_IU.USER_ID FIN_USER_ID,CASE WHEN '' = FIN_IU.USER_ID THEN 'TRUE' ELSE 'FALSE' END MATCH_USERID ,
       TRIM(A.ADDRESS_LINE1)LEG_ADDRESS_LINE1,FIN_IU.C_ADDR1 FIN_C_ADDR1,CASE WHEN TRIM(A.ADDRESS_LINE1) = FIN_IU.C_ADDR1 THEN 'TRUE' ELSE 'FALSE' END MATCH_ADDRESS_LINE1 ,
       A.ADDRESS_LINE2 LEG_ADDRESS_LINE2,FIN_IU.C_ADDR2 FIN_C_ADDR2,CASE WHEN TRIM(A.ADDRESS_LINE2) = FIN_IU.C_ADDR2 THEN 'TRUE' ELSE 'FALSE' END MATCH_ADDRESS_LINE2 ,
       A.ADDRESS_LINE3 LEG_ADDRESS_LINE3,FIN_IU.C_ADDR3 FIN_C_ADDR3,CASE WHEN TRIM(A.ADDRESS_LINE3) = FIN_IU.C_ADDR3 THEN 'TRUE' ELSE 'FALSE' END MATCH_ADDRESS_LINE3 ,
     --  A.PHONE C_PHONE_NO,FIN_IU.C_PHONE_NO,CASE WHEN TRIM(A.PHONE) = FIN_IU.C_PHONE_NO THEN 'TRUE' ELSE 'FALSE' END MATCH_C_PHONE_NO ,
     S.CU01_MOBPN LEG_CU01_MOBPN,FIN_IU.PRINCIPAL_ID FIN_MOBILE_NUM,CASE WHEN TRIM(S.CU01_MOBPN) = FIN_IU.PRINCIPAL_ID THEN 'TRUE' ELSE 'FALSE' END MATCH_MOBILE_NUM ,
       A.GENDER LEG_GENDER,FIN_IU.C_GENDER FIN_GENDER,CASE WHEN TRIM(A.GENDER) = FIN_IU.C_GENDER THEN 'TRUE' ELSE 'FALSE' END MATCH_C_GENDER ,
       A.CUST_dob LEG_DATE_OF_BIRTH,FIN_IU.DATE_OF_BIRTH FIN_DATE_OF_BIRTH,CASE WHEN TRIM(A.CUST_dob) = FIN_IU.DATE_OF_BIRTH THEN 'TRUE' ELSE 'FALSE' END MATCH_CUST_dob ,
    --   A.NAT_ID_CARD_NUM LEG_NAT_ID_CARD_NUM,FIN_IU.PAN_NATIONAL_ID FIN_PAN_NATIONAL_ID,CASE WHEN TRIM(A.NAT_ID_CARD_NUM) = FIN_IU.PAN_NATIONAL_ID THEN 'TRUE' ELSE 'FALSE' END MATCH_PAN_NATIONAL_ID,
       CU01_LANG LEG_CU01_LANG,FIN_IU.LANG_ID FIN_LANG_ID
        from 
        YSMSCUPF01 S             
       LEFT JOIN map_cif M ON SUBSTR (M.fin_cif_id, 2, 10) = SUBSTR ('0'||S.CU01_CLC||S.CU01_CUS, 2, 10) and individual = 'Y' 
       LEFT JOIN CRMUSER.ACCOUNTS A ON A.ORGKEY = M.fin_cif_id AND a.bank_id = get_param ('BANK_ID')  
       LEFT JOIN (SELECT DISTINCT FIN_CUSR.*,FIN_CSIP.PRINCIPAL_ID FROM ECECUSER.CUSR@EBUAT_DBLINK FIN_CUSR
inner JOIN ECECUSER.CSIP@EBUAT_DBLINK FIN_CSIP ON FIN_CSIP.INDIVIDUAL_ID = FIN_CUSR.INDIVIDUAL_ID  
WHERE FIN_CSIP.CHANNEL_ID='S' and FIN_CUSR.DB_TS='1' AND FIN_CUSR.DB_TS='1' and FIN_CSIP.DB_TS='1'  AND FIN_CUSR.BANK_ID='01' -- AND FIN_CSIP.DEL_FLG='N'
) FIN_IU ON FIN_IU.CUST_ID = ('0'||S.CU01_CLC||S.CU01_CUS)
 WHERE S.CU01_STS ='A'; 
