========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
spot_position_report.sql 
SELECT A.DEAL_DATE LEG_DEALDATE,B.DEAL_DATE FINACLE_DEAL_DATE ,CASE WHEN TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY') = B.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALDATE,
MAIN_LEG_CCY_PAIR LEG_CURRENCY_PAIR,CURRENCY_PAIR FIN_CURRENCY_PAIR,CASE WHEN MAIN_LEG_CCY_PAIR = CURRENCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CURRENCY_PAIR,
ABS( B. CCY_ONE_AMOUNT_VALUE) LEG_AMOUNT,to_number(MAIN_LEG_CCY_ONE_AMOUNT) FIN_AMOUNT,CASE WHEN ABS( B. CCY_ONE_AMOUNT_VALUE) = MAIN_LEG_CCY_ONE_AMOUNT THEN 'TRUE' ELSE 'FALSE' END MATCH_AMOUNT,
CASE WHEN MAIN_LEG_CCY_PAIR LIKE '%JPY%' THEN ROUND(to_number(MARKET_SPOT_RATE),8)  ELSE  ROUND(to_number(MARKET_SPOT_RATE),8) END LEG_SPOT_RATE,ROUND(RATE,8) FIN_SPOT_RATE,
CASE WHEN CASE WHEN MAIN_LEG_CCY_PAIR LIKE '%JPY%' THEN ROUND(to_number(MARKET_SPOT_RATE),8)  ELSE  ROUND(to_number(MARKET_SPOT_RATE),8) END = ROUND(RATE,8) THEN 'TRUE' ELSE 'FALSE' END MATCH_SPOT_RATE,
MEMO_FIELD_1 LEG_BRANCH,MEMO_FIELD0 FIN_BRANCH,CASE WHEN MEMO_FIELD_1 = MEMO_FIELD0 THEN 'TRUE' ELSE 'FALSE' END MATCH_BRANCH,
DEAL_NUM FIN_DEAL_NUM
FROM SPOT_POSITION_DEALS_O_TABLE A
INNER JOIN(
SELECT FIN_FX_OUTRIGHT.DEAL_NUM,FIN_FX_OUTRIGHT.DEAL_TYPE,TTFXFL.CCY_ONE_AMOUNT_VALUE,CURRENCY_PAIR,DEAL_DATE ,CASE WHEN FX_BUY_SELL='B' THEN 'BUY' ELSE 'SELL' END BUY_SELL,TTFXFL.RATE,MEMO_FIELD0 FROM 
TT_FXP_DEAL@FTFC FIN_FX_OUTRIGHT
LEFT JOIN SD_TRADING_BOOK@FTFC SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTFC SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTFC SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTFC TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM
LEFT JOIN TT_FXP_LEG@FTFC TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
WHERE  FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD' AND FIN_FX_OUTRIGHT.DEAL_NUM = FIN_FX_OUTRIGHT.DEAL_IDENTIFIER
) B
ON B.CURRENCY_PAIR = A.MAIN_LEG_CCY_PAIR AND BUY_SELL = MAIN_LEG_FX_BUY_SELL AND ABS( B. CCY_ONE_AMOUNT_VALUE) = MAIN_LEG_CCY_ONE_AMOUNT



SELECT A.DEAL_DATE LEG_DEALDATE,B.DEAL_DATE FINACLE_DEAL_DATE ,CASE WHEN TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY') = B.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALDATE,
MAIN_LEG_CCY_PAIR LEG_CURRENCY_PAIR,CCY1_CALENDAR_SET||'/'||CCY2_CALENDAR_SET FIN_CURRENCY_PAIR,CASE WHEN MAIN_LEG_CCY_PAIR = CURRENCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CURRENCY_PAIR,
to_number(MAIN_LEG_CCY_ONE_AMOUNT) LEG_AMOUNT,ABS( B. CCY_ONE_AMOUNT_VALUE) FIN_AMOUNT,CASE WHEN ABS( B. CCY_ONE_AMOUNT_VALUE) = MAIN_LEG_CCY_ONE_AMOUNT THEN 'TRUE' ELSE 'FALSE' END MATCH_AMOUNT,
CASE WHEN MAIN_LEG_CCY_PAIR LIKE '%JPY%' THEN ROUND(to_number(MARKET_SPOT_RATE),8)  ELSE  ROUND(to_number(MARKET_SPOT_RATE),8) END LEG_SPOT_RATE,ROUND(RATE,8) FIN_SPOT_RATE,
CASE WHEN CASE WHEN MAIN_LEG_CCY_PAIR LIKE '%JPY%' THEN ROUND(to_number(MARKET_SPOT_RATE),8)  ELSE  ROUND(to_number(MARKET_SPOT_RATE),8) END = ROUND(RATE,8) THEN 'TRUE' ELSE 'FALSE' END MATCH_SPOT_RATE,
MEMO_FIELD_1 LEG_BRANCH,MEMO_FIELD0 FIN_BRANCH,CASE WHEN MEMO_FIELD_1 = MEMO_FIELD0 THEN 'TRUE' ELSE 'FALSE' END MATCH_BRANCH,
DEAL_NUM FIN_DEAL_NUM
FROM SPOT_POSITION_DEALS_O_TABLE A
left JOIN(
SELECT CCY1_CALENDAR_SET,CCY2_CALENDAR_SET,FIN_FX_OUTRIGHT.DEAL_NUM,FIN_FX_OUTRIGHT.DEAL_TYPE,TTFXFL.CCY_ONE_AMOUNT_VALUE,CURRENCY_PAIR,DEAL_DATE ,CASE WHEN FX_BUY_SELL='B' THEN 'BUY' ELSE 'SELL' END BUY_SELL,TTFXFL.RATE,MEMO_FIELD0 FROM 
TT_FXP_DEAL@FTFC FIN_FX_OUTRIGHT
LEFT JOIN SD_TRADING_BOOK@FTFC SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTFC SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTFC SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTFC TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM
LEFT JOIN TT_FXP_LEG@FTFC TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
WHERE  FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD' AND FIN_FX_OUTRIGHT.DEAL_NUM = FIN_FX_OUTRIGHT.DEAL_IDENTIFIER
) B
ON CCY1_CALENDAR_SET||'/'||CCY2_CALENDAR_SET  = trim(A.MAIN_LEG_CCY_PAIR) AND trim(BUY_SELL) = trim(MAIN_LEG_FX_BUY_SELL) and trim(MEMO_FIELD0) = trim(MEMO_FIELD_1)




SELECT CCY_PAIR,A.DEAL_DATE LEG_DEALDATE,B.DEAL_DATE FINACLE_DEAL_DATE ,CASE WHEN TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY') = B.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALDATE,
MAIN_LEG_CCY_PAIR LEG_CURRENCY_PAIR,QUOTED_CCY_PAIR FIN_CURRENCY_PAIR,CASE WHEN MAIN_LEG_CCY_PAIR = CURRENCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CURRENCY_PAIR,
to_number(MAIN_LEG_CCY_ONE_AMOUNT) LEG_AMOUNT,ABS( B. CCY_ONE_AMOUNT_VALUE) FIN_AMOUNT,CASE WHEN ABS( B. CCY_ONE_AMOUNT_VALUE) = MAIN_LEG_CCY_ONE_AMOUNT THEN 'TRUE' ELSE 'FALSE' END MATCH_AMOUNT,
 to_char(to_number(MARKET_SPOT_RATE),'9990.999999') LEG_SPOT_RATE,to_char(ROUND(RATE,6),'9990.999999') FIN_SPOT_RATE,
CASE WHEN  to_char(to_number(MARKET_SPOT_RATE),'9990.999999') = to_char(ROUND(RATE,6),'9990.999999') THEN 'TRUE' ELSE 'FALSE' END MATCH_SPOT_RATE,
MEMO_FIELD_1 LEG_BRANCH,MEMO_FIELD0 FIN_BRANCH,CASE WHEN MEMO_FIELD_1 = MEMO_FIELD0 THEN 'TRUE' ELSE 'FALSE' END MATCH_BRANCH,
DEAL_NUM FIN_DEAL_NUM
FROM SPOT_POSITION_DEALS_O_TABLE A
left JOIN(
SELECT CCY_PAIR,CCY1_CALENDAR_SET,CCY2_CALENDAR_SET,FIN_FX_OUTRIGHT.DEAL_NUM,FIN_FX_OUTRIGHT.DEAL_TYPE,
case when CCY_PAIR =QUOTED_CCY_PAIR  then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end CCY_ONE_AMOUNT_VALUE,CURRENCY_PAIR,QUOTED_CCY_PAIR,DEAL_DATE ,
CASE WHEN CCY_PAIR =QUOTED_CCY_PAIR and FX_BUY_SELL='B' THEN 'BUY'  
WHEN CCY_PAIR =QUOTED_CCY_PAIR and FX_BUY_SELL='S' THEN 'SELL' 
WHEN CCY_PAIR !=QUOTED_CCY_PAIR and FX_BUY_SELL='S' THEN 'BUY'
WHEN CCY_PAIR !=QUOTED_CCY_PAIR and FX_BUY_SELL='B' THEN 'SELL'
END BUY_SELL,case when CCY_PAIR =QUOTED_CCY_PAIR then TTFXL.MARKET_SPOT_RATE else 1/TTFXL.MARKET_SPOT_RATE end RATE,MEMO_FIELD0 FROM 
TT_FXP_DEAL@ftuat FIN_FX_OUTRIGHT
LEFT JOIN SD_TRADING_BOOK@ftuat SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@ftuat SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@ftuat SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@ftuat SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@ftuat TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM
LEFT JOIN TT_FXP_LEG@ftuat TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
WHERE  FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD' AND FIN_FX_OUTRIGHT.DEAL_NUM = FIN_FX_OUTRIGHT.DEAL_IDENTIFIER and  MEMO_FIELD0='KUWAIT'
) B
ON QUOTED_CCY_PAIR = trim(A.MAIN_LEG_CCY_PAIR)
 AND trim(BUY_SELL) = trim(MAIN_LEG_FX_BUY_SELL) and 
trim(MEMO_FIELD0) = trim(MEMO_FIELD_1)








SELECT DISTINCT 
TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY')||'-'||MAIN_LEG_CCY_PAIR||'-'||ABS(MAIN_LEG_CCY_ONE_AMOUNT)||'-'|| to_char(to_number(MARKET_SPOT_RATE),'9990.999999')||'-'|| MEMO_FIELD_1 OPICS_DATA,
 B.DEAL_DATE||'-'||CCY_PAIR ||'-'||MAIN_LEG_CCY_ONE_AMOUNT||'-'||CASE WHEN CCY_PAIR='JPY/KWD' THEN to_char(ROUND(RATE*100,6),'9990.999999') ELSE to_char(ROUND(RATE,6),'9990.999999') END||'-'||MEMO_FIELD0  FIN_DATA,
CASE WHEN TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY')||'-'||MAIN_LEG_CCY_PAIR||'-'||ABS(MAIN_LEG_CCY_ONE_AMOUNT)||'-'|| to_char(to_number(MARKET_SPOT_RATE),'9990.999999')||'-'|| MEMO_FIELD_1=
B.DEAL_DATE||'-'||CCY_PAIR ||'-'||MAIN_LEG_CCY_ONE_AMOUNT||'-'||CASE WHEN CCY_PAIR='JPY/KWD' THEN to_char(ROUND(RATE*100,6),'9990.999999') ELSE to_char(ROUND(RATE,6),'9990.999999') END||'-'||MEMO_FIELD0 THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM SPOT_POSITION_DEALS_O_TABLE A
left JOIN(SELECT CCY_PAIR,CCY1_CALENDAR_SET,CCY2_CALENDAR_SET,FIN_FX_OUTRIGHT.DEAL_NUM,FIN_FX_OUTRIGHT.DEAL_TYPE,
case when CCY_PAIR =CURRENCY_PAIR  then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end CCY_ONE_AMOUNT_VALUE,CURRENCY_PAIR,DEAL_DATE ,
CASE WHEN CCY_PAIR =CURRENCY_PAIR and FX_BUY_SELL='B' THEN 'BUY'  
WHEN CCY_PAIR =CURRENCY_PAIR and FX_BUY_SELL='S' THEN 'SELL' 
WHEN CCY_PAIR !=CURRENCY_PAIR and FX_BUY_SELL='S' THEN 'BUY'
WHEN CCY_PAIR !=CURRENCY_PAIR and FX_BUY_SELL='B' THEN 'SELL'
END BUY_SELL,case when CCY_PAIR =CURRENCY_PAIR then TTFXL.MARKET_SPOT_RATE else TTFXL.MARKET_SPOT_RATE end RATE,MEMO_FIELD0 FROM 
TT_FXP_DEAL@FTMIG FIN_FX_OUTRIGHT
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM  and PARENT_FBO_ID_VER='1' and PARENT_FBO_MIN_VER='1'
LEFT JOIN TT_FXP_LEG@FTMIG TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
WHERE  FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD' AND FIN_FX_OUTRIGHT.DEAL_NUM = FIN_FX_OUTRIGHT.DEAL_IDENTIFIER and  MEMO_FIELD0='KUWAIT') B
ON CCY_PAIR = trim(A.MAIN_LEG_CCY_PAIR)
 AND --trim(BUY_SELL) = trim(MAIN_LEG_FX_BUY_SELL) and 
trim(MEMO_FIELD0) = trim(MEMO_FIELD_1)



SELECT DISTINCT 
TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY')||'-'||MAIN_LEG_CCY_PAIR||'-'||ABS(MAIN_LEG_CCY_ONE_AMOUNT)||'-'|| to_char(to_number(MARKET_SPOT_RATE),'9990.999999')||'-'|| MEMO_FIELD_1 OPICS_DATA,
 B.DEAL_DATE||'-'||CCY_PAIR ||'-'||MAIN_LEG_CCY_ONE_AMOUNT||'-'||CASE WHEN CCY_PAIR='JPY/KWD' THEN to_char(ROUND(RATE,6),'9990.999999') ELSE to_char(ROUND(RATE,6),'9990.999999') END||'-'||MEMO_FIELD0  FIN_DATA,
CASE WHEN TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY')||'-'||MAIN_LEG_CCY_PAIR||'-'||ABS(MAIN_LEG_CCY_ONE_AMOUNT)||'-'|| to_char(to_number(MARKET_SPOT_RATE),'9990.999999')||'-'|| MEMO_FIELD_1=
B.DEAL_DATE||'-'||CCY_PAIR ||'-'||MAIN_LEG_CCY_ONE_AMOUNT||'-'||CASE WHEN CCY_PAIR='JPY/KWD' THEN to_char(ROUND(RATE,6),'9990.999999') ELSE to_char(ROUND(RATE,6),'9990.999999') END||'-'||MEMO_FIELD0 THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM SPOT_POSITION_DEALS_O_TABLE A
left JOIN(SELECT CCY_PAIR,CCY1_CALENDAR_SET,CCY2_CALENDAR_SET,FIN_FX_OUTRIGHT.DEAL_NUM,FIN_FX_OUTRIGHT.DEAL_TYPE,
case when CCY_PAIR =CURRENCY_PAIR  then TTFXL.CCY_ONE_AMOUNT_VALUE else TTFXL.CCY_TWO_AMOUNT_VALUE end CCY_ONE_AMOUNT_VALUE,CURRENCY_PAIR,DEAL_DATE ,
CASE WHEN CCY_PAIR =CURRENCY_PAIR and FX_BUY_SELL='B' THEN 'BUY'  
WHEN CCY_PAIR =CURRENCY_PAIR and FX_BUY_SELL='S' THEN 'SELL' 
WHEN CCY_PAIR !=CURRENCY_PAIR and FX_BUY_SELL='S' THEN 'BUY'
WHEN CCY_PAIR !=CURRENCY_PAIR and FX_BUY_SELL='B' THEN 'SELL'
END BUY_SELL,case when CCY_PAIR =CURRENCY_PAIR then TTFXL.MARKET_SPOT_RATE else TTFXL.MARKET_SPOT_RATE end RATE,MEMO_FIELD0 FROM 
TT_FXP_DEAL@FTMIG FIN_FX_OUTRIGHT
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM  and PARENT_FBO_ID_VER='1' and PARENT_FBO_MIN_VER='1'
LEFT JOIN TT_FXP_LEG@FTMIG TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
WHERE  FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD' AND FIN_FX_OUTRIGHT.DEAL_NUM = FIN_FX_OUTRIGHT.DEAL_IDENTIFIER and  MEMO_FIELD0='KUWAIT') B
ON CCY_PAIR = trim(A.MAIN_LEG_CCY_PAIR)
 AND --trim(BUY_SELL) = trim(MAIN_LEG_FX_BUY_SELL) and 
trim(MEMO_FIELD0) = trim(MEMO_FIELD_1)



SELECT DISTINCT 
TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY')||'-'||MAIN_LEG_CCY_PAIR||'-'||ABS(MAIN_LEG_CCY_ONE_AMOUNT)||'-'|| to_char(to_number(MARKET_SPOT_RATE),'9990.999999')||'-'|| MEMO_FIELD_1 OPICS_DATA,
 B.DEAL_DATE||'-'||CCY_PAIR ||'-'||CCY_ONE_AMOUNT_VALUE||'-'||CASE WHEN CCY_PAIR='JPY/KWD' THEN to_char(ROUND(RATE,6),'9990.999999') ELSE to_char(ROUND(RATE,6),'9990.999999') END||'-'||MEMO_FIELD0  FIN_DATA,
CASE WHEN TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY')||'-'||MAIN_LEG_CCY_PAIR||'-'||ABS(MAIN_LEG_CCY_ONE_AMOUNT)||'-'|| to_char(to_number(MARKET_SPOT_RATE),'9990.999999')||'-'|| MEMO_FIELD_1=
B.DEAL_DATE||'-'||CCY_PAIR ||'-'||CCY_ONE_AMOUNT_VALUE||'-'||CASE WHEN CCY_PAIR='JPY/KWD' THEN to_char(ROUND(RATE,6),'9990.999999') ELSE to_char(ROUND(RATE,6),'9990.999999') END||'-'||MEMO_FIELD0 THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM SPOT_POSITION_DEALS_O_TABLE A
left JOIN(SELECT CCY_PAIR,CCY1_CALENDAR_SET,CCY2_CALENDAR_SET,FIN_FX_OUTRIGHT.DEAL_NUM,FIN_FX_OUTRIGHT.DEAL_TYPE,
TTFXL.CCY_ONE_AMOUNT_VALUE CCY_ONE_AMOUNT_VALUE,CURRENCY_PAIR,DEAL_DATE ,
CASE WHEN CCY_PAIR =CURRENCY_PAIR and FX_BUY_SELL='B' THEN 'BUY'  
WHEN CCY_PAIR =CURRENCY_PAIR and FX_BUY_SELL='S' THEN 'SELL' 
WHEN CCY_PAIR !=CURRENCY_PAIR and FX_BUY_SELL='S' THEN 'BUY'
WHEN CCY_PAIR !=CURRENCY_PAIR and FX_BUY_SELL='B' THEN 'SELL'
END BUY_SELL,case when CCY_PAIR =CURRENCY_PAIR then TTFXL.MARKET_SPOT_RATE else TTFXL.MARKET_SPOT_RATE end RATE,MEMO_FIELD0 FROM 
TT_FXP_DEAL@FTMIG FIN_FX_OUTRIGHT
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM  and PARENT_FBO_ID_VER='1' and PARENT_FBO_MIN_VER='1'
LEFT JOIN TT_FXP_LEG@FTMIG TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
WHERE  FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD' AND FIN_FX_OUTRIGHT.DEAL_NUM = FIN_FX_OUTRIGHT.DEAL_IDENTIFIER and  MEMO_FIELD0='KUWAIT') B
ON CCY_PAIR = trim(A.MAIN_LEG_CCY_PAIR)
 AND --trim(BUY_SELL) = trim(MAIN_LEG_FX_BUY_SELL) and 
trim(MEMO_FIELD0) = trim(MEMO_FIELD_1)




SELECT DISTINCT 
TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY')||'-'||MAIN_LEG_CCY_PAIR||'-'||ABS(MAIN_LEG_CCY_ONE_AMOUNT)||'-'|| TRIM(to_char(to_number(MARKET_SPOT_RATE),'9990.999999')) OPICS_DATA,
 B.DEAL_DATE||'-'||CCY_PAIR ||'-'||CCY_ONE_AMOUNT_VALUE||'-'||TRIM(CASE WHEN CCY_PAIR='JPY/KWD' THEN to_char(ROUND(RATE,6),'9990.999999') ELSE to_char(ROUND(RATE,6),'9990.999999') END)  FIN_DATA,
CASE WHEN TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY')||'-'||MAIN_LEG_CCY_PAIR||'-'||ABS(MAIN_LEG_CCY_ONE_AMOUNT)||'-'|| TRIM(to_char(to_number(MARKET_SPOT_RATE),'9990.999999'))=
B.DEAL_DATE||'-'||CCY_PAIR ||'-'||CCY_ONE_AMOUNT_VALUE||'-'||TRIM(CASE WHEN CCY_PAIR='JPY/KWD' THEN to_char(ROUND(RATE,6),'9990.999999') ELSE to_char(ROUND(RATE,6),'9990.999999') END) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM SPOT_POSITION_DEALS_O_TABLE A
left JOIN(SELECT QUOTED_CCY_PAIR,CCY_PAIR,CCY1_CALENDAR_SET,CCY2_CALENDAR_SET,FIN_FX_OUTRIGHT.DEAL_NUM,FIN_FX_OUTRIGHT.DEAL_TYPE,
TTFXL.CCY_ONE_AMOUNT_VALUE CCY_ONE_AMOUNT_VALUE,CURRENCY_PAIR,DEAL_DATE ,
CASE WHEN CCY_PAIR =CURRENCY_PAIR and FX_BUY_SELL='B' THEN 'BUY'  
WHEN CCY_PAIR =CURRENCY_PAIR and FX_BUY_SELL='S' THEN 'SELL' 
WHEN CCY_PAIR !=CURRENCY_PAIR and FX_BUY_SELL='S' THEN 'BUY'
WHEN CCY_PAIR !=CURRENCY_PAIR and FX_BUY_SELL='B' THEN 'SELL'
END BUY_SELL,case when CCY_PAIR =CURRENCY_PAIR then TTFXL.MARKET_SPOT_RATE else TTFXL.MARKET_SPOT_RATE end RATE,MEMO_FIELD0 FROM 
TT_FXP_DEAL@FTMIG FIN_FX_OUTRIGHT
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM  and PARENT_FBO_ID_VER='1' and PARENT_FBO_MIN_VER='1'
LEFT JOIN TT_FXP_LEG@FTMIG TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE
WHERE  FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD' AND  TO_CHAR(TRIM(FIN_FX_OUTRIGHT.DEAL_NUM)) = TO_CHAR(TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)) 
AND DEAL_DATE = TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND TTFXL.VALUE_DATE_ONE = TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND TTFXL.VALUE_DATE_TWO = TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') ) B
ON QUOTED_CCY_PAIR = trim(A.MAIN_LEG_CCY_PAIR)
-- AND --trim(BUY_SELL) = trim(MAIN_LEG_FX_BUY_SELL) and 
--trim(MEMO_FIELD0) = trim(MEMO_FIELD_1)


SELECT DEAL_NUM FIN_DEAL_NUM,
MAIN_LEG_SPOT_RISK_ENTITY MAPPED_ENTITY, NAME FIN_ENTITY, CASE WHEN MAIN_LEG_SPOT_RISK_ENTITY =  NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY') OPICS_DEAL_DATE ,B.DEAL_DATE FIN_DEAL_DATE,CASE WHEN TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY') = B.DEAL_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_DEAL_DATE,
TO_DATE(TRIM(A.MAIN_LEG_VALUE_DATE_ONE),'DD-mON-YYYY') OPICS_START_DATE ,B.VALUE_DATE_ONE FIN_START_DATE,CASE WHEN TO_DATE(TRIM(A.MAIN_LEG_VALUE_DATE_ONE),'DD-mON-YYYY') = B.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
TO_DATE(TRIM(A.MAIN_LEG_VALUE_DATE_ONE),'DD-mON-YYYY') OPICS_END_DATE ,B.VALUE_DATE_TWO FIN_END_DATE,CASE WHEN TO_DATE(TRIM(A.MAIN_LEG_VALUE_DATE_ONE),'DD-mON-YYYY') = B.VALUE_DATE_ONE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
A.MAIN_LEG_CCY_PAIR MAPPED_CCY_PAIR,B.QUOTED_CCY_PAIR FIN_CCY_PAIR, CASE WHEN A.MAIN_LEG_CCY_PAIR = B.QUOTED_CCY_PAIR THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_PAIR,
A.MAIN_LEG_CCY_ONE_AMOUNT OPICS_CCY_AMT,  ( CCY_ONE_AMOUNT_VALUE) FIN_CCY_AMT,CASE WHEN round(to_number(A.MAIN_LEG_CCY_ONE_AMOUNT),8) =  round ( CCY_ONE_AMOUNT_VALUE,8)  THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY_AMT,
ROUND(TO_NUMBER(MARKET_SPOT_RATE),8) OPICS_SPOT_RATE,ROUND(CASE WHEN CCY_PAIR='JPY/KWD' THEN RATE ELSE RATE END,8) FIN_SPOT_RATE, CASE WHEN ROUND(TO_NUMBER(MARKET_SPOT_RATE),8) = ROUND(CASE WHEN CCY_PAIR='JPY/KWD' THEN RATE ELSE RATE END,8) THEN 'TRUE' ELSE 'FALSE' END MATCH_SPOT_RATE,
( CCY_TWO_AMOUNT_VALUE) FIN_CTR_AMT,
TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY')||'-'||MAIN_LEG_CCY_PAIR||'-'||ABS(MAIN_LEG_CCY_ONE_AMOUNT)||'-'|| TRIM(TO_CHAR(TO_NUMBER(MARKET_SPOT_RATE),'9990.999999')) OPICS_DATA,
 B.DEAL_DATE||'-'||CCY_PAIR ||'-'||CCY_ONE_AMOUNT_VALUE||'-'||TRIM(CASE WHEN CCY_PAIR='JPY/KWD' THEN TO_CHAR(ROUND(RATE,6),'9990.999999') ELSE TO_CHAR(ROUND(RATE,6),'9990.999999') END)  FIN_DATA,
CASE WHEN TO_DATE(TRIM(A.DEAL_DATE),'DD-mON-YYYY')||'-'||MAIN_LEG_CCY_PAIR||'-'||ABS(MAIN_LEG_CCY_ONE_AMOUNT)||'-'|| TRIM(TO_CHAR(TO_NUMBER(MARKET_SPOT_RATE),'9990.999999'))=
B.DEAL_DATE||'-'||CCY_PAIR ||'-'||CCY_ONE_AMOUNT_VALUE||'-'||TRIM(CASE WHEN CCY_PAIR='JPY/KWD' THEN TO_CHAR(ROUND(RATE,6),'9990.999999') ELSE TO_CHAR(ROUND(RATE,6),'9990.999999') END) THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM SPOT_POSITION_DEALS_O_TABLE A
LEFT JOIN(SELECT TTFXL.VALUE_DATE_ONE,TTFXL.VALUE_DATE_TWO,SDENT.NAME,QUOTED_CCY_PAIR,CCY_PAIR,CCY1_CALENDAR_SET,CCY2_CALENDAR_SET,FIN_FX_OUTRIGHT.DEAL_NUM,FIN_FX_OUTRIGHT.DEAL_TYPE,
TTFXL.CCY_ONE_AMOUNT_VALUE,TTFXL.CCY_TWO_AMOUNT_VALUE,CURRENCY_PAIR,DEAL_DATE ,
CASE WHEN CCY_PAIR =CURRENCY_PAIR AND FX_BUY_SELL='B' THEN 'BUY'  
WHEN CCY_PAIR =CURRENCY_PAIR AND FX_BUY_SELL='S' THEN 'SELL' 
WHEN CCY_PAIR !=CURRENCY_PAIR AND FX_BUY_SELL='S' THEN 'BUY'
WHEN CCY_PAIR !=CURRENCY_PAIR AND FX_BUY_SELL='B' THEN 'SELL'
END BUY_SELL,CASE WHEN CCY_PAIR =CURRENCY_PAIR THEN TTFXL.MARKET_SPOT_RATE ELSE TTFXL.MARKET_SPOT_RATE END RATE,MEMO_FIELD0 FROM 
TT_FXP_DEAL@FTMIG FIN_FX_OUTRIGHT
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_FX_OUTRIGHT.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_FX_OUTRIGHT.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_FX_OUTRIGHT.CPTY_FBO_ID_NUM
LEFT JOIN TT_FXP_FLOW@FTMIG TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM  AND PARENT_FBO_ID_VER='1' AND PARENT_FBO_MIN_VER='1'
LEFT JOIN TT_FXP_LEG@FTMIG TTFXL ON  TTFXL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM AND TTFXL.PARENT_FBO_ID_TYPE = FIN_FX_OUTRIGHT.DEAL_TYPE AND TTFXL.PARENT_FBO_ID_VER='999999'
WHERE  FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD' AND  TO_CHAR(TRIM(FIN_FX_OUTRIGHT.DEAL_NUM)) = TO_CHAR(TRIM(FIN_FX_OUTRIGHT.DEAL_IDENTIFIER)) 
AND DEAL_DATE = TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND TTFXL.VALUE_DATE_ONE = TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') AND TTFXL.VALUE_DATE_TWO = TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY') ) B
ON QUOTED_CCY_PAIR = TRIM(A.MAIN_LEG_CCY_PAIR)
-- AND --trim(BUY_SELL) = trim(MAIN_LEG_FX_BUY_SELL) and 
--trim(MEMO_FIELD0) = trim(MEMO_FIELD_1) 
