========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
swap_report.sql 

select distinct
S1.DEALNO OPICS_DEALNO, FIN_SWAP.DEAL_IDENTIFIER FINACLE_DEAL_IDENTIFIER, CASE WHEN TRIM(S1.DEALNO) = TRIM(FIN_SWAP.DEAL_IDENTIFIER) THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
C.CMNE OPICS_CMNE,SDCP.MNEMONIC FINACLE_Counterparty,CASE WHEN TRIM(C.CMNE) = TRIM(SDCP.MNEMONIC) THEN 'TRUE' ELSE 'FALSE' END MATCH_Counterparty,--C.CMNE,-- Counterparty, --***
S1.NOTCCY OPICS_NOTCCY,S2.NOTCCY OPICS_NOTCCY,FIN_SWAP.CURRENCY_LIST FINACLE_CURRENCY_STRING,--CURRENCY_STRING,
S1.FIXFLOATIND OPICS_FIXFLOATIND, CASH_FLOW_TYPE FINACLE_CASH_FLOW_TYPE,
S1.MATDATE OPICS_MATDATE,FIN_SWAP.END_DATE FINACLE_END_DATE,CASE WHEN S1.MATDATE= FIN_SWAP.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_END_DATE,
S1.STARTDATE OPICS_STARTDATE,FIN_SWAP.START_DATE OPICS_START_DATE,CASE WHEN S1.STARTDATE= FIN_SWAP.START_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_START_DATE,
S1.PRODTYPE OPICS_PRODTYPE,SDTRBK.NAME FINACLE_TRADING_BOOK,--TRADING_BOOK,--***
S1.PRODTYPE OPICS_PRODTYPE,SDSBTY.NAME FINACLE_SUBTYPE,
S1.NOTCCYAMT OPICS_NOTCCYAMT,NOTIONAL_AMOUNT_VALUE FINACLE_NOTIONAL_AMOUNT_VALUE,--***
S1.NOTCCY OPICS_NOTCCY,S2.NOTCCY OPICS_NOTCCY, FIN_SWAP.CCY_CALENDAR_SET FINACLE_CCY_CALENDAR_SET,
S1.INTRATE_8 OPICS_INTRATE_8,SETTLEMENT_RATE*100 FINACLE_FIX_RATE,--@@@@@@@@
s1.RATECODE OPICS_RATECODE,TTSWFL.CASH_FLOW_TYPE FINACLE_CASH_FLOW_TYPE,
S1.BASIS,BASIS_CODE FINACLE_BASIS_CODE,--***
S2.FIXFLOATIND,FIN_SWAP.TYPE_STRING,
S1.BR,FIN_SWAP.SDENT.NAME FINACLE_ENTITY_NAME--,-- ENTITY_NAME,--***
FROM SWDT S1
INNER JOIN SWDT S2 ON TRIM(S2.DEALNO)=TRIM(S1.DEALNO) AND S2.SEQ='002' 
INNER JOIN SWDH H ON trim(S1.DEALNO)=trim(H.DEALNO) AND TRIM(H.REVDATE) IS NULL
INNER JOIN CUST C ON C.CNO=H.CNO
LEFT JOIN  TT_SWAP@FTUAT FIN_SWAP  ON TRIM(S1.DEALNO) = TRIM(FIN_SWAP.DEAL_IDENTIFIER) and DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@FTUAT SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_SWAP.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTUAT SDENT ON SDENT.FBO_ID_NUM = FIN_SWAP.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTUAT SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_SWAP.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTUAT SDCP ON SDCP.FBO_ID_NUM= FIN_SWAP.CPTY_FBO_ID_NUM
LEFT JOIN TT_SWAP_CASH_FLOWS@FTUAT TTSWFL ON TTSWFL.PARENT_FBO_ID_NUM = FIN_SWAP.DEAL_NUM   AND trim(SETTLEMENT_RATE) IS NOT NULL
WHERE S1.SEQ='001' AND S1.MATDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')
and (S1.INTRATE_8 = SETTLEMENT_RATE*100 or trim(s1.RATECODE) not like 'FIX%' or S1.DEALNO='8100050');

select DISTINCT 
S1.BR||'-'||S1.DEALNO||'-'||S1.FIXFLOATIND||'-'||TRIM(C.CMNE) ||'-'||S1.NOTCCY||','||S2.NOTCCY||'-'||S1.MATDATE||'-'||S1.STARTDATE||'-'||S1.PRODTYPE||'-'||S1.NOTCCYAMT||'-'||S1.INTRATE_8 OPICS_DATA,
CASE WHEN TRIM(S1.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||S1.DEALNO||'-'||CASE WHEN S1.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END||'-'||TRIM(C.CMNE) ||'-'||S1.NOTCCY||','||
S2.NOTCCY||'-'||S1.MATDATE||'-'||S1.STARTDATE||'-'||CASE WHEN TRIM(S1.PRODTYPE)='IR' THEN 'IRSH' ELSE 'CCIRST' END||'-'||ABS(S1.NOTCCYAMT)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN ROUND(S1.INTRATE_8,4) ELSE ROUND(S2.INTRATE_8,4) END ||'-'||ABS(S2.NOTCCYAMT) CONV_OPICS_DATA,
FIN_SWAP.SDENT.NAME||'-'||FIN_SWAP.DEAL_IDENTIFIER||'-'||CASH_FLOW_TYPE||'-'||SDCP.NAME||'-'||CASE WHEN LENGTH(FIN_SWAP.CCY_CALENDAR_SET)=3 THEN FIN_SWAP.CCY_CALENDAR_SET||','||
FIN_SWAP.CCY_CALENDAR_SET ELSE FIN_SWAP.CCY_CALENDAR_SET END ||'-'||FIN_SWAP.END_DATE||'-'||FIN_SWAP.START_DATE||'-'||SDSBTY.NAME||'-'||ABS(PAY_AMOUNT)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN ROUND(PAY_RATE,4) ELSE ROUND(REC_RATE,4) END ||'-'||ABS(REC_AMOUNT) FIN_DATA,
CASE WHEN CASE WHEN TRIM(S1.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||S1.DEALNO||'-'||CASE WHEN S1.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END||'-'||TRIM(C.CMNE) ||'-'||
S1.NOTCCY||','||S2.NOTCCY||'-'||S1.MATDATE||'-'||S1.STARTDATE||'-'||CASE WHEN TRIM(S1.PRODTYPE)='IR' THEN 'IRSH' ELSE 'CCIRST' END||'-'||ABS(S1.NOTCCYAMT)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN ROUND(S1.INTRATE_8,4) ELSE ROUND(S2.INTRATE_8,4) END||'-'||ABS(S2.NOTCCYAMT)  =
FIN_SWAP.SDENT.NAME||'-'||FIN_SWAP.DEAL_IDENTIFIER||'-'||CASH_FLOW_TYPE||'-'||SDCP.NAME||'-'||CASE WHEN LENGTH(FIN_SWAP.CCY_CALENDAR_SET)=3 THEN FIN_SWAP.CCY_CALENDAR_SET||','||
FIN_SWAP.CCY_CALENDAR_SET ELSE FIN_SWAP.CCY_CALENDAR_SET END||'-'||FIN_SWAP.END_DATE||'-'||FIN_SWAP.START_DATE||'-'||SDSBTY.NAME||'-'||ABS(PAY_AMOUNT)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN ROUND(PAY_RATE,4) ELSE ROUND(REC_RATE,4) END||'-'||ABS(REC_AMOUNT)
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM SWDT S1
INNER JOIN SWDT S2 ON TRIM(S2.DEALNO)=TRIM(S1.DEALNO) AND S2.SEQ='002' 
INNER JOIN SWDH H ON trim(S1.DEALNO)=trim(H.DEALNO) AND TRIM(H.REVDATE) IS NULL
INNER JOIN CUST C ON C.CNO=H.CNO
LEFT JOIN  TT_SWAP@FTMIG FIN_SWAP  ON TRIM(S1.DEALNO) = TRIM(FIN_SWAP.DEAL_IDENTIFIER) and DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_SWAP.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_SWAP.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_SWAP.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_SWAP.CPTY_FBO_ID_NUM
LEFT JOIN (select A.PARENT_FBO_ID_NUM,A.CASH_FLOW_TYPE,A.NOTIONAL_AMOUNT_VALUE PAY_AMOUNT,A.SETTLEMENT_RATE PAY_RATE, B.NOTIONAL_AMOUNT_VALUE REC_AMOUNT,B.SETTLEMENT_RATE REC_RATE from (
select distinct PARENT_FBO_ID_NUM,CASH_FLOW_TYPE,NOTIONAL_AMOUNT_VALUE,SETTLEMENT_ACTION,SETTLEMENT_RATE*100 SETTLEMENT_RATE from TT_SWAP_CASH_FLOWS@FTMIG where SETTLEMENT_ACTION='PAY' and PARENT_FBO_ID_VER='999999'
) a
left join (select distinct PARENT_FBO_ID_NUM,CASH_FLOW_TYPE,NOTIONAL_AMOUNT_VALUE,SETTLEMENT_ACTION,SETTLEMENT_RATE*100 SETTLEMENT_RATE from TT_SWAP_CASH_FLOWS@FTMIG where SETTLEMENT_ACTION='REC'  and PARENT_FBO_ID_VER='999999'
)b on a.PARENT_FBO_ID_NUM = b.PARENT_FBO_ID_NUM) TTSWFL ON TTSWFL.PARENT_FBO_ID_NUM = FIN_SWAP.DEAL_NUM
WHERE S1.SEQ='001' AND S1.MATDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')



select DISTINCT 
S1.DEALNO ,FIN_SWAP.DEAL_IDENTIFIER,CASE WHEN TRIM(S1.DEALNO) = FIN_SWAP.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
S1.BR OPICS_BR, CASE WHEN TRIM(S1.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN CASE WHEN TRIM(S2.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
S1.PRODTYPE OPICS_PRODTYPE, CASE WHEN TRIM(S1.PRODTYPE)='IR' THEN 'IRSH' ELSE 'CCIRST' END MAPPED_SUBTYPE, SDSBTY.NAME ,CASE WHEN CASE WHEN TRIM(S1.PRODTYPE)='IR' THEN 'IRSH' ELSE 'CCIRST' END =  SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
S1.STARTDATE OPICS_SIDE1_START_DATE ,TTSWFL.START_DATE_1 FIN_SIDE1_START_DATE,CASE WHEN S1.STARTDATE = TTSWFL.START_DATE_1 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_START_DATE,
S1.MATDATE OPICS_SIDE1_END_DATE ,FIN_SWAP.END_DATE FIN_SIDE1_END_DATE,CASE WHEN S1.MATDATE = FIN_SWAP.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_END_DATE,
CASE WHEN S1.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END OPICS_SIDE1_FIXED_FLOAT, TTSWFL.CASH_FLOW_TYPE_1 FIN_SIDE1_FIXED_FLOAT,CASE WHEN CASE WHEN S1.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END = TTSWFL.CASH_FLOW_TYPE_1 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_FIXED_FLOAT,
S1.NOTCCY OPICS_SIDE1_CCY, TTSWFL.NOTIONAL_AMOUNT_CCY_1 FIN_SIDE1_CCY,CASE WHEN S1.NOTCCY = TTSWFL.NOTIONAL_AMOUNT_CCY_1 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_CCY,
S1.NOTCCYAMT OPICS_SIDE1_AMOUNT, TTSWFL.NOTIONAL_AMOUNT_VALUE_1 FIN_SIDE1_AMOUNT,CASE WHEN S1.NOTCCYAMT = TTSWFL.NOTIONAL_AMOUNT_VALUE_1 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_AMOUNT,
S1.INTRATE_8 OPICS_SIDE1_RATE, TTSWFL.FIX_RATE_1*100 FIN_SIDE1_RATE,CASE WHEN S1.INTRATE_8 = TTSWFL.FIX_RATE_1*100 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_FIX_RATE,
S2.STARTDATE OPICS_SIDE1_START_DATE ,TTSWFL.START_DATE_2 FIN_SIDE1_START_DATE,CASE WHEN S2.STARTDATE = TTSWFL.START_DATE_2 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_START_DATE,
S2.MATDATE OPICS_SIDE1_END_DATE ,FIN_SWAP.END_DATE FIN_SIDE1_END_DATE,CASE WHEN S2.MATDATE = FIN_SWAP.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_END_DATE,
CASE WHEN S2.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END OPICS_SIDE1_FIXED_FLOAT, TTSWFL.CASH_FLOW_TYPE_2 FIN_SIDE1_FIXED_FLOAT,CASE WHEN CASE WHEN S2.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END = TTSWFL.CASH_FLOW_TYPE_2 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_FIXED_FLOAT,
S2.NOTCCY OPICS_SIDE1_CCY, TTSWFL.NOTIONAL_AMOUNT_CCY_2 FIN_SIDE1_CCY,CASE WHEN S2.NOTCCY = TTSWFL.NOTIONAL_AMOUNT_CCY_2 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_CCY,
S2.NOTCCYAMT OPICS_SIDE1_AMOUNT, TTSWFL.NOTIONAL_AMOUNT_VALUE_2 FIN_SIDE1_AMOUNT,CASE WHEN S2.NOTCCYAMT = TTSWFL.NOTIONAL_AMOUNT_VALUE_2 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_AMOUNT,
S2.INTRATE_8 OPICS_SIDE1_RATE, TTSWFL.FIX_RATE_2*100 FIN_SIDE1_RATE,CASE WHEN S2.INTRATE_8 = TTSWFL.FIX_RATE_2*100 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_FIX_RATE,
S1.INTPAYCYCLE OPICS_PAY_INTPAYCYCLE,CF_SIDES.CREATION_FREQUENCY_1 FIN_PAY_INTPAYCYCLE, CASE WHEN TRIM(S1.INTPAYCYCLE)=TRIM(CF_SIDES.CREATION_FREQUENCY_1) THEN 'TRUE' ELSE 'FALSE' END MATCH_PAY_INTPAYCYCLE,
S2.INTPAYCYCLE OPICS_RECEIVE_INTPAYCYCLE,CF_SIDES.CREATION_FREQUENCY_2 FIN_REC_INTPAYCYCLE ,  CASE WHEN TRIM(S2.INTPAYCYCLE)=TRIM(CF_SIDES.CREATION_FREQUENCY_2) THEN 'TRUE' ELSE 'FALSE' END MATCH_REC_INTPAYCYCLE,
case when s1.PRODTYPE='IR' and s1.INTSMEANS='NOS' then s1.INTSACCT else 'BRIDGE_'||TRIM(s1.NOTCCY)||CASE WHEN TRIM(s1.BR)='51' THEN '_ABKU' ELSE '_ABKK' END  end OPICS_PAY_NOSTRO,PAY_NOS FIN_PAY_NOS, CASE WHEN TRIM(case when s1.PRODTYPE='IR' and s1.INTSMEANS='NOS' then s1.INTSACCT else 'BRIDGE_'||TRIM(s1.NOTCCY)||CASE WHEN TRIM(s1.BR)='51' THEN '_ABKU' ELSE '_ABKK' END  end) =TRIM(PAY_NOS) THEN 'TRUE' ELSE 'FALSE' END MATCH_PAY_NOS,
case when s2.PRODTYPE='IR' and s2.INTSMEANS='NOS' then s2.INTSACCT else 'BRIDGE_'||TRIM(s2.NOTCCY)||CASE WHEN TRIM(s2.BR)='51' THEN '_ABKU' ELSE '_ABKK' END  end OPICS_REC_NOSTRO,REC_NOS FIN_REC_NOS, CASE WHEN TRIM(case when s2.PRODTYPE='IR' and s2.INTSMEANS='NOS' then s2.INTSACCT else 'BRIDGE_'||TRIM(s2.NOTCCY)||CASE WHEN TRIM(s2.BR)='51' THEN '_ABKU' ELSE '_ABKK' END  end) = TRIM(REC_NOS) THEN 'TRUE' ELSE 'FALSE' END MATCH_REC_NOS,     
S1.BR||'-'||S1.DEALNO||'-'||S1.FIXFLOATIND||'-'||TRIM(C.CMNE) ||'-'||S1.NOTCCY||','||S2.NOTCCY||'-'||S1.MATDATE||'-'||S1.STARTDATE||'-'||S1.PRODTYPE||'-'||S1.NOTCCYAMT||'-'||S1.INTRATE_8 OPICS_DATA,
CASE WHEN TRIM(S1.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||S1.DEALNO||'-'||CASE WHEN S1.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END||'-'||TRIM(C.CMNE) ||'-'||S1.NOTCCY||','||
S2.NOTCCY||'-'||S1.MATDATE||'-'||S1.STARTDATE||'-'||CASE WHEN TRIM(S1.PRODTYPE)='IR' THEN 'IRSH' ELSE 'CCIRST' END||'-'||ABS(S1.NOTCCYAMT)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN (S1.INTRATE_8) ELSE (S2.INTRATE_8) END ||'-'||ABS(S2.NOTCCYAMT) CONV_OPICS_DATA,
FIN_SWAP.SDENT.NAME||'-'||FIN_SWAP.DEAL_IDENTIFIER||'-'||CASH_FLOW_TYPE_1||'-'||SDCP.NAME||'-'||CASE WHEN LENGTH(FIN_SWAP.CCY_CALENDAR_SET)=3 THEN FIN_SWAP.CCY_CALENDAR_SET||','||
FIN_SWAP.CCY_CALENDAR_SET ELSE FIN_SWAP.CCY_CALENDAR_SET END ||'-'||FIN_SWAP.END_DATE||'-'||FIN_SWAP.START_DATE||'-'||SDSBTY.NAME||'-'||ABS(TTSWFL.NOTIONAL_AMOUNT_VALUE_1)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN (TTSWFL.FIX_RATE_1) ELSE (TTSWFL.FIX_RATE_2) END*100 ||'-'||ABS(TTSWFL.NOTIONAL_AMOUNT_VALUE_2) FIN_DATA,
CASE WHEN CASE WHEN TRIM(S1.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||S1.DEALNO||'-'||CASE WHEN S1.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END||'-'||TRIM(C.CMNE) ||'-'||
S1.NOTCCY||','||S2.NOTCCY||'-'||S1.MATDATE||'-'||S1.STARTDATE||'-'||CASE WHEN TRIM(S1.PRODTYPE)='IR' THEN 'IRSH' ELSE 'CCIRST' END||'-'||ABS(S1.NOTCCYAMT)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN (S1.INTRATE_8) ELSE (S2.INTRATE_8) END||'-'||ABS(S2.NOTCCYAMT)  =
FIN_SWAP.SDENT.NAME||'-'||FIN_SWAP.DEAL_IDENTIFIER||'-'||CASH_FLOW_TYPE_1||'-'||SDCP.NAME||'-'||CASE WHEN LENGTH(FIN_SWAP.CCY_CALENDAR_SET)=3 THEN FIN_SWAP.CCY_CALENDAR_SET||','||
FIN_SWAP.CCY_CALENDAR_SET ELSE FIN_SWAP.CCY_CALENDAR_SET END||'-'||FIN_SWAP.END_DATE||'-'||FIN_SWAP.START_DATE||'-'||SDSBTY.NAME||'-'||ABS(TTSWFL.NOTIONAL_AMOUNT_VALUE_1)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN (TTSWFL.FIX_RATE_1) ELSE (TTSWFL.FIX_RATE_2) END*100||'-'||ABS(TTSWFL.NOTIONAL_AMOUNT_VALUE_2)
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM SWDT S1
INNER JOIN SWDT S2 ON TRIM(S2.DEALNO)=TRIM(S1.DEALNO) AND S2.SEQ='002' 
INNER JOIN SWDH H ON trim(S1.DEALNO)=trim(H.DEALNO) AND TRIM(H.REVDATE) IS NULL
INNER JOIN CUST C ON C.CNO=H.CNO
LEFT JOIN TT_SWAP@FTMIG FIN_SWAP  ON TRIM(S1.DEALNO) = TRIM(FIN_SWAP.DEAL_IDENTIFIER) and DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_SWAP.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_SWAP.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_SWAP.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_SWAP.CPTY_FBO_ID_NUM
LEFT JOIN (SELECT * FROM (
SELECT PARENT_FBO_ID_NUM PARENT_FBO_ID_NUM_1,START_DATE START_DATE_1,END_DATE END_DATE_1,CASH_FLOW_TYPE CASH_FLOW_TYPE_1 ,LONG_OR_SHORT LONG_OR_SHORT_1,NOTIONAL_AMOUNT_CCY NOTIONAL_AMOUNT_CCY_1,
NOTIONAL_AMOUNT_VALUE NOTIONAL_AMOUNT_VALUE_1,FIX_RATE FIX_RATE_1 FROM TT_SWAP_CASH_FLOWS@FTMIG WHERE SIDE_SEQUENCE='1' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='1'
) A
LEFT JOIN(
SELECT PARENT_FBO_ID_NUM PARENT_FBO_ID_NUM_2,START_DATE START_DATE_2,END_DATE END_DATE_2,CASH_FLOW_TYPE CASH_FLOW_TYPE_2 ,LONG_OR_SHORT LONG_OR_SHORT_2,NOTIONAL_AMOUNT_CCY NOTIONAL_AMOUNT_CCY_2,
NOTIONAL_AMOUNT_VALUE NOTIONAL_AMOUNT_VALUE_2,FIX_RATE FIX_RATE_2 FROM TT_SWAP_CASH_FLOWS@FTMIG WHERE SIDE_SEQUENCE='1' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='2'
) B ON A.PARENT_FBO_ID_NUM_1 = B.PARENT_FBO_ID_NUM_2) TTSWFL ON TTSWFL.PARENT_FBO_ID_NUM_1 = FIN_SWAP.DEAL_NUM
left join (
  SELECT distinct a.PARENT_FBO_ID_NUM,a.PARENT_FBO_ID_TYPE,A.IQ_CURRENCY PAY_CCY,a.NAME pay_nos ,B.IQ_CURRENCY REC_CCY,b.NAME rec_nos  FROM (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT') A
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT') B ON A.PARENT_FBO_ID_TYPE = B.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM
  ) NOS on NOS.PARENT_FBO_ID_NUM = FIN_SWAP.DEAL_NUM AND FIN_SWAP.DEAL_TYPE =  NOS.PARENT_FBO_ID_TYPE
LEFT JOIN (
SELECT * FROM (
SELECT PARENT_FBO_ID_NUM PARENT_FBO_ID_NUM_1,LONG_OR_SHORT LONG_OR_SHORT_1,SETTLEMENT_ACTION SETTLEMENT_ACTION_1,REFERENCE_RATE_FBO_ID_NUM REFERENCE_RATE_FBO_ID_NUM_1
,BASIS_CODE BASIS_CODE_1,START_DATE START_DATE_1,END_DATE END_DATE_1,NOTIONAL_AMOUNT_CCY NOTIONAL_AMOUNT_CCY_1,NOTIONAL_AMOUNT_VALUE NOTIONAL_AMOUNT_VALUE_1,FIX_RATE FIX_RATE_1,CREATION_FREQUENCY CREATION_FREQUENCY_1 FROM TT_CF_SIDES@FTMIG WHERE SETTLEMENT_ACTION='PAY' AND PARENT_FBO_ID_NUM='106139'
)A 
JOIN (  
SELECT PARENT_FBO_ID_NUM PARENT_FBO_ID_NUM_2,LONG_OR_SHORT LONG_OR_SHORT_2,SETTLEMENT_ACTION SETTLEMENT_ACTION_2,REFERENCE_RATE_FBO_ID_NUM REFERENCE_RATE_FBO_ID_NUM_2
,BASIS_CODE BASIS_CODE_2,START_DATE START_DATE_2,END_DATE END_DATE_2,NOTIONAL_AMOUNT_CCY NOTIONAL_AMOUNT_CCY_2,NOTIONAL_AMOUNT_VALUE NOTIONAL_AMOUNT_VALUE_2,FIX_RATE FIX_RATE_2,CREATION_FREQUENCY CREATION_FREQUENCY_2 FROM TT_CF_SIDES@FTMIG WHERE SETTLEMENT_ACTION='REC' AND PARENT_FBO_ID_NUM='106139'
) B ON A.PARENT_FBO_ID_NUM_1 (+)= B.PARENT_FBO_ID_NUM_2) CF_SIDES ON CF_SIDES.PARENT_FBO_ID_NUM_1 =  FIN_SWAP.DEAL_NUM
WHERE S1.SEQ='001' AND S1.MATDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')




select DISTINCT 
S1.DEALNO ,FIN_SWAP.DEAL_IDENTIFIER,CASE WHEN TRIM(S1.DEALNO) = FIN_SWAP.DEAL_IDENTIFIER THEN 'TRUE' ELSE 'FALSE' END MATCH_DEALNO,
S1.BR OPICS_BR, CASE WHEN TRIM(S1.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END MAPPED_ENTITY, SDENT.NAME FIN_ENTITY, CASE WHEN CASE WHEN TRIM(S2.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END =  SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
S1.PRODTYPE OPICS_PRODTYPE, CASE WHEN TRIM(S1.PRODTYPE)='IR' THEN 'IRSH' ELSE 'CCIRST' END MAPPED_SUBTYPE, SDSBTY.NAME ,CASE WHEN CASE WHEN TRIM(S1.PRODTYPE)='IR' THEN 'IRSH' ELSE 'CCIRST' END =  SDSBTY.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_SUBTYPE,
S1.STARTDATE OPICS_SIDE1_START_DATE ,TTSWFL.START_DATE_1 FIN_SIDE1_START_DATE,CASE WHEN S1.STARTDATE = TTSWFL.START_DATE_1 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_START_DATE,
S1.MATDATE OPICS_SIDE1_END_DATE ,FIN_SWAP.END_DATE FIN_SIDE1_END_DATE,CASE WHEN S1.MATDATE = FIN_SWAP.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_END_DATE,
CASE WHEN S1.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END OPICS_SIDE1_FIXED_FLOAT, TTSWFL.CASH_FLOW_TYPE_1 FIN_SIDE1_FIXED_FLOAT,CASE WHEN CASE WHEN S1.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END = TTSWFL.CASH_FLOW_TYPE_1 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_FIXED_FLOAT,
S1.NOTCCY OPICS_SIDE1_CCY, TTSWFL.NOTIONAL_AMOUNT_CCY_1 FIN_SIDE1_CCY,CASE WHEN S1.NOTCCY = TTSWFL.NOTIONAL_AMOUNT_CCY_1 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_CCY,
S1.NOTCCYAMT OPICS_SIDE1_AMOUNT, TTSWFL.NOTIONAL_AMOUNT_VALUE_1 FIN_SIDE1_AMOUNT,CASE WHEN S1.NOTCCYAMT = TTSWFL.NOTIONAL_AMOUNT_VALUE_1 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_AMOUNT,
S1.INTRATE_8 OPICS_SIDE1_RATE, TTSWFL.FIX_RATE_1*100 FIN_SIDE1_RATE,CASE WHEN S1.INTRATE_8 = TTSWFL.FIX_RATE_1*100 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_FIX_RATE,
S2.STARTDATE OPICS_SIDE1_START_DATE ,TTSWFL.START_DATE_2 FIN_SIDE1_START_DATE,CASE WHEN S2.STARTDATE = TTSWFL.START_DATE_2 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_START_DATE,
S2.MATDATE OPICS_SIDE1_END_DATE ,FIN_SWAP.END_DATE FIN_SIDE1_END_DATE,CASE WHEN S2.MATDATE = FIN_SWAP.END_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_END_DATE,
CASE WHEN S2.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END OPICS_SIDE1_FIXED_FLOAT, TTSWFL.CASH_FLOW_TYPE_2 FIN_SIDE1_FIXED_FLOAT,CASE WHEN CASE WHEN S2.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END = TTSWFL.CASH_FLOW_TYPE_2 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_FIXED_FLOAT,
S2.NOTCCY OPICS_SIDE1_CCY, TTSWFL.NOTIONAL_AMOUNT_CCY_2 FIN_SIDE1_CCY,CASE WHEN S2.NOTCCY = TTSWFL.NOTIONAL_AMOUNT_CCY_2 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_CCY,
S2.NOTCCYAMT OPICS_SIDE1_AMOUNT, TTSWFL.NOTIONAL_AMOUNT_VALUE_2 FIN_SIDE1_AMOUNT,CASE WHEN S2.NOTCCYAMT = TTSWFL.NOTIONAL_AMOUNT_VALUE_2 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_AMOUNT,
S2.INTRATE_8 OPICS_SIDE1_RATE, TTSWFL.FIX_RATE_2*100 FIN_SIDE1_RATE,CASE WHEN S2.INTRATE_8 = TTSWFL.FIX_RATE_2*100 THEN 'TRUE' ELSE 'FALSE' END MATCH_SIDE1_FIX_RATE,
S1.INTPAYCYCLE OPICS_PAY_INTPAYCYCLE,CF_SIDES.CREATION_FREQUENCY_1 FIN_PAY_INTPAYCYCLE, CASE WHEN TRIM(S1.INTPAYCYCLE)=TRIM(CF_SIDES.CREATION_FREQUENCY_1) THEN 'TRUE' ELSE 'FALSE' END MATCH_PAY_INTPAYCYCLE,
S2.INTPAYCYCLE OPICS_RECEIVE_INTPAYCYCLE,CF_SIDES.CREATION_FREQUENCY_2 FIN_REC_INTPAYCYCLE ,  CASE WHEN TRIM(S2.INTPAYCYCLE)=TRIM(CF_SIDES.CREATION_FREQUENCY_2) THEN 'TRUE' ELSE 'FALSE' END MATCH_REC_INTPAYCYCLE,
case when s1.PRODTYPE='IR' and s1.INTSMEANS='NOS' then s1.INTSACCT else 'BRIDGE_'||TRIM(s1.NOTCCY)||CASE WHEN TRIM(s1.BR)='51' THEN '_ABKU' ELSE '_ABKK' END  end OPICS_PAY_NOSTRO,PAY_NOS FIN_PAY_NOS, CASE WHEN TRIM(case when s1.PRODTYPE='IR' and s1.INTSMEANS='NOS' then s1.INTSACCT else 'BRIDGE_'||TRIM(s1.NOTCCY)||CASE WHEN TRIM(s1.BR)='51' THEN '_ABKU' ELSE '_ABKK' END  end) =TRIM(PAY_NOS) THEN 'TRUE' ELSE 'FALSE' END MATCH_PAY_NOS,
case when s2.PRODTYPE='IR' and s2.INTSMEANS='NOS' then s2.INTSACCT else 'BRIDGE_'||TRIM(s2.NOTCCY)||CASE WHEN TRIM(s2.BR)='51' THEN '_ABKU' ELSE '_ABKK' END  end OPICS_REC_NOSTRO,REC_NOS FIN_REC_NOS, CASE WHEN TRIM(case when s2.PRODTYPE='IR' and s2.INTSMEANS='NOS' then s2.INTSACCT else 'BRIDGE_'||TRIM(s2.NOTCCY)||CASE WHEN TRIM(s2.BR)='51' THEN '_ABKU' ELSE '_ABKK' END  end) = TRIM(REC_NOS) THEN 'TRUE' ELSE 'FALSE' END MATCH_REC_NOS,     
S1.BR||'-'||S1.DEALNO||'-'||S1.FIXFLOATIND||'-'||TRIM(C.CMNE) ||'-'||S1.NOTCCY||','||S2.NOTCCY||'-'||S1.MATDATE||'-'||S1.STARTDATE||'-'||S1.PRODTYPE||'-'||S1.NOTCCYAMT||'-'||S1.INTRATE_8 OPICS_DATA,
CASE WHEN TRIM(S1.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||S1.DEALNO||'-'||CASE WHEN S1.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END||'-'||TRIM(C.CMNE) ||'-'||S1.NOTCCY||','||
S2.NOTCCY||'-'||S1.MATDATE||'-'||S1.STARTDATE||'-'||CASE WHEN TRIM(S1.PRODTYPE)='IR' THEN 'IRSH' ELSE 'CCIRST' END||'-'||ABS(S1.NOTCCYAMT)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN (S1.INTRATE_8) ELSE (S2.INTRATE_8) END ||'-'||ABS(S2.NOTCCYAMT) CONV_OPICS_DATA,
FIN_SWAP.SDENT.NAME||'-'||FIN_SWAP.DEAL_IDENTIFIER||'-'||CASH_FLOW_TYPE_1||'-'||SDCP.NAME||'-'||CASE WHEN LENGTH(FIN_SWAP.CCY_CALENDAR_SET)=3 THEN FIN_SWAP.CCY_CALENDAR_SET||','||
FIN_SWAP.CCY_CALENDAR_SET ELSE FIN_SWAP.CCY_CALENDAR_SET END ||'-'||FIN_SWAP.END_DATE||'-'||FIN_SWAP.START_DATE||'-'||SDSBTY.NAME||'-'||ABS(TTSWFL.NOTIONAL_AMOUNT_VALUE_1)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN (TTSWFL.FIX_RATE_1) ELSE (TTSWFL.FIX_RATE_2) END*100 ||'-'||ABS(TTSWFL.NOTIONAL_AMOUNT_VALUE_2) FIN_DATA,
CASE WHEN CASE WHEN TRIM(S1.BR)='51' THEN 'ABKUAE' ELSE 'ABKKWT' END||'-'||S1.DEALNO||'-'||CASE WHEN S1.FIXFLOATIND='L' THEN 'FLOAT' ELSE 'FIXED' END||'-'||TRIM(C.CMNE) ||'-'||
S1.NOTCCY||','||S2.NOTCCY||'-'||S1.MATDATE||'-'||S1.STARTDATE||'-'||CASE WHEN TRIM(S1.PRODTYPE)='IR' THEN 'IRSH' ELSE 'CCIRST' END||'-'||ABS(S1.NOTCCYAMT)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN (S1.INTRATE_8) ELSE (S2.INTRATE_8) END||'-'||ABS(S2.NOTCCYAMT)  =
FIN_SWAP.SDENT.NAME||'-'||FIN_SWAP.DEAL_IDENTIFIER||'-'||CASH_FLOW_TYPE_1||'-'||SDCP.NAME||'-'||CASE WHEN LENGTH(FIN_SWAP.CCY_CALENDAR_SET)=3 THEN FIN_SWAP.CCY_CALENDAR_SET||','||
FIN_SWAP.CCY_CALENDAR_SET ELSE FIN_SWAP.CCY_CALENDAR_SET END||'-'||FIN_SWAP.END_DATE||'-'||FIN_SWAP.START_DATE||'-'||SDSBTY.NAME||'-'||ABS(TTSWFL.NOTIONAL_AMOUNT_VALUE_1)||'-'||CASE WHEN S1.FIXFLOATIND='X' THEN (TTSWFL.FIX_RATE_1) ELSE (TTSWFL.FIX_RATE_2) END*100||'-'||ABS(TTSWFL.NOTIONAL_AMOUNT_VALUE_2)
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
FROM (select * from SWDT where trim(PAYRECIND)='P') S1 
INNER JOIN (select * from SWDT where trim(PAYRECIND)='R') S2 ON trim(S2.DEALNO)=trim(S1.DEALNO) 
INNER JOIN SWDH H ON trim(S1.DEALNO)=trim(H.DEALNO) AND TRIM(H.REVDATE) IS NULL
INNER JOIN CUST C ON C.CNO=H.CNO
LEFT JOIN TT_SWAP@FTMIG FIN_SWAP  ON TRIM(FIN_SWAP.DEAL_IDENTIFIER) like TRIM(S1.DEALNO)||'%' and DEAL_STATE!='DLTD'
LEFT JOIN SD_TRADING_BOOK@FTMIG SDTRBK ON SDTRBK.FBO_ID_NUM = FIN_SWAP.TRADING_BOOK_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = FIN_SWAP.ENTITY_FBO_ID_NUM
LEFT JOIN SD_SUBTYPE@FTMIG SDSBTY ON SDSBTY.FBO_ID_NUM = FIN_SWAP.SUBTYPE_FBO_ID_NUM
LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= FIN_SWAP.CPTY_FBO_ID_NUM
LEFT JOIN (SELECT * FROM (
SELECT PARENT_FBO_ID_NUM PARENT_FBO_ID_NUM_1,START_DATE START_DATE_1,END_DATE END_DATE_1,CASH_FLOW_TYPE CASH_FLOW_TYPE_1 ,LONG_OR_SHORT LONG_OR_SHORT_1,NOTIONAL_AMOUNT_CCY NOTIONAL_AMOUNT_CCY_1,
NOTIONAL_AMOUNT_VALUE NOTIONAL_AMOUNT_VALUE_1,FIX_RATE FIX_RATE_1 FROM TT_SWAP_CASH_FLOWS@FTMIG WHERE SIDE_SEQUENCE='1' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='1'
) A
LEFT JOIN(
SELECT PARENT_FBO_ID_NUM PARENT_FBO_ID_NUM_2,START_DATE START_DATE_2,END_DATE END_DATE_2,CASH_FLOW_TYPE CASH_FLOW_TYPE_2 ,LONG_OR_SHORT LONG_OR_SHORT_2,NOTIONAL_AMOUNT_CCY NOTIONAL_AMOUNT_CCY_2,
NOTIONAL_AMOUNT_VALUE NOTIONAL_AMOUNT_VALUE_2,FIX_RATE FIX_RATE_2 FROM TT_SWAP_CASH_FLOWS@FTMIG WHERE SIDE_SEQUENCE='1' AND PARENT_FBO_ID_VER='999999' AND SIDE_REFERENCE='2'
) B ON A.PARENT_FBO_ID_NUM_1 = B.PARENT_FBO_ID_NUM_2) TTSWFL ON TTSWFL.PARENT_FBO_ID_NUM_1 = FIN_SWAP.DEAL_NUM
left join (
  SELECT distinct a.PARENT_FBO_ID_NUM,a.PARENT_FBO_ID_TYPE,A.IQ_CURRENCY PAY_CCY,a.NAME pay_nos ,B.IQ_CURRENCY REC_CCY,b.NAME rec_nos  FROM (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='P' AND ACTION!='DLT') A
  LEFT JOIN (SELECT * FROM TT_SETT_INS_FLOWS@FTMIG  SIFL
  LEFT JOIN SD_NOSTRO@FTMIG SDNOS  ON SDNOS.FBO_ID_NUM = SIFL.NOSTRO_FBO_ID_NUM WHERE PAY_REC='R' AND ACTION!='DLT') B ON A.PARENT_FBO_ID_TYPE = B.PARENT_FBO_ID_TYPE AND A.PARENT_FBO_ID_NUM = B.PARENT_FBO_ID_NUM
  ) NOS on NOS.PARENT_FBO_ID_NUM = FIN_SWAP.DEAL_NUM AND FIN_SWAP.DEAL_TYPE =  NOS.PARENT_FBO_ID_TYPE
LEFT JOIN (
SELECT * FROM (
SELECT PARENT_FBO_ID_NUM PARENT_FBO_ID_NUM_1,LONG_OR_SHORT LONG_OR_SHORT_1,SETTLEMENT_ACTION SETTLEMENT_ACTION_1,REFERENCE_RATE_FBO_ID_NUM REFERENCE_RATE_FBO_ID_NUM_1
,BASIS_CODE BASIS_CODE_1,START_DATE START_DATE_1,END_DATE END_DATE_1,NOTIONAL_AMOUNT_CCY NOTIONAL_AMOUNT_CCY_1,NOTIONAL_AMOUNT_VALUE NOTIONAL_AMOUNT_VALUE_1,FIX_RATE FIX_RATE_1,CREATION_FREQUENCY CREATION_FREQUENCY_1 FROM TT_CF_SIDES@FTMIG WHERE SETTLEMENT_ACTION='PAY' --AND PARENT_FBO_ID_NUM='106139'
)A 
JOIN (  
SELECT PARENT_FBO_ID_NUM PARENT_FBO_ID_NUM_2,LONG_OR_SHORT LONG_OR_SHORT_2,SETTLEMENT_ACTION SETTLEMENT_ACTION_2,REFERENCE_RATE_FBO_ID_NUM REFERENCE_RATE_FBO_ID_NUM_2
,BASIS_CODE BASIS_CODE_2,START_DATE START_DATE_2,END_DATE END_DATE_2,NOTIONAL_AMOUNT_CCY NOTIONAL_AMOUNT_CCY_2,NOTIONAL_AMOUNT_VALUE NOTIONAL_AMOUNT_VALUE_2,FIX_RATE FIX_RATE_2,CREATION_FREQUENCY CREATION_FREQUENCY_2 FROM TT_CF_SIDES@FTMIG WHERE SETTLEMENT_ACTION='REC' --AND PARENT_FBO_ID_NUM='106139'
) B ON A.PARENT_FBO_ID_NUM_1 (+)= B.PARENT_FBO_ID_NUM_2) CF_SIDES ON CF_SIDES.PARENT_FBO_ID_NUM_1 =  FIN_SWAP.DEAL_NUM
WHERE S1.MATDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') 
