========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
treasury_counter_party_limit_report.sql 
SELECT 
 LM.PRODGROUPID OPICS_PRODGROUPID, LM.LIMITMEMBER OPICS_LIMITMEMBER,LM.MTYDATE OPICS_MTYDATE,BR OPICS_BR,CPTY_LIMIT.LIMIT_NAME FINACLE_LIMIT_NAME,
         LM.PRODGROUPID, MTYDATE,ULT.USER_LIMIT_TYPE FINACLE_USER_LIMIT_TYPE,
         LM.CCY OPCIS_CCY ,LIMIT_CCY FINACLE_CCY,CASE WHEN LM.CCY = LIMIT_CCY THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
         LM.CREQLIMAMT, LIMIT_AMOUNT FINACLE_LIMIT_AMOUNT,CASE WHEN LM.CREQLIMAMT = LIMIT_AMOUNT THEN 'TRUE' ELSE 'FALSE' END MATCH_LIMIT_AMOUNT,
         EXPDATE, EXPIRY_DATE FINACLE_EXPIRY_DATE,CASE WHEN TO_DATE(EXPDATE,'YYYY-MM-DD') = EXPIRY_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_EXPIRY_DATE,
         BR,SDENT.NAME FINACLE_ENTITY,CASE WHEN CASE WHEN BR='51' THEN 'ABKUAE' ELSE 'ABKKWT' END = SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
         LIMITTYPE,LM.LIMITMEMBER,SDCP.MNEMONIC COUNTERPARTY_STRING,
         MTYDATE , TENOR_START_CODE FINACLE_TENOR_START_CODE,
         MTYDATE, TENOR_END_CODE FINACLE_TENOR_END_CODE,
         MTYDATE, TENOR_END_YEARS FINACLE_TENOR_END_YEARS,
         MTYDATE, TENOR_END_MONTHS FINACLE_TENOR_END_MONTHS,
         MTYDATE,TENOR_END_DAYS FINACLE_TENOR_END_DAYS
  FROM CRLM LM
  LEFT JOIN CUST CU ON TRIM(LM.LIMITMEMBER) = TRIM(CU.CNO)
  LEFT JOIN FTABKBPD.SD_CPTY_LIMIT_INFO@FTFC CPTY_LIMIT ON TRIM(CPTY_LIMIT.LIMIT_NAME) = ( CASE WHEN TRIM(LM.PRODGROUPID)='FX DEALS' THEN 'FX_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='INVESTMENT' THEN 'IN_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='IRS DEALS' THEN 'IR_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='MM DEALS' THEN 'MM_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE ||'_'||BR
       END)
       LEFT JOIN FTABKBPD.SD_CPTY@FTFC SDCP ON SDCP.FBO_ID_NUM= CPTY_LIMIT.COUNTERPARTY_FBO_ID_NUM
       LEFT JOIN FTABKBPD.sd_user_limit_type@FTFC ULT ON ULT.FBO_ID_NUM = CPTY_LIMIT.USER_LIMIT_TYPE_FBO_ID_NUM
       LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = CPTY_LIMIT.ENTITY_NAME_FBO_ID_NUM
  WHERE LIMITTYPE IN ('C','G') AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>'30-SEP-2016' OR TRIM(EXPDATE) IS NULL)
  AND (CASE WHEN LM.LIMITTYPE='C' AND CU.CMNE IS NULL THEN 0 ELSE 1 END =1)
    ORDER BY LIMITTYPE DESC;
	
	
	
SELECT CPTY_GROUP_LIMIT.ENTITY||'-'||CPTY_GROUP_LIMIT.COUNTERPARTY_STRING||'-'||CPTY_GROUP_LIMIT.LIMIT_NAME||'-'||CPTY_GROUP_LIMIT.LIMIT_CCY||'-'||CPTY_GROUP_LIMIT.LIMIT_AMOUNT||'-'||
TO_DATE(CPTY_GROUP_LIMIT.EXPIRY_DATE,'DD-MON-YYYY')||'-'||CPTY_GROUP_LIMIT.TENOR_END_YEARS||'-'||CPTY_GROUP_LIMIT.TENOR_END_MONTHS||'-'||CPTY_GROUP_LIMIT.TENOR_END_DAYS OPICS_DATA,
SDENT.NAME||'-'||trim(SDCP.NAME)||'-'||CPTY_LIMIT.LIMIT_NAME||'-'||CPTY_LIMIT.LIMIT_CCY||'-'||CPTY_LIMIT.ALLOCATED_LIMIT||'-'||CPTY_LIMIT.EXPIRY_DATE||'-'||CPTY_LIMIT.TENOR_END_YEARS||'-'||
CPTY_LIMIT.TENOR_END_MONTHS||'-'||CPTY_LIMIT.TENOR_END_DAYS FIN_DATA,
CASE WHEN CPTY_GROUP_LIMIT.ENTITY||'-'||CPTY_GROUP_LIMIT.COUNTERPARTY_STRING||'-'||CPTY_GROUP_LIMIT.LIMIT_NAME||'-'||CPTY_GROUP_LIMIT.LIMIT_CCY||'-'||CPTY_GROUP_LIMIT.LIMIT_AMOUNT||'-'||
TO_DATE(CPTY_GROUP_LIMIT.EXPIRY_DATE,'DD-MON-YYYY')||'-'||CPTY_GROUP_LIMIT.TENOR_END_YEARS||'-'||CPTY_GROUP_LIMIT.TENOR_END_MONTHS||'-'||CPTY_GROUP_LIMIT.TENOR_END_DAYS = 
SDENT.NAME||'-'||trim(SDCP.NAME)||'-'||CPTY_LIMIT.LIMIT_NAME||'-'||CPTY_LIMIT.LIMIT_CCY||'-'||CPTY_LIMIT.ALLOCATED_LIMIT||'-'||CPTY_LIMIT.EXPIRY_DATE||'-'||CPTY_LIMIT.TENOR_END_YEARS||'-'||
CPTY_LIMIT.TENOR_END_MONTHS||'-'||CPTY_LIMIT.TENOR_END_DAYS
 THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
 FROM CPTY_CUST_GROUP_LIMIT_O_TABLE CPTY_GROUP_LIMIT
LEFT JOIN SD_CPTY_LIMIT_INFO@FTMIG CPTY_LIMIT ON TRIM(CPTY_LIMIT.LIMIT_NAME) =TRIM(CPTY_GROUP_LIMIT.LIMIT_NAME)
       LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= CPTY_LIMIT.COUNTERPARTY_FBO_ID_NUM
       LEFT JOIN sd_user_limit_type@FTMIG ULT ON ULT.FBO_ID_NUM = CPTY_LIMIT.USER_LIMIT_TYPE_FBO_ID_NUM
       LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = CPTY_LIMIT.ENTITY_NAME_FBO_ID_NUM  
	   
	   
	   
SELECT 
CASE WHEN TRIM(CPTY_GROUP_LIMIT.ENTITY)='ABKKWT' THEN '01' ELSE '51' END OPICS_ENTITY,TRIM(CPTY_GROUP_LIMIT.ENTITY) MAPPED_ENTITY, TRIM(SDENT.NAME) FIN_ENTITY, CASE WHEN  TRIM(CPTY_GROUP_LIMIT.ENTITY) = TRIM(SDENT.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
TRIM(CPTY_GROUP_LIMIT.COUNTERPARTY_STRING) OPICS_CPTY,TRIM(SDCP.NAME) FIN_CPTY, CASE WHEN  TRIM(CPTY_GROUP_LIMIT.COUNTERPARTY_STRING) = TRIM(SDCP.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_CPTY,
SUBSTR(CPTY_GROUP_LIMIT.LIMIT_NAME,INSTR(CPTY_GROUP_LIMIT.LIMIT_NAME,'_',1,2)+1,LENGTH(SUBSTR(CPTY_GROUP_LIMIT.LIMIT_NAME,INSTR(CPTY_GROUP_LIMIT.LIMIT_NAME,'_',1,2)+1))-5) OPICS_MTYDATE,
CPTY_GROUP_LIMIT.TENOR_END_YEARS MAPPED_TENOR_END_YEARS,CPTY_LIMIT.TENOR_END_YEARS FIN_TENOR_END_YEARS,CASE WHEN CPTY_GROUP_LIMIT.TENOR_END_YEARS  = CPTY_LIMIT.TENOR_END_YEARS THEN 'TRUE' ELSE 'FALSE' END MATCH_TENOR_END_YEARS,
CPTY_GROUP_LIMIT.TENOR_END_MONTHS MAPPED_TENOR_END_MONTHS,CPTY_LIMIT.TENOR_END_MONTHS FIN_TENOR_END_MONTHS,CASE WHEN CPTY_GROUP_LIMIT.TENOR_END_MONTHS  = CPTY_LIMIT.TENOR_END_MONTHS THEN 'TRUE' ELSE 'FALSE' END MATCH_TENOR_END_MONTHS,
CPTY_GROUP_LIMIT.TENOR_END_DAYS MAPPED_TENOR_END_DAYS,CPTY_LIMIT.TENOR_END_DAYS FIN_TENOR_END_DAYS,CASE WHEN CPTY_GROUP_LIMIT.TENOR_END_DAYS  = CPTY_LIMIT.TENOR_END_DAYS THEN 'TRUE' ELSE 'FALSE' END MATCH_TENOR_END_DAYS,
CPTY_GROUP_LIMIT.LIMIT_NAME MAPPED_LIMIT_NAME, CPTY_LIMIT.LIMIT_NAME FIN_LIMIT_NAME,CASE WHEN  TRIM(CPTY_GROUP_LIMIT.LIMIT_NAME) = TRIM(CPTY_LIMIT.LIMIT_NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_LIMIT_NAME,
CPTY_GROUP_LIMIT.LIMIT_CCY MAPPED_LIMIT_CCY, CPTY_LIMIT.LIMIT_CCY FIN_LIMIT_CCY,CASE WHEN  TRIM(CPTY_GROUP_LIMIT.LIMIT_CCY) = TRIM(CPTY_LIMIT.LIMIT_CCY) THEN 'TRUE' ELSE 'FALSE' END MATCH_LIMIT_CCY,
CPTY_GROUP_LIMIT.LIMIT_AMOUNT OPICS_LIMIT_AMOUNT, CPTY_LIMIT.ALLOCATED_LIMIT FIN_LIMIT_AMOUNT,CASE WHEN  TRIM(CPTY_GROUP_LIMIT.LIMIT_AMOUNT) = TRIM(CPTY_LIMIT.ALLOCATED_LIMIT) THEN 'TRUE' ELSE 'FALSE' END MATCH_LIMIT_AMOUNT,
TO_DATE(CPTY_GROUP_LIMIT.EXPIRY_DATE,'DD-MON-YYYY') MAPPED_EXPIRY_DATE, CPTY_LIMIT.EXPIRY_DATE FIN_EXPIRY_DATE,CASE WHEN  NVL(TO_DATE(CPTY_GROUP_LIMIT.EXPIRY_DATE,'DD-MON-YYYY'),SYSDATE) = NVL(CPTY_LIMIT.EXPIRY_DATE ,SYSDATE) THEN 'TRUE' ELSE 'FALSE' END MATCH_EXPIRY_DATE,
CPTY_GROUP_LIMIT.ENTITY||'-'||CPTY_GROUP_LIMIT.COUNTERPARTY_STRING||'-'||CPTY_GROUP_LIMIT.LIMIT_NAME||'-'||CPTY_GROUP_LIMIT.LIMIT_CCY||'-'||CPTY_GROUP_LIMIT.LIMIT_AMOUNT||'-'||
TO_DATE(CPTY_GROUP_LIMIT.EXPIRY_DATE,'DD-MON-YYYY')||'-'||CPTY_GROUP_LIMIT.TENOR_END_YEARS||'-'||CPTY_GROUP_LIMIT.TENOR_END_MONTHS||'-'||CPTY_GROUP_LIMIT.TENOR_END_DAYS OPICS_DATA,
SDENT.NAME||'-'||TRIM(SDCP.NAME)||'-'||CPTY_LIMIT.LIMIT_NAME||'-'||CPTY_LIMIT.LIMIT_CCY||'-'||CPTY_LIMIT.ALLOCATED_LIMIT||'-'||CPTY_LIMIT.EXPIRY_DATE||'-'||CPTY_LIMIT.TENOR_END_YEARS||'-'||
CPTY_LIMIT.TENOR_END_MONTHS||'-'||CPTY_LIMIT.TENOR_END_DAYS FIN_DATA,
CASE WHEN CPTY_GROUP_LIMIT.ENTITY||'-'||CPTY_GROUP_LIMIT.COUNTERPARTY_STRING||'-'||CPTY_GROUP_LIMIT.LIMIT_NAME||'-'||CPTY_GROUP_LIMIT.LIMIT_CCY||'-'||CPTY_GROUP_LIMIT.LIMIT_AMOUNT||'-'||
TO_DATE(CPTY_GROUP_LIMIT.EXPIRY_DATE,'DD-MON-YYYY')||'-'||CPTY_GROUP_LIMIT.TENOR_END_YEARS||'-'||CPTY_GROUP_LIMIT.TENOR_END_MONTHS||'-'||CPTY_GROUP_LIMIT.TENOR_END_DAYS = 
SDENT.NAME||'-'||TRIM(SDCP.NAME)||'-'||CPTY_LIMIT.LIMIT_NAME||'-'||CPTY_LIMIT.LIMIT_CCY||'-'||CPTY_LIMIT.ALLOCATED_LIMIT||'-'||CPTY_LIMIT.EXPIRY_DATE||'-'||CPTY_LIMIT.TENOR_END_YEARS||'-'||
CPTY_LIMIT.TENOR_END_MONTHS||'-'||CPTY_LIMIT.TENOR_END_DAYS
 THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
 FROM CPTY_CUST_GROUP_LIMIT_O_TABLE CPTY_GROUP_LIMIT
LEFT JOIN SD_CPTY_LIMIT_INFO@FTMIG CPTY_LIMIT ON TRIM(CPTY_LIMIT.LIMIT_NAME) =TRIM(CPTY_GROUP_LIMIT.LIMIT_NAME)
       LEFT JOIN SD_CPTY@FTMIG SDCP ON SDCP.FBO_ID_NUM= CPTY_LIMIT.COUNTERPARTY_FBO_ID_NUM
       LEFT JOIN SD_USER_LIMIT_TYPE@FTMIG ULT ON ULT.FBO_ID_NUM = CPTY_LIMIT.USER_LIMIT_TYPE_FBO_ID_NUM
       LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = CPTY_LIMIT.ENTITY_NAME_FBO_ID_NUM 
