========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
treasury_country_limit_report.sql 
SELECT 
 LM.PRODGROUPID OPICS_PRODGROUPID, LM.LIMITMEMBER OPICS_LIMITMEMBER,LM.MTYDATE OPICS_MTYDATE,BR OPICS_BR,CNTRY_LIMIT.LIMIT_NAME FINACLE_LIMIT_NAME,
         LM.PRODGROUPID OPICS_PRODGROUPID, MTYDATE OPICS_MTYDATE ,ULT.USER_LIMIT_TYPE FINACLE_USER_LIMIT_TYPE,
         LM.CCY OPICS_CCY ,LIMIT_CCY FINACLE_LIMIT_CCY,CASE WHEN LM.CCY = LIMIT_CCY THEN 'TRUE' ELSE 'FALSE' END MATCH_CCY,
         LM.CREQLIMAMT OPICS_CREQLIMAMT, LIMIT_AMOUNT FINACLE_LIMIT_AMOUNT,CASE WHEN LM.CREQLIMAMT = LIMIT_AMOUNT THEN 'TRUE' ELSE 'FALSE' END MATCH_LIMIT_AMOUNT,
         EXPDATE OPICS_EXPDATE, EXPIRY_DATE FINACLE_EXPIRY_DATE,CASE WHEN TO_DATE(EXPDATE,'YYYY-MM-DD') = EXPIRY_DATE THEN 'TRUE' ELSE 'FALSE' END MATCH_EXPIRY_DATE,
         BR  OPICS_BR,SDENT.NAME FINACLE_ENTITY,CASE WHEN CASE WHEN BR='51' THEN 'ABKUAE' ELSE 'ABKKWT' END = SDENT.NAME THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
         LM.LIMITMEMBER OPICS_LIMITMEMBER,SDCP.CODE COUNTRY_CODE,CASE WHEN LM.LIMITMEMBER = SDCP.CODE THEN 'TRUE' ELSE 'FALSE' END MATCH_COUNTRY_CODE,
         MTYDATE , CNTRY_LIMIT.TENOR_START_CODE FINACLE_TENOR_START_CODE,
         MTYDATE, CNTRY_LIMIT.TENOR_END_CODE FINACLE_TENOR_END_CODE,
         MTYDATE, CNTRY_LIMIT.TENOR_END_YEARS FINACLE_TENOR_END_YEARS,
         MTYDATE, CNTRY_LIMIT.TENOR_END_MONTHS FINACLE_TENOR_END_MONTHS,
         MTYDATE, CNTRY_LIMIT.TENOR_END_DAYS FINACLE_TENOR_END_DAYS
  FROM CRLM LM
  LEFT JOIN SD_CNTRY_LIMIT_INFO@FTMIG CNTRY_LIMIT ON TRIM(CNTRY_LIMIT.LIMIT_NAME) = TRIM(CASE WHEN TRIM(LM.PRODGROUPID)='FX DEALS' THEN 'FX_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='INVESTMENT' THEN 'IN_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='IRS DEALS' THEN 'IR_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE||'_'||BR
            WHEN TRIM(LM.PRODGROUPID)='MM DEALS' THEN 'MM_'||TRIM(LM.LIMITMEMBER)||'_'||LM.MTYDATE ||'_'||BR
       END)
       LEFT JOIN SD_COUNTRY@FTMIG SDCP ON SDCP.FBO_ID_NUM= CNTRY_LIMIT.COUNTRY_DATA_FBO_ID_NUM
       LEFT JOIN sd_user_limit_type@FTMIG ULT ON ULT.FBO_ID_NUM = CNTRY_LIMIT.USER_LIMIT_TYPE_FBO_ID_NUM
       LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = CNTRY_LIMIT.ENTITY_NAME_FBO_ID_NUM
  WHERE LIMITTYPE IN ('U') AND (TO_DATE(EXPDATE,'YYYY-MM-DD')>to_date(get_param('EOD_DATE'),'dd-mm-yyyy') OR TRIM(EXPDATE) IS NULL)
    ORDER BY LIMITTYPE DESC;
	
	
	
       
SELECT ENTITY||'-'||COUNTRY_CODE||'-'||COUNTRY_LIM.LIMIT_CCY||'-'||TRIM(COUNTRY_LIM.LIMIT_NAME)||'-'||COUNTRY_LIM.LIMIT_AMOUNT||'-'||TO_DATE(COUNTRY_LIM.EXPIRY_DATE,'DD-MON-YYYY')||'-'||
COUNTRY_LIM.TENOR_END_YEARS||'-'||COUNTRY_LIM.TENOR_END_MONTHS||'-'||COUNTRY_LIM.TENOR_END_DAYS OPICS_DATA,
SDENT.NAME||'-'||SDCP.CODE||'-'||CNTRY_LIMIT.LIMIT_CCY||'-'||TRIM(CNTRY_LIMIT.LIMIT_NAME)||'-'||CNTRY_LIMIT.LIMIT_AMOUNT||'-'||CNTRY_LIMIT.EXPIRY_DATE||'-'||
CNTRY_LIMIT.TENOR_END_YEARS||'-'||CNTRY_LIMIT.TENOR_END_MONTHS||'-'||CNTRY_LIMIT.TENOR_END_DAYS FIN_DATA,
CASE WHEN ENTITY||'-'||COUNTRY_CODE||'-'||COUNTRY_LIM.LIMIT_CCY||'-'||TRIM(COUNTRY_LIM.LIMIT_NAME)||'-'||COUNTRY_LIM.LIMIT_AMOUNT||'-'||TO_DATE(COUNTRY_LIM.EXPIRY_DATE,'DD-MON-YYYY')||'-'||
COUNTRY_LIM.TENOR_END_YEARS||'-'||COUNTRY_LIM.TENOR_END_MONTHS||'-'||COUNTRY_LIM.TENOR_END_DAYS =
SDENT.NAME||'-'||SDCP.CODE||'-'||CNTRY_LIMIT.LIMIT_CCY||'-'||TRIM(CNTRY_LIMIT.LIMIT_NAME)||'-'||CNTRY_LIMIT.LIMIT_AMOUNT||'-'||CNTRY_LIMIT.EXPIRY_DATE||'-'||
CNTRY_LIMIT.TENOR_END_YEARS||'-'||CNTRY_LIMIT.TENOR_END_MONTHS||'-'||CNTRY_LIMIT.TENOR_END_DAYS
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
 FROM CPTY_COUNTRY_LIMIT_O_TABLE COUNTRY_LIM   
LEFT JOIN SD_CNTRY_LIMIT_INFO@FTMIG CNTRY_LIMIT ON TRIM(CNTRY_LIMIT.LIMIT_NAME) = TRIM(COUNTRY_LIM.LIMIT_NAME)
LEFT JOIN SD_COUNTRY@FTMIG SDCP ON SDCP.FBO_ID_NUM= CNTRY_LIMIT.COUNTRY_DATA_FBO_ID_NUM
LEFT JOIN sd_user_limit_type@FTMIG ULT ON ULT.FBO_ID_NUM = CNTRY_LIMIT.USER_LIMIT_TYPE_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = CNTRY_LIMIT.ENTITY_NAME_FBO_ID_NUM



SELECT
CASE WHEN TRIM(COUNTRY_LIM.ENTITY)='ABKKWT' THEN '01' ELSE '51' END OPICS_ENTITY,TRIM(COUNTRY_LIM.ENTITY) MAPPED_ENTITY, TRIM(SDENT.NAME) FIN_ENTITY, CASE WHEN  TRIM(COUNTRY_LIM.ENTITY) = TRIM(SDENT.NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_ENTITY,
TRIM(COUNTRY_LIM.COUNTRY_CODE) OPICS_COUNTRY_CODE,TRIM(SDCP.CODE) FIN_COUNTRY_CODE, CASE WHEN  TRIM(COUNTRY_LIM.COUNTRY_CODE) = TRIM(SDCP.CODE) THEN 'TRUE' ELSE 'FALSE' END MATCH_COUNTRY_CODE,
SUBSTR(COUNTRY_LIM.LIMIT_NAME,INSTR(COUNTRY_LIM.LIMIT_NAME,'_',1,2)+1,LENGTH(SUBSTR(COUNTRY_LIM.LIMIT_NAME,INSTR(COUNTRY_LIM.LIMIT_NAME,'_',1,2)+1))-3) OPICS_MTYDATE,
COUNTRY_LIM.TENOR_END_YEARS MAPPED_TENOR_END_YEARS,COUNTRY_LIM.TENOR_END_YEARS FIN_TENOR_END_YEARS,CASE WHEN COUNTRY_LIM.TENOR_END_YEARS  = CNTRY_LIMIT.TENOR_END_YEARS THEN 'TRUE' ELSE 'FALSE' END MATCH_TENOR_END_YEARS,
COUNTRY_LIM.TENOR_END_MONTHS MAPPED_TENOR_END_MONTHS,COUNTRY_LIM.TENOR_END_MONTHS FIN_TENOR_END_MONTHS,CASE WHEN COUNTRY_LIM.TENOR_END_MONTHS  = CNTRY_LIMIT.TENOR_END_MONTHS THEN 'TRUE' ELSE 'FALSE' END MATCH_TENOR_END_MONTHS,
COUNTRY_LIM.TENOR_END_DAYS MAPPED_TENOR_END_DAYS,COUNTRY_LIM.TENOR_END_DAYS FIN_TENOR_END_DAYS,CASE WHEN COUNTRY_LIM.TENOR_END_DAYS  = CNTRY_LIMIT.TENOR_END_DAYS THEN 'TRUE' ELSE 'FALSE' END MATCH_TENOR_END_DAYS,
COUNTRY_LIM.LIMIT_NAME MAPPED_LIMIT_NAME, CNTRY_LIMIT.LIMIT_NAME FIN_LIMIT_NAME,CASE WHEN  TRIM(COUNTRY_LIM.LIMIT_NAME) = TRIM(CNTRY_LIMIT.LIMIT_NAME) THEN 'TRUE' ELSE 'FALSE' END MATCH_LIMIT_NAME,
COUNTRY_LIM.LIMIT_CCY MAPPED_LIMIT_CCY, CNTRY_LIMIT.LIMIT_CCY FIN_LIMIT_CCY,CASE WHEN  TRIM(COUNTRY_LIM.LIMIT_CCY) = TRIM(CNTRY_LIMIT.LIMIT_CCY) THEN 'TRUE' ELSE 'FALSE' END MATCH_LIMIT_CCY,
COUNTRY_LIM.LIMIT_AMOUNT OPICS_LIMIT_AMOUNT, CNTRY_LIMIT.ALLOCATED_LIMIT FIN_LIMIT_AMOUNT,CASE WHEN  TRIM(COUNTRY_LIM.LIMIT_AMOUNT) = TRIM(CNTRY_LIMIT.ALLOCATED_LIMIT) THEN 'TRUE' ELSE 'FALSE' END MATCH_LIMIT_AMOUNT,
TO_DATE(COUNTRY_LIM.EXPIRY_DATE,'DD-MON-YYYY') MAPPED_EXPIRY_DATE, TO_DATE(COUNTRY_LIM.EXPIRY_DATE,'DD-MON-YYYY') FIN_EXPIRY_DATE,CASE WHEN  NVL(TO_DATE(COUNTRY_LIM.EXPIRY_DATE,'DD-MON-YYYY'),SYSDATE) = NVL(TO_DATE(COUNTRY_LIM.EXPIRY_DATE,'DD-MON-YYYY'),SYSDATE) THEN 'TRUE' ELSE 'FALSE' END MATCH_EXPIRY_DATE,
ENTITY||'-'||COUNTRY_CODE||'-'||COUNTRY_LIM.LIMIT_CCY||'-'||TRIM(COUNTRY_LIM.LIMIT_NAME)||'-'||COUNTRY_LIM.LIMIT_AMOUNT||'-'||TO_DATE(COUNTRY_LIM.EXPIRY_DATE,'DD-MON-YYYY')||'-'||
COUNTRY_LIM.TENOR_END_YEARS||'-'||COUNTRY_LIM.TENOR_END_MONTHS||'-'||COUNTRY_LIM.TENOR_END_DAYS OPICS_DATA,
SDENT.NAME||'-'||SDCP.CODE||'-'||CNTRY_LIMIT.LIMIT_CCY||'-'||TRIM(CNTRY_LIMIT.LIMIT_NAME)||'-'||CNTRY_LIMIT.ALLOCATED_LIMIT||'-'||CNTRY_LIMIT.EXPIRY_DATE||'-'||
CNTRY_LIMIT.TENOR_END_YEARS||'-'||CNTRY_LIMIT.TENOR_END_MONTHS||'-'||CNTRY_LIMIT.TENOR_END_DAYS FIN_DATA,
CASE WHEN ENTITY||'-'||COUNTRY_CODE||'-'||COUNTRY_LIM.LIMIT_CCY||'-'||TRIM(COUNTRY_LIM.LIMIT_NAME)||'-'||COUNTRY_LIM.LIMIT_AMOUNT||'-'||TO_DATE(COUNTRY_LIM.EXPIRY_DATE,'DD-MON-YYYY')||'-'||
COUNTRY_LIM.TENOR_END_YEARS||'-'||COUNTRY_LIM.TENOR_END_MONTHS||'-'||COUNTRY_LIM.TENOR_END_DAYS =
SDENT.NAME||'-'||SDCP.CODE||'-'||CNTRY_LIMIT.LIMIT_CCY||'-'||TRIM(CNTRY_LIMIT.LIMIT_NAME)||'-'||CNTRY_LIMIT.ALLOCATED_LIMIT||'-'||CNTRY_LIMIT.EXPIRY_DATE||'-'||
CNTRY_LIMIT.TENOR_END_YEARS||'-'||CNTRY_LIMIT.TENOR_END_MONTHS||'-'||CNTRY_LIMIT.TENOR_END_DAYS
THEN 'TRUE' ELSE 'FALSE' END MATCH_DATA
 FROM CPTY_COUNTRY_LIMIT_O_TABLE COUNTRY_LIM   
LEFT JOIN SD_CNTRY_LIMIT_INFO@FTMIG CNTRY_LIMIT ON TRIM(CNTRY_LIMIT.LIMIT_NAME) = TRIM(COUNTRY_LIM.LIMIT_NAME)
LEFT JOIN SD_COUNTRY@FTMIG SDCP ON SDCP.FBO_ID_NUM= CNTRY_LIMIT.COUNTRY_DATA_FBO_ID_NUM
LEFT JOIN sd_user_limit_type@FTMIG ULT ON ULT.FBO_ID_NUM = CNTRY_LIMIT.USER_LIMIT_TYPE_FBO_ID_NUM
LEFT JOIN SD_ENTITY@FTMIG SDENT ON SDENT.FBO_ID_NUM = CNTRY_LIMIT.ENTITY_NAME_FBO_ID_NUM 
