========================================================================================================================================================================================== 
****************************************************************************************************************************************************************************************** 
volume_report.sql 
--COM LOAN


SELECT A.DEAL_TYPE,a.currency opics_currency,A.com_loan_deal_count OPICS_DEAL_COUNT,A.total_amt  OPICS_DEAL_AMOUNT,b.currency finacle_currency,B.com_loan_deal_count FINACLE_DEAL_COUNT,B.total_amt FINACLE_DEAL_AMOUNT FROM 
(
select 'COM_LOAN' DEAL_TYPE,d.ccy currency,count(S.DEALNO) com_loan_deal_count,sum(D.CCYAMT) total_amt 
FROM DLDT D
INNER JOIN CUST C ON TRIM(D.CNO)=TRIM(C.CNO)
LEFT JOIN SCHD S ON TRIM(D.DEALNO)=TRIM(S.DEALNO) AND S.SCHDSEQ='001' AND D.BR=S.BR 
left join  FTABKBPD.TT_COM_LOAN@FTFC FIN_COM_LOAN on TRIM(D.DEALNO)=TRIM(FIN_COM_LOAN.DEAL_IDENTIFIER)
WHERE D.MDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(D.REVDATE) IS NULL
and D.BR='01'
group by d.ccy
) A
full JOIN 
(
select 'COM_LOAN' DEAL_TYPE ,CURRENCY_LIST currency,count(1) com_loan_deal_count,sum(TTCMFL.NOTIONAL_AMOUNT_VALUE) total_amt 
from  FTABKBPD.TT_COM_LOAN@FTFC FIN_COM_LOAN 
left JOIN FTABKBPD.TT_CMLOAN_CASH_FLOWS@FTFC TTCMFL ON TRIM(TTCMFL.PARENT_FBO_ID_NUM) = TRIM(FIN_COM_LOAN.DEAL_NUM) and TTCMFL.SIDE_SEQUENCE='1'
LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = FIN_COM_LOAN.ENTITY_FBO_ID_NUM
where FIN_COM_LOAN.SUBTYPE_FBO_ID_NUM NOT IN (SELECT FBO_ID_NUM FROM FTABKBPD.SD_SUBTYPE@FTFC WHERE TRIM(DESCRIPTION) IN ('REPO deal with Banks','REPO deal with Central Banks'))
AND SDENT.NAME='ABKKWT' and DEAL_STATE!='DLTD' 
group by CURRENCY_LIST
)B ON A.DEAL_TYPE = B.DEAL_TYPE and a.currency = b.currency;


----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

--REPO
SELECT A.DEAL_TYPE,a.currency opics_currency,A.deal_count OPICS_DEAL_COUNT,A.total_amt  OPICS_DEAL_AMOUNT,b.currency finacle_currency,B.deal_count FINACLE_DEAL_COUNT,B.total_amt FINACLE_DEAL_AMOUNT FROM 
(
SELECT 'REPO' DEAL_TYPE,D.CCY currency,count(*) deal_count,sum(R.PROCEEDAMT) total_amt 
FROM RPRH D
LEFT JOIN CUST C ON TRIM(D.CNO)=TRIM(C.CNO)
LEFT JOIN RPDT R ON TRIM(D.DEALNO)=TRIM(R.DEALNO)
WHERE R.MDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(R.REVDATE) IS NULL AND D.BR='01'
group by D.CCY
) A
left JOIN (
SELECT  'REPO' DEAL_TYPE,CURRENCY_LIST currency,count(*) deal_count ,SUM(TTCMFL.NOTIONAL_AMOUNT_VALUE) total_amt
FROM  FTABKBPD.TT_COM_LOAN@FTFC FIN_REPO 
LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = FIN_REPO.ENTITY_FBO_ID_NUM
LEFT JOIN FTABKBPD.TT_CMLOAN_CASH_FLOWS@FTFC TTCMFL ON TTCMFL.PARENT_FBO_ID_NUM = FIN_REPO.DEAL_NUM and TTCMFL.SIDE_SEQUENCE='1'
WHERE SUBTYPE_FBO_ID_NUM IN (SELECT FBO_ID_NUM FROM FTABKBPD.SD_SUBTYPE@FTFC WHERE TRIM(DESCRIPTION) IN ('REPO deal with Banks','REPO deal with Central Banks'))
AND SDENT.NAME='ABKKWT'
group by CURRENCY_LIST
) B
ON A.DEAL_TYPE = B.DEAL_TYPE;

--------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

--FX OUTRIGHT ***
SELECT A.DEAL_TYPE,a.currency opics_currency, A.deal_count OPICS_DEAL_COUNT,A.total_amt  OPICS_DEAL_AMOUNT,b.currency finacle_currency,B.deal_count FINACLE_DEAL_COUNT,B.total_amt FINACLE_DEAL_AMOUNT FROM 
(
SELECT 'FX_OUTRIGHT' DEAL_TYPE,(CASE WHEN CCYTERMS='M' THEN TRIM(CCY) ELSE TRIM(CTRCCY) END) currency,count(*) deal_count,sum(
CASE WHEN CCYTERMS='M' THEN (CCYAMT) ELSE (CTRAMT) END) total_amt  FROM
 FXDH F
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(F.CUST)
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(PRODCODE)!='CCS' AND TRIM(REVDATE) IS NULL AND TRIM(SWAPDEAL)='0' AND  SPOTFWDIND='F'
AND TRIM(C.CMNE)!='CCIRS' and trim(PORT)!='EQFX' AND F.BR='01'
group by (CASE WHEN CCYTERMS='M' THEN TRIM(CCY) ELSE TRIM(CTRCCY) END)
) A
full JOIN (
SELECT 'FX_OUTRIGHT' DEAL_TYPE,TTFXFL.CCY_ONE_AMOUNT_CCY currency,count(*) deal_count ,SUM(TTFXFL.CCY_ONE_AMOUNT_VALUE) total_amt
from FTABKBPD.TT_FXP_DEAL@FTFC FIN_FX_OUTRIGHT
LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN FTABKBPD.TT_FXP_FLOW@FTFC TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM 
WHERE FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD' AND SDENT.NAME='ABKKWT' and FIN_FX_OUTRIGHT.deal_num !=FIN_FX_OUTRIGHT.deal_identifier
group by TTFXFL.CCY_ONE_AMOUNT_CCY 
) B ON  A.DEAL_TYPE = B.DEAL_TYPE and a.currency = b.currency;

--------------

SELECT 'FX_OUTRIGHT'  opics_DEAL_TYPE,count(*) opics_deal_count,CCY opics_currency1,sum(
CCYAMT) opics_total_amt1,CTRCCY opics_currency2,sum(
CTRAMT) opics_total_am2  FROM
 FXDH F
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(F.CUST)
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND TRIM(PRODCODE)!='CCS' AND TRIM(REVDATE) IS NULL AND TRIM(SWAPDEAL)='0' AND  SPOTFWDIND='F'
AND TRIM(C.CMNE)!='CCIRS' and trim(PORT)!='EQFX' AND F.BR='01'
group by CCY,CTRCCY;

SELECT 'FX_OUTRIGHT'  finacle_DEAL_TYPE,count(*) finacle_deal_count ,TTFXFL.CCY_ONE_AMOUNT_CCY finacle_currency1,SUM(TTFXFL.CCY_ONE_AMOUNT_VALUE) finacle_total_amt1,TTFXFL.CCY_two_AMOUNT_CCY finacle_currency2,SUM(TTFXFL.CCY_two_AMOUNT_VALUE) finacle_total_amt2
from FTABKBPD.TT_FXP_DEAL@FTFC FIN_FX_OUTRIGHT
LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = FIN_FX_OUTRIGHT.ENTITY_FBO_ID_NUM
LEFT JOIN FTABKBPD.TT_FXP_FLOW@FTFC TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_OUTRIGHT.DEAL_NUM 
WHERE FIN_FX_OUTRIGHT.DEAL_TYPE='FXPLOU' AND FIN_FX_OUTRIGHT.DEAL_STATE!='DLTD' AND SDENT.NAME='ABKKWT' and FIN_FX_OUTRIGHT.deal_num !=FIN_FX_OUTRIGHT.deal_identifier
group by TTFXFL.CCY_ONE_AMOUNT_CCY ,TTFXFL.CCY_two_AMOUNT_CCY ;


------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

--FX SPOT   ***

SELECT A.DEAL_TYPE,a.currency opics_currency,A.deal_count OPICS_DEAL_COUNT,A.total_amt  OPICS_DEAL_AMOUNT,b.currency finacle_currency,B.deal_count FINACLE_DEAL_COUNT,B.total_amt FINACLE_DEAL_AMOUNT FROM 
(
SELECT 'FX_SPOT' DEAL_TYPE,CASE WHEN CCYTERMS='M' THEN TRIM(CCY) ELSE TRIM(CTRCCY) END currency,count(*) deal_count,sum(TO_CHAR(CASE WHEN CCYTERMS='M' THEN (CCYAMT) ELSE (CTRAMT) END,'9999999999999999990.99999999')) total_amt 
FROM FXDH F
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(F.CUST)
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND SPOTFWDIND='S' AND TRIM(SWAPDEAL)='0' AND TRIM(REVDATE) IS NULL 
AND TRIM(C.CMNE)!='CCIRS' and trim(port) !='EQFX' AND F.BR='01'
group by CASE WHEN CCYTERMS='M' THEN TRIM(CCY) ELSE TRIM(CTRCCY) END
)A
full JOIN (
SELECT  'FX_SPOT' DEAL_TYPE,TTFXFL.CCY_ONE_AMOUNT_CCY currency,count(*) deal_count ,SUM(TTFXFL.CCY_ONE_AMOUNT_VALUE) total_amt
FROM ftabkbpd.TT_FXP_DEAL@ftfc FIN_FX_SPOT
LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = FIN_FX_SPOT.ENTITY_FBO_ID_NUM
LEFT JOIN FTABKBPD.TT_FXP_FLOW@FTFC TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_SPOT.DEAL_NUM
WHERE FIN_FX_SPOT.DEAL_TYPE='FXPLSP' AND FIN_FX_SPOT.DEAL_STATE!='DLTD' AND SDENT.NAME='ABKKWT'
group by TTFXFL.CCY_ONE_AMOUNT_CCY
) B  ON  A.DEAL_TYPE = B.DEAL_TYPE and a.currency = b.currency;


----------------------


SELECT 'FX_SPOT' opics_DEAL_TYPE,count(*) opics_deal_count,CCY opics_currency1,sum(CCYAMT) opics_total_amt1 , CTRCCY opics_currency2,sum(CTRAMT) total_amt2 
FROM FXDH F
INNER JOIN CUST C ON TRIM(C.CNO)=TRIM(F.CUST)
WHERE TO_DATE(VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') AND SPOTFWDIND='S' AND TRIM(SWAPDEAL)='0' AND TRIM(REVDATE) IS NULL 
AND TRIM(C.CMNE)!='CCIRS' and trim(port) !='EQFX' AND F.'51'
group by CCY,CTRCCY;

SELECT  'FX_SPOT' finacle_DEAL_TYPE,count(*) finacle_deal_count,TTFXFL.CCY_ONE_AMOUNT_CCY finacle_currency1 ,SUM(TTFXFL.CCY_ONE_AMOUNT_VALUE) finacle_total_amt1,TTFXFL.CCY_TWO_AMOUNT_CCY finacle_currency2 ,SUM(TTFXFL.CCY_TWO_AMOUNT_VALUE) finacle_total_amt2
FROM ftabkbpd.TT_FXP_DEAL@ftfc FIN_FX_SPOT
LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = FIN_FX_SPOT.ENTITY_FBO_ID_NUM
LEFT JOIN FTABKBPD.TT_FXP_FLOW@FTFC TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = FIN_FX_SPOT.DEAL_NUM
WHERE FIN_FX_SPOT.DEAL_TYPE='FXPLSP' AND FIN_FX_SPOT.DEAL_STATE!='DLTD' AND SDENT.NAME='ABKKWT'
group by TTFXFL.CCY_ONE_AMOUNT_CCY,TTFXFL.CCY_TWO_AMOUNT_CCY


----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

--SWAP

SELECT 'SWAP' DEAL_TYPE,count(*) deal_count,S1.NOTCCY PAY_SIDE_NOTIONAL_AMOUNT_CCY,sum(S1.NOTCCYAMT) PAY_SIDE_NOTIONAL_AMT_VALUE,
S2.NOTCCY RECEIVE_SIDE_NOTIONAL_AMT_CCY,sum(S2.NOTCCYAMT) RECEIV_SIDE_NOTIONAL_AMT_VALUE
FROM SWDT S1 
INNER JOIN SWDT S2 ON S2.DEALNO=S1.DEALNO AND S2.SEQ='002' 
INNER JOIN SWDH H ON trim(S1.DEALNO)=trim(H.DEALNO) AND TRIM(H.REVDATE) IS NULL
INNER JOIN CUST C ON C.CNO=H.CNO
WHERE S1.SEQ='001' AND S1.MATDATE>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')
AND trim(S1.BR)='01'
group by S1.NOTCCY,S2.NOTCCY;

SELECT 'SWAP' DEAL_TYPE,count(*) deal_count,TTSWFL.PAY_NOTIONAL_AMOUNT_CCY ,SUM(TTSWFL.PAY_NOTIONAL_AMOUNT_VALUE) PAY_NOTIONAL_AMOUNT_VALUE,TTSWFL.REC_NOTIONAL_AMOUNT_CCY ,SUM(TTSWFL.REC_NOTIONAL_AMOUNT_VALUE) REC_NOTIONAL_AMOUNT_VALUE
FROM FTABKBPD.TT_SWAP@FTFC FIN_SWAP
LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = FIN_SWAP.ENTITY_FBO_ID_NUM
LEFT JOIN (select distinct TTSWFL_PAY.PARENT_FBO_ID_NUM,TTSWFL_PAY.NOTIONAL_AMOUNT_CCY  PAY_NOTIONAL_AMOUNT_CCY,TTSWFL_PAY.NOTIONAL_AMOUNT_VALUE PAY_NOTIONAL_AMOUNT_VALUE,
TTSWFL_REC.NOTIONAL_AMOUNT_CCY REC_NOTIONAL_AMOUNT_CCY,TTSWFL_REC.NOTIONAL_AMOUNT_VALUE REC_NOTIONAL_AMOUNT_VALUE
from (select * from FTABKBPD.TT_SWAP_CASH_FLOWS@FTFC where SETTLEMENT_ACTION='PAY' AND SIDE_SEQUENCE='1'  and PARENT_FBO_ID_VER='999999')TTSWFL_PAY 
left join (select distinct * from FTABKBPD.TT_SWAP_CASH_FLOWS@FTFC where SETTLEMENT_ACTION='REC'  AND SIDE_SEQUENCE='1'  and PARENT_FBO_ID_VER='999999')TTSWFL_REC on  TTSWFL_PAY.PARENT_FBO_ID_NUM = TTSWFL_REC.PARENT_FBO_ID_NUM)  TTSWFL ON TTSWFL.PARENT_FBO_ID_NUM = FIN_SWAP.DEAL_NUM 
WHERE DEAL_STATE!='DLTD' AND  SDENT.NAME='ABKKWT' 
group by TTSWFL.PAY_NOTIONAL_AMOUNT_CCY,TTSWFL.REC_NOTIONAL_AMOUNT_CCY;

SELECT 'SWAP' DEAL_TYPE,count(*) deal_count,
TTFXFL_PAY.NOTIONAL_AMOUNT_CCY ,
SUM(TTFXFL_REC.NOTIONAL_AMOUNT_VALUE) PAY_NOTIONAL_AMOUNT_VALUE,
TTFXFL_REC.NOTIONAL_AMOUNT_CCY ,
SUM(TTFXFL_PAY.NOTIONAL_AMOUNT_VALUE) REC_NOTIONAL_AMOUNT_VALUE
FROM FTABKBPD.TT_SWAP@FTFC FIN_SWAP
LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = FIN_SWAP.ENTITY_FBO_ID_NUM
LEFT JOIN FTABKBPD.TT_SWAP_CASH_FLOWS@FTFC TTFXFL_PAY ON TTFXFL_PAY.PARENT_FBO_ID_NUM = FIN_SWAP.DEAL_NUM AND TTFXFL_PAY.SETTLEMENT_ACTION='PAY' AND TTFXFL_PAY.SIDE_SEQUENCE='1' AND TTFXFL_PAY.PARENT_FBO_ID_VER='999999'
LEFT JOIN FTABKBPD.TT_SWAP_CASH_FLOWS@FTFC TTFXFL_REC ON TTFXFL_REC.PARENT_FBO_ID_NUM = FIN_SWAP.DEAL_NUM AND TTFXFL_REC.SETTLEMENT_ACTION='REC' AND TTFXFL_REC.SIDE_SEQUENCE='1' AND TTFXFL_REC.PARENT_FBO_ID_VER='999999'
WHERE TRIM(SDENT.NAME)='ABKKWT' AND (TTFXFL_PAY.PARENT_FBO_ID_NUM IS NOT NULL  OR TTFXFL_REC.PARENT_FBO_ID_NUM IS NOT NULL )
--AND FIN_SWAP.DEAL_NUM='100231'
GROUP BY TTFXFL_PAY.NOTIONAL_AMOUNT_CCY,TTFXFL_REC.NOTIONAL_AMOUNT_CCY 


----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

--FX SWAP

SELECT 'FX_SWAP' DEAL_TYPE,count(*) deal_count,sum(CASE WHEN A.CCYTERMS='M' THEN ABS(A.CCYAMT) ELSE ABS(A.CTRAMT) END) NEAR_LEG_total_amt,
SUM(CASE WHEN B.CCYTERMS='M' THEN ABS(B.CCYAMT*B.CCYRATE_8) ELSE ABS(B.CTRAMT*B.CCYRATE_8)  END) FAR_LEG_TOTAL_AMT
FROM  FXDH A
INNER JOIN CUST C ON TRIM(A.CUST)=TRIM(C.CNO)
INNER JOIN FXDH B ON A.SWAPDEAL=B.DEALNO AND B.FARNEARIND='F' AND TO_DATE(B.VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')  AND A.BR=B.BR
WHERE  A.SWAPDEAL>0 AND TRIM(A.REVDATE) IS NULL and A.PRODCODE!='CCS' AND TRIM(C.CMNE)!='CCIRS' AND TRIM(A.PORT)!='EQFX' AND TRIM(B.PORT)!='EQFX'
AND A.'51';


SELECT 'FX_SWAP' DEAL_TYPE,count(*) deal_count
,sum(TTFXFL.CCY_ONE_AMOUNT_VALUE) NEAR_LEG_total_amt,SUM(TTFXFL.CCY_TWO_AMOUNT_VALUE) FAR_LEG_TOTAL_AMT
from FTABKBPD.TT_FXP_DEAL@FTFC fin_fx_swap
LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = fin_fx_swap.ENTITY_FBO_ID_NUM
LEFT JOIN FTABKBPD.TT_FXP_FLOW@FTFC TTFXFL ON TTFXFL.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM
WHERE   DEAL_TYPE='FXPLSW' AND fin_fx_swap.DEAL_STATE!='DLTD' AND SDENT.NAME='ABKKWT';


------------------

SELECT 'FX_SWAP' DEAL_TYPE,count(*) deal_count,
CASE WHEN A.CCYTERMS='M' THEN TRIM(A.CCY)||'/'||TRIM(A.CTRCCY) ELSE TRIM(A.CTRCCY)||'/'||TRIM(A.CCY) END  NEAR_LEG_CCY_PAIR,
sum(TO_CHAR(CASE WHEN A.CCYTERMS='M' THEN (A.CCYAMT) ELSE (A.CTRAMT) END,'9999999999999999990.99999999')) NEAR_LEG_CCY_ONE_AMOUNT,
sum(TO_CHAR(CASE WHEN A.CCYTERMS='M' THEN (A.CCYAMT*A.CCYRATE_8) ELSE (A.CTRAMT*A.CCYRATE_8) END,'9999999999999999990.99999999')) NEAR_LEG_CCY_TWO_AMOUNT,
CASE WHEN B.CCYTERMS !='M' THEN TRIM(B.CCY)||'/'||TRIM(B.CTRCCY) ELSE TRIM(B.CTRCCY)||'/'||TRIM(B.CCY) END  FAR_LEG_CCY_PAIR,
sum((TO_CHAR(CASE WHEN B.CCYTERMS='M' THEN B.CCYAMT ELSE B.CTRAMT END,'9999999999999999990.99999999'))) FAR_LEG_CCY_ONE_AMOUNT,
sum(TO_CHAR(CASE WHEN B.CCYTERMS='M' THEN (B.CCYAMT*B.CCYRATE_8) ELSE (B.CTRAMT*B.CCYRATE_8)  END ,'9999999999999999990.99999999'))FAR_LEG_CCY_TWO_AMOUNT
FROM  FXDH A
INNER JOIN CUST C ON TRIM(A.CUST)=TRIM(C.CNO)
INNER JOIN FXDH B ON A.SWAPDEAL=B.DEALNO AND B.FARNEARIND='F' AND TO_DATE(B.VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')  AND A.BR=B.BR
WHERE  A.SWAPDEAL>0 AND TRIM(A.REVDATE) IS NULL and A.PRODCODE!='CCS' AND TRIM(C.CMNE)!='CCIRS' AND TRIM(A.PORT)!='EQFX' AND TRIM(B.PORT)!='EQFX'
AND A.'51'
group by CASE WHEN A.CCYTERMS='M' THEN TRIM(A.CCY)||'/'||TRIM(A.CTRCCY) ELSE TRIM(A.CTRCCY)||'/'||TRIM(A.CCY) END,
CASE WHEN B.CCYTERMS !='M' THEN TRIM(B.CCY)||'/'||TRIM(B.CTRCCY) ELSE TRIM(B.CTRCCY)||'/'||TRIM(B.CCY) END;



SELECT 'FX_SWAP' DEAL_TYPE,count(*) deal_count,
CASE WHEN A.CCYTERMS='M' THEN TRIM(A.CCY) ELSE TRIM(A.CTRCCY) END  NEAR_LEG_CCY1,
sum(TO_CHAR(CASE WHEN A.CCYTERMS='M' THEN (A.CCYAMT) ELSE (A.CTRAMT) END,'9999999999999999990.99999999')) NEAR_LEG_CCY_ONE_AMOUNT,
CASE WHEN A.CCYTERMS='M' THEN TRIM(A.CTRCCY) ELSE TRIM(A.CCY) END  NEAR_LEG_CCY2,
sum(TO_CHAR(CASE WHEN A.CCYTERMS='M' THEN (A.CCYAMT*A.CCYRATE_8) ELSE (A.CTRAMT*A.CCYRATE_8) END,'9999999999999999990.99999999')) NEAR_LEG_CCY_TWO_AMOUNT,
CASE WHEN B.CCYTERMS !='M' THEN TRIM(B.CCY) ELSE TRIM(B.CTRCCY) END  FAR_LEG_CCY1,
sum((TO_CHAR(CASE WHEN B.CCYTERMS='M' THEN B.CCYAMT ELSE B.CTRAMT END,'9999999999999999990.99999999'))) FAR_LEG_CCY_ONE_AMOUNT,
CASE WHEN B.CCYTERMS !='M' THEN TRIM(B.CTRCCY) ELSE TRIM(B.CCY) END  FAR_LEG_CCY2,
sum(TO_CHAR(CASE WHEN B.CCYTERMS='M' THEN (B.CCYAMT*B.CCYRATE_8) ELSE (B.CTRAMT*B.CCYRATE_8)  END ,'9999999999999999990.99999999'))FAR_LEG_CCY_TWO_AMOUNT
FROM  FXDH A
INNER JOIN CUST C ON TRIM(A.CUST)=TRIM(C.CNO)
INNER JOIN FXDH B ON A.SWAPDEAL=B.DEALNO AND B.FARNEARIND='F' AND TO_DATE(B.VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')  AND A.BR=B.BR
WHERE  A.SWAPDEAL>0 AND TRIM(A.REVDATE) IS NULL and A.PRODCODE!='CCS' AND TRIM(C.CMNE)!='CCIRS' AND TRIM(A.PORT)!='EQFX' AND TRIM(B.PORT)!='EQFX'
AND A.'51'
group by CASE WHEN A.CCYTERMS='M' THEN TRIM(A.CCY) ELSE TRIM(A.CTRCCY) END,CASE WHEN A.CCYTERMS='M' THEN TRIM(A.CTRCCY) ELSE TRIM(A.CCY) END,
CASE WHEN B.CCYTERMS !='M' THEN TRIM(B.CCY) ELSE TRIM(B.CTRCCY) END,CASE WHEN B.CCYTERMS !='M' THEN TRIM(B.CTRCCY) ELSE TRIM(B.CCY) END



SELECT 'FX_SWAP' DEAL_TYPE,count(*) deal_count,
 TTFXFL_NEAR1.CCY_ONE_AMOUNT_CCY,SUM(TTFXFL_NEAR1.CCY_ONE_AMOUNT_VALUE),
TTFXFL_NEAR2.PL_CCY,SUM(TTFXFL_FAR1.CCY_two_AMOUNT_VALUE),
TTFXFL_FAR1.PL_CCY,SUM(TTFXFL_FAR1.CCY_ONE_AMOUNT_VALUE),
TTFXFL_FAR2.CCY_ONE_AMOUNT_CCY, SUM(TTFXFL_NEAR1.CCY_two_AMOUNT_VALUE)
FROM FTABKBPD.TT_FXP_DEAL@FTFC fin_fx_swap
LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = fin_fx_swap.ENTITY_FBO_ID_NUM
LEFT JOIN FTABKBPD.TT_FXP_FLOW@FTFC TTFXFL_NEAR1 ON TTFXFL_NEAR1.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXFL_NEAR1.PARENT_LEG_IDENTIFIER='NELG' AND TTFXFL_NEAR1.FXP_FLOW_REFERENCE='1'
LEFT JOIN FTABKBPD.TT_FXP_FLOW@FTFC TTFXFL_NEAR2 ON TTFXFL_NEAR2.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXFL_NEAR2.PARENT_LEG_IDENTIFIER='NELG' AND TTFXFL_NEAR2.FXP_FLOW_REFERENCE='2'
LEFT JOIN FTABKBPD.TT_FXP_FLOW@FTFC TTFXFL_FAR1 ON TTFXFL_FAR1.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXFL_FAR1.PARENT_LEG_IDENTIFIER='FALG' AND TTFXFL_FAR1.FXP_FLOW_REFERENCE='1'
LEFT JOIN FTABKBPD.TT_FXP_FLOW@FTFC TTFXFL_FAR2 ON TTFXFL_FAR2.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXFL_FAR2.PARENT_LEG_IDENTIFIER='FALG' AND TTFXFL_FAR2.FXP_FLOW_REFERENCE='2'
WHERE TRIM(SDENT.NAME)='ABKKWT' AND (TTFXFL_NEAR1.PARENT_FBO_ID_NUM IS NOT NULL  OR TTFXFL_NEAR2.PARENT_FBO_ID_NUM IS NOT NULL  OR TTFXFL_FAR1.PARENT_FBO_ID_NUM IS NOT NULL  OR TTFXFL_FAR2.PARENT_FBO_ID_NUM IS NOT NULL)
GROUP BY TTFXFL_NEAR1.CCY_ONE_AMOUNT_CCY,TTFXFL_NEAR2.PL_CCY,TTFXFL_FAR1.PL_CCY,TTFXFL_FAR2.CCY_ONE_AMOUNT_CCY



-----------
----------

SELECT 'FX_SWAP' DEAL_TYPE,count(*) deal_count,
CASE WHEN A.CCYTERMS='M' THEN TRIM(A.CCY) ELSE TRIM(A.CTRCCY) END  NEAR_LEG_CCY1,
sum(TO_CHAR(CASE WHEN A.CCYTERMS='M' THEN (A.CCYAMT) ELSE (A.CTRAMT) END,'9999999999999999990.99999999')) NEAR_LEG_CCY_ONE_AMOUNT,
CASE WHEN B.CCYTERMS !='M' THEN TRIM(B.CCY) ELSE TRIM(B.CTRCCY) END  FAR_LEG_CCY1,
sum((TO_CHAR(CASE WHEN B.CCYTERMS='M' THEN B.CCYAMT ELSE B.CTRAMT END,'9999999999999999990.99999999'))) FAR_LEG_CCY_ONE_AMOUNT
FROM  FXDH A
INNER JOIN CUST C ON TRIM(A.CUST)=TRIM(C.CNO)
INNER JOIN FXDH B ON A.SWAPDEAL=B.DEALNO AND B.FARNEARIND='F' AND TO_DATE(B.VDATE,'YYYY-MM-DD')>TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')  AND A.BR=B.BR
WHERE  A.SWAPDEAL>0 AND TRIM(A.REVDATE) IS NULL and A.PRODCODE!='CCS' AND TRIM(C.CMNE)!='CCIRS' AND TRIM(A.PORT)!='EQFX' AND TRIM(B.PORT)!='EQFX'
AND A.BR='01'
group by CASE WHEN A.CCYTERMS='M' THEN TRIM(A.CCY) ELSE TRIM(A.CTRCCY) END,CASE WHEN A.CCYTERMS='M' THEN TRIM(A.CTRCCY) ELSE TRIM(A.CCY) END,
CASE WHEN B.CCYTERMS !='M' THEN TRIM(B.CCY) ELSE TRIM(B.CTRCCY) END,CASE WHEN B.CCYTERMS !='M' THEN TRIM(B.CTRCCY) ELSE TRIM(B.CCY) END


SELECT 'FX_SWAP' DEAL_TYPE1, count(*) deal_count,
TTFXFL_NEAR1.CCY_ONE_AMOUNT_CCY FINACLE_NEAR_LEG_CCY1,
SUM(TTFXFL_NEAR1.CCY_ONE_AMOUNT_VALUE) FIN_NEAR_LEG_CCY_ONE_AMOUNT ,
TTFXFL_FAR1.PL_CCY FINACLE_FAR_LEG_CCY1,
SUM(TTFXFL_FAR1.CCY_ONE_AMOUNT_VALUE) FINACLE_FAR_LEG_CCY_ONE_AMOUNT--,
FROM FTABKBPD.TT_FXP_DEAL@FTFC fin_fx_swap
LEFT JOIN FTABKBPD.SD_ENTITY@FTFC SDENT ON SDENT.FBO_ID_NUM = fin_fx_swap.ENTITY_FBO_ID_NUM
LEFT JOIN FTABKBPD.TT_FXP_FLOW@FTFC TTFXFL_NEAR1 ON TTFXFL_NEAR1.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXFL_NEAR1.PARENT_LEG_IDENTIFIER='NELG' AND TTFXFL_NEAR1.FXP_FLOW_REFERENCE='1' 
LEFT JOIN FTABKBPD.TT_FXP_FLOW@FTFC TTFXFL_FAR1 ON TTFXFL_FAR1.PARENT_FBO_ID_NUM = fin_fx_swap.DEAL_NUM AND TTFXFL_FAR1.PARENT_LEG_IDENTIFIER='FALG' AND TTFXFL_FAR1.FXP_FLOW_REFERENCE='1' 
WHERE TRIM(SDENT.NAME)='ABKKWT' AND (TTFXFL_NEAR1.PARENT_FBO_ID_NUM IS NOT NULL  OR TTFXFL_FAR1.PARENT_FBO_ID_NUM IS NOT NULL  )
AND  DEAL_TYPE='FXPLSW' AND fin_fx_swap.DEAL_STATE!='DLTD' 
GROUP BY TTFXFL_NEAR1.CCY_ONE_AMOUNT_CCY,TTFXFL_NEAR1.PL_CCY,TTFXFL_FAR1.PL_CCY




----------------------------------------------------------------------


select 'COM_LOAN_DEAL' PRODUCT, count(*) OPICS_DEAL_COUNT,count(*) FINACLE_DEAL_COUNT  from COM_LOAN_O_TABLE
UNION 
select 'FX_OUTRIGHT_DEAL',count(*),count(*) from FX_OUTRIGHT_DEALS_O_TABLE
UNION 
select 'REPO_DEAL',count(*),count(*) from REPO_O_TABLE
UNION 
select 'FX_SPOT_DEAL',count(*),count(*) from FX_SPOT_DEALS_O_TABLE
UNION 
select 'FX_SWAP_DEAL',count(*),count(*) from FX_SWAP_O_TABLE
UNION 
select 'SWAP_DEAL',count(*),count(*) from SWAP_O_TABLE
UNION 
select 'SPOT_POSITION_DEAL',count(*),count(*) from SPOT_POSITION_DEALS_O_TABLE
UNION 
select 'EQUITY_DEAL',count(*),count(*) from EQUITY_MF_O_TABLE
UNION 
select 'SECURITY DEAL',count(*),count(*) from SEC_BUY_SELL_O_TABLE
UNION 
select 'INTERNAL DEAL',count(*),count(*) from INTERNAL_DEALS_O_TABLE


select PRODUCT_TYPE,SUBTYPE,INDICATOR,CCY,sum(FCY_AMOUNT) FCY_AMOUNT,sum(KWD_AMOUNT) KWD_AMOUNT from TREASURY_OPEN_DEALS group by PRODUCT_TYPE,SUBTYPE,INDICATOR,CCY;

select INSTRUMENT_CLASS_DATA_NAME,SUBTYPE,BUY_OR_SELL,CCY,sum(FCY_AMOUNT) FCY_AMOUNT ,sum(KWD_AMOUNT) KWD_AMOUNT from TREASURY_OPEN_INV_DEASL group by INSTRUMENT_CLASS_DATA_NAME,SUBTYPE,BUY_OR_SELL,CCY;


select PRODUCT_TYPE,CCY,SUM(FCY_AMOUNT) FCY_AMOUNT ,SUM(KWD_AMOUNT) KWD_AMOUNT  from TREASURY_OPEN_DEALS GROUP BY PRODUCT_TYPE,CCY
UNION ALL
select case when DEAL_IDENTIFIER like '6%' THEN 'SECURITY' ELSE 'EQUITY' END TYPE,TO_CHAR(CCY),SUM(FCY_AMOUNT) FCY_AMOUNT ,SUM(KWD_AMOUNT) KWD_AMOUNT from TREASURY_OPEN_INV_DEASL
GROUP BY case when DEAL_IDENTIFIER like '6%' THEN 'SECURITY' ELSE 'EQUITY' END,CCY 
