-- File Name		: com_loan_spool.sql
-- File Created for	: Creation of source table
-- Created By		: Sharanappa S
-- Client		    : ABK
-- Created On		: 28-09-2016
-------------------------------------------------------------------
set head off
set feedback off
set term off
set lines 2000
set page size 0
set pages 0
set trimspool on
spool $MIG_PATH/output/finacle/treasury/COM_LOAN.TXT
SELECT
'RESPONSE'||'|'||
'DEAL_IDENTIFIER'||'|'||
'TRADING_BOOK'||'|'||
'ENTITY_NAME'||'|'||
'DEPT_NAME'||'|'||
'SUBTYPE'||'|'||
'COUNTERPARTY_STRING'||'|'||
'DEAL_DATE'||'|'||
'START_DATE'||'|'||
'END_DATE'||'|'||
'SIDE.SIDE_ONE.LONG_OR_SHORT'||'|'||
'TYPE_STRING'||'|'||
'CURRENCY_STRING'||'|'||
'SIDE.SIDE_ONE.NOTIONAL_AMOUNT.VALUE'||'|'||
'SIDE.SIDE_ONE.BASIS_CODE'||'|'||
'SIDE.SIDE_ONE.CREATION_FREQUENCY'||'|'||
'SIDE.SIDE_ONE.FIX_RATE'||'|'||
'SIDE.SIDE_ONE.SPREAD_RATE'||'|'||
--'SIDE.$1.CASH_FLOW_SIDE_TYPE'||'|'||
'SIDE.SIDE_ONE.REFERENCE_RATE'||'|'||
'AUTO_OR_PENDING'||'|'||
'CONFIRM_METHOD'||'|'||
'SIDE.CURREC.SI_FLOW_PAY.SSI_ID'||'|'||
'SIDE.CURREC.SI_FLOW_PAY.NOSTRO'||'|'||
'SIDE.CURREC.SI_FLOW_PAY.SETT_METHOD'||'|'||
'SIDE.CURREC.SI_FLOW_PAY.CPTY_AGENT'||'|'||
'SIDE.CURREC.SI_FLOW_REC.SSI_ID'||'|'||
'SIDE.CURREC.SI_FLOW_REC.NOSTRO'||'|'||
'SIDE.CURREC.SI_FLOW_REC.SETT_METHOD'||'|'||
'SIDE.CURREC.SI_FLOW_REC.CPTY_AGENT'||'|'||
'SIFLOW_INTEREST_PAY.NOSTRO'||'|'||
'SIFLOW_INTEREST_PAY.SETT_METHOD'||'|'||
'SIFLOW_INTEREST_PAY.CPTY_AGENT'||'|'||
'SIFLOW_INTEREST_PAY.SSI_ID'||'|'||
'SIFLOW_INTEREST_RECIEVE.NOSTRO'||'|'||
'SIFLOW_INTEREST_RECIEVE.SETT_METHOD'||'|'||
'SIFLOW_INTEREST_RECIEVE.CPTY_AGENT'||'|'||
'SIFLOW_INTEREST_RECIEVE.SSI_ID'||'|'||
'SIDE.SIDE_ONE.COMPOUNDING_METHOD'||'|'||
'SIDE.SIDE_ONE.COMPOUNDING_FREQUENCY'||'|'||
'SIDE.SIDE_ONE.START_DATE_DAY_CONVENTION'||'|'||
'SIDE.SIDE_ONE.END_DATE_DAY_CONVENTION'||'|'||
'SIDE.SIDE_ONE.CASH_FLOW_DAY_CONVENTION'||'|'||
'SIDE.SIDE_ONE.AMORTISATION_TYPE'||'|'||
'SIDE.SIDE_ONE.AMORTISATION_FREQUENCY'||'|'||
'SIDE.SIDE_ONE.AMORTISATION_START_DATE'||'|'||
'SIDE.SIDE_ONE.AMORTISATION_END_DATE'||'|'||
'SIDE.SIDE_ONE.AMORTISATION_STEP_AMOUNT'
FROM DUAL
UNION ALL
select
TO_CHAR(TRIM(RESPONSE)||'|'||
TRIM(DEAL_IDENTIFIER)||'|'||
TRIM(TRADING_BOOK)||'|'||
TRIM(ENTITY_NAME)||'|'||
TRIM(DEPT_NAME)||'|'||
TRIM(SUBTYPE)||'|'||
TRIM(COUNTERPARTY_STRING)||'|'||
TRIM(DEAL_DATE)||'|'||
TRIM(START_DATE)||'|'||
TRIM(END_DATE)||'|'||
TRIM(SIDE_SIDE_ONE_LONG_OR_SHORT)||'|'||
TRIM(TYPE_STRING)||'|'||
TRIM(CURRENCY_STRING)||'|'||
abs(TRIM(SIDE_SIDE_1_NOTNAL_AMT_VALUE))||'|'||
TRIM(SIDE_SIDE_ONE_BASIS_CODE)||'|'||
TRIM(SIDE_SIDE_ONE_CREATION_FREQ)||'|'||
TRIM(SIDE_SIDE_ONE_FIX_RATE)||'|'||
TRIM(SIDE_SIDE_ONE_SPREAD_RATE)||'|'||
--TRIM("SIDE.$1.CASH_FLOW_SIDE_TYPE")||'|'||
TRIM("SIDE.$1.REFERENCE_RATE")||'|'||
TRIM(AUTO_OR_PENDING)||'|'||
TRIM(CONFIRM_METHOD)||'|'||
TRIM(SIDE_CURREC_SI_FLOW_PAY_SSI_ID)||'|'||
TRIM(SIDE_CURREC_SI_FLOW_PAY_NOSTRO)||'|'||
TRIM(SIDE_CUR_SI_FLOW_PAY_SETT_MTHD)||'|'||
TRIM(SIDE_CUR_SI_FLOW_PAY_CPTY_AGNT)||'|'||
TRIM(SIDE_CURREC_SI_FLOW_REC_SSI_ID)||'|'||
TRIM(SIDE_CURREC_SI_FLOW_REC_NOSTRO)||'|'||
TRIM(SIDE_CUR_SI_FLOW_REC_SETT_MTHD)||'|'||
TRIM(SIDE_CUR_SI_FLOW_REC_CPTY_AGNT)||'|'||
TRIM(SIFLOW_INTEREST_PAY_NOSTRO)||'|'||
TRIM(SIFLOW_INT_PAY_SETT_METHOD)||'|'||
TRIM(SIFLOW_INTEREST_PAY_CPTY_AGENT)||'|'||
TRIM(SIFLOW_INTEREST_PAY_SSI_ID)||'|'||
TRIM(SIFLOW_INTEREST_RECIEVE_NOSTRO)||'|'||
TRIM(SIFLOW_INT_RECIEVE_SETT_METHOD)||'|'||
TRIM(SIFLOW_INT_RECIEVE_CPTY_AGENT)||'|'||
TRIM(SIFLOW_INTEREST_RECIEVE_SSI_ID)||'|'||
TRIM(SIDE_SIDE_ONE_COMP_METHOD)||'|'||
TRIM(SIDE_SIDE_ONE_COMP_FREQUENCY)||'|'||
TRIM(SIDE_SIDE_ONE_START_DD_CNVNTN)||'|'||
TRIM(SIDE_SIDE_ONE_END_DD_CNVNTN)||'|'||
TRIM(SIDE_SIDE_1_CASH_FLW_D_CNVNTN)||'|'||
TRIM(AMORTISATION_TYPE)||'|'||
TRIM(AMORTISATION_FREQUENCY)||'|'||
TRIM(AMORTISATION_START_DATE)||'|'||
TRIM(AMORTISATION_END_DATE)||'|'||
TRIM(AMORTISATION_STEP_AMOUNT)
)
from COM_LOAN_O_TABLE;
exit; 
