-- File Name		: equity_defn_spool.sql
-- File Created for	: Creation of source table
-- Created By		: Sharanappa S
-- Client		    : ABK
-- Created On		: 28-09-2016
-------------------------------------------------------------------
set head off
set feedback off
set term off
set lines 2000
set page size 0
set pages 0
set trimspool on
spool $MIG_PATH/output/finacle/treasury/EQUITY_DEFN.TXT
SELECT 
'RESPONSE'||'|'||
'Template'||'|'||
'NAME'||'|'||
'INSTRUMENT_TYPE'||'|'||
'INSTRUMENT_SUBTYPE'||'|'||
'ISSUER_STRING'||'|'||
'INSTRUMENT_CLASS_DATA_NAME'||'|'||
'LISTING_DATE'||'|'||
'ISSUE_CCY'||'|'||
'PRICE_QUOTE'||'|'||
'ACTIVE_STATUS'||'|'||
'ENTITY_PERM_GROUP'||'|'||
'DESCRIPTION'||'|'||
'EXCHANGES_LIST'||'|'||
'DEFAULT_EXCHANGE_STR'||'|'||
'NO_DELIVERY_START'||'|'||
'NO_DELIVERY_END'||'|'||
'MARKET_LOT'||'|'||
'MATURITY_DATE'||'|'||
'PAID_UP_VALUE'||'|'||
'FACE_VALUE'||'|'||
'ENTRY_LOAD'||'|'||
'EXIT_LOAD'||'|'||
'AUTO_OR_MANUAL_RESET'||'|'||
'SHORT_SALES_ACTION'||'|'||
'MIN_INVEST'||'|'||
'TRADING_STRATEGY'||'|'||
'REALISATION_METHOD'||'|'||
'DATE_TO_REALISE'||'|'||
'INVEST_MULTIPLE'||'|'||
'PREBLOCK_PRICE'||'|'||
'EQMF_MTM_CALC_METHOD'||'|'||
'IS_DEMAT'||'|'||
'ISSUANCE_DATA.COI'||'|'||
'ISSUANCE_DATA.COUR'||'|'||
'INSTRUMENT_ID.$1.IDENTIFIER'||'|'||
'INSTRUMENT_ID.$1.CODE'||'|'||
'INSTRUMENT_ID.$2.IDENTIFIER'||'|'||
'INSTRUMENT_ID.$2.CODE'||'|'||
'INSTRUMENT_ID.$3.IDENTIFIER'||'|'||
'INSTRUMENT_ID.$3.CODE'||'|'||
'ALT_ID1'||'|'||
'ALT_ID2'||'|'||
'ISSUANCE_DATA.COI'||'|'||
'ISSUANCE_DATA.COUR'||'|'||
'RIGHT_WARRANT_DATA.OPTIONALITY'||'|'||
'RIGHT_WARRANT_DATA.ISSUE_PRICE_STRING'||'|'||
'RIGHT_WARRANT_DATA.ISSUE_DISB_QTY'||'|'||
'RIGHT_WARRANT_DATA.ISSUE_BASE_QTY'||'|'||
'RIGHT_WARRANT_DATA.ISSUE_FRAC_SCRIPT_TREATMENT'||'|'||
'RIGHT_WARRANT_DATA.CASH_PAYMENT_DATE'||'|'||
'RIGHT_WARRANT_DATA.ACCEPTANCE_CLOSING_DATE'||'|'||
'RIGHT_WARRANT_DATA.DELIVERY_DATE'||'|'||
'RIGHT_WARRANT_DATA.TRADING_PERIOD_START'||'|'||
'RIGHT_WARRANT_DATA.TRADING_PERIOD_END'||'|'||
'RIGHT_WARRANT_DATA.UNDERLYING_EQT_DEFN_NAME'||'|'||
'RIGHT_WARRANT_DATA.OPTION_STYLE'||'|'||
'RIGHT_WARRANT_DATA.STRIKE_PRICE'||'|'||
'RIGHT_WARRANT_DATA.OPTION_TYPE'||'|'||
'RIGHT_WARRANT_DATA.EXERCISE_DISB_QTY'||'|'||
'RIGHT_WARRANT_DATA.EXERCISE_BASE_QTY'||'|'||
'RIGHT_WARRANT_DATA.EXERCISE_START_DATE'||'|'||
'RIGHT_WARRANT_DATA.EXCERCISE_END_DATE'||'|'||
'RIGHT_WARRANT_DATA.FREQUENCY'||'|'||
'RIGHT_WARRANT_DATA.SUB_RESP_DATE'||'|'||
'RIGHT_WARRANT_DATA.SELL_RESP_DATE'||'|'||
'RIGHT_WARRANT_DATA.EQUITY_Delivery_Date_DATE'||'|'||
'RIGHT_WARRANT_DATA.EXCERCISE_FRAC_SCRIPT_TREATMENT'||'|'||
'RIGHT_WARRANT_DATA.HAS_ASSESSED_VALUE_PYMT'||'|'||
'RIGHT_WARRANT_DATA.ASSESSED_VALUE_PYMNT_DATE'||'|'||
'RIGHT_WARRANT_DATA.ASSESSED_VALUE_PYMNT_TYPE'||'|'||
'RIGHT_WARRANT_DATA.ASSESSED_VALUE_PYMNT_ABS'||'|'||
'RIGHT_WARRANT_DATA.ASSESSED_VALUE_PMT_PCNT'
FROM DUAL
UNION ALL
select
TO_CHAR(TRIM(RESPONSE)||'|'||
TRIM(TEMPLATE)||'|'||
TRIM(NAME)||'|'||
TRIM(INSTRUMENT_TYPE)||'|'||
TRIM(INSTRUMENT_SUBTYPE)||'|'||
TRIM(ISSUER_STRING)||'|'||
TRIM(INSTRUMENT_CLASS_DATA_NAME)||'|'||
TRIM(LISTING_DATE)||'|'||
TRIM(ISSUE_CCY)||'|'||
TRIM(PRICE_QUOTE)||'|'||
TRIM(ACTIVE_STATUS)||'|'||
TRIM(ENTITY_PERM_GROUP)||'|'||
TRIM(DESCRIPTION)||'|'||
TRIM(EXCHANGES_LIST)||'|'||
TRIM(DEFAULT_EXCHANGE_STR)||'|'||
TRIM(NO_DELIVERY_START)||'|'||
TRIM(NO_DELIVERY_END)||'|'||
TRIM(MARKET_LOT)||'|'||
TRIM(MATURITY_DATE)||'|'||
TRIM(PAID_UP_VALUE)||'|'||
TRIM(FACE_VALUE)||'|'||
TRIM(ENTRY_LOAD)||'|'||
TRIM(EXIT_LOAD)||'|'||
TRIM(AUTO_OR_MANUAL_RESET)||'|'||
TRIM(SHORT_SALES_ACTION)||'|'||
TRIM(MIN_INVEST)||'|'||
TRIM(TRADING_STRATEGY)||'|'||
TRIM(REALISATION_METHOD)||'|'||
TRIM(DATE_TO_REALISE)||'|'||
TRIM(INVEST_MULTIPLE)||'|'||
TRIM(PREBLOCK_PRICE)||'|'||
TRIM(EQMF_MTM_CALC_METHOD)||'|'||
TRIM(IS_DEMAT)||'|'||
TRIM(ISSUANCE_DATA_COI)||'|'||
TRIM(ISSUANCE_DATA_COUR)||'|'||
TRIM(INSTRUMENT_ID_$1_IDENTIFIER)||'|'||
TRIM(INSTRUMENT_ID_$1_CODE)||'|'||
TRIM(INSTRUMENT_ID_$2_IDENTIFIER)||'|'||
TRIM(INSTRUMENT_ID_$2_CODE)||'|'||
TRIM(INSTRUMENT_ID_$3_IDENTIFIER)||'|'||
TRIM(INSTRUMENT_ID_$3_CODE)||'|'||
TRIM(ALT_ID1)||'|'||
TRIM(ALT_ID2)||'|'||
TRIM(ISSUANCE_DATA_COI_1)||'|'||
TRIM(ISSUANCE_DATA_COUR_1)||'|'||
TRIM(RIGHT_WARRANT_DATA_OPTIONALITY)||'|'||
TRIM(RT_WRNT_DATA_ISSUE_PRICE_STR)||'|'||
TRIM(RT_WRT_DATA_ISSUE_DISB_QTY)||'|'||
TRIM(RT_WRT_DATA_ISSUE_BASE_QTY)||'|'||
TRIM(WRT_DATA_ISS_FRAC_SCPT_TRTMNT)||'|'||
TRIM(RIGHT_WARRANT_CASH_PAYMNT_DATE)||'|'||
TRIM(RIGHT_WRT_ACCEPTANCE_CLOSG_DT)||'|'||
TRIM(RIGHT_WARRANT_DELIVERY_DATE)||'|'||
TRIM(RIGHT_WRT_TRADING_PERIOD_START)||'|'||
TRIM(RIGHT_WRT_TRADING_PERIOD_END)||'|'||
TRIM(RIGHT_WRT_UNRLYNG_EQT_DEFN_NM)||'|'||
TRIM(RIGHT_WARRANT_OPTION_STYLE)||'|'||
TRIM(RIGHT_WARRANT_STRIKE_PRICE)||'|'||
TRIM(RIGHT_WARRANT_OPTION_TYPE)||'|'||
TRIM(RIGHT_WRT_EXERCISE_DISB_QTY)||'|'||
TRIM(RIGHT_WRANT_EXERCISE_BASE_QTY)||'|'||
TRIM(RIGHT_WRANT_EXERISE_START_DATE)||'|'||
TRIM(RIGHT_WRANT_EXCERCISE_END_DATE)||'|'||
TRIM(RIGHT_WARRANT_DATA_FREQUENCY)||'|'||
TRIM(RIGHT_WRANT_DATA_SUB_RESP_DATE)||'|'||
TRIM(RIGHT_WRANT_DTA_SELL_RESP_DATE)||'|'||
TRIM(RGT_WRT_DATA_EQITY_DLVRY_DATE)||'|'||
TRIM(RGT_WRT_EXRCS_FRAC_SCRT_TREATT)||'|'||
TRIM(RIGHT_WARRANT_ASSED_VALUE_PYMT)||'|'||
TRIM(RIGHT_WRT_ASSED_VALUE_PYMNT_DT)||'|'||
TRIM(RIGHT_WRT_ASSED_VALUE_PYMNT_TP)||'|'||
TRIM(RGHT_WRT_ASSED_VALUE_PYMNT_ABS)||'|'||
TRIM(RGHT_WRT_ASSED_VALUE_PMT_PCNT)
)
from EQUITY_DEFN_O_TABLE;
exit; 
