-- File Name		: swap_spool.sql
-- File Created for	: Creation of source table
-- Created By		: Sharanappa S
-- Client		    : ABK
-- Created On		: 28-09-2016
-------------------------------------------------------------------
set head off
set feedback off
set term off
set lines 2000
set page size 0
set pages 0
set trimspool on
spool $MIG_PATH/output/finacle/treasury/SWAP.TXT
SELECT
'Response'||'|'||
'Product_TYPE'||'|'||
'Identifier'||'|'||
'Counterparty'||'|'||
'CURRENCY_STRING'||'|'||
'SWAP_FX_RATE'||'|'||
'SIDE.PAY_SIDE.CASH_FLOW_SIDE_TYPE'||'|'||
'END_DATE'||'|'||
'SIDE.PAY_SIDE.START_DATE'||'|'||
'SIDE.PAY_SIDE.END_DATE'||'|'||
'TRADING_BOOK'||'|'||
'DEPT_NAME'||'|'||
'SUBTYPE'||'|'||
'SIDE.PAY_IS_ALWAYS_SIDE_1'||'|'||
'SIDE.PAY_SIDE.NOTIONAL_AMOUNT.VALUE'||'|'||
'SIDE.RECEIVE_SIDE.END_DATE'||'|'||
'SIDE.PAY_SIDE.NOTIONAL_AMOUNT.CURRENCY'||'|'||
'SIDE.RECEIVE_SIDE.CASH_FLOW_SIDE_TYPE'||'|'||
'SIDE.RECEIVE_SIDE.REFERENCE_RATE'||'|'||
'SIDE.RECEIVE_SIDE.BASIS_CODE'||'|'||
'SIDE.RECEIVE_SIDE.NOTIONAL_AMOUNT.CURRENCY'||'|'||
'SIDE.RECEIVE_SIDE.LONG_OR_SHORT'||'|'||
'SIDE.RECEIVE_SIDE.CREATION_FREQUENCY'||'|'||
'SIDE.PAY_SIDE.CREATION_FREQUENCY'||'|'||
'SIDE.RECEIVE_SIDE.NOTIONAL_AMOUNT.VALUE'||'|'||
'CCY_CALENDAR_SET'||'|'||
'SIDE.PAY_SIDE.LONG_OR_SHORT'||'|'||
'SIDE.PAY_SIDE.FIX_RATE'||'|'||
'START_DATE'||'|'||
'SIDE.PAY_SIDE.BASIS_CODE'||'|'||
'COST_OF_CARRY_REF_RATE_CODE'||'|'||
'TYPE_STRING'||'|'||
'SIDE.RECEIVE_SIDE.START_DATE'||'|'||
'SIDE.PAY_SIDE.REFERENCE_RATE'||'|'||
'ENTITY_NAME'||'|'||
'SIDE.$2.FIX_RATE'||'|'||
'SIDE.$1.IS_RESET_IN_ARREARS'||'|'||
'SIDE.$1.START_DATE_DAY_CONVENTION'||'|'||
'SIDE.$1.CASH_FLOW_DAY_CONVENTION'||'|'||
'SIDE.$1.END_DATE_DAY_CONVENTION'||'|'||
'SIDE.$1.MARGIN'||'|'||
'SIDE.$2.MARGIN'
FROM DUAL
UNION ALL
select
TO_CHAR(
TRIM(RESPONSE) ||'|'||
TRIM(PRODUCT_TYPE) ||'|'||
TRIM(IDENTIFIER) ||'|'||
TRIM(COUNTERPARTY) ||'|'||
TRIM(CURRENCY_STRING) ||'|'||
TRIM(SWAP_FX_RATE) ||'|'||
TRIM("SIDESIDE.CASH_FLOW_SIDE_TYPE") ||'|'||
TRIM(END_DATE) ||'|'||
TRIM("SIDE.PAY_SIDE.START_DATE") ||'|'||
TRIM("SIDE.PAY_SIDE.END_DATE") ||'|'||
TRIM(TRADING_BOOK) ||'|'||
TRIM(DEPT_NAME) ||'|'||
TRIM(SUBTYPE) ||'|'||
TRIM(SIDE_PAY_IS_ALWAYS_SIDE_1) ||'|'||
TRIM(PAY_SIDE_NOTIONAL_AMT_VALUE) ||'|'||
TRIM(SIDE_RECEIVE_SIDE_END_DATE) ||'|'||
TRIM(PAY_SIDE_NOTIONAL_AMOUNT_CCY) ||'|'||
TRIM(REC_SIDE_CASH_FLW_SIDE_TYPE) ||'|'||
TRIM(SIDE_RECEIVE_SIDE_REFENCE_RATE) ||'|'||
TRIM(SIDE_RECEIVE_SIDE_BASIS_CODE) ||'|'||
TRIM(RECEIVE_SIDE_NOTIONAL_AMT_CCY) ||'|'||
TRIM(RECEIVE_SIDE_LONG_OR_SHORT) ||'|'||
TRIM(RECEIVE_SIDE_CREATION_FREQ) ||'|'||
TRIM(PAY_SIDE_CREATION_FREQUENCY) ||'|'||
TRIM(RECEIV_SIDE_NOTIONAL_AMT_VALUE) ||'|'||
TRIM(CCY_CALENDAR_SET) ||'|'||
TRIM(SIDE_PAY_SIDE_LONG_OR_SHORT) ||'|'||
TRIM(SIDE_PAY_SIDE_FIX_RATE) ||'|'||
TRIM(START_DATE) ||'|'||
TRIM(SIDE_PAY_SIDE_BASIS_CODE) ||'|'||
TRIM(COST_OF_CARRY_REF_RATE_CODE) ||'|'||
TRIM(TYPE_STRING) ||'|'||
TRIM(SIDE_RECEIVE_SIDE_START_DATE) ||'|'||
TRIM("SIDE.PAY_SIDE.REFERENCE_RATE") ||'|'||
TRIM(ENTITY_NAME) ||'|'||
TRIM("SIDE.RECIVE_SIDE.FIXED_RATE") ||'|'||
TRIM(IS_RESET_IN_ARREARS) ||'|'||
TRIM(START_DATE_DAY_CONVENTION) ||'|'||
TRIM(SIDE_CASH_FLOW_DAY_CONVENTION) ||'|'||
TRIM(END_DATE_DAY_CONVENTION)||'|'||
trim(SIDE1_MARGIN)||'|'||
trim(SIDE2_MARGIN)
)
from SWAP_O_TABLE;
exit; 
