set head off
set feedback off
set term off
set linesize 5000
set page size 0
set pages 0
set trimspool on
spool $MIG_PATH/output/finacle/laa/KW/RL001.txt
select 
Account_Number		||
Customer_Credit_Pref_Percent	||
Customer_Debit_Pref_Percent||
Acct_ID_Credit_Pref_Percent||
Acct_ID_Debit_Pref_Percent	||
Repricing_Plan		||
Pegging_Frequency_in_Months	||
Pegging_Frequency_in_Days||
Interest_Route_Flag||
Acct_Currency_Code||
Sol_ID||
GL_Sub_Head_Code||
Schm_Code||
CIF_ID||
Acct_Open_Date||
Sanction_Limit||
Ledger_Number||
Sector_Code||
Sub_Sector_Code||
Purpose_of_Advance||
Nature_of_Advance||
Free_Code_3||
Sanction_Reference_Number||
Sanction_Limit_Date||
Sanction_Level_Code||
Limit_Expiry_Date||
Sanction_Authority_Code||
Loan_Paper_Date||
Operative_Acct_ID||
Operative_Currency_Code||
Operative_Sol_ID||
Demand_Satisfy_Method||
Lien_on_Operative_Acct_Flag||
Repayment_currency_rate_code||
Interest_table_code||
Interest_on_principal_Flag||
Penal_int_ovdue_princ_dmd_Flg||
Princ_Dmd_Ovdue_end_month_Flg||
Int_On_Int_Demand_Flag||
penal_int_overdue_int_dmd_Flg||
Int_Demand_Ovdue_End_Mnth_Flg||
Transfer_Effective_Date||
Cumulative_Normal_int_amt||
Cumulative_penal_int_amt||
cumulative_additional_int_amt||
Liab_Transfer_Effective_date||
Disbursement_Previous_Sche||
Debit_Int_Calc_upto_date||
Repayment_Schedule_Date||
Repayment_Period_in_months||
Repayment_Period_in_Days||
Past_Due_Flag||
Past_Due_Transfer_Date||
Prv_To_Pd_GL_Sub_Head_Code||
Interest_Suspense_Amount||
Penal_Interest_Suspense_Amt||
Charge_Off_Flag||
Charge_Off_Date||
Charge_Off_Principle||
Pending_Interest||
Principal_Recovery||
Interest_Recovery||
source_dealer_code||
Disburse_dealer_code||
Apply_late_fee_Flag||
Late_Fee_Grace_Period_Months||
Late_Fee_Grace_Period_Days||
Instal_amt_collect_upfront||
Num_of_instal_collec_upfront||
upfront_instalment_amount||
Demand_Past_Due_counter||
Sum_of_the_princ_demand_amt||
Payoff_Flag||
ExcLd_for_Combined_Statement||
Statement_CIF_ID||
Transfer_Cycle_String||
Bank_IRR_Rate||
Value_Of_Asset||
Occupation_code_customer||
Borrower_category_code||
Mode_of_the_advance||
Type_of_the_advance||
guarantee_coverage_Code||
Industry_Type||
Free_Code_1||
Free_Code_2||
Free_Code_4||
Free_Code_5||
Free_Code_6||
Free_Code_7||
Free_Code_8||
Free_Code_9||
Free_Code_10||
Acct_Location_Code||
credit_report_file_Ref_ID||
DICGC_Fee_Percent||
Last_Compound_Date||
Daily_Compound_Interest_Flag||
CalculateOverdue_Int_rate_Flg||
EI_paying_period_start_date||
EI_paying_period_end_date||
IRR_Rate||
Advance_interest_amount||
Amortised_Amount||
Debit_Booked_Upto_Date||
Adv_Int_Collection_upto_Date||
Accrual_Rate||
Int_Rate_Sanction_Limit_Flg||
Interest_Rest_Frequency||
Interest_Rest_Basis||
Charge_Route_Flag||
Final_Disbursement_Flag||
Auto_Resch_after_Holiday_Prd||
total_number_of_deferments||
num_deferments_current_repay||
End_Date||
Penal_interest_on_Outstanding||
Charge_off_type||
Deferred_appli_int_rate_flg||
Def_applicable_int_rate||
Deferred_Interest_Amount||
Auto_Reschedule_Not_Allowed||
Rescheduled_Overdue_Principal||
Reschedule_Overdue_Interest||
Loan_Type||
Pay_Off_Reason_Code||
Related_Deposit_Acct_ID||
Last_AckNowledgt_Dr_Prd_date||
Refinance_Sanction_Date||
Refinance_Amount||
Subsidy_Acct_ID||
Subsidy_Agency||
Subsidy_Claimed_Date||
Subsidy_Activity_Code||
Debit_AckNowledgement_Type||
Refinance_Sanction_Number||
Refinance_Reference_Number||
Refinance_Claimed_Date||
Subsidy_Amount||
Subsidy_Received_Date||
Preprocess_Fee||
Activity_Code||
Probation_Period_in_Months||
Probation_Period_in_Days||
Compound_Rest_Indicator_Flag||
Discounted_Int_Rate_Flag||
Collect_Interest_Flag||
Despatch_mode||
Acct_Manager||
Mode_of_Oper_Code||
Statement_Frequency_Type||
Week_num_for_Statement_Date||
Week_Day_for_Statement_Date||
Week_Dt_for_Statement_Date||
Statement_Freq_case_of_Hldys||
Statement_of_the_Account||
Next_Print_date||
Fixed_Rate_Term_in_Months||
Fixed_Rate_Term_in_Days||
Minimum_Int_Percent_Debit||
Maximum_Int_Percent_Debit||
Instalment_Income_Ratio||
Product_Group||
Free_Text||
Linked_Account_ID||
Delinquency_Resch_Method_Flg||
Total_Number_of_Switch_Over||
Non_Starter_Flag||
Floating_Interest_Table_Code||
Floating_Repricing_Frequency||
Floating_Repricing_Freq_Days||
Single_EMI_Turn_Over_Diff_Flg||
IBAN_Number||
IAS_CLASSIFICATION_CODE||
Account_Number1||
Type_of_top_up||
Negotiated_Rate_Debit_Percent||
Normal_Int_Product_Method||
Penal_Interest_Rate_Method||
Penal_Interest_Method||
hldy_prd_frm_first_disb_flg||
EI_Scheme_Flag||
EI_Method||
Ei_Formula_Flag||
Normal_Holiday_Period_in_Mnth||
Holiday_Period_Interest_Flag||
Holiday_Period_Interest_Amt||
Resche_by_Adjust_TeNor_Amt||
Auto_Reschedule_every_Disb||
Auto_Reschule_Int_Rate_Change||
Auto_Reschedule_Prepayment||
Rescheduling_Amount_flag||
Capitalize_Int_on_Rephasement||
Carry_over_Demands||
Type_Instalment_Combination||
Cap_Int_to_EMI_Flg||
Deferred_Int_Due_to_EMI_Cap||
Month_for_Deferment||
Num_Months_Deferred||
Channel_Credit_Pref_Percent||
Channel_Debit_Pref_Percent||
Channel_Id||
Channel_Level_Code||
Instalment_Effective_Flag||
Notice_Period||
Shift_Instalment_Flag||
Include_Maturity_Date||
Interest_Rule_Code||
Cumulative_Capitalize_Fees||
upfront_instalment_int_amount||
Recall_Flag||
Recall_Date||
Diff_PS_Freq_For_Rel_Party||
Diff_Swift_Freq_For_Rel_Party||
Penal_Interest_table_code||
Penal_Preferential_Percent||
RA_ref_number||
Interest_table_Version||
Address_Type||
Phone_Type||
Email_Type||
Accrued_Penal_Int_Recovery||
Penal_Interest_Recovery||
Collection_Interest_Recovery||
Collection_Penal_Int_Recovery||
Mark_Up_Applicable_Flag||
Pref_Calendar_base_processing||
Purchase_Reference||
Frez_code||
Frez_reason_code||
Bank_Profit_Share_Pcnt||
Bank_Loss_Share_Pcnt||
Next_Profit_Adj_Due_Dt||
Profit_Adj_Freq||
Week_Num_for_Profit_Adj||
Week_Day_for_Profit_Adj||
Start_Day_for_Profit_Adj||
Profit_Adj_Freq_holidays||
Adj_Freq_Calendar_Base||
Salam_Sale_Ref_ID||
Salam_Asset_Code||
Seller_Dealer_ID||
Salam_Seller_Det||
Para_Salam_Seller_Ref_ID||
Para_Salam_Asset_Code||
Buyer_Dealer_ID||
Salam_Buyer_Details||
Purchase_Price_Per_Unit||
Dealer_Id||
Asset_Code||
Margin_Money_Acc_Flag||
Margin_Money_Type||
Margin_Money_Pcnt||
Margin_Money_Amt||
Invoice_Amount||
Debit_Account_ID||
Purchase_Aqad_Amt||
Sale_Aqad_Amt||
Purc_Aqad_Ref||
Sale_Aqad_Ref||
Purc_Aqad_Date||
Purc_Aqad_DateHH||
Purc_Aqad_DateMM||
Purc_Aqad_DateSS||
Sale_Aqad_Date||
Sale_Aqad_DateHH||
Sale_Aqad_DateMM||
Sale_Aqad_DateSS||
No_Of_Units||
Asset_Particulars||
Unearned_Income||
Security_Dep_Amt||
Adj_Advance_Rent||
Repossess_Flag||
Cumu_Deposit_Amt||
Last_Dep_Date||
Istisna_with_Parallel_Istisna||
Construction_TenorMM||
SettlementTenorMM||
SettlementTenorDD||
Istisna_Contract_ID||
Cost_Of_Construction||
Unearned_Inc_for_Cons_Prd||
Unearned_Inc_for_Settle_Prd||
Const_Prd_Profit_Method||
Retention_Amt||
Retentio_Rel_Flg||
Parallel_Istisna_Delivery_Dt||
Builder_Profit||
Builder_Profit_Pcnt||
Builder_Profit_Amt||
Notes||
Builder_ACC_ID||
Is_CP_Over||
Rebate_Benefit_Amount||
Process_Rebate_on_Mat||
Print_Print_Statement||
Print_Advice_for_SI||
Print_Deposit_Notice||
Print_Loan_Notice||
Interest_Certificate||
Interest_Rate_Change_Adv||
Collect_Excess_Profit||
Carry_Forward||
Adj_Order_for_CF_PL||
Expected_Turnover_Amt||
Turn_Over_Currency||
Expected_Profit_Amt||
Profit_Currency||
Nature_of_Business||
Free_Text2||
Asset_Id||
Lease_type||
End_of_Lease_Option||
Collect_security_Deposit||
Adjust_Security_Deposit||
Agreed_Usage_Freq||
Agreed_Usage||
Collect_Tax||
Collect_Insu_Premium||
Residual_Value_type||
Guaranteed_by||
Apply_Lease_Canc_Fee||
Lease_Canc_not_acce_after_days||
Lease_Canc_not_accp_after_Mths||
Expected_Future_Value||
Carry_Over_Rents||
Rent_Dmd_OD_at_end_of_Mnth||
Rent_Dmd_OD_at_end_of_days||
Rent_OD_After_MMMDDD||
Lnk_Trade_Fin_Entity_Type||
Linked_Entity_Sol_ID||
Linked_Trade_Fin_Entity_ID||
Intend_to_Export||
Exp_Financing_Type||
Exp_Financing_Perc||
Broken_Prd_Int_Flag||
Normal_Hldy_Prd_in_Days
from lam_o_table
--left join (select foracid from tbaadm.gam where bank_id=get_param('BANK_ID')) a on foracid = trim(Account_Number)
--where foracid is null
ORDER BY Sol_ID;
exit;
 
