set head off
set feedback off
set term off
set linesize 5000
set page size 0
set pages 0
set trimspool on
spool $MIG_PATH/output/finacle/laa/KW/RL_late_fee.txt
select
ACCOUNT_ID||CHARGE_TYPE||USER_CALC_CHARGE_AMT||CURRENCY_CODE||CHARGE_WAIVED||CHARGE_AMT_COLLECTED||AMORTIZATION_FLAG||AMORTIZED_AMOUNT||LAST_AMORTIZATION_DATE||TRANSACTION_DATE||TRANSACTION_ID||NEXT_ASSESMENT_DATE||ASSESMENT_FREQUENCY_TYPE||ASSES_FREQ_WEEK_NUM||ASSESS_FREQ_WEEK_DAY||ASSESS_FREQ_START_DATE||ASSESS_FREQ_HLDY_STATUS||NO_TIMES_ASSESSED||LAST_ASSESSMENT_DATE||DEDUCTIBLE_FLAG||EVENT_ID_PTTM||AMORT_TENOR||PENDING_AMORT_TENOR||MAX_NO_ASSESSMENTS
from ldt_fee;
exit; 
