-- File Name        : cropmisc_upload.sql
-- File Created for    : Upload file for cropmisc
-- Created By        : Jagadeesh M
-- Client            : Emirates Islamic Bak
-- Created On        : 27-05-2015
-------------------------------------------------------------------
truncate table CU5CORP_O_TABLE;
insert into CU5CORP_O_TABLE
SELECT   
--   CORP_KEY           CHAR(50) NULL,
    fin_cif_id,
--   CIF_ID         CHAR(32) NULL,
    fin_cif_id,
--   CORP_REP_KEY      CHAR(38) NULL,
    '',
-- TYPE             CHAR(50) NULL,
    'CURRENCY',
-- STR1             CHAR(255) NULL,
    --trim(CURRENCY), 
	CCY,-- Script changed on 30-05-2017 based on Vijay confirmation and mail dt on 29-05-2017
-- STR2             CHAR(255) NULL,
    '',
-- STR3             CHAR(255) NULL,
    --'Beneficiary',
    '',--changed on 17-01-2016
--   STR4          CHAR(255) NULL,
    '',
--   STR5          CHAR(255) NULL,
    '',
-- STR6             CHAR(255) NULL,
    '',
-- STR7             CHAR(255) NULL,
    '',
-- STR8             CHAR(255) NULL,
    '',
-- STR9             CHAR(255) NULL,
    '',
--   STR10         CHAR(255) NULL,
    '',
--   STR11         CHAR(50) NULL,
    '',
--   DATE1         CHAR(17) NULL,
    '31-DEC-2099',
--   STR12         CHAR(50) NULL,
    '',
--   DATE2         CHAR(17) NULL,
    '',
--   AMOUNT1         CHAR(20) NULL,
    '0',
--   AMOUNT2         CHAR(20) NULL,
    '',
--   AMOUNT3         CHAR(20) NULL,
    '',
--   AMOUNT4         CHAR(20) NULL,
    '',
--   SMALL_STR1         CHAR(50) NULL,
    '',
--   SMALL_STR2         CHAR(50) NULL,
    '',
--   SMALL_STR3         CHAR(50) NULL,
    '',
--   SMALL_STR4         CHAR(50) NULL,
    '',
--   SMALL_STR5         CHAR(50) NULL,
    '',
--   SMALL_STR6         CHAR(50) NULL,
    '',
--   SMALL_STR7         CHAR(50) NULL,
    '',
--   SMALL_STR8         CHAR(50) NULL,
    '',
--   SMALL_STR9         CHAR(50) NULL,
    '',
--  SMALL_STR10         CHAR(50) NULL,
    '',
--   MED_STR1         CHAR(100) NULL,
    '',
--   MED_STR2         CHAR(100) NULL,
    '',
--   MED_STR3         CHAR(100) NULL,
    '',
--   MED_STR4         CHAR(100) NULL,
    '',
--   MED_STR5         CHAR(100) NULL,
    '',
--   MED_STR6         CHAR(100) NULL,
    '',
--   MED_STR7         CHAR(100) NULL,
    '',
--   MED_STR8         CHAR(100) NULL,
    '',
--   MED_STR9         CHAR(100) NULL,
    '',
--   MED_STR10         CHAR(100) NULL,
    '',
--   LARGE_STR1         CHAR(250) NULL,
    '',
--   LARGE_STR2         CHAR(250) NULL,
    '',
--   LARGE_STR3         CHAR(250) NULL,
    '',
--   LARGE_STR4         CHAR(250) NULL,
    '',
--   LARGE_STR5         CHAR(250) NULL,
    '',
--   DATE3         CHAR(17) NULL,
    '',
--   DATE4         CHAR(17) NULL,
    '',
--   DATE5         CHAR(17) NULL,
    '',
--   DATE6         CHAR(17) NULL,
    '',
--   DATE7         CHAR(17) NULL,
    '',
--   DATE8         CHAR(17) NULL,
    '',
--   DATE9         CHAR(17) NULL,
    '',
--   DATE10         CHAR(17) NULL,
    '',
--   NUMBER1         CHAR(38) NULL,
    '',
--   NUMBER2         CHAR(38) NULL,
    '',
--   NUMBER3         CHAR(38) NULL,
    '',
--   NUMBER4         CHAR(38) NULL,
    '',
--   NUMBER5         CHAR(38) NULL,
    '',
--   NUMBER6         CHAR(38) NULL,
    '',
--   NUMBER7         CHAR(38) NULL,
    '',
--   NUMBER8         CHAR(38) NULL,
    '',
--   NUMBER9         CHAR(38) NULL,
    '',
--   NUMBER10         CHAR(38) NULL,
    '',
--   DECIMAL1         CHAR(25) NULL,
    '',
--   DECIMAL2         CHAR(25) NULL,
    '',
--   DECIMAL3         CHAR(25) NULL,
    '',
--   DECIMAL4         CHAR(25) NULL,
    '',
--   DECIMAL5         CHAR(25) NULL,
    '',
--   DECIMAL6         CHAR(25) NULL,
    '',
--   DECIMAL7         CHAR(25) NULL,
    '',
--   DECIMAL8         CHAR(25) NULL,
    '',
--   DECIMAL9         CHAR(25) NULL,
    '',
--   DECIMAL10         CHAR(25) NULL,
    '',
--   ENTITYTYPE         CHAR(50) NULL,
    --'CORPORATE',
    '',--chanegd on 17-01-2016
--   STR43         CHAR(50) NULL,
    '',
--   STR44         CHAR(50) NULL,
    '',
--   STR45         CHAR(50) NULL,
    '',
--   STR46         CHAR(50) NULL,
    '',
--   STR47         CHAR(50) NULL,
    '',
--   STR48         CHAR(50) NULL,
    '',
--   STR49         CHAR(50) NULL,
    '',
--   STR50         CHAR(50) NULL,
    '',
--   ORG_KEY         CHAR(50) NULL,
    fin_cif_id,
--   STR21         CHAR(50) NULL,
    '',
--   STR22         CHAR(50) NULL,
    '',
--   STR23         CHAR(50) NULL,
    '',
--   STR24         CHAR(50) NULL,
    '',
--   STR25         CHAR(50) NULL,
    '',
--   STR26         CHAR(50) NULL,
    '',
--   STR27         CHAR(50) NULL,
    '',
--   STR28         CHAR(1) NULL,
    '',
--   STR29         CHAR(1) NULL,
    '',
--   STR30         CHAR(1) NULL,
    '',
--   STR31         CHAR(1) NULL,
    '',
--   STR32         CHAR(1) NULL,
    '',
--   STR38         CHAR(200) NULL,
    '',
--   STR39         CHAR(200) NULL,
    '',
--   STR40         CHAR(200) NULL,
    '',
--   STR41         CHAR(200) NULL,
    '',
--   STR42         CHAR(200) NULL,
    '',
--   DBFLOAT1         CHAR(99) NULL,
    '',
--   DBFLOAT2         CHAR(99) NULL,
    '',
--   DBFLOAT3         CHAR(99) NULL,
    '',
--   DBFLOAT4         CHAR(99) NULL,
    '',
--   DBFLOAT5         CHAR(99) NULL,
    '',
--   AMOUNT5         CHAR(20) NULL,
    '',
--   FLAG1         CHAR(10) NULL,
    '',
--   FLAG2         CHAR(10) NULL,
    '',
--   FLAG3         CHAR(10) NULL,
    '',
--   FLAG4         CHAR(10) NULL,
    '',
--   FLAG5         CHAR(10) NULL,
    '',
-- INT1             CHAR(38) NULL,
    '',
-- INT2             CHAR(38) NULL,
    '',
-- INT3             CHAR(38) NULL,
    '',
-- INT4             CHAR(38) NULL,
    '',
-- INT5             CHAR(38) NULL,
    '',
-- INT6             CHAR(38) NULL,
    '',
-- INT7             CHAR(38) NULL,
    '',
-- INT8             CHAR(38) NULL,
    '',
-- INT9             CHAR(38) NULL,
    '',
--   INT10         CHAR(38) NULL,
    '',
--   INT11         CHAR(38) NULL,
    '',
--   INT12         CHAR(38) NULL,
    '',
--   INT13         CHAR(38) NULL,
    '',
--   INT14         CHAR(38) NULL,
    '',
--   INT15         CHAR(38) NULL,
    '',
-- MLUSERFIELD1         CHAR(80) NULL,
    '',
-- MLUSERFIELD2         CHAR(80) NULL,
    '',
-- MLUSERFIELD3         CHAR(80) NULL,
    '',
-- MLUSERFIELD4         CHAR(80) NULL,
    '',
-- MLUSERFIELD5         CHAR(80) NULL,
    '',
--   STR1_CODE         CHAR(5) NULL,
    '',
--   STR2_CODE         CHAR(5) NULL,
    '',
--   STR3_CODE         CHAR(5) NULL,
    '',
--   STR4_CODE         CHAR(5) NULL,
    '',
--   STR5_CODE         CHAR(5) NULL,
    '',
-- CORE_CUST_ID         CHAR(9) NULL,
    '',
--   CORE_CHILD_CUST_ID     CHAR(9) NULL,
    '',
-- PERCENTAGE1         CHAR(9) NULL,
    '0',
-- PERCENTAGE2         CHAR(9) NULL,
    '0',
-- PERCENTAGE3         CHAR(9) NULL,
    '0',
-- PERCENTAGE4         CHAR(9) NULL,
    '',
-- PERCENTAGE5         CHAR(9) NULL,
    '',
--   BANK_ID         CHAR(8) NULL,
    get_param('BANK_ID'),
--   STR4_ALT1         CHAR(99) NULL,
    '',
--   STR4_ALT2         CHAR(99) NULL,
    '',
--   STR4_ALT3         CHAR(99) NULL
    ''
--from cust_currency 
from map_cif 
inner join currency on 1=1
where INDIVIDUAL='N' and del_flg<>'Y';
commit;
--insert into CU5CORP_O_TABLE
--SELECT   
----   CORP_KEY           CHAR(50) NULL,
--    CORP_KEY,
----   CIF_ID         CHAR(32) NULL,
--    CORP_KEY,
----   CORP_REP_KEY      CHAR(38) NULL,
--    '',
---- TYPE             CHAR(50) NULL,
--    'CURRENCY',
---- STR1             CHAR(255) NULL,
--    'KWD', 
---- STR2             CHAR(255) NULL,
--    '',
---- STR3             CHAR(255) NULL,
--    --'Beneficiary',
--    '',--changed on 17-01-2016
----   STR4          CHAR(255) NULL,
--    '',
----   STR5          CHAR(255) NULL,
--    '',
---- STR6             CHAR(255) NULL,
--    '',
---- STR7             CHAR(255) NULL,
--    '',
---- STR8             CHAR(255) NULL,
--    '',
---- STR9             CHAR(255) NULL,
--    '',
----   STR10         CHAR(255) NULL,
--    '',
----   STR11         CHAR(50) NULL,
--    '',
----   DATE1         CHAR(17) NULL,
--    '31-DEC-2099',
----   STR12         CHAR(50) NULL,
--    '',
----   DATE2         CHAR(17) NULL,
--    '',
----   AMOUNT1         CHAR(20) NULL,
--    '0',
----   AMOUNT2         CHAR(20) NULL,
--    '',
----   AMOUNT3         CHAR(20) NULL,
--    '',
----   AMOUNT4         CHAR(20) NULL,
--    '',
----   SMALL_STR1         CHAR(50) NULL,
--    '',
----   SMALL_STR2         CHAR(50) NULL,
--    '',
----   SMALL_STR3         CHAR(50) NULL,
--    '',
----   SMALL_STR4         CHAR(50) NULL,
--    '',
----   SMALL_STR5         CHAR(50) NULL,
--    '',
----   SMALL_STR6         CHAR(50) NULL,
--    '',
----   SMALL_STR7         CHAR(50) NULL,
--    '',
----   SMALL_STR8         CHAR(50) NULL,
--    '',
----   SMALL_STR9         CHAR(50) NULL,
--    '',
----  SMALL_STR10         CHAR(50) NULL,
--    '',
----   MED_STR1         CHAR(100) NULL,
--    '',
----   MED_STR2         CHAR(100) NULL,
--    '',
----   MED_STR3         CHAR(100) NULL,
--    '',
----   MED_STR4         CHAR(100) NULL,
--    '',
----   MED_STR5         CHAR(100) NULL,
--    '',
----   MED_STR6         CHAR(100) NULL,
--    '',
----   MED_STR7         CHAR(100) NULL,
--    '',
----   MED_STR8         CHAR(100) NULL,
--    '',
----   MED_STR9         CHAR(100) NULL,
--    '',
----   MED_STR10         CHAR(100) NULL,
--    '',
----   LARGE_STR1         CHAR(250) NULL,
--    '',
----   LARGE_STR2         CHAR(250) NULL,
--    '',
----   LARGE_STR3         CHAR(250) NULL,
--    '',
----   LARGE_STR4         CHAR(250) NULL,
--    '',
----   LARGE_STR5         CHAR(250) NULL,
--    '',
----   DATE3         CHAR(17) NULL,
--    '',
----   DATE4         CHAR(17) NULL,
--    '',
----   DATE5         CHAR(17) NULL,
--    '',
----   DATE6         CHAR(17) NULL,
--    '',
----   DATE7         CHAR(17) NULL,
--    '',
----   DATE8         CHAR(17) NULL,
--    '',
----   DATE9         CHAR(17) NULL,
--    '',
----   DATE10         CHAR(17) NULL,
--    '',
----   NUMBER1         CHAR(38) NULL,
--    '',
----   NUMBER2         CHAR(38) NULL,
--    '',
----   NUMBER3         CHAR(38) NULL,
--    '',
----   NUMBER4         CHAR(38) NULL,
--    '',
----   NUMBER5         CHAR(38) NULL,
--    '',
----   NUMBER6         CHAR(38) NULL,
--    '',
----   NUMBER7         CHAR(38) NULL,
--    '',
----   NUMBER8         CHAR(38) NULL,
--    '',
----   NUMBER9         CHAR(38) NULL,
--    '',
----   NUMBER10         CHAR(38) NULL,
--    '',
----   DECIMAL1         CHAR(25) NULL,
--    '',
----   DECIMAL2         CHAR(25) NULL,
--    '',
----   DECIMAL3         CHAR(25) NULL,
--    '',
----   DECIMAL4         CHAR(25) NULL,
--    '',
----   DECIMAL5         CHAR(25) NULL,
--    '',
----   DECIMAL6         CHAR(25) NULL,
--    '',
----   DECIMAL7         CHAR(25) NULL,
--    '',
----   DECIMAL8         CHAR(25) NULL,
--    '',
----   DECIMAL9         CHAR(25) NULL,
--    '',
----   DECIMAL10         CHAR(25) NULL,
--    '',
----   ENTITYTYPE         CHAR(50) NULL,
--    --'CORPORATE',
--    '',--chanegd on 17-01-2016
----   STR43         CHAR(50) NULL,
--    '',
----   STR44         CHAR(50) NULL,
--    '',
----   STR45         CHAR(50) NULL,
--    '',
----   STR46         CHAR(50) NULL,
--    '',
----   STR47         CHAR(50) NULL,
--    '',
----   STR48         CHAR(50) NULL,
--    '',
----   STR49         CHAR(50) NULL,
--    '',
----   STR50         CHAR(50) NULL,
--    '',
----   ORG_KEY         CHAR(50) NULL,
--    CORP_KEY,
----   STR21         CHAR(50) NULL,
--    '',
----   STR22         CHAR(50) NULL,
--    '',
----   STR23         CHAR(50) NULL,
--    '',
----   STR24         CHAR(50) NULL,
--    '',
----   STR25         CHAR(50) NULL,
--    '',
----   STR26         CHAR(50) NULL,
--    '',
----   STR27         CHAR(50) NULL,
--    '',
----   STR28         CHAR(1) NULL,
--    '',
----   STR29         CHAR(1) NULL,
--    '',
----   STR30         CHAR(1) NULL,
--    '',
----   STR31         CHAR(1) NULL,
--    '',
----   STR32         CHAR(1) NULL,
--    '',
----   STR38         CHAR(200) NULL,
--    '',
----   STR39         CHAR(200) NULL,
--    '',
----   STR40         CHAR(200) NULL,
--    '',
----   STR41         CHAR(200) NULL,
--    '',
----   STR42         CHAR(200) NULL,
--    '',
----   DBFLOAT1         CHAR(99) NULL,
--    '',
----   DBFLOAT2         CHAR(99) NULL,
--    '',
----   DBFLOAT3         CHAR(99) NULL,
--    '',
----   DBFLOAT4         CHAR(99) NULL,
--    '',
----   DBFLOAT5         CHAR(99) NULL,
--    '',
----   AMOUNT5         CHAR(20) NULL,
--    '',
----   FLAG1         CHAR(10) NULL,
--    '',
----   FLAG2         CHAR(10) NULL,
--    '',
----   FLAG3         CHAR(10) NULL,
--    '',
----   FLAG4         CHAR(10) NULL,
--    '',
----   FLAG5         CHAR(10) NULL,
--    '',
---- INT1             CHAR(38) NULL,
--    '',
---- INT2             CHAR(38) NULL,
--    '',
---- INT3             CHAR(38) NULL,
--    '',
---- INT4             CHAR(38) NULL,
--    '',
---- INT5             CHAR(38) NULL,
--    '',
---- INT6             CHAR(38) NULL,
--    '',
---- INT7             CHAR(38) NULL,
--    '',
---- INT8             CHAR(38) NULL,
--    '',
---- INT9             CHAR(38) NULL,
--    '',
----   INT10         CHAR(38) NULL,
--    '',
----   INT11         CHAR(38) NULL,
--    '',
----   INT12         CHAR(38) NULL,
--    '',
----   INT13         CHAR(38) NULL,
--    '',
----   INT14         CHAR(38) NULL,
--    '',
----   INT15         CHAR(38) NULL,
--    '',
---- MLUSERFIELD1         CHAR(80) NULL,
--    '',
---- MLUSERFIELD2         CHAR(80) NULL,
--    '',
---- MLUSERFIELD3         CHAR(80) NULL,
--    '',
---- MLUSERFIELD4         CHAR(80) NULL,
--    '',
---- MLUSERFIELD5         CHAR(80) NULL,
--    '',
----   STR1_CODE         CHAR(5) NULL,
--    '',
----   STR2_CODE         CHAR(5) NULL,
--    '',
----   STR3_CODE         CHAR(5) NULL,
--    '',
----   STR4_CODE         CHAR(5) NULL,
--    '',
----   STR5_CODE         CHAR(5) NULL,
--    '',
---- CORE_CUST_ID         CHAR(9) NULL,
--    '',
----   CORE_CHILD_CUST_ID     CHAR(9) NULL,
--    '',
---- PERCENTAGE1         CHAR(9) NULL,
--    '0',
---- PERCENTAGE2         CHAR(9) NULL,
--    '0',
---- PERCENTAGE3         CHAR(9) NULL,
--    '0',
---- PERCENTAGE4         CHAR(9) NULL,
--    '',
---- PERCENTAGE5         CHAR(9) NULL,
--    '',
----   BANK_ID         CHAR(8) NULL,
--    get_param('BANK_ID'),
----   STR4_ALT1         CHAR(99) NULL,
--    '',
----   STR4_ALT2         CHAR(99) NULL,
--    '',
----   STR4_ALT3         CHAR(99) NULL
--    ''
--from CU1corp_O_TABLE a where not exists(select  distinct corp_key from CU5corp_O_TABLE b where a.corp_key=b.corp_key );
--commit;
----added LBP,MAD,PHP & SEK based on discussion with Vijay--
--delete from CU5CORP_O_TABLE where  STR1 in('ATS','BEF','DEM','ESP','FRF','ITL','NLG','DKK','HKD','MYR','NOK''LBP','MAD','PHP','SEK'); 
--commit;
exit; 
