

drop table hmpf_mig;
create table hmpf_mig as
select HMCNA, HMGRP, nvl(trim(HMCUS),TRIM(GFCUS)) HMCUS, nvl(trim(HMCLC),TRIM(GFCLC)) HMCLC,TRIM(HMLC)HMLC, HMCCY, HMMDT, HMSEQ, HMYGUA, HMYE, HMYOVD, HMEXPM, HMAMT, HMGCCY, HMXDT, HMGTP, HMGPC from hmpf
left JOIN GFPF ON TRIM(HmGRP) = TRIM(GFGRP);
DROP TABLE HNPF_MAX_SEQ;
CREATE TABLE HNPF_MAX_SEQ AS
SELECT TRIM(HNAB) HNAB,TRIM(HNAN) HNAN,TRIM(HNAS) HNAS,MAX(TO_NUMBER(TRIM(HNSEQ))) HNSEQ FROM HMPF_MIG HM 
INNER JOIN HNPF HN ON TRIM(HM.HMSEQ)=TRIM(HN.HNSEQ)
GROUP BY TRIM(HNAB),TRIM(HNAN),TRIM(HNAS);
CREATE INDEX HMPF_MIG_IDX1 ON HMPF_MIG(HMCLC||HMCUS);
CREATE INDEX HMPF_MIG_ID21 ON HMPF_MIG( HMLC);
create index HNPF_MIG_HNSEQ_IDX on HNPF_MAX_SEQ(HNSEQ);
create index  limit_core_temp_idx on LIMIT_CORE_TEMP_TABLE(LIMIT_PREFIX,LIMIT_SUFFIX);
create index  limit_core_idx on LIMIT_CORE_O_TABLE(LIMIT_PREFIX,LIMIT_SUFFIX);
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('MIGAPPKW','HMPF_MIG',CASCADE=>TRUE);
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('MIGAPPKW','MAP_ACC',CASCADE=>TRUE);
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('MIGAPPKW','HNPF_MAX_SEQ',CASCADE=>TRUE);


truncate table LIMIT_LINKAGE_TO_ACCT_O_TABLE;
DROP TABLE LIMIT_LINK_TEMP;


CREATE TABLE LIMIT_LINK_TEMP AS
select DISTINCT LT.LIMIT_PREFIX,LT.LIMIT_SUFFIX,
SANCTION_LIMIT LIMIT_AMOUNT,CRNCY_CODE LIMIT_CCY, HN.HNAB||HN.HNAN||HN.HNAS ACCT_NUM,LT.LIMIT_EXPIRY_DATE
FROM HNPF_MAX_SEQ HN
inner join HMPF_MIG  HM ON trim(hmseq) = trim(hnseq)
INNER JOIN MAP_CIF ON  gfclc||gfcus =  hmclc||hmcus
INNER JOIN (SELECT DISTINCT LIMIT_CAT,LIMIT_PREFIX,LIMIT_SUFFIX,NODE_LEVEL,LIMIT_EXPIRY_DATE,SANCTION_LIMIT,CRNCY_CODE FROM LIMIT_CORE_TEMP_TABLE WHERE NODE_LEVEL='7' AND TRIM(limit_suffix) NOT in ('GEODR','GEVOD') ) LT 
ON fin_cif_id=lt.LIMIT_PREFIX AND LIMIT_CAT = hmlc
WHERE  TRIM(LT.limit_suffix) NOT in ('GEODR','GEVOD') AND  LT.NODE_LEVEL='7';


INSERT INTO LIMIT_LINKAGE_TO_ACCT_O_TABLE 
SELECT LIMIT_PREFIX, LIMIT_SUFFIX, LIMIT_AMOUNT, LIMIT_CCY, MAP_ACC.FIN_ACC_NUM ACCT_NUM, LIMIT_EXPIRY_DATE FROM LIMIT_LINK_TEMP A
INNER JOIN MAP_ACC ON LEG_BRANCH_ID||LEG_SCAN||LEG_SCAS = ACCT_NUM and SCHM_TYPE not in('CAA','OOO','ODA');


INSERT INTO LIMIT_LINKAGE_TO_ACCT_O_TABLE 
select DISTINCT LOT.LIMIT_PREFIX,LOT.LIMIT_SUFFIX,
LOT.SANCTION_LIMIT LIMIT_AMOUNT,CRNCY_CODE LIMIT_CCY, MAP_ACC.FIN_ACC_NUM ACCT_NUM,LOT.LIMIT_EXPIRY_DATE 
from MAP_ACC 
left join LIMIT_CORE_O_TABLE LOT on FIN_CIF_ID = borrower_name and limit_suffix in ('GEODR','GEVOD')
where SCHM_TYPE='ODA' and borrower_name is not null; 


delete from LIMIT_LINKAGE_TO_ACCT_O_TABLE where trim(ACCT_NUM) is null;
commit;

delete from LIMIT_LINKAGE_TO_ACCT_O_TABLE where rowid not in(
select a.rowid row_id from LIMIT_LINKAGE_TO_ACCT_O_TABLE a
inner join map_acc b on a.LIMIT_PREFIX = b.fin_cif_id and a.ACCT_NUM = b.FIN_ACC_NUM
);


commit;
DROP index  limit_core_temp_idx ;
DROP index  limit_core_idx ;



--SELECT SANCT_LIMIT_LINK_ACCNT.*,SCODL/C8PWD FROM SANCT_LIMIT_LINK_ACCNT
--INNER JOIN MAP_ACC ON TRIM(FIN_ACC_NUM) = TRIM(FORACID)
--INNER JOIN SCPF ON SCAB||SCAN||SCAS = LEG_BRANCH_ID||LEG_SCAN||LEG_SCAS 
--LEFT JOIN C8PF ON C8CCY = SCCCY
--WHERE SANCT_LIM != ABS(SCODL/C8PWD) AND  ABS(SCODL/C8PWD)<>0 
  

delete from LIMIT_LINKAGE_TO_ACCT_O_TABLE where ( LIMIT_PREFIX,LIMIT_SUFFIX ) in(
select distinct c.limit_prefix,c.limit_suffix from COMMITMENT_LIMIT_DATA a
inner join LIMIT_CORE_O_TABLE_CLA b on FIN_CIF_ID =b.limit_prefix  and a.LIMIT_SUFFIX=b.LIMIT_SUFFIX
inner join LIMIT_CORE_temp_TABLE c on FIN_CIF_ID = c.PARENT_LIMIT_PREFIX and c. PARENT_LIMIT_SUFFIX = a.PARENT_LIMIT_SUFFIX
where trim(FIN_ACC_NUM) is not null
);

commit;

insert into LIMIT_LINKAGE_TO_ACCT_O_TABLE
select distinct b.LIMIT_PREFIX, b.LIMIT_SUFFIX, b.SANCTION_LIMIT LIMIT_AMOUNT, b.CRNCY_CODE  LIMIT_CCY, FIN_ACC_NUM ACCT_NUM, b.LIMIT_EXPIRY_DATE LIMIT_EXPIRY_DATE from COMMITMENT_LIMIT_DATA a
inner join LIMIT_CORE_O_TABLE_CLA b on b.LIMIT_PREFIX=a.FIN_CIF_ID and a.LIMIT_SUFFIX=b.LIMIT_SUFFIX
inner join LIMIT_CORE_INFY_TABLE c on  c.LIMIT_PREFIX=a.FIN_CIF_ID and a.LIMIT_SUFFIX=c.LIMIT_SUFFIX
where trim(FIN_ACC_NUM) is not null;
commit;



update LIMIT_LINKAGE_TO_ACCT_O_TABLE set limit_suffix='GLLF0' where limit_suffix='GELLF';
update LIMIT_LINKAGE_TO_ACCT_O_TABLE set limit_suffix='GLLH0' where limit_suffix='GELLH';
update LIMIT_LINKAGE_TO_ACCT_O_TABLE set limit_suffix='GRVF0' where limit_suffix='GERVF';
update LIMIT_LINKAGE_TO_ACCT_O_TABLE set limit_suffix='GRVH0' where limit_suffix='GERVH';
update LIMIT_LINKAGE_TO_ACCT_O_TABLE set limit_suffix='GTLF0' where limit_suffix='GETLF';
update LIMIT_LINKAGE_TO_ACCT_O_TABLE set limit_suffix='GTLH0' where limit_suffix='GETLH';
update LIMIT_LINKAGE_TO_ACCT_O_TABLE set limit_suffix='SYLH0' where limit_suffix='SYLHC';
update LIMIT_LINKAGE_TO_ACCT_O_TABLE set limit_suffix='SYLF0' where limit_suffix='SYLFC';
commit;  

delete LIMIT_LINKAGE_TO_ACCT_O_TABLE where (LIMIT_PREFIX,LIMIT_SUFFIX) not in(select LIMIT_PREFIX,LIMIT_SUFFIX from LIMIT_CORE_INFY_TABLE);
commit;

truncate table SANCT_LIMIT_LINK_ACCNT;

INSERT INTO SANCT_LIMIT_LINK_ACCNT

SELECT ACCT_NUM FORACID,
       TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') LIMITAPPDATE,
       ROWNUM SRL_NUM,
       '0' UPLOAD_STATUS,
       CURRENCY CRNCY_CODE,
        LIMIT_AMOUNT*(C8A.C8SPT/C8B.C8SPT) SANCT_LIM,
       '99999999999' MAXALLWDLIMIT,
       TO_DATE(LIMIT_EXPIRY_DATE,'DD-MM-YYYY') EXPDATE,
       TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') SANCTDATE,
       TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY') DOCDATE
  FROM LIMIT_LINKAGE_TO_ACCT_O_TABLE
  INNER JOIN MAP_ACC ON TRIM(FIN_ACC_NUM) = TRIM(ACCT_NUM) 
  LEFT JOIN C8PF C8A ON TRIM(C8A.C8CCY) = TRIM(LIMIT_CCY)
  LEFT JOIN C8PF C8B ON TRIM(C8B.C8CCY) = TRIM(CURRENCY);

  commit;
  
exit; 
