load data
truncate into table rep_LOMBARD
fields terminated by '|'
TRAILING NULLCOLS
(
SECU_LINKAGE_TYPE,
SECU_SRL_NUM,
BANK_ID,
ENTITY_CRE_FLG,
DEL_FLG,
FREE_FIELD1,
FREE_FIELD2,
FREE_FIELD3,
FREE_FIELD4,
COLL_PROVIDERNO,
TICKER_ISIN,
ALLOTTED_QTY,
SECURITY_VALUE,
COLLATERAL_TYPE_VALUE 
)