CREATE OR REPLACE VIEW PR_ESSENCE_CUST_VOLUME ("TABLE_NAME", "RECORD_COUNT") AS
SELECT 'O_PARTY_COMMON', COUNT(1) FROM O_PARTY_COMMON
UNION
SELECT 'O_PARTY_PERSON_DETAILS', COUNT(1) FROM O_PARTY_PERSON_DETAILS;

