Truncate TABLE E_BANKING_USER_O_TABLE;
Truncate TABLE BANK_DETAILS_O_TABLE;
Truncate TABLE BANK_MASTER_O_TABLE;
Truncate TABLE BANK_ROUTING_O_TABLE;
Truncate TABLE CUSTOMER_PAYEE_O_TABLE;
Truncate TABLE PAYEE_MASTER_O_TABLE; 
Exit;

