Truncate table cl001_o_table;
Truncate table cl002_o_table;
Truncate table cl003_o_table;
Truncate table cl004_o_table
Truncate table cl005_o_table;
Truncate table cl006_o_table;
Truncate table cl007_o_table;
Truncate table cl008_o_table;
Truncate table cl009_o_table;
Truncate table cl010_o_table;
Truncate table cl011_o_table;
Truncate table cl012_o_table;
Truncate table cl013_o_table;
Truncate table cl014_o_table;
Truncate table cl015_o_table;
Truncate table cl016_o_table;
Truncate table AC1SBCA_O_TABLE;
Truncate table AC1ODCC_O_TABLE;
Truncate table AC2_O_TABLE;
Truncate table AC_BALANCE_O_TABLE;
Truncate table CBS_O_TABLE;
Truncate table SPT_O_TABLE;
Truncate table LIEN_O_TABLE;
Truncate table CARDDETAILS_O_TABLE;
Truncate table CARDHOT_O_TABLE;
Truncate table CARDLINKAGE_O_TABLE;
Truncate table COL_DEP_O_TABLE;
Truncate table COL_G_O_TABLE;
Truncate table COL_MACH_O_TABLE;
Truncate table COL_OTHERS_O_TABLE;
Truncate TABLE COL_TRADEABLE_O_TABLE;
Truncate TABLE COL_IP_RE_O_TABLE;
Truncate table CU1CORP_O_TABLE;
Truncate table CU2CORP_O_TABLE;
Truncate table CU5CORP_O_TABLE;
Truncate table CU7CORP_O_TABLE;
Truncate table CU8CORP_O_TABLE;
Truncate table MEMOPAD_O_TABLE;
Truncate table SIU_O_TABLE;
Truncate table DDS_O_TABLE;
Truncate table CU1_O_TABLE;
Truncate table CU2_O_TABLE;
Truncate table CU3_O_TABLE;
Truncate table CU4_O_TABLE;
Truncate table CU5_O_TABLE;
Truncate table CU6_O_TABLE;
Truncate table CU8_O_TABLE;
Truncate table cu9_O_TABLE;
Truncate table LAINT_O_TABLE;
Truncate table LAM_O_TABLE;
Truncate table LAT1_O_TABLE;
Truncate table LAT_O_TABLE;
Truncate table LDT_O_TABLE;
Truncate table LRS_O_TABLE;
Truncate table TDINTEREST_O_TABLE;
Truncate TABLE TDA_O_TABLE;
Truncate table TDT_O_TABLE;
Truncate table TTUM1_O_TABLE;
Truncate table TTUM2_O_TABLE;
Truncate table TTUM3_O_TABLE;
Truncate table CUSTOM_EAB_O_TABLE;
Truncate TABLE BO_O_TABLE;
Truncate table SIU_CCCY_O_TABLE;
Truncate table BO_CCCY_O_TABLE;
Truncate table CUSTOM_CCPOS01_O_TABLE;
Truncate table CUSTOM_CCUNLIN01_O_TABLE;
Truncate table CUSTOM_CCSTAT01_O_TABLE;
Truncate table CUSTOM_CCHOT01_O_TABLE;
Truncate table ACCOUNT_LABEL_O_TABLE;
Truncate table ACCOUNT_FAX_HELD_O_TABLE;
Truncate table SIU_TT_O_TABLE;
Truncate table custom_pool_payout_o_table;
Truncate table COL_OTHERS_INS_O_TABLE;
Truncate table col_ins_o_table;
Truncate table KYCR01_O_TABLE;
Truncate table KYCC02_o_table;
Truncate table KYC03_O_TABLE;
Truncate table KYC04_O_TABLE;
Truncate table KYC05_O_TABLE;
Truncate table KYC06_O_TABLE;
Truncate table KYC07_O_TABLE;
Truncate table KYC08_O_TABLE;
Truncate table KYC09_O_TABLE;
Truncate table CUSTOM_LOCKERS_O_TABLE;
Truncate table CUSTOM_CFR001_O_TABLE ;
Truncate table CUSTOM_CFR002_O_TABLE  ;
Truncate table custom_cfr003_o_table  ;
Truncate table custom_cfr004_o_table  ;
Truncate table custom_cfr005_o_table  ;
Truncate table custom_cfr006_o_table  ;
Truncate table custom_cfr007_o_table  ;
Truncate table custom_cfr008_o_table  ;
Truncate table custom_cfr009_o_table  ;
Truncate table custom_cfr010_o_table  ;
Truncate table custom_cfr011_o_table  ;
Truncate table custom_cfr012_o_table  ;
Truncate table custom_cfr013_o_table  ;
Truncate table custom_cfr014_o_table  ;
Truncate table custom_cfr015_o_table  ;
Truncate table custom_cfr016_o_table  ;
Truncate table CUSTOM_CFR017_O_TABLE ;
Truncate table CUSTOM_COL_LINKAGE_O_TABLE;
Truncate table CUSTOM_COL_LOMBARD_O_TABLE ;
Truncate table CUSTOM_COL_GUARANTEE_O_TABLE  ;
Truncate table CUSTOM_COL_SECU_O_TABLE  ;
Truncate table custom_col_ins_company_o_table  ;
Truncate table custom_col_valuator_o_table  ;
Truncate table custom_Col_Advent_o_table  ;
Truncate table custom_Col_eifb_o_table  ;
Truncate table CUSTOM_CFR016_O_TABLE;
Truncate table TUAT_O_TABLE;
Truncate table CUSTOM_SKYWARDS_O_TABLE;
Truncate table CUSTOM_ACCURED_CHARGES_O_TABLE;
Truncate table PDC_O_TABLE;
Truncate TABLE TTUM4_O_TABLE;
Truncate table custom_sweeps_o_table;
Truncate table custom_lcu001_o_table;
Truncate table custom_ltu001_o_table;
Truncate table custom_lnu001_o_table;
Truncate table custom_lku001_o_table;
Truncate table TEST_EIDEM_SUM;
Truncate table CUSTOM_SEGMENT_HIS_O_TABLE;
Truncate table CREDIT_CARD_CIF_O_TABLE;
Truncate table credit_card_dd_o_table;
Truncate table CUSTOM_OPERATION_REASON_CODES;
Truncate table CHEQUE_PROCESSED;
Truncate table CHEQUE_UNUSED;
Truncate table CUSTOM_NOMINATED_ACCT;
Truncate TABLE CUSTOM_POOL_O_TABLE;
Truncate table CU9CORP_O_TABLE;
Truncate table custom_htd_o_TABLE;
Truncate table custom_mt950;
Truncate table advance_int_o_table;
Truncate table corp_sch_detl;
Truncate table custom_C_GAC_EXT;
exit;
