set head off
set feedback off
set term off
set linesize 5000
set page size 0
set pages 0
set trimspool on
spool $MIG_PATH/output/finacle/collateral/COL_IP_RE.txt
select 
TRIM(COL_TYPE) ||'|'||
TRIM(COL_CODE) ||'|'||
TRIM(CEILING_LIMIT) ||'|'||
TRIM(COL_CLASS) ||'|'||
TRIM(COL_GROUP) ||'|'||
TRIM(MARGIN) ||'|'||
TRIM(LTV_PCNT) ||'|'||
TRIM(DR_ACC_FOR_FEES) ||'|'||
TRIM(LAST_VALUATION_DT) ||'|'||
TRIM(REASON_CODE) ||'|'||
TRIM(NATURE_OF_CHARGE) ||'|'||
TRIM(THIRD_PARTY_LIEN_VALUE) ||'|'||
TRIM(DERIVE_VALUE_FROM) ||'|'||
TRIM(ASSESSED_VALUE) ||'|'||
TRIM(INVOICE_VALUE) ||'|'||
TRIM(MARKET_VALUE) ||'|'||
TRIM(WRITTEN_DOWN_VALUE) ||'|'||
TRIM(APPORTIONED_VALUE) ||'|'||
TRIM(COLLATERAL_VALUE) ||'|'||
TRIM(PROPERTY_DOCUMENT_NO) ||'|'||
TRIM(LODGED_DATE) ||'|'||
TRIM(REVIEW_DATE) ||'|'||
TRIM(RECEIVED_DATE) ||'|'||
TRIM(DUE_DATE) ||'|'||
TRIM(DATE_OF_PURCHASE) ||'|'||
TRIM(BUILT_AREA) ||'|'||
TRIM(UNIT_OF_MEASUREMENT_1) ||'|'||
TRIM(LAND_AREA) ||'|'||
TRIM(UNIT_OF_MEASUREMENT_2) ||'|'||
TRIM(BUILDER_NAME) ||'|'||
TRIM(PROPERTY_RATING) ||'|'||
TRIM(YEAR_OF_CONSTRUCTION) ||'|'||
TRIM(ADDRESSLINE_1) ||'|'||
TRIM(ADDRESSLINE_2) ||'|'||
TRIM(CITY_CODE_1) ||'|'||
TRIM(STATE_CODE_1) ||'|'||
TRIM(COUNTRY_CODE_1) ||'|'||
TRIM(PIN_CODE) ||'|'||
TRIM(PROPERTY_OWNER) ||'|'||
TRIM(LEASED) ||'|'||
TRIM(LEASE_EXPIRY_DATE) ||'|'||
TRIM(CIF_ID) ||'|'||
TRIM(AGE_OF_BUILDING) ||'|'||
TRIM(NOTES0) ||'|'||
TRIM(INSPECTION_TYPE) ||'|'||
TRIM(ADDRESS_LINE1) ||'|'||
TRIM(ADDRESS_LINE2) ||'|'||
TRIM(CITY_CODE_2) ||'|'||
TRIM(STATE_CODE_2) ||'|'||
TRIM(ZIP_CODE_2) ||'|'||
TRIM(TELEPHONE_NUMBER) ||'|'||
TRIM(DATE_OF_VISIT) ||'|'||
TRIM(DUE_DATE_OF_VISIT) ||'|'||
TRIM(INSPECTED_VALUE) ||'|'||
TRIM(INSPECTED_EMP_ID) ||'|'||
TRIM(NOTES1) ||'|'||
TRIM(NOTES2) ||'|'||
TRIM(DUMMY_FIELD) ||'|'||
TRIM(INSURANCE_TYPE) ||'|'||
TRIM(INSURER_DETAILS) ||'|'||
TRIM(INSURANCE_POLICY_NUMBER) ||'|'||
TRIM(INSURANCE_POLICY_AMOUNT) ||'|'||
TRIM(RISK_COVER_START_DATE) ||'|'||
TRIM(RISK_COVER_END_DATE) ||'|'||
TRIM(LAST_PREMIUM_PAID_DATE) ||'|'||
TRIM(PREMIUM_AMOUNT) ||'|'||
TRIM(FREQUENCY_OF_THE_STATEMENT) ||'|'||
TRIM(ITEMS_INSURED) ||'|'||--ITEMS_INSURED
TRIM(NOTES) ||'|'||
TRIM(COLLATERAL_STATUS) ||'|'||
TRIM(LINKAGE_TYPE) ||'|'||
TRIM(ACCOUNT_TO_BE_LINKED) ||'|'||
TRIM(LIMIT_PREFIX) ||'|'||
TRIM(LIMIT_SUFFIX) ||'|'||
TRIM(SERIAL_NUMBER) ||'|'|| 
TRIM(FORACID_COLL_VALUE) ||'|'||
TRIM(CC_FINONE_ACCNT) ||'|'||
TRIM(SERIAL_NUMBER) ||'|'||
TRIM(UPLOAD_STATUS) ||'|'||
TRIM(get_param('BANK_ID'))
from COL_IP_RE_O_TABLE;
exit;
 
