CREATE OR REPLACE VIEW PROFILE_EQ3_CUSTOMER_CASA_VOLUME ("TABLE_NAME", "RECORD_COUNT") AS
SELECT "GFPF", COUNT(1) FROM GFPF
UNION
SELECT "SCPF", COUNT(1) FROM SCPF
UNION
SELECT "C8PF", COUNT(1) FROM C8PF
UNION
SELECT "S5PF", COUNT(1) FROM S5PF
UNION
SELECT "C5PF", COUNT(1) FROM C5PF
UNION
SELECT "SX20LF", COUNT(1) FROM SX20LF
UNION
SELECT "SVPF", COUNT(1) FROM SCPF
/

