-- File Name		: cu1crop.sql
-- File Created for	: Creation of source table
-- Created By		: Kumaresan.B
-- Client		    : Emirates Islamic Bank
-- Created On		: 26-05-2015
-------------------------------------------------------------------
set head off
set feedback off
set term off
set lines 1100
set page size 0
set pages 0
set trimspool on
spool $MIG_PATH/output/finacle/cifkw/CC001.txt
select
trim(CORP_KEY)||'|'||
trim(ENTITY_TYPE)||'|'||
trim(CORPORATENAME_NATIVE)||'|'||
trim(RELATIONSHIP_STARTDATE)||'|'||
trim(STATUS)||'|'||
trim(LEGALENTITY_TYPE)||'|'||
trim(SEGMENT)||'|'||
trim(SUBSEGMENT)||'|'||
trim(WEBSITE_ADDRESS)||'|'||
trim(KEYCONTACT_PERSONNAME)||'|'||
trim(PHONECITYCODE)||'|'||
trim(PHONELOCALCODE)||'|'||
trim(PHONECOUNTRYCODE)||'|'||
trim(NOTES)||'|'||
trim(PRINCIPLE_PLACEOPERATION)||'|'||
trim(BUSINESS_GROUP)||'|'||
trim(PRIMARYRM_ID)||'|'||
trim(DATE_OF_INCORPORATION)||'|'||
trim(DATE_OF_COMMENCEMENT)||'|'||
trim(PRIMARY_SERVICE_CENTER)||'|'||
trim(RELATIONSHIP_CREATEDBY)||'|'||
trim(SECTOR_CODE)||'|'||
trim(SUBSECTOR_CODE)||'|'||
trim(TAXID)||'|'||
trim(ENTITYCLASS)||'|'||
trim(AVERAGE_ANNUALINCOME)||'|'||
trim(SOURCE_OF_FUNDS)||'|'||
trim(GROUP_ID)||'|'||
trim(GROUP_ID_CODE)||'|'||
trim(PARENT_CIF)||'|'||
trim(CUSTOMER_RATING_CODE)||'|'||
trim(HEALTH_CODE)||'|'||
trim(RECORD_STATUS)||'|'||
trim(EFFECTIVE_DATE)||'|'||
trim(LINE_OF_ACTIVITY_DESC)||'|'||
trim(CUST_MGR_OPIN)||'|'||
trim(CUST_TYPE_DESC)||'|'||
trim(CUST_STAT_CHG_DATE)||'|'||
trim(TDS_TBL_DESC)||'|'||
trim(CUST_SWIFT_CODE)||'|'||
trim(IS_SWIFT_CODE_OF_BANK)||'|'||
trim(CUSTDEPOSITSINOTHERBANKS)||'|'||
trim(TOTALFUNDBASE)||'|'||
trim(TOTALNONFUNDBASE)||'|'||
trim(ADVANCEASONDATE)||'|'||
trim(CUST_CONST)||'|'||
trim(DOCUMENT_RECEIVED_FLAG)||'|'||
trim(CRNCY_CODE_CORPORATE)||'|'||
trim(TRADE_SERVICES_AVAILED)||'|'||
trim(PRIMARYSOLID)||'|'||
trim(CHRG_DR_FORACID)||'|'||
trim(CHRG_DR_SOL_ID)||'|'||
trim(CUST_CHRG_HISTORY_FLG)||'|'||
trim(TOT_TOD_ALWD_TIMES)||'|'||
trim(SMALL_STR1)||'|'||
trim(SMALL_STR2)||'|'||
trim(SMALL_STR3)||'|'||
trim(SMALL_STR4)||'|'||
trim(SMALL_STR5)||'|'||
trim(SMALL_STR6)||'|'||
trim(SMALL_STR7)||'|'||
trim(SMALL_STR8)||'|'||
trim(SMALL_STR9)||'|'||
trim(SMALL_STR10)||'|'||
trim(MED_STR1)||'|'||
trim(MED_STR2)||'|'||
trim(MED_STR3)||'|'||
trim(MED_STR4)||'|'||
trim(MED_STR5)||'|'||
trim(MED_STR6)||'|'||
trim(MED_STR7)||'|'||
trim(MED_STR8)||'|'||
trim(MED_STR9)||'|'||
trim(MED_STR10)||'|'||
trim(LARGE_STR1)||'|'||
trim(LARGE_STR2)||'|'||
trim(LARGE_STR3)||'|'||
trim(LARGE_STR4)||'|'||
trim(LARGE_STR5)||'|'||
trim(DATE1)||'|'||
trim(DATE2)||'|'||
trim(DATE3)||'|'||
trim(DATE4)||'|'||
trim(DATE5)||'|'||
trim(DATE6)||'|'||
trim(DATE7)||'|'||
trim(DATE8)||'|'||
trim(DATE9)||'|'||
trim(DATE10)||'|'||
trim(NUMBER1)||'|'||
trim(NUMBER2	)||'|'||
trim(NUMBER3)||'|'||
trim(NUMBER4)||'|'||
trim(NUMBER5)||'|'||
trim(NUMBER6)||'|'||
trim(NUMBER7)||'|'||
trim(NUMBER8)||'|'||
trim(NUMBER9)||'|'||
trim(NUMBER10)||'|'||
trim(DECIMAL1)||'|'||
trim(DECIMAL2)||'|'||
trim(DECIMAL3)||'|'||
trim(DECIMAL4)||'|'||
trim(DECIMAL5)||'|'||
trim(DECIMAL6)||'|'||
trim(DECIMAL7)||'|'||
trim(DECIMAL8)||'|'||
trim(DECIMAL9)||'|'||
trim(DECIMAL10)||'|'||
trim(CORE_CUST_ID)||'|'||
trim(CIFID)||'|'||
trim(CREATEDBYSYSTEMID)||'|'||
trim(CORPORATENAME_NATIVE1)||'|'||
trim(SHORT_NAME_NATIVE1)||'|'||
trim(OWNERAGENT)||'|'||
trim(PRIMARYRMLOGIN_ID)||'|'||
trim(SecondRMLogin_ID)||'|'||
trim(TERTIARYRMLOGIN_ID)||'|'||
trim(ACCESSOWNERGROUP)||'|'||
trim(ACCESSOWNERSEGMENT)||'|'||
trim(ACCESSOWNERBC)||'|'||
trim(ACCESSOWNERAGENT)||'|'||
trim(ACCESSASSIGNEEAGENT)||'|'||
trim(PRIMARYPARENTCOMPANY)||'|'||
trim(COUNTRYOFPRINCIPALOPERATION)||'|'||
trim(PARENTCIF_ID)||'|'||
trim(CHARGELEVELCODE)||'|'||
trim(COUNTRYOFORIGIN)||'|'||
trim(COUNTRYOFINCORPORATION)||'|'||
trim(INTUSERFIELD1)||'|'||
trim(INTUSERFIELD2)||'|'||
trim(INTUSERFIELD3)||'|'||
trim(INTUSERFIELD4)||'|'||
trim(INTUSERFIELD5)||'|'||
trim(StrUserField1)||'|'||
trim(StrUserField2)||'|'||
trim(StrUserField3)||'|'||
trim(StrUserField4)||'|'||
trim(StrUserField5)||'|'||
trim(StrUserField6)||'|'||
trim(StrUserField7)||'|'||
trim(StrUserField8)||'|'||
trim(StrUserField9)||'|'||
trim(StrUserField10)||'|'||
trim(StrUserField11)||'|'||
trim(StrUserField12)||'|'||
trim(StrUserField13)||'|'||
trim(StrUserField14)||'|'||
trim(StrUserField15)||'|'||
trim(StrUserField16)||'|'||
trim(StrUserField17)||'|'||
trim(StrUserField18)||'|'||
trim(StrUserField19)||'|'||
trim(StrUserField20)||'|'||
trim(StrUserField21)||'|'||
trim(StrUserField22)||'|'||
trim(StrUserField23)||'|'||
trim(StrUserField24)||'|'||
trim(StrUserField25)||'|'||
trim(StrUserField26)||'|'||
trim(StrUserField27)||'|'||
trim(StrUserField28)||'|'||
trim(StrUserField29)||'|'||
trim(StrUserField30)||'|'||
trim(DateUserField1)||'|'||
trim(DateUserField2)||'|'||
trim(DateUserField3)||'|'||
trim(DateUserField4)||'|'||
trim(DateUserField5)||'|'||
trim(NATIVELANGCODE)||'|'||
trim(CUST_HLTH)||'|'||
trim(LASTSUBMITTEDDATE)||'|'||
trim(RISK_PROFILE_SCORE)||'|'||
trim(RISK_PROFILE_EXPIRY_DATE)||'|'||
trim(OUTSTANDING_MORTAGE)||'|'||
trim(CORPORATE_NAME)||'|'||
trim(SHORT_NAME)||'|'||
trim(SHORT_NAME_NATIVE)||'|'||
trim(REGISTRATION_NUMBER)||'|'||
trim(CHANNELSACCESSED)||'|'||
trim(ZIP)||'|'||
trim(BACKENDID)||'|'||
trim(DELINQUENCYFLAG)||'|'||
trim(SUSPEND_FLAG)||'|'||
trim(SUSPEND_NOTES)||'|'||
trim(SUSPEND_REASON)||'|'||
trim(BLACKLIST_FLAG)||'|'||
trim(BLACKLIST_NOTES)||'|'||
trim(BLACKLIST_REASON)||'|'||
trim(NEGATIVE_FLAG)||'|'||
trim(NEGATIVE_NOTES)||'|'||
trim(NEGATIVE_REASON)||'|'||
trim(DSAID)||'|'||
trim(CUSTASSET_CLASSIFICATION)||'|'||
trim(CLASSIFIED_ON)||'|'||
trim(CUST_CREATION_MODE)||'|'||
trim(INCREMENTALDATEUPDATE)||'|'||
trim(LANG_CODE)||'|'||
trim(TDS_CUST_ID)||'|'||
trim(OTHERLIMITS)||'|'||
trim(CORE_INTROD_CUST_ID)||'|'||
trim(INTROD_NAME)||'|'||
trim(INTROD_STAT_CODE)||'|'||
trim(ENTITY_STAGE)||'|'||
trim(ENTITY_STEP_STATUS)||'|'||
trim(EMAIL2)||'|'||
trim(CUST_GRP)||'|'||
trim(CUST_CONST_CODE)||'|'||
trim(CUSTASSET_CLSFTION_CODE)||'|'||
trim(LEGALENTITY_TYPE_CODE)||'|'||
trim(REGION_CODE)||'|'||
trim(PRIORITY_CODE)||'|'||
trim(BUSINESS_TYPE_CODE)||'|'||
trim(RELATIONSHIP_TYPE_CODE)||'|'||
trim(CRNCY_CODE)||'|'||
trim(STR1)||'|'||
trim(STR2)||'|'||
trim(STR3)||'|'||
trim(STR4)||'|'||
trim(STR5)||'|'||
trim(STR6)||'|'||
trim(STR7)||'|'||
trim(STR8)||'|'||
trim(STR9)||'|'||
trim(STR10)||'|'||
trim(STR11)||'|'||
trim(STR12)||'|'||
trim(STR13)||'|'||
trim(STR14)||'|'||
trim(STR15)||'|'||
trim(AMOUNT1)||'|'||
trim(AMOUNT2)||'|'||
trim(AMOUNT3)||'|'||
trim(AMOUNT4)||'|'||
trim(AMOUNT5)||'|'||
trim(INT1)||'|'||
trim(INT2)||'|'||
trim(INT3)||'|'||
trim(INT4)||'|'||
trim(INT5)||'|'||
trim(Flag1)||'|'||
trim(Flag2)||'|'||
trim(Flag3)||'|'||
trim(Flag4)||'|'||
trim(Flag5)||'|'||
trim(MLUSERFIELD1)||'|'||
trim(MLUSERFIELD2)||'|'||
trim(MLUSERFIELD3)||'|'||
trim(MLUSERFIELD4)||'|'||
trim(MLUSERFIELD5)||'|'||
trim(MLUSERFIELD6)||'|'||
trim(MLUSERFIELD7)||'|'||
trim(MLUSERFIELD8)||'|'||
trim(MLUSERFIELD9)||'|'||
trim(MLUSERFIELD10)||'|'||
trim(UNIQUEGROUPFLAG)||'|'||
trim(BANK_ID)||'|'||
trim(ZAKAT_DEDUCTION)||'|'||
trim(ASSET_CLASSIFICATION)||'|'||
trim(CUSTOMER_LEVEL_PROVISIONING)||'|'||
trim(ISLAMIC_BANKING_CUSTOMER)||'|'||
trim(PREFERREDCALENDAR)||'|'||
trim(IDTYPEC1)||'|'||
trim(IDTYPEC2)||'|'||
trim(IDTYPEC3)||'|'||
trim(IDTYPEC4)||'|'||
trim(IDTYPEC5)||'|'||
trim(IDTYPEC6)||'|'||
trim(IDTYPEC7)||'|'||
trim(IDTYPEC8)||'|'||
trim(IDTYPEC9)||'|'||
trim(IDTYPEC10)||'|'||
trim(CORPORATE_NAME_ALT1)||'|'||
trim(short_Name_alt1)||'|'||
trim(KEYCONTACT_PERSONNAME_ALT1)||'|'||
trim(PARENT_CIF_ALT1)||'|'||
trim(BOCREATEDDBYLOGINID)||'|'||
trim(SUBMIT_FOR_KYC)||'|'||           
trim(KYC_REV_DATE)||'|'||              
trim(KYC_DATE)||'|'||                  
trim(RISKRATING)||'|'||                
trim(FATCA_REQUIRED)||'|'||            
trim(FORGN_TAX_REP_REQ_CUNTRY)||'|'||  
trim(FORGN_TAX_REP_REQ_STATUS)||'|'||  
trim(LAST_FORGN_TAX_REVW_DATE)||'|'||  
trim(NEXT_FORGN_TAX_REVW_DATE)||'|'||  
trim(TIN_EIN)||'|'||                   
trim(GIIN)||'|'||                      
trim(CUST_TYPE_CODE)||'|'||            
trim(PURGE_TEXT)
from CU1CORP_O_TABLE;
exit;
 
