-- File Name		: cu1crop.sql
-- File Created for	: Creation of source table
-- Created By		: Kumaresan.B
-- Client		    : Emirates Islamic Bank
-- Created On		: 26-05-2015
-------------------------------------------------------------------
set head off
set feedback off
set term off
set lines 800
set page size 0
set pages 0
set trimspool on
spool $MIG_PATH/output/finacle/cifkw/CC005.txt
select
trim(CORP_KEY)||'|'||
trim(CIF_ID)||'|'||
trim(CORP_REP_KEY)||'|'||
trim(TYPE)||'|'||
trim(STR1)||'|'||
trim(STR2)||'|'||
trim(STR3)||'|'||
trim(STR4)||'|'||
trim(STR5)||'|'||
trim(STR6)||'|'||
trim(STR7)||'|'||
trim(STR8)||'|'||
trim(STR9)||'|'||
trim(STR10)||'|'||
trim(STR11)||'|'||
trim(DATE1)||'|'||
trim(STR12)||'|'||
trim(DATE2)||'|'||
trim(AMOUNT1)||'|'||
trim(AMOUNT2)||'|'||
trim(AMOUNT3)||'|'||
trim(AMOUNT4)||'|'||
trim(SMALL_STR1)||'|'||
trim(SMALL_STR2)||'|'||
trim(SMALL_STR3)||'|'||
trim(SMALL_STR4)||'|'||
trim(SMALL_STR5)||'|'||
trim(SMALL_STR6)||'|'||
trim(SMALL_STR7)||'|'||
trim(SMALL_STR8)||'|'||
trim(SMALL_STR9)||'|'||
trim(SMALL_STR10)||'|'||
trim(MED_STR1)||'|'||
trim(MED_STR2)||'|'||
trim(MED_STR3)||'|'||
trim(MED_STR4)||'|'||
trim(MED_STR5)||'|'||
trim(MED_STR6)||'|'||
trim(MED_STR7)||'|'||
trim(MED_STR8)||'|'||
trim(MED_STR9)||'|'||
trim(MED_STR10)||'|'||
trim(LARGE_STR1)||'|'||
trim(LARGE_STR2)||'|'||
trim(LARGE_STR3)||'|'||
trim(LARGE_STR4)||'|'||
trim(LARGE_STR5)||'|'||
trim(DATE3)||'|'||
trim(DATE4)||'|'||
trim(DATE5)||'|'||
trim(DATE6)||'|'||
trim(DATE7)||'|'||
trim(DATE8)||'|'||
trim(DATE9)||'|'||
trim(DATE10)||'|'||
trim(NUMBER1)||'|'||
trim(NUMBER2)||'|'||
trim(NUMBER3)||'|'||
trim(NUMBER4)||'|'||
trim(NUMBER5)||'|'||
trim(NUMBER6)||'|'||
trim(NUMBER7)||'|'||
trim(NUMBER8)||'|'||
trim(NUMBER9)||'|'||
trim(NUMBER10)||'|'||
trim(DECIMAL1)||'|'||
trim(DECIMAL2)||'|'||
trim(DECIMAL3)||'|'||
trim(DECIMAL4)||'|'||
trim(DECIMAL5)||'|'||
trim(DECIMAL6)||'|'||
trim(DECIMAL7)||'|'||
trim(DECIMAL8)||'|'||
trim(DECIMAL9)||'|'||
trim(DECIMAL10)||'|'||
trim(ENTITYTYPE)||'|'||
trim(STR43)||'|'||
trim(STR44)||'|'||
trim(STR45)||'|'||
trim(STR46)||'|'||
trim(STR47)||'|'||
trim(STR48)||'|'||
trim(STR49)||'|'||
trim(STR50)||'|'||
trim(ORG_KEY)||'|'||
trim(STR21)||'|'||
trim(STR22)||'|'||
trim(STR23)||'|'||
trim(STR24)||'|'||
trim(STR25)||'|'||
trim(STR26)||'|'||
trim(STR27)||'|'||
trim(STR28)||'|'||
trim(STR29)||'|'||
trim(STR30)||'|'||
trim(STR31)||'|'||
trim(STR32)||'|'||
trim(STR38)||'|'||
trim(STR39)||'|'||
trim(STR40)||'|'||
trim(STR41)||'|'||
trim(STR42)||'|'||
trim(DBFLOAT1)||'|'||
trim(DBFLOAT2)||'|'||
trim(DBFLOAT3)||'|'||
trim(DBFLOAT4)||'|'||
trim(DBFLOAT5)||'|'||
trim(AMOUNT5)||'|'||
trim(FLAG1)||'|'||
trim(FLAG2)||'|'||
trim(FLAG3)||'|'||
trim(FLAG4)||'|'||
trim(FLAG5)||'|'||
trim(INT1)||'|'||
trim(INT2)||'|'||
trim(INT3)||'|'||
trim(INT4)||'|'||
trim(INT5)||'|'||
trim(INT6)||'|'||
trim(INT7)||'|'||
trim(INT8)||'|'||
trim(INT9)||'|'||
trim(INT10)||'|'||
trim(INT11)||'|'||
trim(INT12)||'|'||
trim(INT13)||'|'||
trim(INT14)||'|'||
trim(INT15)||'|'||
trim(MLUSERFIELD1)||'|'||
trim(MLUSERFIELD2)||'|'||
trim(MLUSERFIELD3)||'|'||
trim(MLUSERFIELD4)||'|'||
trim(MLUSERFIELD5)||'|'||
trim(STR1_CODE)||'|'||
trim(STR2_CODE)||'|'||
trim(STR3_CODE)||'|'||
trim(STR4_CODE)||'|'||
trim(STR5_CODE)||'|'||
trim(CORE_CUST_ID)||'|'||
trim(CORE_CHILD_CUST_ID)||'|'||
trim(PERCENTAGE1)||'|'||
trim(PERCENTAGE2)||'|'||
trim(PERCENTAGE3)||'|'||
trim(PERCENTAGE4)||'|'||
trim(PERCENTAGE5)||'|'||
trim(BANK_ID)||'|'||
trim(STR4_ALT1)||'|'||
trim(STR4_ALT2)||'|'||
trim(STR4_ALT3)
from CU5CORP_O_TABLE;
exit;
 