set head off
set feedback off
set term off
set lines 800
set page size 0
set pages 0
set trimspool on
spool $MIG_PATH/output/finacle/cifkw/CC006.txt
select
trim(FINANCIAL_DETAILS_ID)||'|'||
trim(BANK_ID)||'|'||
trim(STR4_ALT1)||'|'||
trim(FINANCIAL_ID)||'|'||
trim(FINANCEDETAIL_TYPE)||'|'||
trim(STR1)||'|'||
trim(STR2)||'|'||
trim(STR3)||'|'||
trim(STR4)||'|'||
trim(STR5)||'|'||
trim(STR6)||'|'||
trim(STR7)||'|'||
trim(STR8)||'|'||
trim(STR9)||'|'||
trim(STR10)||'|'||
trim(STR11)||'|'||
trim(STR12)||'|'||
trim(STR13)||'|'||
trim(STR14)||'|'||
trim(STR15)||'|'||
trim(STR16)||'|'||
trim(STR17)||'|'||
trim(STR18)||'|'||
trim(STR19)||'|'||
trim(STR20)||'|'||
trim(STR21)||'|'||
trim(STR22)||'|'||
trim(STR23)||'|'||
trim(STR24)||'|'||
trim(STR25)||'|'||
trim(STR26)||'|'||
trim(STR27)||'|'||
trim(STR28)||'|'||
trim(STR29)||'|'||
trim(STR30)||'|'||
trim(DATE1)||'|'||
trim(DATE2)||'|'||
trim(DATE3)||'|'||
trim(DATE4)||'|'||
trim(DATE5)||'|'||
trim(DATE6)||'|'||
trim(DATE7)||'|'||
trim(DATE8)||'|'||
trim(DATE9)||'|'||
trim(DATE10)||'|'||
trim(AMOUNT1)||'|'||
trim(AMOUNT2)||'|'||
trim(AMOUNT3)||'|'||
trim(AMOUNT4)||'|'||
trim(AMOUNT5)||'|'||
trim(AMOUNT6)||'|'||
trim(AMOUNT7)||'|'||
trim(AMOUNT8)||'|'||
trim(AMOUNT9)||'|'||
trim(AMOUNT10)||'|'||
trim(AMOUNT11)||'|'||
trim(AMOUNT12)||'|'||
trim(AMOUNT13)||'|'||
trim(AMOUNT14)||'|'||
trim(AMOUNT15)||'|'||
trim(AMOUNT16)||'|'||
trim(AMOUNT17)||'|'||
trim(AMOUNT18)||'|'||
trim(AMOUNT19)||'|'||
trim(AMOUNT20)||'|'||
trim(AMOUNT21)||'|'||
trim(AMOUNT22)||'|'||
trim(AMOUNT23)||'|'||
trim(AMOUNT24)||'|'||
trim(AMOUNT25)||'|'||
trim(AMOUNT26)||'|'||
trim(AMOUNT27)||'|'||
trim(AMOUNT28)||'|'||
trim(AMOUNT29)||'|'||
trim(AMOUNT30)||'|'||
trim(FLAG1)||'|'||
trim(FLAG2)||'|'||
trim(FLAG3)||'|'||
trim(FLAG4)||'|'||
trim(FLAG5)||'|'||
trim(INT1)||'|'||
trim(INT2)||'|'||
trim(INT3)||'|'||
trim(INT4)||'|'||
trim(INT5)||'|'||
trim(INT6)||'|'||
trim(INT7)||'|'||
trim(INT8)||'|'||
trim(INT9)||'|'||
trim(INT10)||'|'||
trim(INT11)||'|'||
trim(INT12)||'|'||
trim(INT13)||'|'||
trim(INT14)||'|'||
trim(INT15)||'|'||
trim(MLUSERFIELD1)||'|'||
trim(MLUSERFIELD2)||'|'||
trim(MLUSERFIELD3)||'|'||
trim(MLUSERFIELD4)||'|'||
trim(MLUSERFIELD5)||'|'||
trim(ENTITYID)||'|'||
trim(ENTITYKEY)||'|'||
trim(CIFTYPE)||'|'||
trim(ENTITYTYPE)||'|'||
trim(ORGKEY)||'|'||
trim(STR31)||'|'||
trim(STR32)||'|'||
trim(STR33)||'|'||
trim(STR34)||'|'||
trim(STR35)||'|'||
trim(INT16)||'|'||
trim(INT17)||'|'||
trim(INT18)||'|'||
trim(INT19)||'|'||
trim(INT20)||'|'||
trim(AMOUNT31)||'|'||
trim(AMOUNT32)||'|'||
trim(AMOUNT33)||'|'||
trim(AMOUNT34)||'|'||
trim(AMOUNT35)||'|'||
trim(DATE11)||'|'||
trim(FINYEAR)||'|'||
trim(FINMONTH)||'|'||
trim(AUDITSTATUS)||'|'||
trim(TANG_FIX_ASSETS)||'|'||
trim(SG_RECEIPTS)||'|'||
trim(GROSS_PROFIT)||'|'||
trim(PROFIT_INT_DEP_TAXES)||'|'||
trim(NET_PROFIT_RATIO)||'|'||
trim(GROSS_GEARING_RATIO)||'|'||
trim(NET_GEARING_RATIO)||'|'||
trim(FREQUENCY)||'|'||
trim(TMDATE)
from cu6corp_o_table;
exit;
 
 