set head off
set feedback off
set term off
set lines 1200
set page size 0
set pages 0
set trimspool on
spool $MIG_PATH/output/finacle/cifkw/RC003.txt
SELECT 
trim(ORGKEY)||'|'||
trim(CIF_ID)||'|'||
trim(STRTEXT2)||'|'||
trim(STRTEXT1)||'|'||
trim(TYPE)||'|'||
trim(CUSTOMERCURRENCY)||'|'||
trim(CREDITDISCOUNTPERCENT)||'|'||
trim(DEBITDISCOUNTPERCENT)||'|'||
trim(WITHHOLDTAXPCNT)||'|'||
trim(WITHHOLDTAXFLOORLMT)||'|'||
trim(DTDATE1)||'|'||
trim(DTDATE2)||'|'||
trim(COUNTRYOFISSUE_CODE)||'|'||
trim(SMALL_STR1)||'|'||
trim(SMALL_STR2)||'|'||
trim(SMALL_STR3)||'|'||
trim(SMALL_STR4)||'|'||
trim(SMALL_STR5)||'|'||
trim(SMALL_STR6)||'|'||
trim(SMALL_STR7)||'|'||
trim(SMALL_STR8)||'|'||
trim(SMALL_STR9)||'|'||
trim(SMALL_STR10)||'|'||
trim(MED_STR1)||'|'||
trim(MED_STR2)||'|'||
trim(MED_STR3)||'|'||
trim(MED_STR4)||'|'||
trim(MED_STR5)||'|'||
trim(MED_STR6)||'|'||
trim(MED_STR7)||'|'||
trim(MED_STR8)||'|'||
trim(MED_STR9)||'|'||
trim(MED_STR10)||'|'||
trim(LARGE_STR1)||'|'||
trim(LARGE_STR2)||'|'||
trim(LARGE_STR3)||'|'||
trim(LARGE_STR4)||'|'||
trim(LARGE_STR5)||'|'||
trim(DATE1)||'|'||
trim(DATE2)||'|'||
trim(DATE3)||'|'||
trim(DATE4)||'|'||
trim(DATE5)||'|'||
trim(DATE6)||'|'||
trim(DATE7)||'|'||
trim(DATE8)||'|'||
trim(DATE9)||'|'||
trim(DATE10)||'|'||
trim(NUMBER1)||'|'||
trim(NUMBER2)||'|'||
trim(NUMBER3)||'|'||
trim(NUMBER4)||'|'||
trim(NUMBER5)||'|'||
trim(NUMBER6)||'|'||
trim(NUMBER7)||'|'||
trim(NUMBER8)||'|'||
trim(NUMBER9)||'|'||
trim(NUMBER10)||'|'||
trim(DECIMAL1)||'|'||
trim(DECIMAL2)||'|'||
trim(DECIMAL3)||'|'||
trim(DECIMAL4)||'|'||
trim(DECIMAL5)||'|'||
trim(DECIMAL6)||'|'||
trim(DECIMAL7)||'|'||
trim(DECIMAL8)||'|'||
trim(DECIMAL9)||'|'||
trim(DECIMAL10)||'|'||
trim(STRTEXT3)||'|'||
trim(STRTEXT4)||'|'||
trim(STRTEXT5)||'|'||
trim(STRTEXT6)||'|'||
trim(STRTEXT7)||'|'||
trim(STRTEXT8)||'|'||
trim(STRTEXT9)||'|'||
trim(STRTEXT10)||'|'||
trim(INTINTEGER1)||'|'||
trim(INTINTEGER2)||'|'||
trim(INTINTEGER3)||'|'||
trim(INTINTEGER4)||'|'||
trim(INTINTEGER5)||'|'||
trim(INTINTEGER6)||'|'||
trim(INTINTEGER7)||'|'||
trim(INTINTEGER8)||'|'||
trim(INTINTEGER9)||'|'||
trim(INTINTEGER10)||'|'||
trim(INTINTEGER11)||'|'||
trim(INTINTEGER12)||'|'||
trim(INTINTEGER13)||'|'||
trim(INTINTEGER14)||'|'||
trim(INTINTEGER15)||'|'||
trim(DTDATE3)||'|'||
trim(DTDATE4)||'|'||
trim(DTDATE5)||'|'||
trim(DBFLOAT1)||'|'||
trim(DBFLOAT2)||'|'||
trim(DBFLOAT3)||'|'||
trim(DBFLOAT4)||'|'||
trim(DBFLOAT5)||'|'||
trim(STRTEXT11)||'|'||
trim(STRTEXT12)||'|'||
trim(STRTEXT13)||'|'||
trim(STRTEXT14)||'|'||
trim(STRTEXT15)||'|'||
trim(STRTEXT16)||'|'||
trim(STRTEXT17)||'|'||
trim(STRTEXT18)||'|'||
trim(STRTEXT19)||'|'||
trim(STRTEXT20)||'|'||
trim(STRTEXT21)||'|'||
trim(STRTEXT22)||'|'||
trim(STRTEXT23)||'|'||
trim(STRTEXT24)||'|'||
trim(STRTEXT25)||'|'||
trim(STRTEXT26)||'|'||
trim(STRTEXT27)||'|'||
trim(EMPLOYERID)||'|'||
trim(EMPLOYEEID)||'|'||
trim(STRTEXT1_CODE)||'|'||
trim(STRTEXT2_CODE)||'|'||
trim(STRTEXT28)||'|'||
trim(BANK_ID)||'|'||
trim(STRTEXT4_ALT1)
  FROM CU3_O_TABLE; 
spool off;
exit;
