DROP TABLE E_BANKING_USER_O_TABLE;
DROP TABLE BANK_DETAILS_O_TABLE;
DROP TABLE BANK_MASTER_O_TABLE;
DROP TABLE BANK_ROUTING_O_TABLE;
DROP TABLE CUSTOMER_PAYEE_O_TABLE;
DROP TABLE PAYEE_MASTER_O_TABLE; 