--E_Banking user Details
CREATE TABLE E_BANKING_USER_O_TABLE
(
  CORP_ID                  NVARCHAR2(32),
  CIF_ID                   NVARCHAR2(64),
  SALUTATION               NVARCHAR2(10),
  FIRST_NAME               NVARCHAR2(100),
  LAST_NAME                NVARCHAR2(100),
  GENDER                   CHAR(1 BYTE),
  ALERT_REGISTRATION_FLAG  CHAR(1 BYTE),
  EMAIL_ID                 NVARCHAR2(80),
  MOBILE_NO                NVARCHAR2(20),
  BRAND_ID                 NVARCHAR2(100),
  CATEGORY_CODE            NVARCHAR2(8),
  OCCUPATION               NVARCHAR2(5),
  LIMIT_SCHEME             NVARCHAR2(3),
  AUTH_USER                CHAR(1 BYTE),
  RANGE_LIMIT_SCHEME       NVARCHAR2(3),
  AUTHENTICATION_MODE      NVARCHAR2(4),
  AUTHORIZATION_MODE       NVARCHAR2(4),
  SCHEME_ID                NVARCHAR2(256),
  DND_START_TIME           NUMBER(2),
  DND_END_TIME             NUMBER(2),
  LANG_ID                  NVARCHAR2(10),
  USER_ID                  NVARCHAR2(65),
  NATIONAL_ID              NVARCHAR2(20)
);

--Beneficiary Bank Details
CREATE TABLE BANK_DETAILS_O_TABLE
(
  DB_TS                        NUMBER(5),
  LANG_ID                      NVARCHAR2(10),
  BANK_REF_NO                  NVARCHAR2(11),
  BANK_TYPE                    NVARCHAR2(2),
  UPDATE_DATE                  DATE,
  INSTITUTION_TYPE             NVARCHAR2(2),
  INSTITUTION_NAME             NVARCHAR2(105),
  SHORT_NAME                   NVARCHAR2(50),
  ADDRESS                      NVARCHAR2(255),
  ADDRESS2                     NVARCHAR2(35),
  ADDRESS3                     NVARCHAR2(35),
  CITY_ZIPCODE                 NVARCHAR2(61),
  COUNTRY_CODE                 NVARCHAR2(5),
  STATE_CODE                   NVARCHAR2(5),
  ZIP_EXTN                     NVARCHAR2(4),
  BRANCH_NAME                  NVARCHAR2(255),
  PH_AREA_CODE                 NVARCHAR2(3),
  PH_NO                        NVARCHAR2(20),
  PH_NO_EXTN                   NVARCHAR2(5),
  FAX_AREA_CODE                NVARCHAR2(3),
  FAX_NO                       NVARCHAR2(35),
  FAX_NO_EXTN                  NVARCHAR2(5),
  SERVICES                     NVARCHAR2(60),
  EXTRA_INFO                   NVARCHAR2(35),
  INSTITUTION_IDENTIFIER       NVARCHAR2(8),
  IBAN_SUPPORT_INDICATOR_FLAG  NVARCHAR2(1),
  DIRECT_DEBIT_SUPPORT_FLAG    NVARCHAR2(1),
  ROUTING_NUMBER_SOURCE        NVARCHAR2(28),
  DEL_FLG                      CHAR(1 BYTE),
  FREE_TXT1                    NVARCHAR2(50),
  FREE_TXT2                    NVARCHAR2(50),
  FREE_TXT3                    NVARCHAR2(50),
  FREE_NUM1                    NUMBER(12),
  FREE_NUM2                    NUMBER(12),
  FREE_DATE1                   DATE,
  FREE_DATE2                   DATE,
  R_MOD_ID                     NVARCHAR2(65),
  R_MOD_TIME                   DATE,
  R_CRE_ID                     NVARCHAR2(65),
  R_CRE_TIME                   DATE
);


--Beneficiary Bank Master
CREATE TABLE BANK_MASTER_O_TABLE
(
  DB_TS             NUMBER(5),
  BANK_REF_NO       NVARCHAR2(11),
  HOST_BANK_CODE    NVARCHAR2(11),
  HOST_BRANCH_CODE  NVARCHAR2(9),
  DEL_FLG           CHAR(1 BYTE),
  R_MOD_ID          NVARCHAR2(65),
  R_MOD_TIME        DATE,
  R_CRE_ID          NVARCHAR2(65),
  R_CRE_TIME        DATE
);

--Beneficiary Bank Routing 
CREATE TABLE BANK_ROUTING_O_TABLE
(
  DB_TS                  NUMBER(5),
  BANK_REF_NO            NVARCHAR2(11),
  NETWORK_TYPE           NVARCHAR2(28),
  SEQ_NO                 NUMBER(10),
  ROUTING_NO             NVARCHAR2(32),
  ROUTING_NUMBER_SOURCE  NVARCHAR2(28),
  R_MOD_ID               NVARCHAR2(65),
  R_MOD_TIME             DATE,
  R_CRE_ID               NVARCHAR2(65),
  R_CRE_TIME             DATE,
  DEL_FLG                CHAR(1 BYTE)
);


--Beneficiary Customer Payye
CREATE TABLE CUSTOMER_PAYEE_O_TABLE
(
  PAYEE_LIST_ID            NUMBER(10),
  BANK_ID                  NVARCHAR2(11),
  USER_ID                  NVARCHAR2(32),
  DB_TS                    NUMBER(5),
  CORP_ID                  NVARCHAR2(32),
  BNF_ID                   NUMBER(10),
  BNF_NIC_NAME             NVARCHAR2(80),
  FREE_FIELD_1             NVARCHAR2(140),
  FREE_FIELD_2             NVARCHAR2(140),
  FREE_FIELD_3             NVARCHAR2(140),
  FREE_FLG1                CHAR(1 BYTE),
  FREE_FLG2                CHAR(1 BYTE),
  DEL_FLG                  CHAR(1 BYTE),
  R_MOD_ID                 NVARCHAR2(65),
  R_MOD_TIME               DATE,
  R_CRE_ID                 NVARCHAR2(65),
  R_CRE_TIME               DATE,
  CONSUMER_CD              NVARCHAR2(350),
  RECEIVE_BILLS_FLG        CHAR(1 BYTE),
  AUTOPAY_FLG              CHAR(1 BYTE),
  AUTOPAY_AMT              NUMBER(18,3),
  AUTOPAY_CRN              NVARCHAR2(3),
  AUTOPAY_ACID             NVARCHAR2(34),
  AUTOPAY_BRCH_ID          NVARCHAR2(9),
  AUTOPAY_MODE             CHAR(1 BYTE),
  SUBSCRIPTION_START_DATE  DATE,
  ADHOC_PAYEE              NVARCHAR2(1),
  NICKNAME_CRE_ID          NVARCHAR2(32),
  BNF_PYMT_DETAILS_1       NVARCHAR2(254),
  BNF_PYMT_DETAILS_2       NVARCHAR2(254),
  BNF_PYMT_DETAILS_3       NVARCHAR2(254),
  BNF_PYMT_DETAILS_4       NVARCHAR2(254),
  NOTIFICATION_REF_NO      NUMBER(10),
  MAX_AMT_IN_HOMECRN       NUMBER(18,3),
  REG_ACTIVE_FLG           NVARCHAR2(1),
  CUSTOMER_ID              NVARCHAR2(64),
  FILE_SEQN_NUM            NVARCHAR2(12),
  FU_REC_NUM               NUMBER(10)
);

--Payee Master
CREATE TABLE PAYEE_MASTER_O_TABLE
(
  BANK_ID                   NVARCHAR2(11),
  BNF_ID                    NUMBER(10),
  DB_TS                     NUMBER(5),
  LANG_ID                   NVARCHAR2(10),
  DISPLAY_ID                NUMBER(10),
  CORP_ID                   NVARCHAR2(32),
  BNF_CODE                  NVARCHAR2(80),
  BNF_NAME                  NVARCHAR2(80),
  BNF_ADDRESS_1             NVARCHAR2(80),
  BNF_ADDRESS_2             NVARCHAR2(80),
  BNF_ADDRESS_3             NVARCHAR2(80),
  BNF_STATE                 NVARCHAR2(5),
  BNF_CNTRY                 NVARCHAR2(5),
  BNF_TEL                   NVARCHAR2(20),
  BNF_MOB                   NVARCHAR2(20),
  BNF_FAX                   NVARCHAR2(35),
  BNF_TYPE                  NVARCHAR2(2),
  OTH_BANK_REF_NO           NVARCHAR2(11),
  BNF_BANK_NAME             NVARCHAR2(105),
  BNF_BANK_ADDRESS          NVARCHAR2(255),
  HOME_BANK_BRANCH_CODE     NVARCHAR2(9),
  BNF_BANK_COUNTRY          NVARCHAR2(5),
  ACCOUNT_ID                NVARCHAR2(34),
  BNF_ACCT_CRN              NVARCHAR2(3),
  BNF_COMM_IND              NVARCHAR2(2),
  PAYEE_FORMAT              NVARCHAR2(255),
  PYMT_FORMAT               NVARCHAR2(255),
  EXPIRY_DATE               DATE,
  BNF_IND                   CHAR(1 BYTE),
  FREE_FIELD_1              NVARCHAR2(256),
  FREE_FIELD_2              NVARCHAR2(256),
  FREE_FIELD_3              NVARCHAR2(256),
  FREE_FIELD_4              NVARCHAR2(256),
  FREE_FLG_1                CHAR(1 BYTE),
  FREE_FLG_2                CHAR(1 BYTE),
  FREE_FLG_3                CHAR(1 BYTE),
  FREE_FLG_4                CHAR(1 BYTE),
  FREE_IND_1                NVARCHAR2(2),
  FREE_IND_2                NVARCHAR2(2),
  BILL_EXPIRY_PRD           NUMBER(5),
  MIN_PMT_AMT               NUMBER(18,3),
  LATE_PYMT_FLG             CHAR(1 BYTE),
  PART_PYMT_FLG             CHAR(1 BYTE),
  EXS_PYMT_FLG              CHAR(1 BYTE),
  REAL_TIME_CREDIT_FLG      CHAR(1 BYTE),
  CHRG_PMT_FLG              CHAR(1 BYTE),
  PRENOTE_REQUIRED          CHAR(1 BYTE),
  DEL_FLG                   CHAR(1 BYTE),
  GLOBAL_FLG                CHAR(1 BYTE),
  R_MOD_ID                  NVARCHAR2(65),
  R_MOD_TIME                DATE,
  R_CRE_ID                  NVARCHAR2(65),
  R_CRE_TIME                DATE,
  BNF_ACCT_TYPE             NVARCHAR2(3),
  BNF_CITY_ZIP              NVARCHAR2(61),
  BNF_BANK_CITY_ZIP         NVARCHAR2(61),
  BNF_GROUP_ID              NVARCHAR2(56),
  BNF_EMAIL                 NVARCHAR2(80),
  STD_IND_CD                NVARCHAR2(7),
  DIVISION                  NVARCHAR2(56),
  ADDED_BANK_BRANCH_NAME    NVARCHAR2(255),
  BANK_TYPE                 NVARCHAR2(56),
  BNF_CITY_CODE             NVARCHAR2(5),
  BNF_ZIP_CODE              NVARCHAR2(10),
  NETWORK_ID                NVARCHAR2(10),
  BANK_IDENTIFIER           NVARCHAR2(32),
  PTP_TYPE                  NVARCHAR2(5),
  PTP_ID                    NVARCHAR2(35),
  DELIVERY_MODES_SUPPORTED  NVARCHAR2(35),
  FILE_SEQ_NUM              NVARCHAR2(10),
  FU_REC_NUM                NUMBER(10),
  EXTERNAL_BILLER_ID        NVARCHAR2(10),
  SERVICE_TYPE              NVARCHAR2(10),
  AGGREGATOR_ID             NVARCHAR2(10)
); 