drop table cl001_o_table;
drop table cl002_o_table;
drop table cl003_o_table;
drop table cl004_o_table
drop table cl005_o_table;
drop table cl006_o_table;
drop table cl007_o_table;
drop table cl008_o_table;
drop table cl009_o_table;
drop table cl010_o_table;
drop table cl011_o_table;
drop table cl012_o_table;
drop table cl013_o_table;
drop table cl014_o_table;
drop table cl015_o_table;
drop table cl016_o_table;
Drop table AC1SBCA_O_TABLE;
Drop table AC1ODCC_O_TABLE;
drop table AC2_O_TABLE;
drop table AC_BALANCE_O_TABLE;
drop table CBS_O_TABLE;
Drop table SPT_O_TABLE;
drop table LIEN_O_TABLE;
drop table CARDDETAILS_O_TABLE;
drop table CARDHOT_O_TABLE;
drop table CARDLINKAGE_O_TABLE;
drop table COL_DEP_O_TABLE;
drop table COL_G_O_TABLE;
drop table COL_MACH_O_TABLE;
drop table COL_OTHERS_O_TABLE;
DROP TABLE COL_TRADEABLE_O_TABLE;
DROP TABLE COL_IP_RE_O_TABLE;
drop table CU1CORP_O_TABLE;
drop table CU2CORP_O_TABLE;
drop table CU5CORP_O_TABLE;
drop table CU7CORP_O_TABLE;
drop table CU8CORP_O_TABLE;
Drop table MEMOPAD_O_TABLE;
Drop table SIU_O_TABLE;
drop table DDS_O_TABLE;
drop table CU1_O_TABLE;
drop table CU2_O_TABLE;
drop table CU3_O_TABLE;
drop table CU4_O_TABLE;
drop table CU5_O_TABLE;
drop table CU6_O_TABLE;
drop table CU8_O_TABLE;
drop table cu9_O_TABLE;
drop table LAINT_O_TABLE;
drop table LAM_O_TABLE;
drop table LAT1_O_TABLE;
drop table LAT_O_TABLE;
drop table LDT_O_TABLE;
drop table LRS_O_TABLE;
drop table TDINTEREST_O_TABLE;
DROP TABLE TDA_O_TABLE;
drop table TDT_O_TABLE;
drop table TTUM1_O_TABLE;
drop table TTUM2_O_TABLE;
drop table TTUM3_O_TABLE;
drop table CUSTOM_EAB_O_TABLE;
drop TABLE BO_O_TABLE;
drop table SIU_CCCY_O_TABLE;
drop table BO_CCCY_O_TABLE;
drop table CUSTOM_CCPOS01_O_TABLE;
drop table CUSTOM_CCUNLIN01_O_TABLE;
drop table CUSTOM_CCSTAT01_O_TABLE;
drop table CUSTOM_CCHOT01_O_TABLE;
drop table ACCOUNT_LABEL_O_TABLE;
drop table ACCOUNT_FAX_HELD_O_TABLE;
drop table SIU_TT_O_TABLE;
drop table custom_pool_payout_o_table;
drop table COL_OTHERS_INS_O_TABLE;
drop table col_ins_o_table;
drop table KYCR01_O_TABLE;
drop table KYCC02_o_table;
drop table KYC03_O_TABLE;
drop table KYC04_O_TABLE;
drop table KYC05_O_TABLE;
drop table KYC06_O_TABLE;
drop table KYC07_O_TABLE;
drop table KYC08_O_TABLE;
drop table KYC09_O_TABLE;
drop table CUSTOM_LOCKERS_O_TABLE;
drop table CUSTOM_CFR001_O_TABLE ;
drop table CUSTOM_CFR002_O_TABLE  ;
drop table custom_cfr003_o_table  ;
drop table custom_cfr004_o_table  ;
drop table custom_cfr005_o_table  ;
drop table custom_cfr006_o_table  ;
drop table custom_cfr007_o_table  ;
drop table custom_cfr008_o_table  ;
drop table custom_cfr009_o_table  ;
drop table custom_cfr010_o_table  ;
drop table custom_cfr011_o_table  ;
drop table custom_cfr012_o_table  ;
drop table custom_cfr013_o_table  ;
drop table custom_cfr014_o_table  ;
drop table custom_cfr015_o_table  ;
drop table custom_cfr016_o_table  ;
drop table CUSTOM_CFR017_O_TABLE ;
drop table CUSTOM_COL_LINKAGE_O_TABLE;
drop table CUSTOM_COL_LOMBARD_O_TABLE ;
drop table CUSTOM_COL_GUARANTEE_O_TABLE  ;
drop table CUSTOM_COL_SECU_O_TABLE  ;
drop table custom_col_ins_company_o_table  ;
drop table custom_col_valuator_o_table  ;
drop table custom_Col_Advent_o_table  ;
drop table custom_Col_eifb_o_table  ;
drop table CUSTOM_CFR016_O_TABLE;
drop table TUAT_O_TABLE;
drop table CUSTOM_SKYWARDS_O_TABLE;
drop table CUSTOM_ACCURED_CHARGES_O_TABLE;
drop table PDC_O_TABLE;
DROP TABLE TTUM4_O_TABLE;
drop table custom_sweeps_o_table;
drop table custom_lcu001_o_table;
drop table custom_ltu001_o_table;
drop table custom_lnu001_o_table;
drop table custom_lku001_o_table;
drop table TEST_EIDEM_SUM;
drop table CUSTOM_SEGMENT_HIS_O_TABLE;
drop table CREDIT_CARD_CIF_O_TABLE;
drop table credit_card_dd_o_table;
drop table CUSTOM_OPERATION_REASON_CODES;
drop table CHEQUE_PROCESSED;
drop table CHEQUE_UNUSED;
drop table CUSTOM_NOMINATED_ACCT;
DROP TABLE CUSTOM_POOL_O_TABLE;
drop table CU9CORP_O_TABLE;
drop table custom_htd_o_TABLE;
drop table custom_mt950;
drop table advance_int_o_table;
drop table corp_sch_detl;
drop table custom_C_GAC_EXT;
exit;