select distinct HYCLR COLLATERAL_REFERENCE, HYCLP DEAL_TYPE, HYDLP DEPARTMENT_CODE, COLLATERAL_LINKAGE_TO_LIMIT.LIMIT_PREFIX, COLLATERAL_LINKAGE_TO_LIMIT.LIMIT_SUFFIX, COLLATERAL_VALUE,
 APPORTIONED_VALUE FROM YCCLC5PF01
inner join hypf on trim(hyclr) = trim(CCC5_CLR)
inner join c8pf on trim(c8ccy) = trim(CCC5_CCY)
inner join map_cif on trim(hycus)=trim(map_cif.gfcus) and nvl(trim(hyclc),' ')=nvl(trim(map_cif.gfclc),' ') AND  IS_JOINT <>'Y'
inner join (
    select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLGUARANTEE
    UNION ALL
    select COLLATERAL_TYPE,COLLATERAL_CODE,COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLIMMOV
    UNION ALL
    select COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLTRADE
    UNION ALL
    select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLOTHERS
    UNION ALL
    select COLLATERAL_TYPE,COLLATERAL_CODE,TOTAL_COLLATERAL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.COLL_MUTUAL_FUND
    UNION ALL
    select COLTRLTYPE,COLTRLCODE,COLL_VALUE,SECU_SRL_NUM,CIF_ID,TO_CHAR(CC_FINONE_ACCNT) COL_REF from MIGADM.C_COLLDEPOSITS
) b on TRIM(COL_REF) = TRIM(HYCLR) or trim(hydbnm)||trim(hydlp)||trim(hydlr) = TRIM(COL_REF)
inner join  (select distinct * from COLLATERAL_LINKAGE_TO_LIMIT) COLLATERAL_LINKAGE_TO_LIMIT on trim(COLLATERAL_LINKAGE_TO_LIMIT.COLLATERAL_ID) = trim(b.SECU_SRL_NUM)
inner JOIN (SELECT DISTINCT LIMIT_PREFIX,LIMIT_SUFFIX,COLLATERAL_NODE FROM LIMIT_CORE_INFY_TABLE INNER JOIN COLL_LIMIT_MAP ON LIMIT_NODE = LIMIT_SUFFIX) LIMIT ON LIMIT.LIMIT_PREFIX =  map_cif.FIN_CIF_ID AND trim(COLLATERAL_NODE) = TRIM(CCC5_PRDC)
order by 1
 
