-- File Name           : COL_G_upload.sql
-- File Created for    : Upload file for Collateral for Guarantor
-- Created By          : B.Kumaresan
-- Client              : ENBD
-- Created On          : 10-11-2015
-------------------------------------------------------------------
TRUNCATE TABLE COL_DEP_O_TABLE;
INSERT INTO COL_DEP_O_TABLE
SELECT  DISTINCT
--COL_TYPE                NVARCHAR2(1),
'D',
--COL_CODE                NVARCHAR2(8),
CASE WHEN HYDPC='199' THEN 'RDEP-'||trim(HYCCY) ELSE 'DEP-'||trim(HYCCY) END,
--CEILING_LIMIT           NVARCHAR2(17),
'9999999999999',
--COL_CLASS               NVARCHAR2(5),
'',
--COL_GROUP               NVARCHAR2(5),
'',
--MARGIN                  NVARCHAR2(8),
'0',
--LTV_PCNT                NVARCHAR2(8),
HYSVM,
--DR_ACC_FOR_FEES         NVARCHAR2(16),
'',
--LAST_VALUATION_DT       NVARCHAR2(10),
'',
--REASON_CODE             NVARCHAR2(5),
'',
--DEPOSIT_ACCOUNT_NUMBER  NVARCHAR2(16),
MAP_ACC.FIN_ACC_NUM,
--APPORTIONED_VALUE       NVARCHAR2(17),
'',
--REVIEW_DATE             NVARCHAR2(10),
CASE WHEN HYNRD<>0 AND GET_DATE_FM_BTRV(HYNRD)<> 'ERROR' THEN TO_CHAR(TO_DATE(GET_DATE_FM_BTRV(HYNRD),'YYYYMMDD'),'DD-MM-YYYY') 
     WHEN CONV_TO_VALID_DATE( GET_DATE_FM_BTRV(HYCXD),'YYYYMMDD') <= to_date(get_param('EOD_DATE'),'dd-mm-yyyy') THEN TO_CHAR(TO_DATE(get_param('EOD_DATE'),'DD-MM-YYYY')-1,'DD-MM-YYYY')
     ELSE ''
END,
--RECEIVED_DATE           NVARCHAR2(10),
'',
--COL_VALUE
--CASE WHEN HYPF.HYCLV=0 THEN 0.001 ELSE TO_NUMBER((HYPF.HYCLV)/POWER(10,C8CED)) END ,
TO_NUMBER((HYPF.HYCLV)/POWER(10,C8CED)),
--DUE_DATE                NVARCHAR2(10),
CASE WHEN HYCXD='9999999' THEN '31-12-2099'
	 WHEN CONV_TO_VALID_DATE( GET_DATE_FM_BTRV(HYCXD),'YYYYMMDD') <= to_date(get_param('EOD_DATE'),'dd-mm-yyyy') THEN get_param('EOD_DATE')
ELSE       
     NVL(TO_CHAR(TO_DATE(GET_DATE_FM_BTRV(HYCXD),'YYYYMMDD'),'DD-MM-YYYY'),'31-12-2099')
END,
--LODGED_DATE             NVARCHAR2(10),
GET_PARAM('EOD_DATE'),
--DENOMINATION_NUMBER_1   NVARCHAR2(12),
'',
--DENOMINATION_NUMBER_2   NVARCHAR2(12),
'',
--FULL_BENEFIT_FLAG       NVARCHAR2(5),
'N',
--CIF_ID                  NVARCHAR2(45),
MAP_CIF.FIN_CIF_ID,
--NOTES                   NVARCHAR2(240)
TRIM(REPLACE(REPLACE(TRIM(TRIM(HYNR1)||' '||TRIM(HYNR2)||' '||TRIM(HYNR3)||' '||TRIM(HYNR4)||' '||
CASE WHEN CONV_TO_VALID_DATE( GET_DATE_FM_BTRV(HYCXD),'YYYYMMDD') <= to_date(get_param('EOD_DATE'),'dd-mm-yyyy') THEN CONV_TO_VALID_DATE( GET_DATE_FM_BTRV(HYCXD),'YYYYMMDD') END ),CHR(10),' '),CHR(13),' '))  ,
--LINKAGE TYPE
'',
--COLL_STATUS
'',
--ACCOUNT TO BE LINKED
'',
--DP_CONTRBTN
'',
--LIMIT PREFIX
'',
--LIMIT SUFFIX
'',
--UPLOAD_STATUS
'0',
--SERIAL NUMBER
'',
--FORACID_COLL_VALUE
'',
--CC_FINONE_ACCNT
TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR),
--FINACLE_COLLATERAL_ID
--'',
--COL_DOC_ID
--''
--ASSET_CODE
TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR),
--COL_LOCATION
trim(HYCLO),
--LAST_REVIEW_DATE
CASE WHEN HYLRD<>0 AND GET_DATE_FM_BTRV(HYLRD)<> 'ERROR' THEN TO_DATE(GET_DATE_FM_BTRV(HYLRD),'YYYYMMDD') END
FROM HYPF
INNER JOIN MAP_ACC ON TRIM(HYDBNM)||TRIM(HYDLP)||TRIM(HYDLR)=LEG_ACC_NUM
INNER JOIN C8PF ON C8CCY = HYCCY
INNER JOIN GFPF ON TRIM(GFPF.GFCUS)= TRIM(HYCUS) AND NVL(TRIM(GFPF.GFCLC),' ') = NVL(TRIM(HYCLC),' ') 
INNER JOIN MAP_CIF ON TRIM(GFPF.GFCUS)= TRIM(MAP_CIF.GFCUS) AND NVL(TRIM(GFPF.GFCLC),' ') = NVL(TRIM(MAP_CIF.GFCLC),' ')
WHERE SCHM_TYPE='TDA' AND HYCLP ='021' --AND TO_NUMBER((HYPF.HYCLV)/POWER(10,C8CED)) <> 0  AND (CONV_TO_VALID_DATE( GET_DATE_FM_BTRV(HYCXD),'YYYYMMDD') > to_date(get_param('EOD_DATE'),'dd-mm-yyyy') or HYCXD='9999999' OR TRIM(HYCXD) IS NULL)
;
COMMIT;
UPDATE COL_DEP_O_TABLE SET LTV_PCNT='100' WHERE LTV_PCNT='99.999';
UPDATE  COL_DEP_O_TABLE SET REVIEW_DATE=GET_PARAM('EOD_DATE') WHERE TO_DATE(REVIEW_DATE,'DD-MM-YYYY')<TO_DATE(GET_PARAM('EOD_DATE'),'DD-MM-YYYY')  or TRIM(REVIEW_DATE) is null;
COMMIT;
--DELETE FROM COL_DEP_O_TABLE WHERE TRIM(CEILING_LIMIT)='0';
--COMMIT;
------------------------------------------------------------------------------------------------------------------------------
--
--DECLARE
--V_ALL_DEALS_CEILING_AMT NUMBER;
--CURSOR C1 IS SELECT DISTINCT CIF_ID,TO_NUMBER(CEILING_LIMIT) CEILING_LIMIT FROM COL_DEP_O_TABLE GROUP BY CIF_ID,TO_NUMBER(CEILING_LIMIT) HAVING COUNT(*)>1 ;
--
--BEGIN
--
--FOR LRECORD1 IN C1 
--LOOP
--
-- SELECT SUM(TO_NUMBER(V5BAL)/C8PWD) INTO V_ALL_DEALS_CEILING_AMT FROM V5PF
--INNER JOIN C8PF ON C8CCY=V5CCY WHERE V5BRNM||V5DLP||V5DLR IN(SELECT LEG_ACC_NUM FROM MAP_ACC WHERE FIN_CIF_ID=LRECORD1.CIF_ID AND SCHM_TYPE='TDA');
--
--IF V_ALL_DEALS_CEILING_AMT = LRECORD1.CEILING_LIMIT THEN 
--
--    DECLARE
--        CURSOR C2 IS SELECT * FROM COL_DEP_O_TABLE WHERE CIF_ID =LRECORD1.CIF_ID;
--        V_DEAL_AMT NUMBER;
--    BEGIN
--    
--    FOR LRECORD2 IN C2 LOOP
--    
--       SELECT TO_NUMBER(V5BAL)/C8PWD INTO V_DEAL_AMT FROM V5PF
--       INNER JOIN C8PF ON C8CCY=V5CCY WHERE V5BRNM||V5DLP||V5DLR IN(SELECT LEG_ACC_NUM FROM MAP_ACC WHERE FIN_ACC_NUM=LRECORD2.DEPOSIT_ACCOUNT_NUMBER AND SCHM_TYPE='TDA');
--    
--         UPDATE COL_DEP_O_TABLE SET CEILING_LIMIT=V_DEAL_AMT WHERE DEPOSIT_ACCOUNT_NUMBER= LRECORD2.DEPOSIT_ACCOUNT_NUMBER;
--    
--    END LOOP;
--    
--    END;
--
--ELSIF V_ALL_DEALS_CEILING_AMT < LRECORD1.CEILING_LIMIT THEN
--    DELETE FROM COL_DEP_O_TABLE WHERE CIF_ID =LRECORD1.CIF_ID;
--
--ELSE
--
--        DECLARE
--        CURSOR C3 IS  SELECT TO_NUMBER(V5BAL)/C8PWD DEAL_AMT,MAPACC.FIN_ACC_NUM FROM V5PF
--                        INNER JOIN C8PF ON C8CCY=V5CCY 
--                        LEFT JOIN (SELECT * FROM MAP_ACC WHERE FIN_CIF_ID=LRECORD1.CIF_ID AND SCHM_TYPE='TDA') MAPACC ON LEG_ACC_NUM=V5BRNM||V5DLP||V5DLR ORDER BY TO_NUMBER(V5BAL)/C8PWD DESC;
--        V_CEILING_AMT NUMBER;
--        
--    BEGIN
--        V_CEILING_AMT := LRECORD1.CEILING_LIMIT;
--         FOR LRECORD3 IN C3 LOOP
--    
--            IF V_CEILING_AMT <> 0 THEN 
--            
--                 IF  (V_CEILING_AMT-LRECORD3.DEAL_AMT) >= 0 THEN 
--           
--                 UPDATE COL_DEP_O_TABLE SET CEILING_LIMIT=LRECORD3.DEAL_AMT WHERE DEPOSIT_ACCOUNT_NUMBER= LRECORD3.FIN_ACC_NUM;
--                 V_CEILING_AMT := V_CEILING_AMT-LRECORD3.DEAL_AMT;
--               
--                 ELSE 
--                    UPDATE COL_DEP_O_TABLE SET CEILING_LIMIT=V_CEILING_AMT WHERE DEPOSIT_ACCOUNT_NUMBER= LRECORD3.FIN_ACC_NUM;
--                    V_CEILING_AMT := 0;
--                 END IF;
--             
--            ELSE 
--            
--            UPDATE COL_DEP_O_TABLE SET CEILING_LIMIT=0 WHERE DEPOSIT_ACCOUNT_NUMBER= LRECORD3.FIN_ACC_NUM;
--            
--             END IF;  
--    
--         END LOOP;
--    
--    END;
--
--END IF;
--
--END LOOP;
--COMMIT;
--
--
--END;
--/
---------------------------------------------------------------------------------------------------------------------
--
--DELETE FROM COL_DEP_O_TABLE WHERE TO_NUMBER(TRIM(CEILING_LIMIT)) = 0;
--COMMIT;
--
--DELETE FROM COL_DEP_O_TABLE WHERE DEPOSIT_ACCOUNT_NUMBER IN (
--SELECT  MAP_ACC.FIN_ACC_NUM FROM
--COL_DEP_O_TABLE
--INNER JOIN  MAP_ACC ON FIN_ACC_NUM=DEPOSIT_ACCOUNT_NUMBER AND SCHM_TYPE='TDA'
--INNER JOIN V5PF ON LEG_ACC_NUM = TRIM(V5BRNM)||TRIM(V5DLP)||TRIM(V5DLR)
--INNER JOIN C8PF ON C8CCY=V5CCY 
--WHERE DEPOSIT_ACCOUNT_NUMBER NOT IN(SELECT CIF_ID FROM COL_DEP_O_TABLE GROUP BY CIF_ID HAVING COUNT(*)>1) AND 
--TO_NUMBER(V5BAL)/C8PWD < TO_NUMBER(TRIM(CEILING_LIMIT))
--);
--COMMIT;
UPDATE COL_DEP_O_TABLE SET SERIAL_NUMBER='D'||ROWNUM;
COMMIT;
EXIT;
 