
truncate table COLL_ACCOUNT_LINKAGE_DATA;

insert into COLL_ACCOUNT_LINKAGE_DATA
select FIN_CIF_ID, FIN_ACC_NUM, SCHEME_CODE, SCHEME_TYPE, SCCCY, abs(SCBAL/c8pwd) SCBAL, abs((scbal/c8pwd)*c8rte) KWD_SCBAL, '' TOTAL_COL_VAL, '' APPR_COL_VAL from ALL_FINAL_TRIAL_BALANCE 
left join c8pf on c8ccy = scccy
where  SCHEME_TYPE not in('TDA','SBA','OOO') 
and fin_cif_id in(select distinct fin_cif_id from YCCLC5PF01 
inner join map_cif on gfclc||gfcus = CCC5_CLC||CCC5_CUS
left join LIMIT_CORE_INFY_TABLE on fin_cif_id = limit_prefix
where limit_prefix is null and nvl(trim(CCC5_COVG),' ') !='U') 
and scbal <> 0;

TRUNCATE TABLE COLL_ACCOUNT_LINKAGE;

INSERT INTO COLL_ACCOUNT_LINKAGE
SELECT FIN_CIF_ID,
       SECU_SRL_NUM COLLATERAL_CODE,
       ROUND(KWD_SCBAL/(SUM(KWD_SCBAL) OVER(PARTITION BY FIN_CIF_ID)/COUNT(*) OVER(PARTITION BY FIN_CIF_ID,FIN_ACC_NUM))*SECU_VALUE,3) APPORTIONED_VALUE,
       FIN_ACC_NUM FORACID,
       ROUND((ROUND(KWD_SCBAL/(SUM(KWD_SCBAL) OVER(PARTITION BY FIN_CIF_ID)/COUNT(*) OVER(PARTITION BY FIN_CIF_ID,FIN_ACC_NUM))*SECU_VALUE,3))/SECU_VALUE*100,3) MARGIN_PERCENT,
       'P' PRIMARY_SECONDARY,
       SECU_VALUE
  FROM (
  SELECT * FROM COLL_ACCOUNT_LINKAGE_DATA A
  INNER JOIN (
  SELECT DISTINCT SCMT.SECU_SRL_NUM,scmt.SECU_CODE,SECU_TYPE_IND,CMG.CIF_ID,SECU_VALUE FROM TBAADM.SCMT
left join tbaadm.csd on csd.SECU_SRL_NUM = scmt.SECU_SRL_NUM
LEFT JOIN TBAADM.CMG ON NVL(SCMT.CUST_ID,CSD.CUST_ID) = CMG.CUST_ID
WHERE SCMT.SECU_VALUE >'0.01'
) B ON A.FIN_CIF_ID = B.CIF_ID) ;

commit;

update COLL_ACCOUNT_LINKAGE a set APPORTIONED_VALUE = APPORTIONED_VALUE-(
select dif_val from (
select COLLATERAL_CODE,sum(APPORTIONED_VALUE)-(sum(SECU_VALUE))/count(*) dif_val from COLL_ACCOUNT_LINKAGE group by COLLATERAL_CODE having sum(APPORTIONED_VALUE)-(sum(SECU_VALUE))/count(*) > 0
) b where a.COLLATERAL_CODE = b.COLLATERAL_CODE)
where (COLLATERAL_CODE,FORACID) in(select COLLATERAL_CODE,min(FORACID) FORACID from COLL_ACCOUNT_LINKAGE group by COLLATERAL_CODE having sum(APPORTIONED_VALUE)-(sum(SECU_VALUE))/count(*) > 0);
commit;

delete  COLL_ACCOUNT_LINKAGE where APPORTIONED_VALUE='0';
commit;
  
exit;  

--select COLLATERAL_CODE,sum(APPORTIONED_VALUE),min(SECU_VALUE) ,sum(APPORTIONED_VALUE)-min(SECU_VALUE) from COLL_ACCOUNT_LINKAGE group by COLLATERAL_CODEl

--select a.*,abs(b.clr_bal_amt)-APPORTIONED_VALUE from (
--select FORACID,sum(APPORTIONED_VALUE) APPORTIONED_VALUE from COLL_ACCOUNT_LINKAGE group by FORACID
--) a
--left join tbaadm.gam b on bank_id='01' and a.foracid = b.foracid 
