set head off
set feedback off
set term off
set lines 5000
set pages 0
set colsep ''
set trimspool on
spool $MIG_PATH/output/finacle/TF/TF003.txt
SELECT 
FUNCCODE,
SOLID,
GUARANTEE_NO,
MARK_INVOKE_SRL_NUM,
MARK_INVOCATION_AMT,
EVENT_DATE_FOR_BG_EVENT_UPLOAD,
REMARKS,
ORIGINAL_BG_RECEIVED,
OPERATIVE_AC_ID,
LOAN_AC_ID,
INVOCATION_CREDIT_AC_ID,
RATE_CODE,
RATE,
VALUE_DATE,
SYSTEM_REMIT_MODE,
PAYSYSID,
REMITMODE,
DTLSOFCHRG,
FREE_CODE_1,
FREE_CODE_2,
FREE_CODE_3,
FREE_CODE_4,
FREE_CODE_5,
SLA_CATEGORY,
LOCAL_CORRESPONDENT_BANK,
LOCAL_CORRESPONDENT_BRANCH,
RECEIVER_CORRESPONDENT_BANK,
RECEIVER_CORRESPONDENT_BRANCH,
COLLECTION_CORRESPONDENT_BANK,
COLLECTION_CORR_BRANCH,
BENEFICIARY_CORRESPONDENT_BANK,
BENEFICIARY_CORR_BRANCH,
PAYMENT_DATE
FROM TF003
ORDER BY GUARANTEE_NO,
TO_DATE(EVENT_DATE_FOR_BG_EVENT_UPLOAD,'DD-MM-YYYY'),
MARK_INVOKE_SRL_NUM;
spool off;
 
