
set head off
set feedback off
set term off
set lines 6000
set pages 0
set trimspool on
spool $MIG_PATH/output/finacle/cifuae/TF_CIF.txt
--spool '/export/home/migapp/devmig/output/finacle/cifuae/TF_CIF_'||(select to_char(sysdate,'DDMMYY_HHMMSS') from dual)||'.txt';
select
trim(TRADE_FINANCE_ID)||'|'||
trim(BANK_ID)||'|'||
trim(CORPORATE_NAME_ALT1)||'|'||
trim(NAME_ALT1)||'|'||
trim(CORP_ID)||'|'||
trim(CORP_KEY)||'|'||
trim(ENTITY_TYPE)||'|'||
trim(CENTRAL_BANKCODE)||'|'||
trim(TRADE_AUTHORITYCODE)||'|'||
trim(LEASING_LIABILITIES)||'|'||
trim(PRODUCTION_CYCLE)||'|'||
trim(DC_SANCTIONINGAUTHORITY)||'|'||
trim(DC_SANCTIONINGAUTHORITY_CODE)||'|'||
trim(FC_SANCTIONINGAUTHORITY)||'|'||
trim(FC_SANCTIONINGAUTHORITY_CODE)||'|'||
trim(AUTHORISED_SIGN1)||'|'||
trim(AUTHORISED_SIGN2)||'|'||
trim(AUTHORISED_SIGN3)||'|'||
trim(DC_MARGINPERCENTAGE)||'|'||
trim(DC_SANCTIONEXPIRYDATE)||'|'||
trim(DC_NEXTNOCODE)||'|'||
trim(REMARKS)||'|'||
trim(EXP_IMP_IND_CODE)||'|'||
trim(EXP_IMP_IND)||'|'||
trim(CAUTION_STAT)||'|'||
trim(PARTY_TYPE_CODE)||'|'||
trim(PARTY_TYPE)||'|'||
trim(HUND_PCNT_EOU_FLG)||'|'||
trim(INLAND_TRADE_ALLOWED)||'|'||
trim(CNTRCT_LIMIT)||'|'||
trim(CRNCY_CODE)||'|'||
trim(CRNCY_DESC)||'|'||
trim(INDIVIDUALCORPFLAG)||'|'||
trim(CUST_NATIVE_CODE)||'|'||
trim(CUST_NATIVE)||'|'||
trim(REVIEW_DATE)||'|'||
trim(SSI_FLAG)||'|'||
trim(SPECIAL_CUST_FLAG)||'|'||
trim(PARTY_CONST_CODE)||'|'||
trim(PARTY_CONST)||'|'||
trim(STATE_CODE)||'|'||
trim(STATE_DESC)||'|'||
trim(CORPORATE_NAME)||'|'||
trim(PHONE)||'|'||
trim(DEL_FLG)||'|'||
trim(ADDR_1)||'|'||
trim(ADDR_2)||'|'||
trim(ADDR_3)||'|'||
trim(CNTRY_CODE)||'|'||
trim(FAXNO)||'|'||
trim(TELEX)||'|'||
trim(CITY_CODE)||'|'||
trim(CITY)||'|'||
trim(ZIP)||'|'||
trim(CORE_CUST_ID)||'|'||
trim(PHONECITYCODE)||'|'||
trim(PHONELOCALCODE)||'|'||
trim(PHONECOUNTRYCODE)||'|'||
trim(STR1)||'|'||
trim(STR2)||'|'||
trim(STR3)||'|'||
trim(STR4)||'|'||
trim(STR5)||'|'||
trim(STR6)||'|'||
trim(STR7)||'|'||
trim(STR8)||'|'||
trim(STR9)||'|'||
trim(STR10)||'|'||
trim(STR11)||'|'||
trim(STR12)||'|'||
trim(STR13)||'|'||
trim(STR14)||'|'||
trim(STR15)||'|'||
trim(DATE1)||'|'||
trim(DATE2)||'|'||
trim(DATE3)||'|'||
trim(DATE4)||'|'||
trim(DATE5)||'|'||
trim(AMOUNT1)||'|'||
trim(AMOUNT2)||'|'||
trim(AMOUNT3)||'|'||
trim(AMOUNT4)||'|'||
trim(AMOUNT5)||'|'||
trim(FLAG1)||'|'||
trim(FLAG2)||'|'||
trim(FLAG3)||'|'||
trim(FLAG4)||'|'||
trim(FLAG5)||'|'||
trim(INT1)||'|'||
trim(INT2)||'|'||
trim(INT3)||'|'||
trim(INT4)||'|'||
trim(INT5)||'|'||
trim(MLUSERFIELD1)||'|'||
trim(MLUSERFIELD2)||'|'||
trim(MLUSERFIELD3)||'|'||
trim(MLUSERFIELD4)||'|'||
trim(MLUSERFIELD5)||'|'||
trim(BODATECREATED)||'|'||
trim(BOCREATEDBY)||'|'||
trim(BODATEMODIFIED)||'|'||
trim(BOMODIFIEDBY)||'|'||
trim(CONCURDETECT_X)||'|'||
trim(BOACLID)||'|'||
''||'|'||
trim(EXTENSIONID)||'|'||
trim(SECURITYILHINT)||'|'||
trim(SECURITYIUHINT)||'|'||
trim(SECURITYGLHINT)||'|'||
trim(SECURITYGUHINT)||'|'||
trim(CREATED_FROM)||'|'||
trim(ENTITY_TYPE_CODE)||'|'||
trim(CNTRY_DESC)||'|'||
trim(CUST_FLG)||'|'||
trim(ACCOUNTID)||'|'||
trim(ENTITY_CRE_FLG)||'|'||
trim(ORGKEY)||'|'||
trim(NAME)||'|'||
trim(ENTITY_CREATE_FLG)||'|'||
trim(NONCUSTOMERID)||'|'||
trim(DC_NEXTNOCODE_RCODE)||'|'||
trim(CHECKSUM)||'|'||
trim(TMDATE)
from tf_tradefinance;
spool off;
 
